### PR TITLE
rpma: gpspm: do not depend on user-provided blocksize

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/153)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/153)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 164 at r1](https://reviewable.io/reviews/pmem/fio/153#-MRTS9Gu9U3Cqj5xJMb_:-MRTS9Gu9U3Cqj5xJMba:b-s8n03r) ([raw file](https://github.com/pmem/fio/blob/dec5cc2cc0bd2d442dd103d11685e40d14874563/engines/librpma_gpspm.c#L164)):*
> ```
> DDIR_READ
> ```
DDIR_WRITE?

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/153)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 162 at r1](https://reviewable.io/reviews/pmem/fio/153#-MRTWqwQCtxp2i0fnPhf:-MRTWqwR867c6ZeDk5ZW:bucwx2a) ([raw file](https://github.com/pmem/fio/blob/dec5cc2cc0bd2d442dd103d11685e40d14874563/engines/librpma_gpspm.c#L162)):*
> ```
> omitted
> ```

`ignored` ?
___
*[engines/librpma_gpspm.c, line 164 at r1](https://reviewable.io/reviews/pmem/fio/153#-MRTS9Gu9U3Cqj5xJMb_:-MRTWxJ59rAvH9keMl_p:b32v57) ([raw file](https://github.com/pmem/fio/blob/dec5cc2cc0bd2d442dd103d11685e40d14874563/engines/librpma_gpspm.c#L164)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> DDIR_READ
> ```
DDIR_WRITE?
</blockquote></details>

+1

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/153)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/153#-MRToNtY6F7zItX-5UjC:-MRToNtY6F7zItX-5UjD:b-ettnoe) (no related file):*
we remove something from server.fio side but add to client implementation - do not understand fully

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/153)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma_gpspm.c, line 164 at r1](https://reviewable.io/reviews/pmem/fio/153#-MRTS9Gu9U3Cqj5xJMb_:-MRU7hWU0SHhf4X2QR1c:b7g6j2a) ([raw file](https://github.com/pmem/fio/blob/dec5cc2cc0bd2d442dd103d11685e40d14874563/engines/librpma_gpspm.c#L164)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

DDIR_TRIM? I'm just joking. What is the difference for you guys?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/153)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/153#-MRToNtY6F7zItX-5UjC:-MRU9i09E993-FSKew7q:bd9l8xm) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

we remove something from server.fio side but add to client implementation - do not understand fully
</blockquote></details>

My bad. Luckily we are doing the review. ;-)

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/153)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 164 at r1](https://reviewable.io/reviews/pmem/fio/153#-MRTS9Gu9U3Cqj5xJMb_:-MRU9ZTC5RPPwNmz_1Rt:b-h31xon) ([raw file](https://github.com/pmem/fio/blob/dec5cc2cc0bd2d442dd103d11685e40d14874563/engines/librpma_gpspm.c#L164)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

DDIR_TRIM? I'm just joking. What is the difference for you guys?
</blockquote></details>

GPSPM does not support reads, so it looks strange.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/153)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_gpspm.c, line 164 at r1](https://reviewable.io/reviews/pmem/fio/153#-MRTS9Gu9U3Cqj5xJMb_:-MRU9zZlBpPctXdPjozb:b-gsdp0) ([raw file](https://github.com/pmem/fio/blob/dec5cc2cc0bd2d442dd103d11685e40d14874563/engines/librpma_gpspm.c#L164)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

GPSPM does not support reads, so it looks strange.
</blockquote></details>

... and it is a bit misleading.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/153)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 164 at r1](https://reviewable.io/reviews/pmem/fio/153#-MRTS9Gu9U3Cqj5xJMb_:-MRU9uvz7Bp2Y21gkMBu:bch471h) ([raw file](https://github.com/pmem/fio/blob/dec5cc2cc0bd2d442dd103d11685e40d14874563/engines/librpma_gpspm.c#L164)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

... and it is a bit misleading.
</blockquote></details>

It DID not support reads. Which is not true anymore.
Besides this block size has nothing to do with actual read/write operations.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/153)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_gpspm.c, line 164 at r1](https://reviewable.io/reviews/pmem/fio/153#-MRTS9Gu9U3Cqj5xJMb_:-MRUAYXx3WA-3Rz7eCOn:b32w0x) ([raw file](https://github.com/pmem/fio/blob/dec5cc2cc0bd2d442dd103d11685e40d14874563/engines/librpma_gpspm.c#L164)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It DID not support reads. Which is not true anymore.
Besides this block size has nothing to do with actual read/write operations.
</blockquote></details>

OK

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/153#-:-MRUAb119IhK8N4d-F2V:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/153#-:-MRUBP3U5encNmsw2zRw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/153)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
