### PR TITLE
rpma: gpspm: a multi-connection (multi-thread) mode

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/94)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/94)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 139 at r1](https://reviewable.io/reviews/pmem/fio/94#-MQBxyil4U5PcxbZrSgN:-MQBxyil4U5PcxbZrSgO:b8cqpho) ([raw file](https://github.com/pmem/fio/blob/c3d4a9c84f3ba070cd7eb0009ea8b63d6739505b/engines/librpma_gpspm.c#L139)):*
> ```
> void
> ```
int -> proper error handling is required
(or forget about error handling at all)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/94)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 153 at r1](https://reviewable.io/reviews/pmem/fio/94#-MQCK04xCEY5DFE22LOV:-MQCK04y74YU-WmY1zKC:bq1vhsk) ([raw file](https://github.com/pmem/fio/blob/c3d4a9c84f3ba070cd7eb0009ea8b63d6739505b/engines/librpma_gpspm.c#L153)):*
> ```
> 	if (port_ul + td->thread_number - 1 >= UINT_MAX)
> 		return;
> 	port_new = port_ul + td->thread_number - 1;
> ```

```
	port_new = port_ul + td->thread_number - 1;

	if (port_new >= UINT_MAX)
		return;

```
___
*[examples/librpma_gpspm-server.fio, line 15 at r1](https://reviewable.io/reviews/pmem/fio/94#-MQC7hKW-6Ps_WZdTxAh:-MQC7hKX9MhpcaYfqrTq:bqg1mhr) ([raw file](https://github.com/pmem/fio/blob/c3d4a9c84f3ba070cd7eb0009ea8b63d6739505b/examples/librpma_gpspm-server.fio#L15)):*
> ```
> accept and execute
> ```

`acceptS and executeS`
___
*[examples/librpma_gpspm-server.fio, line 17 at r1](https://reviewable.io/reviews/pmem/fio/94#-MQC87q98fOGsh76Wb-3:-MQC87qA7sKaiJu_O2SD:b-hoq3zf) ([raw file](https://github.com/pmem/fio/blob/c3d4a9c84f3ba070cd7eb0009ea8b63d6739505b/examples/librpma_gpspm-server.fio#L17)):*
> ```
> a termination notice 
> ```

`the termination notice `

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/94)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma_gpspm.c, line 139 at r1](https://reviewable.io/reviews/pmem/fio/94#-MQBxyil4U5PcxbZrSgN:-MQCgALo4NWpr1hXyU8s:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c3d4a9c84f3ba070cd7eb0009ea8b63d6739505b/engines/librpma_gpspm.c#L139)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> void
> ```
int -> proper error handling is required
(or forget about error handling at all)
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 153 at r1](https://reviewable.io/reviews/pmem/fio/94#-MQCK04xCEY5DFE22LOV:-MQCgB-t20wGlVMdoQze:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c3d4a9c84f3ba070cd7eb0009ea8b63d6739505b/engines/librpma_gpspm.c#L153)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	if (port_ul + td->thread_number - 1 >= UINT_MAX)
> 		return;
> 	port_new = port_ul + td->thread_number - 1;
> ```

```
	port_new = port_ul + td->thread_number - 1;

	if (port_new >= UINT_MAX)
		return;

```
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/94)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[examples/librpma_gpspm-server.fio, line 15 at r1](https://reviewable.io/reviews/pmem/fio/94#-MQC7hKW-6Ps_WZdTxAh:-MQCgIRB0mIS3exCyIZS:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c3d4a9c84f3ba070cd7eb0009ea8b63d6739505b/examples/librpma_gpspm-server.fio#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> accept and execute
> ```

`acceptS and executeS`
</blockquote></details>

Done.
___
*[examples/librpma_gpspm-server.fio, line 17 at r1](https://reviewable.io/reviews/pmem/fio/94#-MQC87q98fOGsh76Wb-3:-MQCgYKd1RuDbfQZJAfk:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c3d4a9c84f3ba070cd7eb0009ea8b63d6739505b/examples/librpma_gpspm-server.fio#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> a termination notice 
> ```

`the termination notice `
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/94)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[examples/librpma_gpspm-server.fio, line 21 at r2](https://reviewable.io/reviews/pmem/fio/94#-MQCgxEE9Aq7fZzbW6VP:-MQCgxEE9Aq7fZzbW6VQ:b-ukvk7h) ([raw file](https://github.com/pmem/fio/blob/5eaaee733beb2f063a2944448230e71ded71691f/examples/librpma_gpspm-server.fio#L21)):*
> ```
> numjobs=1
> ```
shall numjobs be placed next to the comment above?
and ```port``` shall be also closer to ```numjobs``` as they are related one to each other

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/94)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/94#-:-MQChZ6t9nNbIORspGFO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/94)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/94)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/librpma_gpspm-server.fio, line 21 at r2](https://reviewable.io/reviews/pmem/fio/94#-MQCgxEE9Aq7fZzbW6VP:-MQChu1iDKwbRR95OjzK:b3hayka) ([raw file](https://github.com/pmem/fio/blob/5eaaee733beb2f063a2944448230e71ded71691f/examples/librpma_gpspm-server.fio#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> numjobs=1
> ```
shall numjobs be placed next to the comment above?
and ```port``` shall be also closer to ```numjobs``` as they are related one to each other

</blockquote></details>

`numjobs` relates to the comment above. It cannot be placed in the global section. On the other hand, the `port` is placed in the global section of all our examples. I think we can live with it. Maybe it will be somehow fixed during possible uniformization.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/94)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
@janekmi please rebase

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/94#-:-MQCj6aN6G3ExXjxWfLU:b-f7mnt4)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/94#-:-MQCjXid0vV6m4GYuMpC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/94)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
