### PR TITLE
rpma: set flush_type

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/45)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/45)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma.c, line 265 at r1](https://reviewable.io/reviews/pmem/fio/45#-MKnzvCT33tSbbf7-HlT:-MKnzvCU2hIsj7FGxBjj:b-h2bc2y) ([raw file](https://github.com/pmem/fio/blob/92ff702e2f3e0152511a21231c3a991ee865d70c/engines/librpma.c#L265)):*
Those two lines:

> ```
> 	cd->ws_size = ws->size;
> 	td->io_ops_data = cd;
> ```

should be located just before `return 0;` as it was before.
___
*[engines/librpma.c, line 267 at r1](https://reviewable.io/reviews/pmem/fio/45#-MKo-7vg9cq_gMPHz9e6:-MKo-7vg9cq_gMPHz9e7:bgtbcqv) ([raw file](https://github.com/pmem/fio/blob/92ff702e2f3e0152511a21231c3a991ee865d70c/engines/librpma.c#L267)):*
> ```
> /* set flush type */
> ```

`/* get flush type of the remote node */`
___
*[engines/librpma.c, line 275 at r1](https://reviewable.io/reviews/pmem/fio/45#-MKo-s6x1ACJrnYm8SoI:-MKo-s6x1ACJrnYm8SoJ:b-6vb5jr) ([raw file](https://github.com/pmem/fio/blob/92ff702e2f3e0152511a21231c3a991ee865d70c/engines/librpma.c#L275)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	if (remote_flush_type & RPMA_MR_USAGE_FLUSH_TYPE_PERSISTENT)
> 		cd->flush_type = RPMA_FLUSH_TYPE_PERSISTENT;
> 	else
> 		cd->flush_type = RPMA_FLUSH_TYPE_VISIBILITY;
> ```
</details>


```
cd->flush_type = (remote_flush_type & RPMA_MR_USAGE_FLUSH_TYPE_PERSISTENT) ?
		RPMA_FLUSH_TYPE_PERSISTENT : RPMA_FLUSH_TYPE_VISIBILITY;
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/45)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma.c, line 272 at r1](https://reviewable.io/reviews/pmem/fio/45#-MKo18Va2ocrCwbKzjq-:-MKo18Va2ocrCwbKzjq0:b-28rvxd) ([raw file](https://github.com/pmem/fio/blob/92ff702e2f3e0152511a21231c3a991ee865d70c/engines/librpma.c#L272)):*
> ```
> 	}
> 	if (remote_flush_type & RPMA_MR_USAGE_FLUSH_TYPE_PERSISTENT)
> ```

Add one empty line in between, please.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/45)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 265 at r1](https://reviewable.io/reviews/pmem/fio/45#-MKnzvCT33tSbbf7-HlT:-MKo3qMN8i0XEnfQhp8Y:b-896fix) ([raw file](https://github.com/pmem/fio/blob/92ff702e2f3e0152511a21231c3a991ee865d70c/engines/librpma.c#L265)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Those two lines:

> ```
> 	cd->ws_size = ws->size;
> 	td->io_ops_data = cd;
> ```

should be located just before `return 0;` as it was before.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 267 at r1](https://reviewable.io/reviews/pmem/fio/45#-MKo-7vg9cq_gMPHz9e6:-MKo3w2R5ljEFkVD8xgn:b-896fix) ([raw file](https://github.com/pmem/fio/blob/92ff702e2f3e0152511a21231c3a991ee865d70c/engines/librpma.c#L267)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> /* set flush type */
> ```

`/* get flush type of the remote node */`
</blockquote></details>

Done.
___
*[engines/librpma.c, line 272 at r1](https://reviewable.io/reviews/pmem/fio/45#-MKo18Va2ocrCwbKzjq-:-MKo3z3o-3lhQ-_iDL1W:b-896fix) ([raw file](https://github.com/pmem/fio/blob/92ff702e2f3e0152511a21231c3a991ee865d70c/engines/librpma.c#L272)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	}
> 	if (remote_flush_type & RPMA_MR_USAGE_FLUSH_TYPE_PERSISTENT)
> ```

Add one empty line in between, please.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 275 at r1](https://reviewable.io/reviews/pmem/fio/45#-MKo-s6x1ACJrnYm8SoI:-MKo4JAW9pDwTSoeNwdp:b-896fix) ([raw file](https://github.com/pmem/fio/blob/92ff702e2f3e0152511a21231c3a991ee865d70c/engines/librpma.c#L275)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	if (remote_flush_type & RPMA_MR_USAGE_FLUSH_TYPE_PERSISTENT)
> 		cd->flush_type = RPMA_FLUSH_TYPE_PERSISTENT;
> 	else
> 		cd->flush_type = RPMA_FLUSH_TYPE_VISIBILITY;
> ```

```
cd->flush_type = (remote_flush_type & RPMA_MR_USAGE_FLUSH_TYPE_PERSISTENT) ?
		RPMA_FLUSH_TYPE_PERSISTENT : RPMA_FLUSH_TYPE_VISIBILITY;
```
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/45#-:-MKo56ZD1XmNHU5kuxbk:bdycpsm)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/45)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/45#-:-MKo923B0VV253DnnKn3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/45#-:-MKoCHMqD6i_WJuXj3SJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/45)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/45)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/45)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma.c, line 280 at r2](https://reviewable.io/reviews/pmem/fio/45#-MKoyYxjAFfZ_csMxnq5:-MKoyYxjAFfZ_csMxnq6:b-2l90io) ([raw file](https://github.com/pmem/fio/blob/c05948455de80f146a6b446cf60a8a2d0df456f8/engines/librpma.c#L280)):*
> ```C
> 		rpma_td_verror(td, ret, "rpma_conn_apply_remote_peer_cfg");
> 		goto peer_cfg_delete;
> 	}
> ```

How it is expected to work? You have to enable direct write to pmem if you are going to do the persistent flush type.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/45)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 280 at r2](https://reviewable.io/reviews/pmem/fio/45#-MKoyYxjAFfZ_csMxnq5:-MKp2K2B6bD1LbbRwuI_:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c05948455de80f146a6b446cf60a8a2d0df456f8/engines/librpma.c#L280)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

How it is expected to work? You have to enable direct write to pmem if you are going to do the persistent flush type.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/45#-:-MKp4Ktj1FRnsqFiSLqV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
