### PR TITLE
rpma: common: separate allocate_pmem() and free()

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #111
- [x] #112

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/113)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/113)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[Makefile, line 116 at r1](https://reviewable.io/reviews/pmem/fio/113#-MR-BBTb7M0lpp5gQcPI:-MR-BBTb7M0lpp5gQcPJ:b-wkcb19) ([raw file](https://github.com/pmem/fio/blob/e15d8ff6e23d49620597e09f1a303194f68197f2/Makefile#L116)):*
> ```
> ifdef librpma_common_SRCS
>   ENGINES += librpma_common
> endif
> ```

Is it really required ? Does `librpma_common` have to be an engine?
Why isn't  it enough to add `engines/librpma_common.c` to the list of sources of our both engines? (just like that):

```
ifdef CONFIG_LIBRPMA
  librpma_SRCS = engines/librpma.c engines/librpma_common.c
  librpma_LIBS = -lrpma -lpmem
  ENGINES += librpma
endif
ifdef CONFIG_LIBRPMA_GPSPM
  librpma_gpspm_SRCS = engines/librpma_gpspm.c engines/librpma_gpspm_flush.pb-c.c engines/librpma_common.c
  librpma_gpspm_LIBS = -lrpma -lpmem -lprotobuf-c
  ENGINES += librpma_gpspm
endif
```
___
*[engines/librpma_common.c, line 89 at r1](https://reviewable.io/reviews/pmem/fio/113#-MR-AtaX4SsLuHR4JqO4:-MR-AtaX4SsLuHR4JqO5:b-ftz7ui) ([raw file](https://github.com/pmem/fio/blob/e15d8ff6e23d49620597e09f1a303194f68197f2/engines/librpma_common.c#L89)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
> 	/* check size of allocated persistent memory */
> 	if (size_mmap <= ws_offset) {
> 		log_err(
> 			"fio: %s is too small to handle so many threads (%zu <= %zu)\n",
> 			filename, size_mmap, ws_offset);
> 		goto err_unmap;
> 	} else if (size_mmap < ws_offset + size) {
> 		log_err(
> 			"fio: %s is too small to handle so many threads (%zu < %zu)\n",
> 			filename, size_mmap, ws_offset + size);
> 		goto err_unmap;
> 	}
> ```
</details>


This is enough and does exactly the same (because the first ws_offset equals 0 and the second condition equals the first one in the next thread):

```
	/* check size of allocated persistent memory */
	if (size_mmap < ws_offset + size) {
		log_err(
			"fio: %s is too small to handle so many threads (%zu < %zu)\n",
			filename, size_mmap, ws_offset + size);
		goto err_unmap;
	}
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/113)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[Makefile, line 116 at r1](https://reviewable.io/reviews/pmem/fio/113#-MR-BBTb7M0lpp5gQcPI:-MR-OIsmBvQ-KuUsEgRO:b-78x4ww) ([raw file](https://github.com/pmem/fio/blob/e15d8ff6e23d49620597e09f1a303194f68197f2/Makefile#L116)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ifdef librpma_common_SRCS
>   ENGINES += librpma_common
> endif
> ```

Is it really required ? Does `librpma_common` have to be an engine?
Why isn't  it enough to add `engines/librpma_common.c` to the list of sources of our both engines? (just like that):

```
ifdef CONFIG_LIBRPMA
  librpma_SRCS = engines/librpma.c engines/librpma_common.c
  librpma_LIBS = -lrpma -lpmem
  ENGINES += librpma
endif
ifdef CONFIG_LIBRPMA_GPSPM
  librpma_gpspm_SRCS = engines/librpma_gpspm.c engines/librpma_gpspm_flush.pb-c.c engines/librpma_common.c
  librpma_gpspm_LIBS = -lrpma -lpmem -lprotobuf-c
  ENGINES += librpma_gpspm
endif
```

</blockquote></details>

Something like:

```
if (defined(CONFIG_LIBRPMA) || defined(CONFIG_LIBRPMA_GPSPM))
  SOURCE += librpma_common
endif
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/113)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[Makefile, line 116 at r1](https://reviewable.io/reviews/pmem/fio/113#-MR-BBTb7M0lpp5gQcPI:-MR-P0VpBb6acW6ZLQKl:b-856j1a) ([raw file](https://github.com/pmem/fio/blob/e15d8ff6e23d49620597e09f1a303194f68197f2/Makefile#L116)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Something like:

```
if (defined(CONFIG_LIBRPMA) || defined(CONFIG_LIBRPMA_GPSPM))
  SOURCE += librpma_common
endif
```
</blockquote></details>

I meant:

```
if (defined(CONFIG_LIBRPMA) || defined(CONFIG_LIBRPMA_GPSPM))
  SOURCE += engines/librpma_common.c
endif
```

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/113)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[Makefile, line 116 at r1](https://reviewable.io/reviews/pmem/fio/113#-MR-BBTb7M0lpp5gQcPI:-MR-Ql9s-QB6bIrakSKs:bkrm581) ([raw file](https://github.com/pmem/fio/blob/e15d8ff6e23d49620597e09f1a303194f68197f2/Makefile#L116)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I meant:

```
if (defined(CONFIG_LIBRPMA) || defined(CONFIG_LIBRPMA_GPSPM))
  SOURCE += engines/librpma_common.c
endif
```
</blockquote></details>

I think we should address this issue in a separate PR.
___
*[engines/librpma_common.c, line 89 at r1](https://reviewable.io/reviews/pmem/fio/113#-MR-AtaX4SsLuHR4JqO4:-MR-R9VC5n2wQAzHovb9:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e15d8ff6e23d49620597e09f1a303194f68197f2/engines/librpma_common.c#L89)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	/* check size of allocated persistent memory */
> 	if (size_mmap <= ws_offset) {
> 		log_err(
> 			"fio: %s is too small to handle so many threads (%zu <= %zu)\n",
> 			filename, size_mmap, ws_offset);
> 		goto err_unmap;
> 	} else if (size_mmap < ws_offset + size) {
> 		log_err(
> 			"fio: %s is too small to handle so many threads (%zu < %zu)\n",
> 			filename, size_mmap, ws_offset + size);
> 		goto err_unmap;
> 	}
> ```

This is enough and does exactly the same (because the first ws_offset equals 0 and the second condition equals the first one in the next thread):

```
	/* check size of allocated persistent memory */
	if (size_mmap < ws_offset + size) {
		log_err(
			"fio: %s is too small to handle so many threads (%zu < %zu)\n",
			filename, size_mmap, ws_offset + size);
		goto err_unmap;
	}
```
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/113)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[Makefile, line 116 at r1](https://reviewable.io/reviews/pmem/fio/113#-MR-BBTb7M0lpp5gQcPI:-MR-RFxB0zQ_Y02N4C2O:b8pei5l) ([raw file](https://github.com/pmem/fio/blob/e15d8ff6e23d49620597e09f1a303194f68197f2/Makefile#L116)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we should address this issue in a separate PR.
</blockquote></details>

Yes, that's right.

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/113#-:-MR-RPqf7J7W61L-RdYo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/113#-:-MR-_pXz-rPJVH8vzzvP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
