### PR TITLE
aof: add librpma_aof_update.proto (the first approximation)

### PR DESCRIPTION
**Pull request by ldorau**
Missing:
- [x] generated header

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/214)

### CODE REVIEW

**Comment by ldorau** [comment]
The generated header will be added soon.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/214)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_aof_update.proto, line 6 at r1](https://reviewable.io/reviews/pmem/fio/214#-MTkb07OAAJmVhvlkAZi:-MTkb07OAAJmVhvlkAZj:b46qaoy) ([raw file](https://github.com/pmem/fio/blob/6cb1103cc1d5425fea72087f3a804672b88109ce/engines/librpma_aof_update.proto#L6)):*
> ```protobuf
>     /*
>      * an offset of the 1st region to be flushed
>      * within its memory registration
> ```

These two lines are unnecessarily short.
___
*[engines/librpma_aof_update.proto, line 10 at r1](https://reviewable.io/reviews/pmem/fio/214#-MTka0FBC3U2fkHrqhU0:-MTka0FBC3U2fkHrqhU1:bu2ruqs) ([raw file](https://github.com/pmem/fio/blob/6cb1103cc1d5425fea72087f3a804672b88109ce/engines/librpma_aof_update.proto#L10)):*
> ```protobuf
>     required fixed64 offset_flush = 1;
>     /* a length of the 1st region to be flushed */
>     required fixed64 length_flush = 2;
> ```

Maybe name them:
- append_offset
- append_length
?
___
*[engines/librpma_aof_update.proto, line 16 at r1](https://reviewable.io/reviews/pmem/fio/214#-MTkaZ2VAwQlEwjw_XOo:-MTkaZ2VAwQlEwjw_XOp:b-qw6zpq) ([raw file](https://github.com/pmem/fio/blob/6cb1103cc1d5425fea72087f3a804672b88109ce/engines/librpma_aof_update.proto#L16)):*
> ```protobuf
>      * within its memory registration
>      */
>     required fixed64 offset_write = 3;
> ```

- pointer_offset?
___
*[engines/librpma_aof_update.proto, line 18 at r1](https://reviewable.io/reviews/pmem/fio/214#-MTkabkq-krTdRvg6tRC:-MTkaPZc3qyPH_auuQP1:b-6a3a8l) ([raw file](https://github.com/pmem/fio/blob/6cb1103cc1d5425fea72087f3a804672b88109ce/engines/librpma_aof_update.proto#L18)):*
> ```protobuf
>     required fixed64 offset_write = 3;
>     /* a value to be written atomically at 'offset_write' */
>     required fixed64 value_write = 4;
> ```

I think we should calculate the new pointer value from other parameters, what do you think?
___
*[engines/librpma_aof_update.proto, line 25 at r1](https://reviewable.io/reviews/pmem/fio/214#-MTk_rlF7AtVbIyyclqX:-MTk_rlG5fJwp5EYoOie:b-ofsf4k) ([raw file](https://github.com/pmem/fio/blob/6cb1103cc1d5425fea72087f3a804672b88109ce/engines/librpma_aof_update.proto#L25)):*
> ```protobuf
> 
> message AOF_update_response {
>     /* the operation context of the 2nd flush request */
> ```

I think the `op_context` is common for the whole `AOF_update_request` e.g.:

```c
/* the user-define AOF update request operation context */
```

What do you think?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/214)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_aof_update.proto, line 6 at r1](https://reviewable.io/reviews/pmem/fio/214#-MTkb07OAAJmVhvlkAZi:-MTo2Azw1kK_hC_YURoa:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6cb1103cc1d5425fea72087f3a804672b88109ce/engines/librpma_aof_update.proto#L6)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

These two lines are unnecessarily short.
</blockquote></details>

Done.
___
*[engines/librpma_aof_update.proto, line 10 at r1](https://reviewable.io/reviews/pmem/fio/214#-MTka0FBC3U2fkHrqhU0:-MTo2N8U3Fk8VwI2mH9i:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6cb1103cc1d5425fea72087f3a804672b88109ce/engines/librpma_aof_update.proto#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Maybe name them:
- append_offset
- append_length
?
</blockquote></details>

Done.
___
*[engines/librpma_aof_update.proto, line 16 at r1](https://reviewable.io/reviews/pmem/fio/214#-MTkaZ2VAwQlEwjw_XOo:-MTo2TQf-veB8m9PAYdF:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6cb1103cc1d5425fea72087f3a804672b88109ce/engines/librpma_aof_update.proto#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

- pointer_offset?
</blockquote></details>

Done.
___
*[engines/librpma_aof_update.proto, line 18 at r1](https://reviewable.io/reviews/pmem/fio/214#-MTkabkq-krTdRvg6tRC:-MTo2Znr-ezRUCDT1jGv:b3iaqwg) ([raw file](https://github.com/pmem/fio/blob/6cb1103cc1d5425fea72087f3a804672b88109ce/engines/librpma_aof_update.proto#L18)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we should calculate the new pointer value from other parameters, what do you think?
</blockquote></details>

`= append_offset + append_length`
___
*[engines/librpma_aof_update.proto, line 25 at r1](https://reviewable.io/reviews/pmem/fio/214#-MTk_rlF7AtVbIyyclqX:-MTo3HAd6Lw28TtQuRm6:bbgyb39) ([raw file](https://github.com/pmem/fio/blob/6cb1103cc1d5425fea72087f3a804672b88109ce/engines/librpma_aof_update.proto#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think the `op_context` is common for the whole `AOF_update_request` e.g.:

```c
/* the user-define AOF update request operation context */
```

What do you think?
</blockquote></details>

`/* a user-defined context of the AOF update operation's request */`

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/214)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_aof_update.proto, line 18 at r1](https://reviewable.io/reviews/pmem/fio/214#-MTkabkq-krTdRvg6tRC:-MTo3niR4k2ZY2XZBOY2:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6cb1103cc1d5425fea72087f3a804672b88109ce/engines/librpma_aof_update.proto#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`= append_offset + append_length`
</blockquote></details>

Done.
___
*[engines/librpma_aof_update.proto, line 25 at r1](https://reviewable.io/reviews/pmem/fio/214#-MTk_rlF7AtVbIyyclqX:-MTo3nLe0IMhKJ9n_XNG:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6cb1103cc1d5425fea72087f3a804672b88109ce/engines/librpma_aof_update.proto#L25)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`/* a user-defined context of the AOF update operation's request */`
</blockquote></details>

Done.

**Comment by ldorau** [comment]
Added the generated header.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/214#-:-MTp85l7CpEA4SYIdFdD:bnfp4nl)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/214)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_aof_update.pb-c.h, line 1 at r2](https://reviewable.io/reviews/pmem/fio/214#-MTtxRn29GXKnEGUDWBb:-MTtxRn29GXKnEGUDWBc:b-jmwusa) ([raw file](https://github.com/pmem/fio/blob/a80787e317fe269c58c7f8a84a681206ba766641/engines/librpma_aof_update.pb-c.h#L1)):*
> ```objc
> /* Generated by the protocol buffer compiler.  DO NOT EDIT! */
> ```

Missing copyright.
___
*[engines/librpma_aof_update.pb-c.c, line 1 at r2](https://reviewable.io/reviews/pmem/fio/214#-MTtxP8B45QfWTeg0-sx:-MTtxP8B45QfWTeg0-sy:b-jmwusa) ([raw file](https://github.com/pmem/fio/blob/a80787e317fe269c58c7f8a84a681206ba766641/engines/librpma_aof_update.pb-c.c#L1)):*
> ```C
> /* Generated by the protocol buffer compiler.  DO NOT EDIT! */
> ```

Missing copyright.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/214)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_aof_update.pb-c.h, line 1 at r2](https://reviewable.io/reviews/pmem/fio/214#-MTtxRn29GXKnEGUDWBb:-MTtzd3SB5Np7hm2q9LG:b-896fix) ([raw file](https://github.com/pmem/fio/blob/a80787e317fe269c58c7f8a84a681206ba766641/engines/librpma_aof_update.pb-c.h#L1)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Missing copyright.
</blockquote></details>

Done.
___
*[engines/librpma_aof_update.pb-c.c, line 1 at r2](https://reviewable.io/reviews/pmem/fio/214#-MTtxP8B45QfWTeg0-sx:-MTtzdQWAL6Hm_yXrsnQ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/a80787e317fe269c58c7f8a84a681206ba766641/engines/librpma_aof_update.pb-c.c#L1)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Missing copyright.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/214#-:-MTu-8C4EzNhb-80i-4u:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
