### PR TITLE
rpma: replace descriptors with descriptor

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/173)

### CODE REVIEW

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/173#-:-MRZBnQxCaK7MNCdtd9f:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/173)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_common.h, line 60 at r1](https://reviewable.io/reviews/pmem/fio/173#-MRZC8RxC-6eWd4Zz1_X:-MRZC8RxC-6eWd4Zz1_Y:b-mp1k74) ([raw file](https://github.com/pmem/fio/blob/af4bc43f72f865fb28541d7c0acdf1e88f39d1fa/engines/librpma_common.h#L60)):*
> ```
> DESCRIPTORS_MAX_SIZE
> ```
DESCRIPTOR_MAX_SIZE

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/173)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[engines/librpma_common.h, line 60 at r1](https://reviewable.io/reviews/pmem/fio/173#-MRZC8RxC-6eWd4Zz1_X:-MRZCql22w5SkeGTNz7J:b-896fix) ([raw file](https://github.com/pmem/fio/blob/af4bc43f72f865fb28541d7c0acdf1e88f39d1fa/engines/librpma_common.h#L60)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> DESCRIPTORS_MAX_SIZE
> ```
DESCRIPTOR_MAX_SIZE
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/173#-:-MRZEOUL3eNWn1Qweh-V:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
