### PR TITLE
 rpma: common: separate client_init

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #120
- [x] #123
- [x] #127

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/124)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/124#-:-MR4mUdP3EYHuVRysLtR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/124#-:-MR4rxfX0I6jtusG7Txs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
