### PR TITLE
rpma: adapt to fs-dax mode

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/256)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/fio/256#-Mf3XeRN0jd6VBLGrZJg:-Mf3XeRN0jd6VBLGrZJh:bhk2hee) (no related file):*
Please rebase it on https://github.com/pmem/fio/tree/rpma and change the PR to target the rpma branch.

---
___
*[engines/librpma_fio.c, line 89 at r1](https://reviewable.io/reviews/pmem/fio/256#-Mf3W_Oa2HC69pTGNxl4:-Mf3W_Oa2HC69pTGNxl5:btccgxc) ([raw file](https://github.com/pmem/fio/blob/d3702d687f5d98e78b12357fd43dcc3072f76994/engines/librpma_fio.c#L89)):*
> ```C
> 	}
> 
> 	if (strncmp(filename, "/dev/dax", strlen("/dev/dax")) == 0)
> ```

Why you have decided to detect the DeviceDAX vs FileSystemDAX by name, which may be problematic, instead of using a clean solution e.g. by checking `td->o.nr_files` ?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[engines/librpma_fio.c, line 89 at r1](https://reviewable.io/reviews/pmem/fio/256#-Mf3W_Oa2HC69pTGNxl4:-Mf3xgI0-xLw8F6pqPr1:bh8duuh) ([raw file](https://github.com/pmem/fio/blob/d3702d687f5d98e78b12357fd43dcc3072f76994/engines/librpma_fio.c#L89)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why you have decided to detect the DeviceDAX vs FileSystemDAX by name, which may be problematic, instead of using a clean solution e.g. by checking `td->o.nr_files` ?
</blockquote></details>

There is a Linux command that does file type checking:
https://linux.die.net/man/1/file

PMem files names are fixed:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_storage_devices/using-nvdimm-persistent-memory-storage_managing-storage-devices#nvdimm-access-modes_using-nvdimm-persistent-memory-storage

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[engines/librpma_fio.c, line 89 at r1](https://reviewable.io/reviews/pmem/fio/256#-Mf3W_Oa2HC69pTGNxl4:-Mf5jxSNEfPDanrRzE4z:b-ibv6n1) ([raw file](https://github.com/pmem/fio/blob/d3702d687f5d98e78b12357fd43dcc3072f76994/engines/librpma_fio.c#L89)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

There is a Linux command that does file type checking:
https://linux.die.net/man/1/file

PMem files names are fixed:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_storage_devices/using-nvdimm-persistent-memory-storage_managing-storage-devices#nvdimm-access-modes_using-nvdimm-persistent-memory-storage


</blockquote></details>

td->o.nr_files is 1 per thread since td is the structure of thread_data.

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[engines/librpma_fio.c, line 89 at r1](https://reviewable.io/reviews/pmem/fio/256#-Mf3W_Oa2HC69pTGNxl4:-Mf5ntvY6zCqE8sPt-bC:bm09wo3) ([raw file](https://github.com/pmem/fio/blob/d3702d687f5d98e78b12357fd43dcc3072f76994/engines/librpma_fio.c#L89)):*
Hi @ewanglong @janekmi @grom72 

If we can pass `struct fio_file *f` instead of `const char *filename` into librpma_fio_allocate_pmem(), we can detect the DeviceDAX vs FileSystemDAX by file type (f->filetype == FIO_TYPE_FILE or f->filetype == FIO_TYPE_CHAR).

@grom72 
> PMem files names are fixed:
For FSDAX, I think we will use the files in pmemX instead of the whole pmemX device.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[engines/librpma_fio.c, line 89 at r1](https://reviewable.io/reviews/pmem/fio/256#-Mf3W_Oa2HC69pTGNxl4:-Mf6__fw1HyXJDCNvbAZ:beiydei) ([raw file](https://github.com/pmem/fio/blob/d3702d687f5d98e78b12357fd43dcc3072f76994/engines/librpma_fio.c#L89)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @ewanglong @janekmi @grom72 

If we can pass `struct fio_file *f` instead of `const char *filename` into librpma_fio_allocate_pmem(), we can detect the DeviceDAX vs FileSystemDAX by file type (f->filetype == FIO_TYPE_FILE or f->filetype == FIO_TYPE_CHAR).

@grom72 
> PMem files names are fixed:
For FSDAX, I think we will use the files in pmemX instead of the whole pmemX device.
</blockquote></details>

I would pass `struct fio_file *f` instead of `const char *filename` into `librpma_fio_allocate_pmem()` as @yangx-jy suggested.

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong and @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)

___
*[engines/librpma_fio.c, line 90 at r2](https://reviewable.io/reviews/pmem/fio/256#-Mf78JG-AkjCXHMtq6wW:-Mf78JG-AkjCXHMtq6wX:bd0u989) ([raw file](https://github.com/pmem/fio/blob/c8e5d84bf9d9fa848ce7ba378645902fa42fe7e0/engines/librpma_fio.c#L90)):*
> ```C
> 
> 	if (f->filetype == FIO_TYPE_CHAR)
> 		ws_offset = (td->thread_number - 1) * size;
> ```

I recommend putting here comments.

```c
	if (f->filetype == FIO_TYPE_CHAR) {
               /* Each thread uses a separate offset within DeviceDAX. */
		ws_offset = (td->thread_number - 1) * size;
	} else {
                /* Each thread uses a separate FileSystemDAX file. No offset is needed. */
		ws_offset = 0;
        }
```

**Note**: Because of having multiple lines of code under the if-else statement you have to also add `{}`.

**Review by yangx-jy — COMMENTED** [review]
Apart from Jan's comment (Add )

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256#-:-Mf7DS6q2Qe9z_yOwRU5:b-61a60r)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[engines/librpma_fio.c, line 90 at r2](https://reviewable.io/reviews/pmem/fio/256#-Mf78JG-AkjCXHMtq6wW:-Mf7Dgwp6-KXZtNaE4RZ:bj8w8ap) ([raw file](https://github.com/pmem/fio/blob/c8e5d84bf9d9fa848ce7ba378645902fa42fe7e0/engines/librpma_fio.c#L90)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I recommend putting here comments.

```c
	if (f->filetype == FIO_TYPE_CHAR) {
               /* Each thread uses a separate offset within DeviceDAX. */
		ws_offset = (td->thread_number - 1) * size;
	} else {
                /* Each thread uses a separate FileSystemDAX file. No offset is needed. */
		ws_offset = 0;
        }
```

**Note**: Because of having multiple lines of code under the if-else statement you have to also add `{}`.
</blockquote></details>

Apart from Jan's comment, it looks good to me. ^_^

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256)* status: 0 of 28 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/256#-Mf3XeRN0jd6VBLGrZJg:-Mf7J7Qu8959tzutviDB:bq01jif) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please rebase it on https://github.com/pmem/fio/tree/rpma and change the PR to target the rpma branch.
</blockquote></details>

Please change the PR to target the rpma branch.

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 28 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256)* status: 2 of 28 files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 28 files at r3, 26 of 26 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong and @yangx-jy)

___
*[engines/librpma_fio.c, line 90 at r2](https://reviewable.io/reviews/pmem/fio/256#-Mf78JG-AkjCXHMtq6wW:-Mf7KLBiEVCMbZyn-rHE:b-eznkwf) ([raw file](https://github.com/pmem/fio/blob/c8e5d84bf9d9fa848ce7ba378645902fa42fe7e0/engines/librpma_fio.c#L90)):*
> Note: Because of having multiple lines of code under the if-else statement you have to also add {}.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/fio/256#-Mf3XeRN0jd6VBLGrZJg:-Mf7KUdk3vZf21wd9w5-:blzmj1z) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please change the PR to target the rpma branch.
</blockquote></details>

Done by @janekmi 

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 28 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[engines/librpma_fio.c, line 90 at r2](https://reviewable.io/reviews/pmem/fio/256#-Mf78JG-AkjCXHMtq6wW:-Mf7OHsiB72-rhCR87QB:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c8e5d84bf9d9fa848ce7ba378645902fa42fe7e0/engines/librpma_fio.c#L90)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> Note: Because of having multiple lines of code under the if-else statement you have to also add {}.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256#-:-Mf7PpLf-jpUE3kQ5L1t:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by yangx-jy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256#-:-Mf7Qi3J5J6gRrlGs4XB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256#-:-Mf7SDS2EsUe3yV6Joqz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/256)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
