### PR TITLE
rpma: basic engine scaffolding

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/1)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/1#-:-MJ224vN9_CRtiridUgB:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 69 at r1](https://reviewable.io/reviews/pmem/fio/1#-MJ227XhBEIMSF1T4W1O:-MJ227XhBEIMSF1T4W1P:bgn33e0) ([raw file](https://github.com/pmem/fio/blob/4dcdd7d43c80e338fda045679d8185a59ab18576/engines/librpma.c#L69)):*
> ```
> ret
> ```
0

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/1)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma.c, line 69 at r1](https://reviewable.io/reviews/pmem/fio/1#-MJ227XhBEIMSF1T4W1O:-MJ24W2H4rIjuzpOckMS:b-896fix) ([raw file](https://github.com/pmem/fio/blob/4dcdd7d43c80e338fda045679d8185a59ab18576/engines/librpma.c#L69)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> ret
> ```
0
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/1)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/1#-:-MJ2AwU89zedQ78Nv-f3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/1#-:-MJ5PZ1g-4H_156sEF9Q:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Pull request merged**
