### PR TITLE
rpma: getevents and event implementation

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/19)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/19)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 378 at r1](https://reviewable.io/reviews/pmem/fio/19#-MJYByvx0eMafGFSld1y:-MJYByvx0eMafGFSld1z:bsfyaeh) ([raw file](https://github.com/pmem/fio/blob/ec78d7a466a576e90e479d48c9ed4920dc31c880/engines/librpma.c#L378)):*
> ```
> ++cd->io_u_completed_nr
> ```
cd->io_u_completed_nr++
___
*[engines/librpma.c, line 385 at r1](https://reviewable.io/reviews/pmem/fio/19#-MJYAwZr3OsIc4LIqniw:-MJYAoaI6o-Lk-i6CNbx:bt006ng) ([raw file](https://github.com/pmem/fio/blob/ec78d7a466a576e90e479d48c9ed4920dc31c880/engines/librpma.c#L385)):*
> ```C
> 		cd->io_us_flight[i - cmpl_num] = cd->io_us_flight[i];
> 	cd->io_u_flight_nr -= cmpl_num;
> ```

empty line
___
*[engines/librpma.c, line 401 at r1](https://reviewable.io/reviews/pmem/fio/19#-MJYBq0aBDbdSzGLZISC:-MJYBq0aBDbdSzGLZISD:b-9szgt3) ([raw file](https://github.com/pmem/fio/blob/ec78d7a466a576e90e479d48c9ed4920dc31c880/engines/librpma.c#L401)):*
> ```
> --cd->io_u_completed_nr
> ```
cd->io_u_completed_nr--
___
*[engines/librpma.c, line 404 at r1](https://reviewable.io/reviews/pmem/fio/19#-MJYAxj82A7AqWKSsWaq:-MJYAxj82A7AqWKSsWar:b3kqx) ([raw file](https://github.com/pmem/fio/blob/ec78d7a466a576e90e479d48c9ed4920dc31c880/engines/librpma.c#L404)):*
> ```C
> 
> 	dprint_io_u(io_u, "client_event");
> ```

.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/19)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 366 at r1](https://reviewable.io/reviews/pmem/fio/19#-MJYIjHp3blHcTRIeQQb:-MJYIjHq4q3CaM4jGAeR:b-ohjcar) ([raw file](https://github.com/pmem/fio/blob/ec78d7a466a576e90e479d48c9ed4920dc31c880/engines/librpma.c#L366)):*
> ```
> 				"no matching io_u for received completion found (io_u_index=%u)\n",
> 				io_u_index);
> ```

too huge indentation

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/19)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 366 at r1](https://reviewable.io/reviews/pmem/fio/19#-MJYIjHp3blHcTRIeQQb:-MJYPjSF4aOWPFQspwXu:b-896fix) ([raw file](https://github.com/pmem/fio/blob/ec78d7a466a576e90e479d48c9ed4920dc31c880/engines/librpma.c#L366)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 				"no matching io_u for received completion found (io_u_index=%u)\n",
> 				io_u_index);
> ```

too huge indentation
</blockquote></details>

Done.
___
*[engines/librpma.c, line 378 at r1](https://reviewable.io/reviews/pmem/fio/19#-MJYByvx0eMafGFSld1y:-MJYPqIO488XouZ2-c-y:b-896fix) ([raw file](https://github.com/pmem/fio/blob/ec78d7a466a576e90e479d48c9ed4920dc31c880/engines/librpma.c#L378)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> ++cd->io_u_completed_nr
> ```
cd->io_u_completed_nr++
</blockquote></details>

Done.
___
*[engines/librpma.c, line 401 at r1](https://reviewable.io/reviews/pmem/fio/19#-MJYBq0aBDbdSzGLZISC:-MJYPqxJ8q-XpkTm7W5z:b-896fix) ([raw file](https://github.com/pmem/fio/blob/ec78d7a466a576e90e479d48c9ed4920dc31c880/engines/librpma.c#L401)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> --cd->io_u_completed_nr
> ```
cd->io_u_completed_nr--
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/19)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 340 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJ_ySmf5A76feJnAWmZ:-MJ_ySmf5A76feJnAWm_:b1m14ys) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L340)):*
> ```C
> 	if ((ret = rpma_conn_completion_wait(cd->conn))) {
> 		rpma_td_verror(td, ret, "rpma_conn_completion_wait");
> 		return -1;
> ```

return ret; ?
___
*[engines/librpma.c, line 346 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJ_yZMpBQVVMoWF0-n8:-MJ_yZMpBQVVMoWF0-n9:b3kqx) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L346)):*
> ```C
> 	if ((ret = rpma_conn_completion_get(cd->conn, &cmpl))) {
> 		rpma_td_verror(td, ret, "rpma_conn_completion_get");
> 		return -1;
> ```

.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/19)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[engines/librpma.c, line 340 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJ_ySmf5A76feJnAWmZ:-MJaPxVSCWPAjYT8qt_y:bx3jy4x) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L340)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

return ret; ?
</blockquote></details>

For this hook, negative output means an error. I know RPMA error codes are negative but I do not want to smuggle this as a fact. So I do not return the `ret` (which I assume may be any non-zero value) and return a simple negative instead.
___
*[engines/librpma.c, line 346 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJ_yZMpBQVVMoWF0-n8:-MJaQ_hWCvXLyU3L6Ybl:b3kqx) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L346)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/19#-:-MJaTptr290uuAH0zAfI:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/19#-:-MJaXVnR-ayFhGwLnKD8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/19)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 349 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJaZw7I5dRScJxmwpJf:-MJaZw7I5dRScJxmwpJg:b-2lzclx) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L349)):*
> ```
> have
> ```

has
___
*[engines/librpma.c, line 349 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJa_51l34rwPZCV_GDZ:-MJa_51l34rwPZCV_GD_:b-xrj5wg) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L349)):*
> ```
>  with error
> ```

with an error
___
*[engines/librpma.c, line 353 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJa_AxVAZN4PYGMJtin:-MJa_AxVAZN4PYGMJtio:b-x98c7z) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L353)):*
> ```
>  lookup
> ```

look up
___
*[engines/librpma.c, line 354 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJa_KfD6iuEEIrIF57v:-MJa_KfD6iuEEIrIF57w:b-p6zsbh) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L354)):*
> ```
> &cmpl.op_context
> ```

And not just `cmpl.op_context` ? - that's why I had added `&` to the io's index in `rpma_read()` previously ...
___
*[engines/librpma.c, line 362 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJaa6-S6pWeo2V_9xUr:-MJaa6-S6pWeo2V_9xUs:b-exz6q1) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L362)):*
> ```
> have been
> ```

has been
___
*[engines/librpma.c, line 383 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJabGJdDntmZQCIJ7Hc:-MJabGJe7QBEYYu1rqn3:b-omv2o1) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L383)):*
> ```
> /* remove completed io_us from the flight queue */
> 	for (i = cmpl_num; i < cd->io_u_flight_nr; ++i)
> 		cd->io_us_flight[i - cmpl_num] = cd->io_us_flight[i];
> ```

The comment does not reflect exactly the code here.
You are not removing the completed io_us from the flight queue, but you are moving the NOT completed io_us to the beginning of the flight queue and by the way overwritting/removing SOME of the completed ious, but if `cmpl_num < cd->io_u_flight_nr/2` than SOME of the completed ious will be still left in this queue. Can they be not NULL?
___
*[engines/librpma.c, line 384 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJadHr-D_FWKYm-0ux9:-MJadHr-D_FWKYm-0uxA:bw1a3ed) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L384)):*
> ```
> for (i = cmpl_num; i < cd->io_u_flight_nr; ++i)
> 		cd->io_us_flight[i - cmpl_num] = cd->io_us_flight[i];
> 	cd->io_u_flight_nr -= cmpl_num;
> ```

Can there be a race in between the last two lines if another thread adds a iou to this queue in menatime?
___
*[engines/librpma.c, line 401 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJadfWoAEJLgGHCTr08:-MJadfWp6rOKtHgSDS7y:bkuvugg) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L401)):*
> ```
> for (i = 1; i < cd->io_u_completed_nr; ++i)
> 		cd->io_us_completed[i - 1] = cd->io_us_completed[i];
> 	cd->io_u_completed_nr--;
> ```

Can there be a race in between the last two lines if another thread adds a iou to this queue in menatime?

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/19)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/19)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 349 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJaZw7I5dRScJxmwpJf:-MJahk_z1WrI1s7Yh2dw:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L349)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> have
> ```

has
</blockquote></details>

Done.
___
*[engines/librpma.c, line 349 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJa_51l34rwPZCV_GDZ:-MJahlvKDVPJukd4YzNe:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L349)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  with error
> ```

with an error
</blockquote></details>

Done.
___
*[engines/librpma.c, line 353 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJa_AxVAZN4PYGMJtin:-MJaiJCg4FbuHDauyAyP:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L353)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  lookup
> ```

look up
</blockquote></details>

Done.
___
*[engines/librpma.c, line 354 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJa_KfD6iuEEIrIF57v:-MJaiOh5-RQYNY94Co-V:b-t35802) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L354)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> &cmpl.op_context
> ```

And not just `cmpl.op_context` ? - that's why I had added `&` to the io's index in `rpma_read()` previously ...
</blockquote></details>

I know. It seems weird. But I want to convey the exact value.
___
*[engines/librpma.c, line 362 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJaa6-S6pWeo2V_9xUr:-MJaj28E5aaGqsSgaYjO:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L362)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> have been
> ```

has been
</blockquote></details>

Done.
___
*[engines/librpma.c, line 384 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJadHr-D_FWKYm-0ux9:-MJajF-y4QG-H0UoBv5d:bhm1hhl) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L384)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> for (i = cmpl_num; i < cd->io_u_flight_nr; ++i)
> 		cd->io_us_flight[i - cmpl_num] = cd->io_us_flight[i];
> 	cd->io_u_flight_nr -= cmpl_num;
> ```

Can there be a race in between the last two lines if another thread adds a iou to this queue in menatime?
</blockquote></details>

No. All of the resources so far are used by one thread only.
___
*[engines/librpma.c, line 401 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJadfWoAEJLgGHCTr08:-MJajTZ7Bkz3vK5IeYNm:b3kqx) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L401)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> for (i = 1; i < cd->io_u_completed_nr; ++i)
> 		cd->io_us_completed[i - 1] = cd->io_us_completed[i];
> 	cd->io_u_completed_nr--;
> ```

Can there be a race in between the last two lines if another thread adds a iou to this queue in menatime?
</blockquote></details>

.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/19)* status: all files reviewed, 8 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 383 at r2](https://reviewable.io/reviews/pmem/fio/19#-MJabGJdDntmZQCIJ7Hc:-MJakogJ8MGrcl_yRMc3:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b8f77c1189c225e6ca497a2a64f99f5532cb65f9/engines/librpma.c#L383)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> /* remove completed io_us from the flight queue */
> 	for (i = cmpl_num; i < cd->io_u_flight_nr; ++i)
> 		cd->io_us_flight[i - cmpl_num] = cd->io_us_flight[i];
> ```

The comment does not reflect exactly the code here.
You are not removing the completed io_us from the flight queue, but you are moving the NOT completed io_us to the beginning of the flight queue and by the way overwritting/removing SOME of the completed ious, but if `cmpl_num < cd->io_u_flight_nr/2` than SOME of the completed ious will be still left in this queue. Can they be not NULL?
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/19)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/19#-:-MJaoAKB15kuznD2LEcm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
