### PR TITLE
rpma: remove not required engine flags (server)

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/192)

### CODE REVIEW

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/192#-:-MRyVDzX3sxsQc6h8QaH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — COMMENTED** [review]
Will it work for ASYNC mode?

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/192#-:-MRynlIo9qBzW3Ba-t1A:bewbon2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> Will it work for ASYNC mode?
Yes.

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/192#-:-MRyoPUeDOPQ4i-CzKyL:b-62j7nz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/192#-:-MRypF_AEwoVTV_E7MBr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
