### PR TITLE
rpma: implement server_queue

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #53
- [x] #55
- [x] #56 
- [x] #57

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/59)

### CODE REVIEW

**Comment by ldorau** [comment]
Rebased

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/59)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 565 at r1](https://reviewable.io/reviews/pmem/fio/59#-MLn0jHW4N53e232Ry2N:-MLn0jHXDNI0FiLVxxb8:bp4uzd6) ([raw file](https://github.com/pmem/fio/blob/1664e90b94f5e936b1214d2641b9e9fc056f8cf1/engines/librpma_gpspm.c#L565)):*
> ```C
> 
> 	/* unpack a flush request from the received buffer */
> 	flush_req = gpspm_flush_request__unpack(NULL, cmpl.byte_len, recv_ptr);
> ```

I think we should take a look at `cmpl.op_context` to identify the recv buffer.
___
*[engines/librpma_gpspm.c, line 615 at r1](https://reviewable.io/reviews/pmem/fio/59#-MLtPd1M6UfjwdWVNocW:-MLtPd1M6UfjwdWVNocX:bc24a9q) ([raw file](https://github.com/pmem/fio/blob/1664e90b94f5e936b1214d2641b9e9fc056f8cf1/engines/librpma_gpspm.c#L615)):*
> ```C
> 		rpma_td_verror(td, ret, "rpma_conn_disconnect");
> 		goto err_conn_delete;
> 	}
> ```

The server should handle multiple io_us. Not just one. But I understand this is how the example works.

Please add a XXX comment we expect to change it in the future. I propose e.g. defining a new message which will be sent when the client will be done. So the server will transition to the cleanup stage accordingly.
___
*[engines/librpma_gpspm.c, line 625 at r1](https://reviewable.io/reviews/pmem/fio/59#-MLtPQJy7mkQfKYVxxTA:-MLtPQJz3VkZqAHnaAgl:b-slhu5c) ([raw file](https://github.com/pmem/fio/blob/1664e90b94f5e936b1214d2641b9e9fc056f8cf1/engines/librpma_gpspm.c#L625)):*
> ```C
> 
> err_conn_delete:
> 	(void) rpma_conn_delete(&sd->conn);
> ```

When we are establishing a connection during `open_file()` I would expect closing the connection on `close_file().

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/59)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_gpspm.c, line 565 at r1](https://reviewable.io/reviews/pmem/fio/59#-MLn0jHW4N53e232Ry2N:-MLvt_wM0PEtZBDzODeG:bbc068n) ([raw file](https://github.com/pmem/fio/blob/1664e90b94f5e936b1214d2641b9e9fc056f8cf1/engines/librpma_gpspm.c#L565)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we should take a look at `cmpl.op_context` to identify the recv buffer.
</blockquote></details>

It is not used in the server of 09-example. What does it contain?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/59)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 615 at r1](https://reviewable.io/reviews/pmem/fio/59#-MLtPd1M6UfjwdWVNocW:-MLvyMOaB5VwGNZN2zRS:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1664e90b94f5e936b1214d2641b9e9fc056f8cf1/engines/librpma_gpspm.c#L615)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The server should handle multiple io_us. Not just one. But I understand this is how the example works.

Please add a XXX comment we expect to change it in the future. I propose e.g. defining a new message which will be sent when the client will be done. So the server will transition to the cleanup stage accordingly.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 625 at r1](https://reviewable.io/reviews/pmem/fio/59#-MLtPQJy7mkQfKYVxxTA:-MLvwnOoDYIvj6J0oH4T:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1664e90b94f5e936b1214d2641b9e9fc056f8cf1/engines/librpma_gpspm.c#L625)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

When we are establishing a connection during `open_file()` I would expect closing the connection on `close_file().
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/59)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 565 at r1](https://reviewable.io/reviews/pmem/fio/59#-MLn0jHW4N53e232Ry2N:-MLwWKKi58dubpJGPT3x:b-x9vp8u) ([raw file](https://github.com/pmem/fio/blob/1664e90b94f5e936b1214d2641b9e9fc056f8cf1/engines/librpma_gpspm.c#L565)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is not used in the server of 09-example. What does it contain?
</blockquote></details>

`cmpl.op_context` will have to be used later, it is not set in case of compatibility with 09 example

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/59)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 565 at r1](https://reviewable.io/reviews/pmem/fio/59#-MLn0jHW4N53e232Ry2N:-MLwe35_DF7brklKd26S:b-lkiz34) ([raw file](https://github.com/pmem/fio/blob/1664e90b94f5e936b1214d2641b9e9fc056f8cf1/engines/librpma_gpspm.c#L565)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`cmpl.op_context` will have to be used later, it is not set in case of compatibility with 09 example
</blockquote></details>

Do you mean that `cmpl.op_context` should contain the offset of the received message in the `io_u->xfer_buf` ?

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/59)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 763 at r4](https://reviewable.io/reviews/pmem/fio/59#-MLwehqCCG6FflZ1TOn8:-MLwehqCCG6FflZ1TOn9:br4b5xy) ([raw file](https://github.com/pmem/fio/blob/fd4c6207ca793c8a3fc73ff4edc80bd38134cbc6/engines/librpma_gpspm.c#L763)):*
> ```C
> 		rpma_td_verror(td, ret, "rpma_conn_disconnect");
> 		goto err_terminate;
> 	}
> ```

I think these two steps:
- next_event AND
- disconnect
should be the part of the `close_file()` hook.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/59)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 763 at r4](https://reviewable.io/reviews/pmem/fio/59#-MLwehqCCG6FflZ1TOn8:-MLwjQIp5tbxTYUp_g61:b-896fix) ([raw file](https://github.com/pmem/fio/blob/fd4c6207ca793c8a3fc73ff4edc80bd38134cbc6/engines/librpma_gpspm.c#L763)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think these two steps:
- next_event AND
- disconnect
should be the part of the `close_file()` hook.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/59#-:-MLwjx1W-1yeXo9DVzSS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
It works with the client of the rpma 09 example

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/59#-:-MLwoRVt6ABsJLUQTjrr:b-7pl5dp)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/59)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 565 at r1](https://reviewable.io/reviews/pmem/fio/59#-MLn0jHW4N53e232Ry2N:-MLwRMAb1A4e_FIl23gU:bgwvc2j) ([raw file](https://github.com/pmem/fio/blob/1664e90b94f5e936b1214d2641b9e9fc056f8cf1/engines/librpma_gpspm.c#L565)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is not used in the server of 09-example. What does it contain?
</blockquote></details>

it contains const value FLUSH_ID but in fio engine, we should use ui.index and send it back to let client combine flush request and response
___
*[engines/librpma_gpspm.c, line 695 at r3](https://reviewable.io/reviews/pmem/fio/59#-MLwR1km9GFx_j5ckGVO:-MLwR1km9GFx_j5ckGVP:b-3pyv9c) ([raw file](https://github.com/pmem/fio/blob/71937456bd1edbe2ef9630d443e15656d8859698/engines/librpma_gpspm.c#L695)):*
> ```
> when the client is done
> ```
it should be indicated by an error recv completion when the connection is closed

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/59)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 565 at r1](https://reviewable.io/reviews/pmem/fio/59#-MLn0jHW4N53e232Ry2N:-MLwuT3N1hp6ibt4bQrp:b4grq9g) ([raw file](https://github.com/pmem/fio/blob/1664e90b94f5e936b1214d2641b9e9fc056f8cf1/engines/librpma_gpspm.c#L565)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

it contains const value FLUSH_ID but in fio engine, we should use ui.index and send it back to let client combine flush request and response
</blockquote></details>

It is already implemented in https://github.com/pmem/fio/pull/62

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/59#-:-MLwvM87AGx0s9VxnS-6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
