### PR TITLE
rpma: use the exact formula for ceil()

### PR DESCRIPTION
**Pull request by ldorau**
... instead of an approximation one.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/95)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/95)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/95#-:-MQByD3HCVtbKo37F0bM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/95)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma.c, line 206 at r1](https://reviewable.io/reviews/pmem/fio/95#-MQBz7xe-mAB3rEQlltH:-MQBz7xe-mAB3rEQlltI:b7d92fh) ([raw file](https://github.com/pmem/fio/blob/2af57250468c19c6fb16a89f3c80c3647bdbf96e/engines/librpma.c#L206)):*
> ```C
> 			 */
> 			sq_size = td->o.iodepth +
> 				(td->o.iodepth + td->o.iodepth_batch - 1) / td->o.iodepth_batch;
> ```

```c
/* ceil(a / b) = (a + b - 1) / b */
#define CEIL(a, b)\
    ((a) + (b) - 1) / (b)
```

```c
/*
 * N * WRITE + B * FLUSH where:
 * - B == ceil(iodepth / iodepth_batch) 
 * which is the number of batches for N writes
 */
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/95)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 206 at r1](https://reviewable.io/reviews/pmem/fio/95#-MQBz7xe-mAB3rEQlltH:-MQC350IAMjTHuOvKOF_:b-896fix) ([raw file](https://github.com/pmem/fio/blob/2af57250468c19c6fb16a89f3c80c3647bdbf96e/engines/librpma.c#L206)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
/* ceil(a / b) = (a + b - 1) / b */
#define CEIL(a, b)\
    ((a) + (b) - 1) / (b)
```

```c
/*
 * N * WRITE + B * FLUSH where:
 * - B == ceil(iodepth / iodepth_batch) 
 * which is the number of batches for N writes
 */
```

</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/95#-:-MQC4ppK2rrBSdAoCya-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
