### PR TITLE
rpma: common: alloc ccd inside client_init

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/133)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/133#-:-MR62kIk3zWYLawvYxnD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/133)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/133#-MRJNYZFC1HUA6OTMglb:-MRJNYZG2p9FDi1u065z:b-4pmu3h) (no related file):*
Where is `ccd` freed?

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/133)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 110 at r1](https://reviewable.io/reviews/pmem/fio/133#-MRJPMSh6y7z9cldPqxv:-MRJPMSiA9G-by_gDxlH:b3cmi6s) ([raw file](https://github.com/pmem/fio/blob/05f3edc8c407972322415439ae7e961a18db7041/engines/librpma_gpspm.c#L110)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 	/* allocate client's data */
> 	ccd = calloc(1, sizeof(struct librpma_common_client_data));
> 	if (ccd == NULL) {
> 		td_verror(td, errno, "calloc");
> 		return 1;
> 	}
> ```
</details>


It should be removed too.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/133)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/133#-MRJNYZFC1HUA6OTMglb:-MRJPfTU75RUacGp-Qul:b-b06zox) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Where is `ccd` freed?
</blockquote></details>

OK, there is - at the end of `client_cleanup()`

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/133)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/133)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 114 at r1](https://reviewable.io/reviews/pmem/fio/133#-MRJQf6Q6WnFirM9CRI7:-MRJQf6R8IvpJUGkFE2Y:b-dp18de) ([raw file](https://github.com/pmem/fio/blob/05f3edc8c407972322415439ae7e961a18db7041/engines/librpma_gpspm.c#L114)):*
> ```
> free(ccd);
> ```

It should be removed too.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/133)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 110 at r1](https://reviewable.io/reviews/pmem/fio/133#-MRJPMSh6y7z9cldPqxv:-MRJg1RfBk-1RCeGGpEC:b-896fix) ([raw file](https://github.com/pmem/fio/blob/05f3edc8c407972322415439ae7e961a18db7041/engines/librpma_gpspm.c#L110)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	/* allocate client's data */
> 	ccd = calloc(1, sizeof(struct librpma_common_client_data));
> 	if (ccd == NULL) {
> 		td_verror(td, errno, "calloc");
> 		return 1;
> 	}
> ```

It should be removed too.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 114 at r1](https://reviewable.io/reviews/pmem/fio/133#-MRJQf6Q6WnFirM9CRI7:-MRJg2-HC02P1PDgJLhn:b-896fix) ([raw file](https://github.com/pmem/fio/blob/05f3edc8c407972322415439ae7e961a18db7041/engines/librpma_gpspm.c#L114)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> free(ccd);
> ```

It should be removed too.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/133)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/133)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/133#-:-MRJqy6NC1OA_QEkbpsN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
