### PR TITLE
aof: client_queue_sync() (the first approximation)

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/222)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/222)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_aof.c, line 60 at r1](https://reviewable.io/reviews/pmem/fio/222#-MUDdae9-zhFNlQENeRE:-MUDdae9-zhFNlQENeRF:b-kwbjou) ([raw file](https://github.com/pmem/fio/blob/5fe4ef412b9fc9735127ea9aa1e4a925b97ba6e7/engines/librpma_aof.c#L60)):*
> ```C
> 
> 	/* only sequential writes are allowed in AOF */
> 	if (!td_write(td)) {
> ```

```c
if (td_random(td) || td_read(td) || td_trim(td)) {
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/222)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_aof.c, line 60 at r1](https://reviewable.io/reviews/pmem/fio/222#-MUDdae9-zhFNlQENeRE:-MUDjkYHDEn42YDA8CHB:b-896fix) ([raw file](https://github.com/pmem/fio/blob/5fe4ef412b9fc9735127ea9aa1e4a925b97ba6e7/engines/librpma_aof.c#L60)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
if (td_random(td) || td_read(td) || td_trim(td)) {
```
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/222#-:-MUDmxWrEur_cwVcQN40:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/222)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/222#-MUDn0rp7AYd-TncROt0:-MUDn0rq3woOZwoyO8Ra:b-ni3tmb) (no related file):*
Rebase please.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/222)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/222#-MUDn0rp7AYd-TncROt0:-MUDo6U14_Z6O-C44yg3:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Rebase please.
</blockquote></details>

Done.

---

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/222#-:-MUDohB32yRZymsTs_7G:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/222#-:-MUDr70G7izOujP4neNn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
