### PR TITLE
rpma: remove rpma_conn_completion_wait()

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/70)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/70)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma.c, line 745 at r1](https://reviewable.io/reviews/pmem/fio/70#-MNyidIS4lyhfMLJHJ2O:-MNyidIT4rkdgN_eKV-K:b-l6jzng) ([raw file](https://github.com/pmem/fio/blob/475bbefad091cc385c353fa45ede308d536f2cd9/engines/librpma.c#L745)):*
> ```C
> 			/* To reduce CPU consumption,
> 			 * use the rpma_conn_completion_wait() function.
> 			 * This change will increase the latency value.
> ```

I will go with:
```
To reduce CPU consumption one can use the rpma_conn_completion_wait() function.
Note this greatly increase the latency and make the results less stable.
The bandwidth stays more or less the same.
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/70)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 745 at r1](https://reviewable.io/reviews/pmem/fio/70#-MNyidIS4lyhfMLJHJ2O:-MNykuCg0159wSCL759o:b-896fix) ([raw file](https://github.com/pmem/fio/blob/475bbefad091cc385c353fa45ede308d536f2cd9/engines/librpma.c#L745)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I will go with:
```
To reduce CPU consumption one can use the rpma_conn_completion_wait() function.
Note this greatly increase the latency and make the results less stable.
The bandwidth stays more or less the same.
```
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/70)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/70#-:-MO0HVC346WDmIDDgRHM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/70#-:-MO1U4jm9gh4rwro2mz1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
