### PR TITLE
aof: add client_hw_get_io_u_index()

### PR DESCRIPTION
**Pull request by ldorau**
Depends on:
- [x] #241

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/243)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/243)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_aof.c, line 608 at r1](https://reviewable.io/reviews/pmem/fio/243#-MUmaQK_1mkVUjRS4Kia:-MUmaQK_1mkVUjRS4Kib:b-vwbhz5) ([raw file](https://github.com/pmem/fio/blob/4cfdbfddb324f745a03e37f077b1ed7d4448b367/engines/librpma_aof.c#L608)):*
> ```C
> 			index, ibv_wc_status_str(cmpl->op_status));
> 		return -1;
> 	}
> ```

No needed.

Ref: https://github.com/pmem/fio/blob/aof/engines/librpma_fio.c#L634
___
*[engines/librpma_aof.c, line 610 at r1](https://reviewable.io/reviews/pmem/fio/243#-MUma_vX5NiVboPc0rEZ:-MUma_vX5NiVboPc0rE_:b-87zaf0) ([raw file](https://github.com/pmem/fio/blob/4cfdbfddb324f745a03e37f077b1ed7d4448b367/engines/librpma_aof.c#L610)):*
> ```C
> 	}
> 
> 	*io_u_index = index;
> ```

You can copy it directly. No need for the intermediate variable.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/243)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_aof.c, line 608 at r1](https://reviewable.io/reviews/pmem/fio/243#-MUmaQK_1mkVUjRS4Kia:-MUmcHAqDKNhnhG1KnU4:b-75dkt3) ([raw file](https://github.com/pmem/fio/blob/4cfdbfddb324f745a03e37f077b1ed7d4448b367/engines/librpma_aof.c#L608)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No needed.

Ref: https://github.com/pmem/fio/blob/aof/engines/librpma_fio.c#L634
</blockquote></details>

What is not needed? The message?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/243)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_aof.c, line 608 at r1](https://reviewable.io/reviews/pmem/fio/243#-MUmaQK_1mkVUjRS4Kia:-MUmcTRuEABzBmBteoim:bxcz44v) ([raw file](https://github.com/pmem/fio/blob/4cfdbfddb324f745a03e37f077b1ed7d4448b367/engines/librpma_aof.c#L608)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What is not needed? The message?
</blockquote></details>

`log_err()` ?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/243)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_aof.c, line 610 at r1](https://reviewable.io/reviews/pmem/fio/243#-MUma_vX5NiVboPc0rEZ:-MUmcmab2eMBqxhshjFl:b-896fix) ([raw file](https://github.com/pmem/fio/blob/4cfdbfddb324f745a03e37f077b1ed7d4448b367/engines/librpma_aof.c#L610)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can copy it directly. No need for the intermediate variable.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/243)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_aof.c, line 608 at r1](https://reviewable.io/reviews/pmem/fio/243#-MUmaQK_1mkVUjRS4Kia:-MUmv2wl7f4wtWtFnV8X:b-vqv0vy) ([raw file](https://github.com/pmem/fio/blob/4cfdbfddb324f745a03e37f077b1ed7d4448b367/engines/librpma_aof.c#L608)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`log_err()` ?
</blockquote></details>

This message won't be displayed never ever because of the condition I have pasted in my previous message. ;-)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/243)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_aof.c, line 608 at r1](https://reviewable.io/reviews/pmem/fio/243#-MUmaQK_1mkVUjRS4Kia:-MUn8H8F6BuF86b7_Ec_:b-9nsq7u) ([raw file](https://github.com/pmem/fio/blob/4cfdbfddb324f745a03e37f077b1ed7d4448b367/engines/librpma_aof.c#L608)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This message won't be displayed never ever because of the condition I have pasted in my previous message. ;-)
</blockquote></details>

Ahh, right ... Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/243)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_aof.c, line 608 at r1](https://reviewable.io/reviews/pmem/fio/243#-MUmaQK_1mkVUjRS4Kia:-MUn8McSAJKHAr5VDAWw:b-896fix) ([raw file](https://github.com/pmem/fio/blob/4cfdbfddb324f745a03e37f077b1ed7d4448b367/engines/librpma_aof.c#L608)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ahh, right ... Done.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/243#-:-MUnAIoqC9sa6FPd3FWy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/243#-:-MUnD4ZKBbeOm9L4gAsL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/243)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
