### PR TITLE
rpma: consume multiple completions in a single getevents call

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/29)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29#-:-MK-I_Ps63YJ7-uVj7Sw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 403 at r1](https://reviewable.io/reviews/pmem/fio/29#-MK0ziUR9y0sFYONPWvA:-MK0ziUR9y0sFYONPWvB:bolcn2o) ([raw file](https://github.com/pmem/fio/blob/c0bae0994ba33d81ba167f63162ff5488a3355e4/engines/librpma.c#L403)):*
> ```
> getevent
> ```
getevents
___
*[engines/librpma.c, line 488 at r1](https://reviewable.io/reviews/pmem/fio/29#-MK0ynH6CYCRbpHFqNGL:-MK0ynH72Cp1TGtPJVjZ:b-qtqnu7) ([raw file](https://github.com/pmem/fio/blob/c0bae0994ba33d81ba167f63162ff5488a3355e4/engines/librpma.c#L488)):*
> ```
> cmpl_num
> ```
shall we move back to rpma_conn_completion_wait if 
```0 == cmpl_num ``` ?
cmpl_num equal to zero means rpma_conn_completion_wait() indicate about already consumed completion.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[engines/librpma.c, line 403 at r1](https://reviewable.io/reviews/pmem/fio/29#-MK0ziUR9y0sFYONPWvA:-MK4eNBlA_J5l4IUBQqD:b8u4fsl) ([raw file](https://github.com/pmem/fio/blob/c0bae0994ba33d81ba167f63162ff5488a3355e4/engines/librpma.c#L403)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> getevent
> ```
getevents
</blockquote></details>

I mean it. We are processing a single event in this call.
___
*[engines/librpma.c, line 488 at r1](https://reviewable.io/reviews/pmem/fio/29#-MK0ynH6CYCRbpHFqNGL:-MK4ehlXEPn2jIRRImZ4:b4gbtfr) ([raw file](https://github.com/pmem/fio/blob/c0bae0994ba33d81ba167f63162ff5488a3355e4/engines/librpma.c#L488)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> cmpl_num
> ```
shall we move back to rpma_conn_completion_wait if 
```0 == cmpl_num ``` ?
cmpl_num equal to zero means rpma_conn_completion_wait() indicate about already consumed completion.
</blockquote></details>

We may if `cmpl_num_total < min`. But it is not yet a part of this implementation.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 488 at r1](https://reviewable.io/reviews/pmem/fio/29#-MK0ynH6CYCRbpHFqNGL:-MK4fJWQ62yYYGs47LC8:b-yw5540) ([raw file](https://github.com/pmem/fio/blob/c0bae0994ba33d81ba167f63162ff5488a3355e4/engines/librpma.c#L488)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We may if `cmpl_num_total < min`. But it is not yet a part of this implementation.
</blockquote></details>

what about the following scenario:
- several items waiting in a queue
- client_getevents consumes 1 event but can consume all queue items
- fio calls client_getevents again and client_getevent_process return 0
- previous step will be executed until all events consumed from  rpma_conn_completion_wait

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 488 at r1](https://reviewable.io/reviews/pmem/fio/29#-MK0ynH6CYCRbpHFqNGL:-MK4wCf50rBa0MN8vUxc:b-ikeqs4) ([raw file](https://github.com/pmem/fio/blob/c0bae0994ba33d81ba167f63162ff5488a3355e4/engines/librpma.c#L488)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

what about the following scenario:
- several items waiting in a queue
- client_getevents consumes 1 event but can consume all queue items
- fio calls client_getevents again and client_getevent_process return 0
- previous step will be executed until all events consumed from  rpma_conn_completion_wait
</blockquote></details>

What do you think?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 488 at r2](https://reviewable.io/reviews/pmem/fio/29#-MK5RZ95AjlXvC3hCjEZ:-MK5RZ95AjlXvC3hCjE_:binxfq2) ([raw file](https://github.com/pmem/fio/blob/a9f0d43ac96247a8a91a9caa1aa8fc6379c2c97a/engines/librpma.c#L488)):*
> ```C
> 		rpma_td_verror(td, ret, "rpma_conn_completion_wait");
> 		return -1;
> 	}
> ```

Not waiting for a completion will probably shorten the completion latency.
Maybe it is worth adding an option for waiting just in case we want to reduce CPU involvement.
The currently proposed implementation is busy polling.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma.c, line 428 at r3](https://reviewable.io/reviews/pmem/fio/29#-MK5T2Ny5FYChycOjJnb:-MK5T2Ny5FYChycOjJnc:baqk70e) ([raw file](https://github.com/pmem/fio/blob/2d66e555ac2952a28233b05cb45d6479979eaaa6/engines/librpma.c#L428)):*
> ```
> rpma_conn_completion_get
> ```

`(ret > 0)` is impossible, because `"The rpma_conn_completion_get() function returns 0 on success or a negative error code on failure."`

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 488 at r1](https://reviewable.io/reviews/pmem/fio/29#-MK0ynH6CYCRbpHFqNGL:-MK5j-BfDHSGYLWhPaG7:bvjgnje) ([raw file](https://github.com/pmem/fio/blob/c0bae0994ba33d81ba167f63162ff5488a3355e4/engines/librpma.c#L488)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What do you think?
</blockquote></details>

I think that the separate subfunction client_getevent_process makes this function really complicated.
I think we should:
a) try to get completions (polling) until we read either max or at least min but no more
b)  if there is no more completion in a queue RPMA_E_NO_COMPLETION we should
b1) return if total > min
b2) wait for next with rpma_conn_completion_wait for next coming event and start again from a)
___
*[engines/librpma.c, line 488 at r2](https://reviewable.io/reviews/pmem/fio/29#-MK5RZ95AjlXvC3hCjEZ:-MK5lpw1EBbyl5Gjhv3m:b-ga6drl) ([raw file](https://github.com/pmem/fio/blob/a9f0d43ac96247a8a91a9caa1aa8fc6379c2c97a/engines/librpma.c#L488)):*
> probably 
All applications will probably use rpma_conn_completion_wait in some way, so nothing wrong is to behave like a normal application here.
___
*[engines/librpma.c, line 421 at r3](https://reviewable.io/reviews/pmem/fio/29#-MK5inGx2T8TWRhqZvTm:-MK5inGx2T8TWRhqZvTn:b61yno6) ([raw file](https://github.com/pmem/fio/blob/2d66e555ac2952a28233b05cb45d6479979eaaa6/engines/librpma.c#L421)):*
> ```
> RPMA_E_NO_COMPLETION
> ```
if this is not an error why this is an error ***_ E _***?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 488 at r1](https://reviewable.io/reviews/pmem/fio/29#-MK0ynH6CYCRbpHFqNGL:-MKYnNQ9DyAHSNKEiOvg:bhsl0lf) ([raw file](https://github.com/pmem/fio/blob/c0bae0994ba33d81ba167f63162ff5488a3355e4/engines/librpma.c#L488)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I think that the separate subfunction client_getevent_process makes this function really complicated.
I think we should:
a) try to get completions (polling) until we read either max or at least min but no more
b)  if there is no more completion in a queue RPMA_E_NO_COMPLETION we should
b1) return if total > min
b2) wait for next with rpma_conn_completion_wait for next coming event and start again from a)
</blockquote></details>

The current implementation differs in two ways comparing to what you have described above:
1. we collect all completions below the max threshold instead of just only above the min threshold
2. we do not use wait

AD 1. If we have hope for more completions (no E_NO_COMPLATION yet) I see no point in returning control to FIO.
AD 2. Is intentional and, in my opinion, maybe critical to simulate latency-critical behavior.
___
*[engines/librpma.c, line 488 at r2](https://reviewable.io/reviews/pmem/fio/29#-MK5RZ95AjlXvC3hCjEZ:-MKYmUf24ZKxdeok3Kw1:bcx92ep) ([raw file](https://github.com/pmem/fio/blob/a9f0d43ac96247a8a91a9caa1aa8fc6379c2c97a/engines/librpma.c#L488)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> probably 
All applications will probably use rpma_conn_completion_wait in some way, so nothing wrong is to behave like a normal application here.
</blockquote></details>

I do not agree the normal application will wait here. It depends if the application is latency-critical or not.
The latency-critical applications are busy poll since waiting, which causes context switch, increases latency.
___
*[engines/librpma.c, line 421 at r3](https://reviewable.io/reviews/pmem/fio/29#-MK5inGx2T8TWRhqZvTm:-MKYlsav4WWvKxkXpdXD:b-m0xq8q) ([raw file](https://github.com/pmem/fio/blob/2d66e555ac2952a28233b05cb45d6479979eaaa6/engines/librpma.c#L421)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_E_NO_COMPLETION
> ```
if this is not an error why this is an error ***_ E _***?
</blockquote></details>

We have started with _W_ but... https://github.com/pmem/rpma/pull/139#pullrequestreview-443577036.
To be discussed.
___
*[engines/librpma.c, line 428 at r3](https://reviewable.io/reviews/pmem/fio/29#-MK5T2Ny5FYChycOjJnb:-MKYmIyF5jZ_jB0utf9L:b-kpqtgr) ([raw file](https://github.com/pmem/fio/blob/2d66e555ac2952a28233b05cb45d6479979eaaa6/engines/librpma.c#L428)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rpma_conn_completion_get
> ```

`(ret > 0)` is impossible, because `"The rpma_conn_completion_get() function returns 0 on success or a negative error code on failure."`
</blockquote></details>

Done. I have missed it. Thank you. :-)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 488 at r1](https://reviewable.io/reviews/pmem/fio/29#-MK0ynH6CYCRbpHFqNGL:-MKZALSn1prHvj8B2Pwp:b2muwpx) ([raw file](https://github.com/pmem/fio/blob/c0bae0994ba33d81ba167f63162ff5488a3355e4/engines/librpma.c#L488)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The current implementation differs in two ways comparing to what you have described above:
1. we collect all completions below the max threshold instead of just only above the min threshold
2. we do not use wait

AD 1. If we have hope for more completions (no E_NO_COMPLATION yet) I see no point in returning control to FIO.
AD 2. Is intentional and, in my opinion, maybe critical to simulate latency-critical behavior.
</blockquote></details>

After reconsideration, I think the asynchronous path should wait if not completion is present. Please see if it fine now.
The latency-critical path would be implemented in a synchronous way.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma.c, line 508 at r4](https://reviewable.io/reviews/pmem/fio/29#-MKZ9OiI7B62tx6C3Kkw:-MKZ9OiI7B62tx6C3Kkx:b-thgjro) ([raw file](https://github.com/pmem/fio/blob/fe845d16307b34fd194eac7b91946962e64c5765/engines/librpma.c#L508)):*
> ```
> INT_MIN
> ```
-1 ? instead

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 508 at r4](https://reviewable.io/reviews/pmem/fio/29#-MKZ9OiI7B62tx6C3Kkw:-MKZNYtO-COamymLsU42:b-896fix) ([raw file](https://github.com/pmem/fio/blob/fe845d16307b34fd194eac7b91946962e64c5765/engines/librpma.c#L508)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> INT_MIN
> ```
-1 ? instead
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29#-:-MKZQ_kk8yNv-f3doFPD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[engines/librpma.c, line 488 at r1](https://reviewable.io/reviews/pmem/fio/29#-MK0ynH6CYCRbpHFqNGL:-MKZPg1Y63UuRMR6ooAx:b-bxs9im) ([raw file](https://github.com/pmem/fio/blob/c0bae0994ba33d81ba167f63162ff5488a3355e4/engines/librpma.c#L488)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

After reconsideration, I think the asynchronous path should wait if not completion is present. Please see if it fine now.
The latency-critical path would be implemented in a synchronous way.
</blockquote></details>

OK 
It seems that implementation follows what is already described in my comment above ;)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 443 at r5](https://reviewable.io/reviews/pmem/fio/29#-MKZYnne-wYiB5rabJx_:-MKZYnne-wYiB5rabJxa:bhuf4kn) ([raw file](https://github.com/pmem/fio/blob/5c6658a16c7720827e7d730a8c5faa0edffcf791/engines/librpma.c#L443)):*
> ```
> the number
> ```

a number
___
*[engines/librpma.c, line 443 at r5](https://reviewable.io/reviews/pmem/fio/29#-MKZYq046js5EEPqmmp9:-MKZYq055AxsgNfNyTrv:b3ik021) ([raw file](https://github.com/pmem/fio/blob/5c6658a16c7720827e7d730a8c5faa0edffcf791/engines/librpma.c#L443)):*
> ```
>  operations. Or:
> ```

`operations, or:`
___
*[engines/librpma.c, line 444 at r5](https://reviewable.io/reviews/pmem/fio/29#-MKZZ0VC5uIVfOsA7-gP:-MKZZ0VC5uIVfOsA7-gQ:b-9jg7vd) ([raw file](https://github.com/pmem/fio/blob/5c6658a16c7720827e7d730a8c5faa0edffcf791/engines/librpma.c#L444)):*
> ```
> found
> ```

Maybe `received` ? 
___
*[engines/librpma.c, line 446 at r5](https://reviewable.io/reviews/pmem/fio/29#-MKZ_CwtAZO7M26BLnmm:-MKZ_CwtAZO7M26BLnmn:b-3bt6li) ([raw file](https://github.com/pmem/fio/blob/5c6658a16c7720827e7d730a8c5faa0edffcf791/engines/librpma.c#L446)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> /*
>  * RETURN VALUE
>  * A positive non-zero value indicating the number of completed operations. Or:
>  * -   0  - when no complications found
>  * - (-1) - when an error occurred
>  */
> ```
</details>


Maybe just like that:

```
/*
 * Meaning of the RETURN VALUE:
 * - > 0  - number of completed operations,
 * -   0  - no complications received,
 * - (-1) - an error occurred
 */
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 464 at r5](https://reviewable.io/reviews/pmem/fio/29#-MKZaG6M3ukM9HP9r1LS:-MKZaG6M3ukM9HP9r1LT:bpp3fty) ([raw file](https://github.com/pmem/fio/blob/5c6658a16c7720827e7d730a8c5faa0edffcf791/engines/librpma.c#L464)):*
> ```
> no waiting needed
> ```

`do not need to wait`
___
*[engines/librpma.c, line 531 at r5](https://reviewable.io/reviews/pmem/fio/29#-MKZaVrMBXG_MLhiN2qD:-MKZaVrMBXG_MLhiN2qE:bqbfmqf) ([raw file](https://github.com/pmem/fio/blob/5c6658a16c7720827e7d730a8c5faa0edffcf791/engines/librpma.c#L531)):*
> ```
> 		}
> 		else if (cmpl_num == 0) {
> ```

```
		} else if (cmpl_num == 0) {
```

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 443 at r5](https://reviewable.io/reviews/pmem/fio/29#-MKZYnne-wYiB5rabJx_:-MKZctZS6DayvpebZNuR:b-896fix) ([raw file](https://github.com/pmem/fio/blob/5c6658a16c7720827e7d730a8c5faa0edffcf791/engines/librpma.c#L443)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> the number
> ```

a number
</blockquote></details>

Done.
___
*[engines/librpma.c, line 443 at r5](https://reviewable.io/reviews/pmem/fio/29#-MKZYq046js5EEPqmmp9:-MKZctrJ8T_ZXpV_ZIAJ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/5c6658a16c7720827e7d730a8c5faa0edffcf791/engines/librpma.c#L443)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  operations. Or:
> ```

`operations, or:`
</blockquote></details>

Done.
___
*[engines/librpma.c, line 531 at r5](https://reviewable.io/reviews/pmem/fio/29#-MKZaVrMBXG_MLhiN2qD:-MKZdVkk1c2OOzvfe9ng:b-896fix) ([raw file](https://github.com/pmem/fio/blob/5c6658a16c7720827e7d730a8c5faa0edffcf791/engines/librpma.c#L531)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 		}
> 		else if (cmpl_num == 0) {
> ```

```
		} else if (cmpl_num == 0) {
```
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/29#-:-MKZeB_hDc2wsK1Ccerl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
