### PR TITLE
rpma: initiate the next receive operation in server_queue()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/67)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/67#-:-MMaR2cD9S9x1CCeEUht:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/67)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 847 at r1](https://reviewable.io/reviews/pmem/fio/67#-MMbDD3uClGl8c_vxrln:-MMbDD3uClGl8c_vxrlo:b-u8ys3i) ([raw file](https://github.com/pmem/fio/blob/67bfd76b4149acfeba45c02ce234deca209b47fd/engines/librpma_gpspm.c#L847)):*
> ```
> send_ptr
> ```
we have send_buff_offset but send_ptr - shall these be unified?
___
*[engines/librpma_gpspm.c, line 915 at r1](https://reviewable.io/reviews/pmem/fio/67#-MMbDgOP5Inq87fa3F18:-MMbDgOP5Inq87fa3F19:b-92oumn) ([raw file](https://github.com/pmem/fio/blob/67bfd76b4149acfeba45c02ce234deca209b47fd/engines/librpma_gpspm.c#L915)):*
> ```
> RPMA_F_COMPLETION_ALWAYS
> ```
do we need to wait for this completion?
would it be better to use _COMPLETION_ON_ERROR and check possible error results next time the server_queue() is called

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/67)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 890 at r1](https://reviewable.io/reviews/pmem/fio/67#-MMcEolV-51sqt-pGZfI:-MMcEolV-51sqt-pGZfJ:b-5jiw1a) ([raw file](https://github.com/pmem/fio/blob/67bfd76b4149acfeba45c02ce234deca209b47fd/engines/librpma_gpspm.c#L890)):*
> ```C
> 		 */
> 		td->done = true;
> 		return FIO_Q_COMPLETED;
> ```

I see what you did here. Smuggling a fix. :P

Please add a note to the commit message at least.
___
*[engines/librpma_gpspm.c, line 915 at r1](https://reviewable.io/reviews/pmem/fio/67#-MMbDgOP5Inq87fa3F18:-MMcDwQo2VGVgTfllqhv:bwi3s0g) ([raw file](https://github.com/pmem/fio/blob/67bfd76b4149acfeba45c02ce234deca209b47fd/engines/librpma_gpspm.c#L915)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_F_COMPLETION_ALWAYS
> ```
do we need to wait for this completion?
would it be better to use _COMPLETION_ON_ERROR and check possible error results next time the server_queue() is called
</blockquote></details>

We would get an error when we will start looking for another recv'es completion.
I do agree it is not needed here. Moreover, it slows down the processing.

@ldorau would you mind submitting another PR fixing this?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/67)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 847 at r1](https://reviewable.io/reviews/pmem/fio/67#-MMbDD3uClGl8c_vxrln:-MMpdV8s7w5X-Hafh8W9:b-mywbvp) ([raw file](https://github.com/pmem/fio/blob/67bfd76b4149acfeba45c02ce234deca209b47fd/engines/librpma_gpspm.c#L847)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> send_ptr
> ```
we have send_buff_offset but send_ptr - shall these be unified?
</blockquote></details>

unified in the last commit "rpma: unify names of variables"
___
*[engines/librpma_gpspm.c, line 890 at r1](https://reviewable.io/reviews/pmem/fio/67#-MMcEolV-51sqt-pGZfI:-MMpbGK-1zxVoJN_TFmY:b1xo2ll) ([raw file](https://github.com/pmem/fio/blob/67bfd76b4149acfeba45c02ce234deca209b47fd/engines/librpma_gpspm.c#L890)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I see what you did here. Smuggling a fix. :P

Please add a note to the commit message at least.
</blockquote></details>

I am not smuggling anything. I have added it in a separate commit named "rpma: do not initiate the next receive operation when server is done" - isn't it enough ?
___
*[engines/librpma_gpspm.c, line 915 at r1](https://reviewable.io/reviews/pmem/fio/67#-MMbDgOP5Inq87fa3F18:-MMpcsSjEMHU6oTM4D6P:b-hf7m7v) ([raw file](https://github.com/pmem/fio/blob/67bfd76b4149acfeba45c02ce234deca209b47fd/engines/librpma_gpspm.c#L915)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We would get an error when we will start looking for another recv'es completion.
I do agree it is not needed here. Moreover, it slows down the processing.

@ldorau would you mind submitting another PR fixing this?
</blockquote></details>

https://github.com/pmem/fio/pull/69

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/67#-:-MMpkaUa-VNy8lhR0Hcl:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72, @janekmi, and @osalyk)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/67)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/67#-:-MMuR641E35nDiH2brnw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 890 at r1](https://reviewable.io/reviews/pmem/fio/67#-MMcEolV-51sqt-pGZfI:-MMuQiCBAaNrxL-Jpo1X:b-p8j8sp) ([raw file](https://github.com/pmem/fio/blob/67bfd76b4149acfeba45c02ce234deca209b47fd/engines/librpma_gpspm.c#L890)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I am not smuggling anything. I have added it in a separate commit named "rpma: do not initiate the next receive operation when server is done" - isn't it enough ?
</blockquote></details>

Ok. Its fine. :-) Sorry. I didn't notice.

**Pull request merged**
