### PR TITLE
rpma: librpma_common_ prefix before all public names

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/188)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/188)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/fio/188#-MRsyksG9GvsG9ygt-Uh:-MRsyksH05SGrUXsAIuq:bife9kt) (no related file):*
TBH I would expect having `librpma_` prefix for all commons since we will drop the `common` part of the file names.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/188)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/fio/188#-MRt4FBU1LROdbZ7L4Mn:-MRt4FBU1LROdbZ7L4Mo:btuugv0) (no related file):*
TBH I would drop the `_common_` and `_COMMON_` parts of all variables. IMHO the `librpma_` and `LIBRPMA_` prefixes are enough for all common variables and constants.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/188)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/fio/188#-MRt4FBU1LROdbZ7L4Mn:-MRt4om0-PXEA9howGmi:bg9nk8a) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

TBH I would drop the `_common_` and `_COMMON_` parts of all variables. IMHO the `librpma_` and `LIBRPMA_` prefixes are enough for all common variables and constants.
</blockquote></details>

... with `_common_` and `_COMMON_` they are just too long ...

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/188)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/188#-MRsyksG9GvsG9ygt-Uh:-MRtViJH-o-8vAAOW4NH:bmh8g7u) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

TBH I would expect having `librpma_` prefix for all commons since we will drop the `common` part of the file names.
</blockquote></details>

This PR is only to fix these names that are defined in the librpma_common.h but do not have librpma_common_ prefix

---
*[a discussion](https://reviewable.io/reviews/pmem/fio/188#-MRt4FBU1LROdbZ7L4Mn:-MRtWK3uB8UJHSPpqc13:b-j4q6i3) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

... with `_common_` and `_COMMON_` they are just too long ...
</blockquote></details>

separate PR #189 propose a shorter prefix

---

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/188)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/188#-MRt4FBU1LROdbZ7L4Mn:-MRtWUwP60rUPcrlC93Y:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

separate PR #189 propose a shorter prefix
</blockquote></details>

Done.

---

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/188#-:-MRteX5B5qjtMUGrF1XO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/188#-:-MRthgQjAKIW6bw8BWIX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/188)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
