### PR TITLE
rpma: gpspm: mind the free SQ space

### PR DESCRIPTION
**Pull request by janekmi**
Having pairs of SEND/RECV buffers, one can not assume an order in which completions from any of them come first to the CQ.
It may happen to collect multiple RECV completions with no SEND completions in the meantime. But since handling RECV requires consuming one SQ slot it is required to control is an SQ slot is available before processing a RECV completion.

The proposed implementation builds up a queue of RECV completions which are processed only when free SQ slots are available.
The number of free SQ slots determines how many RECV completions can be processed.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/103)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:goat:
 but I think the target solution is to have a separate CQ for RECV in the libpma.

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/103#-:-MQWM-f_7lPSRz0uLB7h:blzcovq)* status: 0 of 1 files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/103#-:-MQWc0zHC1MlHn6-6nYB:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/103)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/103)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 1506 at r1](https://reviewable.io/reviews/pmem/fio/103#-MQWwz7k6zTJIT0zhW55:-MQWwz7k6zTJIT0zhW56:b-g1sos5) ([raw file](https://github.com/pmem/fio/blob/7113ab3e888d61537e268e58366de93321a4e2d5/engines/librpma_gpspm.c#L1506)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 	/* progress the queue */
> 	for (i = 0; i < sd->msg_queued_nr - qes_to_process; ++i) {
> 		memcpy(&sd->msgs_queued[i], &sd->msgs_queued[qes_to_process + i],
> 				sizeof(struct rpma_completion));
> 	}
> ```
</details>


If we use the circular buffer here, we will not have to copy data (`memcpy()`) at all.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/103)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/103#-:-MQX871e98bMtHd1jfj1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
