### PR TITLE
rpma: gpspm: wait for CQEs of SENDs

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/231)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/231)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/231#-MUOSFx7BbNyv3KHMhRr:-MUOSFx7BbNyv3KHMhRs:b-f2zfa3) (no related file):*
It is not really GPSPM-specific. This is a common part.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/231)* status: 0 of 1 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/pmem/fio/231#-MUOSFx7BbNyv3KHMhRr:-MUOShfX3ub8i_KMypz6:bb6un1j) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is not really GPSPM-specific. This is a common part.
</blockquote></details>

Done

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/231)* status: 0 of 1 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/pmem/fio/231#-MUOSFx7BbNyv3KHMhRr:-MUOTGpL-_-4mXSMqLSB:bbyyj3l) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done
</blockquote></details>

My comment was not really good since APM does not use sends so this condition does not affect the APM.

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/231)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_fio.c, line 481 at r1](https://reviewable.io/reviews/pmem/fio/231#-MUOTdIx7wMF_RvHYvlz:-MUOTdIx7wMF_RvHYvm-:bpamz8z) ([raw file](https://github.com/pmem/fio/blob/9ef5ed29070a93e7b443c34a27c4eb32ecc796ec/engines/librpma_fio.c#L481)):*
> ```C
> 			break;
> 		}
> 	} while (1);
> ```

Haven't you observed a similar issue with this loop?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/231)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_fio.c, line 743 at r1](https://reviewable.io/reviews/pmem/fio/231#-MUOU1TPES25ZiqnFCyZ:-MUOU1TPES25ZiqnFCy_:b-a6nivj) ([raw file](https://github.com/pmem/fio/blob/9ef5ed29070a93e7b443c34a27c4eb32ecc796ec/engines/librpma_fio.c#L743)):*
> ```C
> 	} while (cmpl_num_total < max ||
> 			ccd->op_send_completed != ccd->op_recv_completed ||
> 			ccd->op_send_posted - ccd->op_send_completed > 1);
> ```

Do you think allowing to differ by one is somehow better than just using `!=`?
I think we should somehow argue for using both. Do you think we should use by-one-condition also for tracking sends vs recvs?

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/231)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/231)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_fio.c, line 743 at r1](https://reviewable.io/reviews/pmem/fio/231#-MUOU1TPES25ZiqnFCyZ:-MUOVlpt1uIDeutmshnE:b-l6q814) ([raw file](https://github.com/pmem/fio/blob/9ef5ed29070a93e7b443c34a27c4eb32ecc796ec/engines/librpma_fio.c#L743)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do you think allowing to differ by one is somehow better than just using `!=`?
I think we should somehow argue for using both. Do you think we should use by-one-condition also for tracking sends vs recvs?
</blockquote></details>

Wouldn't using `!=` be a quasi-synchronous mode instead of the asynchronous one?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/231)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_fio.c, line 481 at r1](https://reviewable.io/reviews/pmem/fio/231#-MUOTdIx7wMF_RvHYvlz:-MUPCsIw0IqoVjGXkn86:b-g4tj1e) ([raw file](https://github.com/pmem/fio/blob/9ef5ed29070a93e7b443c34a27c4eb32ecc796ec/engines/librpma_fio.c#L481)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Haven't you observed a similar issue with this loop?
</blockquote></details>

No, I have not (yet ;-))
___
*[engines/librpma_fio.c, line 743 at r1](https://reviewable.io/reviews/pmem/fio/231#-MUOU1TPES25ZiqnFCyZ:-MUPCoaa-X4K7zPbz72P:b-896fix) ([raw file](https://github.com/pmem/fio/blob/9ef5ed29070a93e7b443c34a27c4eb32ecc796ec/engines/librpma_fio.c#L743)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Wouldn't using `!=` be a quasi-synchronous mode instead of the asynchronous one?
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/231#-:-MUPKqHw6e2tjyRRBHte:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/231#-:-MUSQGdcAzRsfbo9MiTe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
