### PR TITLE
rpma: inline assignment with the directly following condition

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/165)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/165#-:-MRVL7rZAf9q-tujMBfJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/165)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma.c, line 187 at r1](https://reviewable.io/reviews/pmem/fio/165#-MRVMbME7ECgT6BDAChd:-MRVMbME7ECgT6BDAChe:bkxq2x2) ([raw file](https://github.com/pmem/fio/blob/fd8ad2b5fc11b29d17b6f449d2043d5c75843eff/engines/librpma.c#L187)):*
> ```C
> 	if ((ret = rpma_flush(ccd->conn, ccd->server_mr, dst_offset, len,
> 		cd->flush_type, RPMA_F_COMPLETION_ALWAYS,
> 		(void *)(uintptr_t)last_io_u->index))) {
> ```

+ indent

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/165)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 187 at r1](https://reviewable.io/reviews/pmem/fio/165#-MRVMbME7ECgT6BDAChd:-MRVOeBr72Zb2CV0E0pP:b-896fix) ([raw file](https://github.com/pmem/fio/blob/fd8ad2b5fc11b29d17b6f449d2043d5c75843eff/engines/librpma.c#L187)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

+ indent
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/165#-:-MRVPCBDDMqVhw-jCqGi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/165)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
