### PR TITLE
rpma: common: workspace

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/127)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/127)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_common.h, line 33 at r1](https://reviewable.io/reviews/pmem/fio/127#-MR4V7HxA9RjTRYiZ7dO:-MR4V7Hy3HS5lxppEpDd:bynh3in) ([raw file](https://github.com/pmem/fio/blob/89d21cc4a502ed201b10c23a965cff70bd7cb1ff/engines/librpma_common.h#L33)):*
> ```
> workspace
> ```
librpma_common_workspace (?)

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/127)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/127)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_common.h, line 33 at r1](https://reviewable.io/reviews/pmem/fio/127#-MR4V7HxA9RjTRYiZ7dO:-MR4X3ln2LjrFiQKmxga:b-896fix) ([raw file](https://github.com/pmem/fio/blob/89d21cc4a502ed201b10c23a965cff70bd7cb1ff/engines/librpma_common.h#L33)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> workspace
> ```
librpma_common_workspace (?)
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/127#-:-MR4groKDt3f3HqVrnew:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/127)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/127#-:-MR4mB7o3trlRlzhlSdh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/127)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/127)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
