### PR TITLE
rpma: all queues deleted in one place

### PR DESCRIPTION
**Pull request by grom72**
This code change has been discused already but lost during merge/rebase history

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/161)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/161)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_common.c, line 276 at r1](https://reviewable.io/reviews/pmem/fio/161#-MRV-c3eAyR8CnfuTMVl:-MRV-c3f4d4EOgnMkC5C:b-fytcaq) ([raw file](https://github.com/pmem/fio/blob/5f16decbdf916282048f606e959e040d14b02699/engines/librpma_common.c#L276)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 	if (ccd->io_us_queued)
> 		free(ccd->io_us_queued);
> 	if (ccd->io_us_flight)
> 		free(ccd->io_us_flight);
> 	if (ccd->io_us_completed)
> 		free(ccd->io_us_completed);
> ```
</details>


This is redundant. The previous version is correct and enough:

```
	free(ccd->io_us_queued);
	free(ccd->io_us_flight);
	free(ccd->io_us_completed);
```

from `free(3)`'s manual: "If ptr is NULL, no operation is performed."

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/161)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_common.c, line 276 at r1](https://reviewable.io/reviews/pmem/fio/161#-MRV-c3eAyR8CnfuTMVl:-MRV6XHL0KC9FvNkNjGQ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/5f16decbdf916282048f606e959e040d14b02699/engines/librpma_common.c#L276)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	if (ccd->io_us_queued)
> 		free(ccd->io_us_queued);
> 	if (ccd->io_us_flight)
> 		free(ccd->io_us_flight);
> 	if (ccd->io_us_completed)
> 		free(ccd->io_us_completed);
> ```

This is redundant. The previous version is correct and enough:

```
	free(ccd->io_us_queued);
	free(ccd->io_us_flight);
	free(ccd->io_us_completed);
```

from `free(3)`'s manual: "If ptr is NULL, no operation is performed."
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/161)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/161#-:-MRV6kHs00gfHMLVfd9O:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
