### PR TITLE
rpma: gpspm: server handles all flush requests...

### PR DESCRIPTION
**Pull request by janekmi**
...in a single queue() hook call

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/93)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/93)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 1252 at r1](https://reviewable.io/reviews/pmem/fio/93#-MQBwhgg6jrf-tufUOV1:-MQBwhgg6jrf-tufUOV2:bbtsfcy) ([raw file](https://github.com/pmem/fio/blob/a5b876258eefcb3216286c2df9288454c1788d09/engines/librpma_gpspm.c#L1252)):*
> ```
>  | FIO_DISKLESSIO
> ```
Does DISKLESSIO prevent file open at startup?

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/93)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 1252 at r1](https://reviewable.io/reviews/pmem/fio/93#-MQBwhgg6jrf-tufUOV1:-MQC6WpH-ONDYqSi9ROO:babbtfd) ([raw file](https://github.com/pmem/fio/blob/a5b876258eefcb3216286c2df9288454c1788d09/engines/librpma_gpspm.c#L1252)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>  | FIO_DISKLESSIO
> ```
Does DISKLESSIO prevent file open at startup?
</blockquote></details>

@janekmi What is a purpose of this change?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/93)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 1252 at r1](https://reviewable.io/reviews/pmem/fio/93#-MQBwhgg6jrf-tufUOV1:-MQCdqTM55_kENxD-aFp:b-wujdai) ([raw file](https://github.com/pmem/fio/blob/a5b876258eefcb3216286c2df9288454c1788d09/engines/librpma_gpspm.c#L1252)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@janekmi What is a purpose of this change?
</blockquote></details>

Trash. Sorry.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/93)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/93#-:-MQCe3--1EjSU3ep3fun:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/93#-:-MQCgFnZ1iXmPZf4fBfs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/93)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
