### PR TITLE
rpma: implement client_get_file_size and client_queue

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/63)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/63)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_gpspm.c, line 394 at r1](https://reviewable.io/reviews/pmem/fio/63#-MMFozLQCTl5gtBRmpaB:-MMFozLQCTl5gtBRmpaC:b-pz4g30) ([raw file](https://github.com/pmem/fio/blob/9ddf468f82f4a5922ff1d28cf3c485d50833c01d/engines/librpma_gpspm.c#L394)):*
> ```
> 		rpma_td_verror(td, ret, "rpma_mr_remote_get_size");
> 	return ret;
> ```

Add one empty line in between, please.
___
*[engines/librpma_gpspm.c, line 394 at r1](https://reviewable.io/reviews/pmem/fio/63#-MMFq0li3owrvHdgBr1R:-MMFq0li3owrvHdgBr1S:bbccixo) ([raw file](https://github.com/pmem/fio/blob/9ddf468f82f4a5922ff1d28cf3c485d50833c01d/engines/librpma_gpspm.c#L394)):*
> ```C
> 	if ((ret = rpma_mr_remote_get_size(cd->server_mr, &f->real_file_size)))
> 		rpma_td_verror(td, ret, "rpma_mr_remote_get_size");
> 	return ret;
> ```

Add: `fio_file_set_size_known(f);`

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/63)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 394 at r1](https://reviewable.io/reviews/pmem/fio/63#-MMFq0li3owrvHdgBr1R:-MMFuoVE-0cZEBH5uhOr:b-896fix) ([raw file](https://github.com/pmem/fio/blob/9ddf468f82f4a5922ff1d28cf3c485d50833c01d/engines/librpma_gpspm.c#L394)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Add: `fio_file_set_size_known(f);`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/63)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/63#-:-MMLdFl-6ouhVqgeovD4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/63)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/63#-MMPvQZn7G4WkTDr5to-:-MMPvQZn7G4WkTDr5to0:bh49da8) (no related file):*
Why both of these are provided in the same PR?

---
___
*[engines/librpma_gpspm.c, line 391 at r2](https://reviewable.io/reviews/pmem/fio/63#-MMPvaaP-uzsx9volZfk:-MMPvaaP-uzsx9volZfl:bck2iqo) ([raw file](https://github.com/pmem/fio/blob/4f6f605c0db0bbcb5148a3eb482ababef95f9ada/engines/librpma_gpspm.c#L391)):*
> ```C
> 	int ret;
> 
> 	f = td->files[0];
> ```

`f` should have at this point a valid value. No assignment needed.
___
*[engines/librpma_gpspm.c, line 393 at r2](https://reviewable.io/reviews/pmem/fio/63#-MMPwZAbAOaAId9gRDxk:-MMPwZAc3GSujT-sbuQR:b-j7q0l8) ([raw file](https://github.com/pmem/fio/blob/4f6f605c0db0bbcb5148a3eb482ababef95f9ada/engines/librpma_gpspm.c#L393)):*
> ```C
> 	f = td->files[0];
> 	if ((ret = rpma_mr_remote_get_size(cd->server_mr, &f->real_file_size)))
> 		rpma_td_verror(td, ret, "rpma_mr_remote_get_size");
> ```

Why you have decided to implement this part differently comparing to the `librpma.c` engine?
___
*[engines/librpma_gpspm.c, line 419 at r2](https://reviewable.io/reviews/pmem/fio/63#-MMPwxVw9JhuFpFTfUqw:-MMPwxVw9JhuFpFTfUqx:b3o81q5) ([raw file](https://github.com/pmem/fio/blob/4f6f605c0db0bbcb5148a3eb482ababef95f9ada/engines/librpma_gpspm.c#L419)):*
> ```C
> 	if (cd->io_u_queued_nr == (int)td->o.iodepth)
> 		return FIO_Q_BUSY;
> ```

Please add a `XXX` comment so we won't forget about implementing also a synchronous variant for this engine.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/63)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/63#-MMPvQZn7G4WkTDr5to-:-MMQI0RpEn-_Yuev0J2L:b-cseaqp) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why both of these are provided in the same PR?
</blockquote></details>

Because these are short functions.

---
___
*[engines/librpma_gpspm.c, line 391 at r2](https://reviewable.io/reviews/pmem/fio/63#-MMPvaaP-uzsx9volZfk:-MMQJm0F6kb8VszJueif:b-896fix) ([raw file](https://github.com/pmem/fio/blob/4f6f605c0db0bbcb5148a3eb482ababef95f9ada/engines/librpma_gpspm.c#L391)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`f` should have at this point a valid value. No assignment needed.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 393 at r2](https://reviewable.io/reviews/pmem/fio/63#-MMPwZAbAOaAId9gRDxk:-MMQKh5j7hrv-IxgyLWd:b-eiz5uc) ([raw file](https://github.com/pmem/fio/blob/4f6f605c0db0bbcb5148a3eb482ababef95f9ada/engines/librpma_gpspm.c#L393)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why you have decided to implement this part differently comparing to the `librpma.c` engine?
</blockquote></details>

It was a bit faster ;)
___
*[engines/librpma_gpspm.c, line 419 at r2](https://reviewable.io/reviews/pmem/fio/63#-MMPwxVw9JhuFpFTfUqw:-MMQHlLo36IWTpywwq2Q:b-896fix) ([raw file](https://github.com/pmem/fio/blob/4f6f605c0db0bbcb5148a3eb482ababef95f9ada/engines/librpma_gpspm.c#L419)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add a `XXX` comment so we won't forget about implementing also a synchronous variant for this engine.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/63)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/63#-:-MMQLbkW6ZLbTvRK2Cf0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
