### PR TITLE
rpma: use sizeof(variable) instead of sizeof(type)

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #146
- [ ] #147

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/149)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/149#-:-MRPs2aC9psxOb8BHB7o:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
@grom72 rebased

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/149#-:-MRRJ_VU-EMb1XWHNDeU:bnran3z)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/149)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[engines/librpma_common.h, line 218 at r2](https://reviewable.io/reviews/pmem/fio/149#-MRTpVbi7IV1r1-4vP7x:-MRTpVbi7IV1r1-4vP7y:bt5tvbb) ([raw file](https://github.com/pmem/fio/blob/066f1400ec08b4f4cf75ac5928bfc4ba1b8cc970/engines/librpma_common.h#L218)):*
> ```
> struct rpma_conn_cfg *cfg);
> ```
do we need so many tabs at the front of this line?

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/149)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/149)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_common.h, line 218 at r2](https://reviewable.io/reviews/pmem/fio/149#-MRTpVbi7IV1r1-4vP7x:-MRTyG2T1J7_QTo_OCQn:b-izqvsq) ([raw file](https://github.com/pmem/fio/blob/066f1400ec08b4f4cf75ac5928bfc4ba1b8cc970/engines/librpma_common.h#L218)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> struct rpma_conn_cfg *cfg);
> ```
do we need so many tabs at the front of this line?
</blockquote></details>

No, removed

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/149)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/149#-:-MRU2I837UkPALqU7QEp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
