### PR TITLE
 rpma: implement client_post_init

### PR DESCRIPTION
**Pull request by osalyk**
- [x] #54

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/58)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_gpspm.c, line 283 at r1](https://reviewable.io/reviews/pmem/fio/58#-MLmzG4iEYuJUCr8eoof:-MLmzG4j4kOKM8v6H_x1:b-lnag7t) ([raw file](https://github.com/pmem/fio/blob/349a6f1b82d1e1d3538d4edcf0ba0e91d635036e/engines/librpma_gpspm.c#L283)):*
> ```C
> 	if ((ret = rpma_mr_reg(cd->peer, cd->orig_buffer_aligned, io_us_size,
> 			RPMA_MR_USAGE_SEND | RPMA_MR_USAGE_RECV |
> 			RPMA_MR_USAGE_FLUSH_TYPE_VISIBILITY, &cd->orig_mr)))
> ```

The flush usage is not needed here.
___
*[engines/librpma_gpspm.c, line 285 at r1](https://reviewable.io/reviews/pmem/fio/58#-MLmzJck5Nfio43soL_U:-MLmzJcl-3s_diDQrorX:bgf9vi5) ([raw file](https://github.com/pmem/fio/blob/349a6f1b82d1e1d3538d4edcf0ba0e91d635036e/engines/librpma_gpspm.c#L285)):*
> ```C
> 			RPMA_MR_USAGE_FLUSH_TYPE_VISIBILITY, &cd->orig_mr)))
> 		rpma_td_verror(td, ret, "rpma_mr_reg");
> 	return ret;
> ```

Please give a new line before the return.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_gpspm.c, line 92 at r1](https://reviewable.io/reviews/pmem/fio/58#-MLslOx46gLp3fYF8sFQ:-MLslOx46gLp3fYF8sFR:b-gooc7w) ([raw file](https://github.com/pmem/fio/blob/349a6f1b82d1e1d3538d4edcf0ba0e91d635036e/engines/librpma_gpspm.c#L92)):*
> ```C
> 	/* ious's base address memory registration (cd->orig_buffer_aligned) */
> 	struct rpma_mr_local *orig_mr;
> ```

we need also memory for sending and receiving buffered (2 x io_depth x expected sending/receiving msg size)
___
*[engines/librpma_gpspm.c, line 180 at r1](https://reviewable.io/reviews/pmem/fio/58#-MLnCYfb7elcTmHHfcgJ:-MLnCYfb7elcTmHHfcgK:b9bkocf) ([raw file](https://github.com/pmem/fio/blob/349a6f1b82d1e1d3538d4edcf0ba0e91d635036e/engines/librpma_gpspm.c#L180)):*
> ```C
> 		goto err_cfg_delete;
> 	}
> 	
> ```

rpma_conn_cfg_set_rq_size() ?? 
___
*[engines/librpma_gpspm.c, line 285 at r1](https://reviewable.io/reviews/pmem/fio/58#-MLsmZp25reNTsvo9LmD:-MLsmZp25reNTsvo9LmE:b-c6gc57) ([raw file](https://github.com/pmem/fio/blob/349a6f1b82d1e1d3538d4edcf0ba0e91d635036e/engines/librpma_gpspm.c#L285)):*
> ```C
> 			RPMA_MR_USAGE_FLUSH_TYPE_VISIBILITY, &cd->orig_mr)))
> 		rpma_td_verror(td, ret, "rpma_mr_reg");
> 	return ret;
> ```

messaging buffers registration is missing.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[engines/librpma_gpspm.c, line 92 at r1](https://reviewable.io/reviews/pmem/fio/58#-MLslOx46gLp3fYF8sFQ:-MLtNLgl8p-8yny05gop:b-t2005u) ([raw file](https://github.com/pmem/fio/blob/349a6f1b82d1e1d3538d4edcf0ba0e91d635036e/engines/librpma_gpspm.c#L92)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

we need also memory for sending and receiving buffered (2 x io_depth x expected sending/receiving msg size)
</blockquote></details>

Good point. I think here we should a pointer to the buffer. Let's say:
```c
char *io_us_msgs;
```

We can at this point hardcode:
```
#define MSGS_SIZE (1024)
```

I think also during the `post_init()` hook each particular io_u should have assigned specific offsets in the `io_us_msgs` buffer. It can be stored in the `io_u->engine_data`.
___
*[engines/librpma_gpspm.c, line 180 at r1](https://reviewable.io/reviews/pmem/fio/58#-MLnCYfb7elcTmHHfcgJ:-MLtOFO39YcrXJ2EHOGI:b-h5i5y3) ([raw file](https://github.com/pmem/fio/blob/349a6f1b82d1e1d3538d4edcf0ba0e91d635036e/engines/librpma_gpspm.c#L180)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

rpma_conn_cfg_set_rq_size() ?? 
</blockquote></details>

Agree. In this case, RQ size should be equal to CQ size I believe.
___
*[engines/librpma_gpspm.c, line 285 at r1](https://reviewable.io/reviews/pmem/fio/58#-MLsmZp25reNTsvo9LmD:-MLtP0Gd9j7Ssa7lg1I6:b32v57) ([raw file](https://github.com/pmem/fio/blob/349a6f1b82d1e1d3538d4edcf0ba0e91d635036e/engines/librpma_gpspm.c#L285)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

messaging buffers registration is missing.
</blockquote></details>

+1

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 92 at r1](https://reviewable.io/reviews/pmem/fio/58#-MLslOx46gLp3fYF8sFQ:-MLw2_4H2U0P1Yt-hv3F:b-896fix) ([raw file](https://github.com/pmem/fio/blob/349a6f1b82d1e1d3538d4edcf0ba0e91d635036e/engines/librpma_gpspm.c#L92)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Good point. I think here we should a pointer to the buffer. Let's say:
```c
char *io_us_msgs;
```

We can at this point hardcode:
```
#define MSGS_SIZE (1024)
```

I think also during the `post_init()` hook each particular io_u should have assigned specific offsets in the `io_us_msgs` buffer. It can be stored in the `io_u->engine_data`.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 180 at r1](https://reviewable.io/reviews/pmem/fio/58#-MLnCYfb7elcTmHHfcgJ:-MLvxyJkAdZXTbtnVX6j:b-896fix) ([raw file](https://github.com/pmem/fio/blob/349a6f1b82d1e1d3538d4edcf0ba0e91d635036e/engines/librpma_gpspm.c#L180)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Agree. In this case, RQ size should be equal to CQ size I believe.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 283 at r1](https://reviewable.io/reviews/pmem/fio/58#-MLmzG4iEYuJUCr8eoof:-MLvy06k9_4Z1o7mETo6:b-896fix) ([raw file](https://github.com/pmem/fio/blob/349a6f1b82d1e1d3538d4edcf0ba0e91d635036e/engines/librpma_gpspm.c#L283)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The flush usage is not needed here.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 285 at r1](https://reviewable.io/reviews/pmem/fio/58#-MLmzJck5Nfio43soL_U:-MLvy3FZ76tjDdZW9apx:b-896fix) ([raw file](https://github.com/pmem/fio/blob/349a6f1b82d1e1d3538d4edcf0ba0e91d635036e/engines/librpma_gpspm.c#L285)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please give a new line before the return.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 285 at r1](https://reviewable.io/reviews/pmem/fio/58#-MLsmZp25reNTsvo9LmD:-MLvyYG49ygDpUL44cNs:b-896fix) ([raw file](https://github.com/pmem/fio/blob/349a6f1b82d1e1d3538d4edcf0ba0e91d635036e/engines/librpma_gpspm.c#L285)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[engines/librpma_gpspm.c, line 285 at r1](https://reviewable.io/reviews/pmem/fio/58#-MLsmZp25reNTsvo9LmD:-MLw9BJ2C2uS5iXNV9mc:bo7bvj9) ([raw file](https://github.com/pmem/fio/blob/349a6f1b82d1e1d3538d4edcf0ba0e91d635036e/engines/librpma_gpspm.c#L285)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still missing.
___
*[engines/librpma_gpspm.c, line 99 at r2](https://reviewable.io/reviews/pmem/fio/58#-MLw8YJl32KavESMYo2u:-MLw8YJl32KavESMYo2v:bza6k5u) ([raw file](https://github.com/pmem/fio/blob/5c0451aa42d1258e805ea7041f0bdff0b399ef51/engines/librpma_gpspm.c#L99)):*
> ```C
> 
> 	/* memory for sending and reciving buffered */
> 	#define MSGS_SIZE (1024)
> ```

Not the right place. Please put this define somewhere at the top.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 99 at r2](https://reviewable.io/reviews/pmem/fio/58#-MLw8YJl32KavESMYo2u:-MLwACLx4qUI-URfGe8F:b-896fix) ([raw file](https://github.com/pmem/fio/blob/5c0451aa42d1258e805ea7041f0bdff0b399ef51/engines/librpma_gpspm.c#L99)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not the right place. Please put this define somewhere at the top.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[engines/librpma_gpspm.c, line 285 at r1](https://reviewable.io/reviews/pmem/fio/58#-MLsmZp25reNTsvo9LmD:-MLwBO1wES8FkRDRxxIM:b2ngthb) ([raw file](https://github.com/pmem/fio/blob/349a6f1b82d1e1d3538d4edcf0ba0e91d635036e/engines/librpma_gpspm.c#L285)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Still missing.
</blockquote></details>

+1
___
*[engines/librpma_gpspm.c, line 293 at r3](https://reviewable.io/reviews/pmem/fio/58#-MLwQ00r97OzqXYhSDB8:-MLwQ00s73A0aggY8Rf_:b-fgwwxh) ([raw file](https://github.com/pmem/fio/blob/bad83997fe6d07689ce9c680085b2a8d26823626/engines/librpma_gpspm.c#L293)):*
> ```
> + 1
> ```
what is the purpose of this "+1"

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 285 at r1](https://reviewable.io/reviews/pmem/fio/58#-MLsmZp25reNTsvo9LmD:-MLwTlR03NwFcp8IC7kk:b-f7f7w3) ([raw file](https://github.com/pmem/fio/blob/349a6f1b82d1e1d3538d4edcf0ba0e91d635036e/engines/librpma_gpspm.c#L285)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

line 301
___
*[engines/librpma_gpspm.c, line 293 at r3](https://reviewable.io/reviews/pmem/fio/58#-MLwQ00r97OzqXYhSDB8:-MLwXbfV2FzBtspCZlhI:borunps) ([raw file](https://github.com/pmem/fio/blob/bad83997fe6d07689ce9c680085b2a8d26823626/engines/librpma_gpspm.c#L293)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> + 1
> ```
what is the purpose of this "+1"
</blockquote></details>

for rounding

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[engines/librpma_gpspm.c, line 293 at r3](https://reviewable.io/reviews/pmem/fio/58#-MLwQ00r97OzqXYhSDB8:-MLwi5tU9EcLSzMfVAYN:b-l57v5v) ([raw file](https://github.com/pmem/fio/blob/bad83997fe6d07689ce9c680085b2a8d26823626/engines/librpma_gpspm.c#L293)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

for rounding
</blockquote></details>

```c
/* ceil(td->o.iodepth / td->o.iodepth_batch) * MSGS_SIZE */
io_us_msgs_size = (td->o.iodepth / td->o.iodepth_batch + 1) * MSGS_SIZE
```

- You do need `2 *` because MSGS_SIZE is the size for both messages
- You have to do `+ 1` before `* MSGS_SIZE` because `+ 1` serves for rounding the initial division.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 293 at r3](https://reviewable.io/reviews/pmem/fio/58#-MLwQ00r97OzqXYhSDB8:-MLwkGG05JUtAdnZsiMK:b-896fix) ([raw file](https://github.com/pmem/fio/blob/bad83997fe6d07689ce9c680085b2a8d26823626/engines/librpma_gpspm.c#L293)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
/* ceil(td->o.iodepth / td->o.iodepth_batch) * MSGS_SIZE */
io_us_msgs_size = (td->o.iodepth / td->o.iodepth_batch + 1) * MSGS_SIZE
```

- You do need `2 *` because MSGS_SIZE is the size for both messages
- You have to do `+ 1` before `* MSGS_SIZE` because `+ 1` serves for rounding the initial division.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[engines/librpma_gpspm.c, line 293 at r3](https://reviewable.io/reviews/pmem/fio/58#-MLwQ00r97OzqXYhSDB8:-MLwki368SFpLVQiDWZM:bjeydue) ([raw file](https://github.com/pmem/fio/blob/bad83997fe6d07689ce9c680085b2a8d26823626/engines/librpma_gpspm.c#L293)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No no no. You do NOT need `2 *` neither `* 2`. Please remove. :-)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 293 at r3](https://reviewable.io/reviews/pmem/fio/58#-MLwQ00r97OzqXYhSDB8:-MLwmEUQ02ve_eGZ_QVh:b-896fix) ([raw file](https://github.com/pmem/fio/blob/bad83997fe6d07689ce9c680085b2a8d26823626/engines/librpma_gpspm.c#L293)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No no no. You do NOT need `2 *` neither `* 2`. Please remove. :-)
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58#-:-MLwmTVO4wD0xNzER_k_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma_gpspm.c, line 30 at r6](https://reviewable.io/reviews/pmem/fio/58#-MLwp3ua97kDLAtTfwsW:-MLwp3ua97kDLAtTfwsX:b4bpsot) ([raw file](https://github.com/pmem/fio/blob/644e6aeeb83db0828c1495b6a9ff97434086c971/engines/librpma_gpspm.c#L30)):*
> ```C
> 	td_vmsg((td), (err), rpma_err_2str(err), (func))
> 
> #define MSGS_SIZE (1024)
> ```

I would call it `IO_U_BUF_LEN` or sth like this, because the maximum size of all messages is 512.

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58#-:-MLwq16v-S-sIAE-NtjR:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_gpspm.c, line 293 at r6](https://reviewable.io/reviews/pmem/fio/58#-MLwr68E99BeW-URowK9:-MLwr68FBfuCysc-q19w:b48vm3) ([raw file](https://github.com/pmem/fio/blob/644e6aeeb83db0828c1495b6a9ff97434086c971/engines/librpma_gpspm.c#L293)):*
> ```
> 	io_us_msgs_size = (td->o.iodepth/td->o.iodepth_batch + 1) * MSGS_SIZE;
> ```

It is wrong. The correct is:
```
io_us_msgs_size = MSGS_SIZE * ((td->o.iodepth + td->o.iodepth_batch - 1) / td->o.iodepth_batch);
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_gpspm.c, line 298 at r6](https://reviewable.io/reviews/pmem/fio/58#-MLws9Vz2or7bSRPPfVN:-MLws9Vz2or7bSRPPfVO:b-geexti) ([raw file](https://github.com/pmem/fio/blob/644e6aeeb83db0828c1495b6a9ff97434086c971/engines/librpma_gpspm.c#L298)):*
> ```
> rpma_td_verror(td, ret, "posix_memalign");
> ```

`posix_memalign()` is not an RPMA API function - `td_verror` should be used here:

```
td_verror(td, ret, "posix_memalign");
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 30 at r6](https://reviewable.io/reviews/pmem/fio/58#-MLwp3ua97kDLAtTfwsW:-MLws1Tn4hDgFqA9bfD3:b-896fix) ([raw file](https://github.com/pmem/fio/blob/644e6aeeb83db0828c1495b6a9ff97434086c971/engines/librpma_gpspm.c#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I would call it `IO_U_BUF_LEN` or sth like this, because the maximum size of all messages is 512.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 293 at r6](https://reviewable.io/reviews/pmem/fio/58#-MLwr68E99BeW-URowK9:-MLwsZN33LigZb66_NgV:b-896fix) ([raw file](https://github.com/pmem/fio/blob/644e6aeeb83db0828c1495b6a9ff97434086c971/engines/librpma_gpspm.c#L293)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	io_us_msgs_size = (td->o.iodepth/td->o.iodepth_batch + 1) * MSGS_SIZE;
> ```

It is wrong. The correct is:
```
io_us_msgs_size = MSGS_SIZE * ((td->o.iodepth + td->o.iodepth_batch - 1) / td->o.iodepth_batch);
```
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 298 at r6](https://reviewable.io/reviews/pmem/fio/58#-MLws9Vz2or7bSRPPfVN:-MLwsgn52RB1MgEUvzX3:b-896fix) ([raw file](https://github.com/pmem/fio/blob/644e6aeeb83db0828c1495b6a9ff97434086c971/engines/librpma_gpspm.c#L298)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rpma_td_verror(td, ret, "posix_memalign");
> ```

`posix_memalign()` is not an RPMA API function - `td_verror` should be used here:

```
td_verror(td, ret, "posix_memalign");
```
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58#-:-MLwtFA15yogCBcnUEwM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/58)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
