### PR TITLE
rpma: fix C-style issues

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/185)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/185#-:-MRdrAM41wE7O3x-GLnv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/185)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_common.c, line 219 at r1](https://reviewable.io/reviews/pmem/fio/185#-MRdxBlR0lX91IB9Y-c8:-MRdxBlR0lX91IB9Y-c9:bxwlbp) ([raw file](https://github.com/pmem/fio/blob/23617a92785eda072a7626d3c500d1fcc70aeb07/engines/librpma_common.c#L219)):*
> ```C
> 
> 	ccd->io_us_completed = calloc(td->o.iodepth,
> 				sizeof(*ccd->io_us_completed));
> ```

Not too deep?
___
*[engines/librpma_common.c, line 288 at r1](https://reviewable.io/reviews/pmem/fio/185#-MRdxFt51x307PArbzZp:-MRdxFt51x307PArbzZq:b-md5rcn) ([raw file](https://github.com/pmem/fio/blob/23617a92785eda072a7626d3c500d1fcc70aeb07/engines/librpma_common.c#L288)):*
> ```C
> 	ccd->server_mr_flush_type =
> 		(remote_flush_type & RPMA_MR_USAGE_FLUSH_TYPE_PERSISTENT) ?
> 		RPMA_FLUSH_TYPE_PERSISTENT : RPMA_FLUSH_TYPE_VISIBILITY;
> ```

Not too shallow?
___
*[engines/librpma_common.c, line 496 at r1](https://reviewable.io/reviews/pmem/fio/185#-MRdxIrv4Ff_kZub46RR:-MRdxIrv4Ff_kZub46RS:bbf1mhh) ([raw file](https://github.com/pmem/fio/blob/23617a92785eda072a7626d3c500d1fcc70aeb07/engines/librpma_common.c#L496)):*
> ```C
> 		if (io_u->ddir == DDIR_READ) {
> 			if (i + 1 == ccd->io_u_queued_nr ||
> 			    ccd->io_us_queued[i + 1]->ddir == DDIR_WRITE)
> ```

Why spaces?
___
*[engines/librpma_common.c, line 530 at r1](https://reviewable.io/reviews/pmem/fio/185#-MRdxLo8280mqhLnuPi3:-MRdxLo8280mqhLnuPi4:btsg0z1) ([raw file](https://github.com/pmem/fio/blob/23617a92785eda072a7626d3c500d1fcc70aeb07/engines/librpma_common.c#L530)):*
> ```C
> 				 */
> 				if ((i + 1 < ccd->io_u_queued_nr) &&
> 				    (ccd->io_us_queued[i + 1]->ddir == DDIR_WRITE))
> ```

Spaces?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/185)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma_common.c, line 219 at r1](https://reviewable.io/reviews/pmem/fio/185#-MRdxBlR0lX91IB9Y-c8:-MRdyHSoABoFhAdl2vlJ:bsykmkj) ([raw file](https://github.com/pmem/fio/blob/23617a92785eda072a7626d3c500d1fcc70aeb07/engines/librpma_common.c#L219)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not too deep?
</blockquote></details>

one tab less
___
*[engines/librpma_common.c, line 288 at r1](https://reviewable.io/reviews/pmem/fio/185#-MRdxFt51x307PArbzZp:-MRdyO8-BAdTw0RmD9MT:bqd0lts) ([raw file](https://github.com/pmem/fio/blob/23617a92785eda072a7626d3c500d1fcc70aeb07/engines/librpma_common.c#L288)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not too shallow?
</blockquote></details>

I think no, with one tab more it exceeds 80 chars
___
*[engines/librpma_common.c, line 496 at r1](https://reviewable.io/reviews/pmem/fio/185#-MRdxIrv4Ff_kZub46RR:-MRdxlS5BNdpO-kL1GFI:bfwxkus) ([raw file](https://github.com/pmem/fio/blob/23617a92785eda072a7626d3c500d1fcc70aeb07/engines/librpma_common.c#L496)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why spaces?
</blockquote></details>

Because it a continuation of the same `if` condition
___
*[engines/librpma_common.c, line 530 at r1](https://reviewable.io/reviews/pmem/fio/185#-MRdxLo8280mqhLnuPi3:-MRdy07U9lz0HrsTPo_N:b3kqx) ([raw file](https://github.com/pmem/fio/blob/23617a92785eda072a7626d3c500d1fcc70aeb07/engines/librpma_common.c#L530)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Spaces?
</blockquote></details>

.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/185#-:-MRdzFDm7BXooLGPO0Rk:bnfp4nl)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/185)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/185#-:-MRdzmPW9-hqodtjMDNN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/185#-:-MReNvxb3U2LcaZHIqVv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
