### PR TITLE
examples: librpma client and server

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/2)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[examples/librpma-client.fio, line 17 at r1](https://reviewable.io/reviews/pmem/fio/2#-MJ2TxFl-evz9motEei9:-MJ2TxFmAqZ1pTjNK2D0:bc515cc) ([raw file](https://github.com/pmem/fio/blob/3e57d2194f928619b1cd98f02766a95809016d30/examples/librpma-client.fio#L17)):*
> ```
> # XXX each thread should have a separate space of defined size
> size=[XXX a space for a single thread?]
> offset_increment=[XXX should it be == size?]
> ```

The general idea is to force FIO to:
- acknowledge the available space is numjobs * size
- generate for each of the threads `i` offsets from range: `<offset_increment * i, offset_increment * i + size)`
___
*[examples/librpma-server.fio, line 9 at r1](https://reviewable.io/reviews/pmem/fio/2#-MJ2URXO7FrVEe5Hyyjg:-MJ2URXO7FrVEe5Hyyjh:bbzf7ly) ([raw file](https://github.com/pmem/fio/blob/3e57d2194f928619b1cd98f02766a95809016d30/examples/librpma-server.fio#L9)):*
> ```
> # dummy
> [server]
> filename=[device dax or fsdax file]
> ```

I'm not yet sure how it will work on this end. It seems the server should mmap the space once and register it once.
The questions are:
- Can we have here a single thread?
- How to verify the space is sufficient to cover all threads on the client's side?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[examples/librpma-client.fio, line 4 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ3MdMN01RwGlZQHnIp:-MJ3MdMN01RwGlZQHnIq:byiuazb) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-client.fio#L4)):*
> ```
> hostname
> ```
ip
___
*[examples/librpma-server.fio, line 4 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ3MguA1qkMlOqss2Zt:-MJ3MguA1qkMlOqss2Zu:byiuazb) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-server.fio#L4)):*
> ```
> hostname
> ```
ip

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[examples/librpma-client.fio, line 9 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ3NCKT5qa01gIX0VWc:-MJ3NCKT5qa01gIX0VWd:b26kaua) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-client.fio#L9)):*
> ```
> Each job connects to a
> ```
can we use the same port for several connections?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/librpma-client.fio, line 4 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ3MdMN01RwGlZQHnIp:-MJ45auHA48d3bn1ZJNs:b-abh0g5) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-client.fio#L4)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> hostname
> ```
ip
</blockquote></details>

I have reused already a well-defined option. Just not to introduce another one doing the same thing.
https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-hostname

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[examples/librpma-client.fio, line 4 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ3MdMN01RwGlZQHnIp:-MJ6Mog10Qrqz_rOQbTk:b-4rvqw9) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-client.fio#L4)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I have reused already a well-defined option. Just not to introduce another one doing the same thing.
https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-hostname
</blockquote></details>

Maybe more clear is `server_ip`?
___
*[examples/librpma-client.fio, line 9 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ3NCKT5qa01gIX0VWc:-MJ6NCZKBP5k-JqNfO08:bptnizy) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-client.fio#L9)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Each job connects to a
> ```
can we use the same port for several connections?
</blockquote></details>

Fio does not support creating entities common for all working threads. Of course we can do this but will require building some workarounds.

I do not recommend this way as the first step.
___
*[examples/librpma-server.fio, line 4 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ3MguA1qkMlOqss2Zt:-MJ6O8oq5MjNw9NgJ1Sv:b3kqx) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-server.fio#L4)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> hostname
> ```
ip
</blockquote></details>

.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/librpma-client.fio, line 10 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ68wrr-T-szjYfNv8v:-MJ68wrr-T-szjYfNv8w:b-1ntuqx) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-client.fio#L10)):*
> ```
> provided port option + job number
> ```
why ??
___
*[examples/librpma-client.fio, line 18 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ67Ikj7619X62bu5hc:-MJ67Ikj7619X62bu5hd:b-j06k3p) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-client.fio#L18)):*
> ```
> iodepth_batch_submit=[# of ious to submit at once]
> blocksize=[block size]
> size=[XXX a space for a single thread?]
> ```

too far for now 
___
*[examples/librpma-server.fio, line 4 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ63RGr2zcad9PTInHw:-MJ63RGr2zcad9PTInHx:bebtmjb) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-server.fio#L4)):*
> ```
> hostname
> ```
bindname ?
___
*[examples/librpma-server.fio, line 15 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ66dMeD3i6P7g6grYn:-MJ66dMeD3i6P7g6grYo:b-pbicrl) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-server.fio#L15)):*
> ```
> provided port option + job number
> ```
do not like this idea - we have an example (06) where one port is used by all.
___
*[examples/librpma-server.fio, line 16 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ65V9TCUf8-MiLqJ-t:-MJ65V9U1Tt9QoHi_2yj:b-xoxv8k) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-server.fio#L16)):*
> ```
> # Each job starts listening for incoming connections
> # on a port = provided port option + job number
> ```

can we use here mmap and share same file across several jobs based on defined limits?

I think we should not focus on server side with complex configuration now

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @grom72)

___
*[examples/librpma-client.fio, line 10 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ68wrr-T-szjYfNv8v:-MJ6_9s78X_1FKnp0rSH:b-5twvs8) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-client.fio#L10)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> provided port option + job number
> ```
why ??
</blockquote></details>

Please see the comment above + this gives a certainty each thread will work independently.

FYI by default, FIO creates processes instead of threads so you how virtually no way to share resources. ;-)
___
*[examples/librpma-client.fio, line 18 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ67Ikj7619X62bu5hc:-MJ6_WQi8KTS__48wiA5:b-4w1hyr) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-client.fio#L18)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

too far for now 
</blockquote></details>

This is only an example. I wanted to think it throughout.
___
*[examples/librpma-server.fio, line 4 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ63RGr2zcad9PTInHw:-MJ6_n4uCpGs7mBWIlX5:bynwuq) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-server.fio#L4)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> hostname
> ```
bindname ?
</blockquote></details>

I hate this idea of having two parameters with different names but the same value. It is stupid.
What do you think about `server_ip`?
___
*[examples/librpma-server.fio, line 15 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ66dMeD3i6P7g6grYn:-MJ6a0xpD5eUQ-mmYuka:b3kqx) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-server.fio#L15)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> provided port option + job number
> ```
do not like this idea - we have an example (06) where one port is used by all.
</blockquote></details>

.
___
*[examples/librpma-server.fio, line 16 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ65V9TCUf8-MiLqJ-t:-MJ6a5LlEpbZbmVyvZtn:bxd9ygv) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-server.fio#L16)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

can we use here mmap and share same file across several jobs based on defined limits?

I think we should not focus on server side with complex configuration now

</blockquote></details>

I think we have to decide who will partition the remote PMem and in my opinion, the server should do this.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[examples/librpma-client.fio, line 4 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ3MdMN01RwGlZQHnIp:-MJ7G1uF3_opk4-VwNyA:bnwcxwq) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-client.fio#L4)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Maybe more clear is `server_ip`?
</blockquote></details>

hostname is OK
___
*[examples/librpma-client.fio, line 10 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ68wrr-T-szjYfNv8v:-MJ7GI8tEHrA-DJP6N5-:b-yj9bvl) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-client.fio#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please see the comment above + this gives a certainty each thread will work independently.

FYI by default, FIO creates processes instead of threads so you how virtually no way to share resources. ;-)
</blockquote></details>

provided port option + job number **-1**
___
*[examples/librpma-client.fio, line 18 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ67Ikj7619X62bu5hc:-MJ7KPDhBpTWDPpKbajP:bxf87sz) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-client.fio#L18)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This is only an example. I wanted to think it throughout.
</blockquote></details>

please add XXX to all lines that are only placement for  discussion otherwise we will never close this PR in this sprint
___
*[examples/librpma-server.fio, line 4 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ63RGr2zcad9PTInHw:-MJ7JHIyEYYfarlkqjsD:b-bie7il) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-server.fio#L4)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I hate this idea of having two parameters with different names but the same value. It is stupid.
What do you think about `server_ip`?
</blockquote></details>

bindname is already defined - The name to use to bind the local RDMA-CM connection to a local RDMA device.
___
*[examples/librpma-server.fio, line 4 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ3MguA1qkMlOqss2Zt:-MJ64op61-56evAhY_df:b-to2h0j) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-server.fio#L4)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

bindname
___
*[examples/librpma-server.fio, line 15 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ66dMeD3i6P7g6grYn:-MJ7Hsg5A__cZyhCwLC6:ba1qa39) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-server.fio#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

job number <0..N-1> or job number <1 .. N> - based on spec numjobs default is 1
so port = provided port option + job number **- 1**
___
*[examples/librpma-server.fio, line 16 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ65V9TCUf8-MiLqJ-t:-MJ7GvIk9Cc6sSB3TAtd:bgg38gu) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-server.fio#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we have to decide who will partition the remote PMem and in my opinion, the server should do this.
</blockquote></details>

but fio core already know how to do this
if we use fio mechanism here we have to set up a separate thread for every connection on both sides
client_numjobs <= server_numjobs - looks complicated from a configuration point of view but ... looks simply from an implementation/architecture point of view (by the way this is an RDMA engine approach)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/librpma-server.fio, line 16 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ65V9TCUf8-MiLqJ-t:-MJ7aTec-PCRJ3E5WDjw:bnh90os) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-server.fio#L16)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

but fio core already know how to do this
if we use fio mechanism here we have to set up a separate thread for every connection on both sides
client_numjobs <= server_numjobs - looks complicated from a configuration point of view but ... looks simply from an implementation/architecture point of view (by the way this is an RDMA engine approach)

</blockquote></details>

Sadly I'm half-offline today. xD

You have to think whether openning a file means establishing a connection. If it is you can not depend on fio to partition the provided space. Because you will have less connections than threads which doesn't make much sense.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @grom72)

___
*[examples/librpma-client.fio, line 10 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ68wrr-T-szjYfNv8v:-MJ8Wgpc1r-khf2urTMg:b-896fix) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-client.fio#L10)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

provided port option + job number **-1**
</blockquote></details>

Done.
___
*[examples/librpma-client.fio, line 18 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ67Ikj7619X62bu5hc:-MJ8XMIY2PnBVKnyGO4x:blfyjx9) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-client.fio#L18)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

please add XXX to all lines that are only placement for  discussion otherwise we will never close this PR in this sprint
</blockquote></details>

I hope I have added to all controversial lines. If not, please point them out.
___
*[examples/librpma-server.fio, line 4 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ3MguA1qkMlOqss2Zt:-MJ8WMDRCuWNR2Dgd6Or:b-896fix) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-server.fio#L4)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

bindname
</blockquote></details>

Done.
___
*[examples/librpma-server.fio, line 4 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ63RGr2zcad9PTInHw:-MJ8WOuQ-X08cEXrmwdm:b-896fix) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-server.fio#L4)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

bindname is already defined - The name to use to bind the local RDMA-CM connection to a local RDMA device.
</blockquote></details>

Done.
___
*[examples/librpma-server.fio, line 15 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ66dMeD3i6P7g6grYn:-MJ8WfpVAL6eWZYovJuR:b-896fix) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-server.fio#L15)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

job number <0..N-1> or job number <1 .. N> - based on spec numjobs default is 1
so port = provided port option + job number **- 1**
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/librpma-server.fio, line 16 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ65V9TCUf8-MiLqJ-t:-MJ8aOXAE7GmxAffTSt1:b920oi1) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-server.fio#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Sadly I'm half-offline today. xD

You have to think whether openning a file means establishing a connection. If it is you can not depend on fio to partition the provided space. Because you will have less connections than threads which doesn't make much sense.
</blockquote></details>

in case of librpma we need to "open" two files - the local one - (source for write/target for write) and remote one 
the local one could be opened via mmap I guess (at least at the beginning) and the remote one via fileopen

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[examples/librpma-client.fio, line 7 at r3](https://reviewable.io/reviews/pmem/fio/2#-MJ8n68d6zt4aYcdYzpJ:-MJ8n68e3pIm9fD5sfR9:bog9s3d) ([raw file](https://github.com/pmem/fio/blob/d5931b0fabb73925b1930765c8dd044ce98fa9cc/examples/librpma-client.fio#L7)):*
> ```
> group_reporting
> ```
do we need this now?
___
*[examples/librpma-client.fio, line 13 at r3](https://reviewable.io/reviews/pmem/fio/2#-MJ8nFn57hqjcNg8FHVL:-MJ8nFn57hqjcNg8FHVM:b-3em7y5) ([raw file](https://github.com/pmem/fio/blob/d5931b0fabb73925b1930765c8dd044ce98fa9cc/examples/librpma-client.fio#L13)):*
> ```
> # of working threads
> ```
let's start with 1

**Review by ldorau — COMMENTED** [review]
Please rebase

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2#-:-MJBQ4PtA9xv4j4mpJeS:b-n6khor)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/librpma-client.fio, line 7 at r3](https://reviewable.io/reviews/pmem/fio/2#-MJ8n68d6zt4aYcdYzpJ:-MJBWMIZ1QDKU5hb_Sb7:blnowhh) ([raw file](https://github.com/pmem/fio/blob/d5931b0fabb73925b1930765c8dd044ce98fa9cc/examples/librpma-client.fio#L7)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> group_reporting
> ```
do we need this now?
</blockquote></details>

It is OK, it does not do anything wrong. It does not change anything when `numjobs=1` but will be needed when `numjobs>1`, so IMHO it can stay.
___
*[examples/librpma-client.fio, line 13 at r3](https://reviewable.io/reviews/pmem/fio/2#-MJ8nFn57hqjcNg8FHVL:-MJBX3om0sEMmBENJJnD:bk8tnpp) ([raw file](https://github.com/pmem/fio/blob/d5931b0fabb73925b1930765c8dd044ce98fa9cc/examples/librpma-client.fio#L13)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> # of working threads
> ```
let's start with 1
</blockquote></details>

We will start with 1 of course, but there are only comments everywhere for now, so IMHO it can stay.
___
*[examples/librpma-server.fio, line 12 at r3](https://reviewable.io/reviews/pmem/fio/2#-MJBXmCr1YtIxZLNTxrV:-MJBXmCr1YtIxZLNTxrW:b-4uxp9z) ([raw file](https://github.com/pmem/fio/blob/d5931b0fabb73925b1930765c8dd044ce98fa9cc/examples/librpma-server.fio#L12)):*
> ```
> its range 
> ```

its own range
___
*[examples/librpma-server.fio, line 25 at r3](https://reviewable.io/reviews/pmem/fio/2#-MJBZ6Pd7AotMWPm6BeZ:-MJBZ6Pd7AotMWPm6Be_:b4cnf48) ([raw file](https://github.com/pmem/fio/blob/d5931b0fabb73925b1930765c8dd044ce98fa9cc/examples/librpma-server.fio#L25)):*
> ```
> XX
> ```

XXX ;-)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[examples/librpma-server.fio, line 16 at r2](https://reviewable.io/reviews/pmem/fio/2#-MJ65V9TCUf8-MiLqJ-t:-MJMkPYt-X9qspi4I91w:b-896fix) ([raw file](https://github.com/pmem/fio/blob/382ce23d8c85f850907311a221d370862ff155d7/examples/librpma-server.fio#L16)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

in case of librpma we need to "open" two files - the local one - (source for write/target for write) and remote one 
the local one could be opened via mmap I guess (at least at the beginning) and the remote one via fileopen

</blockquote></details>

Done.
___
*[examples/librpma-server.fio, line 12 at r3](https://reviewable.io/reviews/pmem/fio/2#-MJBXmCr1YtIxZLNTxrV:-MJCWGwC7EIU-PLcNsnS:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d5931b0fabb73925b1930765c8dd044ce98fa9cc/examples/librpma-server.fio#L12)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> its range 
> ```

its own range
</blockquote></details>

Done.
___
*[examples/librpma-server.fio, line 25 at r3](https://reviewable.io/reviews/pmem/fio/2#-MJBZ6Pd7AotMWPm6BeZ:-MJMl0TcB1fAYM0R9s_o:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d5931b0fabb73925b1930765c8dd044ce98fa9cc/examples/librpma-server.fio#L25)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> XX
> ```

XXX ;-)
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/2#-MJN-udA-mA1dXoC7hYw:-MJN-udB5WcFl_opwhWH:b9qangx) (no related file):*
I have split this PR into a #5  which is the target for this sprint and this PR, building on top of the #5, for the sake of future sprints.

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/2)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi)

___
*[examples/librpma-client.fio, line 1 at r4](https://reviewable.io/reviews/pmem/fio/2#-MJQeo-K816px_r_A_HZ:-MJQeo-K816px_r_A_H_:b6xpeuh) ([raw file](https://github.com/pmem/fio/blob/54a71c146d1bca0ccd3449ca3b91b6a267528f31/examples/librpma-client.fio#L1)):*
> ```
> Example librpma 
> ```

Example of the librpma ...
___
*[examples/librpma-client.fio, line 6 at r4](https://reviewable.io/reviews/pmem/fio/2#-MJQdLBf5JURn0VNhpP4:-MJQdLBf5JURn0VNhpP5:bd1h4rf) ([raw file](https://github.com/pmem/fio/blob/54a71c146d1bca0ccd3449ca3b91b6a267528f31/examples/librpma-client.fio#L6)):*
> ```
> hostname=[server's listening IP address] 
> port=[server's listening port]
> thread
> ```

Maybe add a comment why threads? - Is it required or optional?
___
*[examples/librpma-client.fio, line 13 at r4](https://reviewable.io/reviews/pmem/fio/2#-MJQdbmf7i9ti92dlHZA:-MJQdbmf7i9ti92dlHZB:b-pa6z17) ([raw file](https://github.com/pmem/fio/blob/54a71c146d1bca0ccd3449ca3b91b6a267528f31/examples/librpma-client.fio#L13)):*
> ```
> # The client after establishing a connection will get a remote memory region
> # description. 
> ```

The client will get the description of a remote memory region after establishing a connection.
___
*[examples/librpma-client.fio, line 13 at r4](https://reviewable.io/reviews/pmem/fio/2#-MJQdvf0DoZMvUMV1Imi:-MJQdvf1-bfVEVZhLSbN:bo54nhk) ([raw file](https://github.com/pmem/fio/blob/54a71c146d1bca0ccd3449ca3b91b6a267528f31/examples/librpma-client.fio#L13)):*
> ```
> in a way most natural
> ```

`in the most natural way` 

or:

 `in a natural way`
___
*[examples/librpma-server.fio, line 1 at r4](https://reviewable.io/reviews/pmem/fio/2#-MJQet3D9P9SnXzmZYvN:-MJQet3D9P9SnXzmZYvO:b6xpeuh) ([raw file](https://github.com/pmem/fio/blob/54a71c146d1bca0ccd3449ca3b91b6a267528f31/examples/librpma-server.fio#L1)):*
> ```
> Example librpma 
> ```

Example of the librpma ...
___
*[examples/librpma-server.fio, line 7 at r4](https://reviewable.io/reviews/pmem/fio/2#-MJQf30F0QsyWjkljtWx:-MJQf30F0QsyWjkljtWy:b-50yw26) ([raw file](https://github.com/pmem/fio/blob/54a71c146d1bca0ccd3449ca3b91b6a267528f31/examples/librpma-server.fio#L7)):*
> ```
>  will spawn 
> ```

spawns
___
*[examples/librpma-server.fio, line 8 at r4](https://reviewable.io/reviews/pmem/fio/2#-MJQfLkTCQbY6QqB3MAO:-MJQfLkTCQbY6QqB3MAP:b-2hkwx8) ([raw file](https://github.com/pmem/fio/blob/54a71c146d1bca0ccd3449ca3b91b6a267528f31/examples/librpma-server.fio#L8)):*
> ```
> will accept
> ```

accepts
___
*[examples/librpma-server.fio, line 9 at r4](https://reviewable.io/reviews/pmem/fio/2#-MJQfQPt8jgq2r8jQE8L:-MJQfQPt8jgq2r8jQE8M:boywdea) ([raw file](https://github.com/pmem/fio/blob/54a71c146d1bca0ccd3449ca3b91b6a267528f31/examples/librpma-server.fio#L9)):*
> ```
> numconns option
> ```

the 'numconns' option
___
*[examples/librpma-server.fio, line 10 at r4](https://reviewable.io/reviews/pmem/fio/2#-MJQfXFW-CRx3KcCyU4k:-MJQfXFW-CRx3KcCyU4l:b-im7ucs) ([raw file](https://github.com/pmem/fio/blob/54a71c146d1bca0ccd3449ca3b91b6a267528f31/examples/librpma-server.fio#L10)):*
> ```
> close
> ```

closes

**Comment by ldorau** [comment]
@janekmi Close it?

**Comment by janekmi** [comment]
Most of these propositions were introduced one by one by other PRs.
Others are probably not applicable anymore.

**Pull request closed without merging**
