### PR TITLE
aof: add empty server_queue handler

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/242)

### CODE REVIEW

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/242#-:-MUmMN2V9e0y6q3ty1dC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

___
*[engines/librpma_aof.c, line 865 at r1](https://reviewable.io/reviews/pmem/fio/242#-MUmM4150zHuKcUYZZus:-MUmM4150zHuKcUYZZut:bddxob4) ([raw file](https://github.com/pmem/fio/blob/c35572a00de4fa41b00902ae778d9125cd218fca/engines/librpma_aof.c#L865)):*
> ```C
> 	/*
> 	 * The actual implementation is picked in the server_init hook
> 	 * according to the chosen aof_mode value
> ```

**Info**: We have to clean up the naming conventions both:
- aof_mode vs mode
- append vs update

**Review by ldorau — APPROVED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/242#-:-MUmZCs7-j0H8begH60Q:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma_aof.c, line 860 at r1](https://reviewable.io/reviews/pmem/fio/242#-MUmZ8OF15RJu7_ZSJd4:-MUmZ8OG3dYgPhid5pxS:bu9m6w5) ([raw file](https://github.com/pmem/fio/blob/c35572a00de4fa41b00902ae778d9125cd218fca/engines/librpma_aof.c#L860)):*
> ```
> server_queue
> ```

`server_queue_temp` ?

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/242#-:-MUmkf_129u8C1-YRq3T:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/242)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
