### PR TITLE
Install librpma in Travis CI linux build

### PR DESCRIPTION
**Pull request by ldorau**
Having the librpma library installed is required by the librpma engine.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/4)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[configure, line 2806 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7A1fp7o2aGaYLFa7R:-MJ7A1fp7o2aGaYLFa7S:b-lnogtp) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/configure#L2806)):*
> ```
> fi
> # XXX librpma specific test needed
> # librpma is not supported on x86 architecture
> ```

`on architectures other than x86` I suppose.
___
*[ci/travis-install.sh, line 46 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7A7VB9q4C6biBZC1T:-MJ7A7VB9q4C6biBZC1U:b3kqx) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/ci/travis-install.sh#L46)):*
> ```Shell
> 	sudo apt-get -qq update
> 	sudo apt-get install --no-install-recommends -qq -y "${pkgs[@]}"
> 	# librpma is not supported on x86 architecture
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[configure, line 2806 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7A1fp7o2aGaYLFa7R:-MJ7BKIGEVQ12araUmvc:b-mzglmx) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/configure#L2806)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`on architectures other than x86` I suppose.
</blockquote></details>

No, it is OK.  'x86' means 32-bit:

```
# Normalise host CPU name and set ARCH.
case "$cpu" in
  ia64|ppc|ppc64|s390|s390x|sparc64)
    cpu="$cpu"
  ;;
  i386|i486|i586|i686|i86pc|BePC)
    cpu="x86"
  ;;
  x86_64|amd64)
    cpu="x86_64"
  ;;
```
___
*[ci/travis-install.sh, line 46 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7A7VB9q4C6biBZC1T:-MJ7BpUE6iFUw1yX8TnS:b3kqx) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/ci/travis-install.sh#L46)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[configure, line 486 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7CAgYC2sn5IBNmuw3:-MJ7CAgYC2sn5IBNmuw4:b-xqgkf8) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/configure#L486)):*
@janekmi see here:
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
> # Normalise host CPU name and set ARCH.
> case "$cpu" in
>   ia64|ppc|ppc64|s390|s390x|sparc64)
>     cpu="$cpu"
>   ;;
>   i386|i486|i586|i686|i86pc|BePC)
>     cpu="x86"
>   ;;
>   x86_64|amd64)
>     cpu="x86_64"
>   ;;
> ```
</details>

___
*[ci/travis-install.sh, line 22 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7BwQr4jAeUA1JoU6n:-MJ7BwQr4jAeUA1JoU6o:b-q1rcxf) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/ci/travis-install.sh#L22)):*
@janekmi see here:

> ```
>     "x86")
> 		pkgs=("${pkgs[@]/%/:i386}")
> ```

**Review by ldorau — COMMENTED** [review]
The Travis build has passed: https://travis-ci.org/github/pmem/fio/builds/733958490

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4#-:-MJ7DUbf5GJT0CE4Kp2B:btz2hv0)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[configure, line 2806 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7A1fp7o2aGaYLFa7R:-MJ7EFZ0EsfT8hr8aPiV:b-4i6jus) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/configure#L2806)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, it is OK.  'x86' means 32-bit:

```
# Normalise host CPU name and set ARCH.
case "$cpu" in
  ia64|ppc|ppc64|s390|s390x|sparc64)
    cpu="$cpu"
  ;;
  i386|i486|i586|i686|i86pc|BePC)
    cpu="x86"
  ;;
  x86_64|amd64)
    cpu="x86_64"
  ;;
```
</blockquote></details>

On x86 behaves like that: https://travis-ci.org/github/ldorau/fio/jobs/733945403

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[configure, line 2806 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7A1fp7o2aGaYLFa7R:-MJ7DXhmBFOEW2PddSB-:b-qggq1m) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/configure#L2806)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, it is OK.  'x86' means 32-bit:

```
# Normalise host CPU name and set ARCH.
case "$cpu" in
  ia64|ppc|ppc64|s390|s390x|sparc64)
    cpu="$cpu"
  ;;
  i386|i486|i586|i686|i86pc|BePC)
    cpu="x86"
  ;;
  x86_64|amd64)
    cpu="x86_64"
  ;;
```
</blockquote></details>

I guess you support **only** x86_64... (not only you don't support "x86" but also not "ppc" or "sparc64" ;) )
___
*[ci/travis-install-librpma.sh, line 10 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7EHp02Dj6beyO2Sex:-MJ7EHp02Dj6beyO2Sey:b-ah12gk) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/ci/travis-install-librpma.sh#L10)):*
> ```Shell
> mkdir -p rpma/build
> cd rpma/build
> git checkout -b v$LIBRPMA_VERSION $LIBRPMA_VERSION
> ```

why you checkout `-b` ? why to create new branch?
___
*[ci/travis-install-librpma.sh, line 16 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7E8bDCyvVK84XnFv6:-MJ7E8bDCyvVK84XnFv7:b-4pz1pv) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/ci/travis-install-librpma.sh#L16)):*
> ```Shell
> 	-DBUILD_EXAMPLES=OFF \
> 	-DBUILD_TESTS=OFF
> make -j2
> ```

2? not `$(nproc)`?

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[configure, line 2807 at r2](https://reviewable.io/reviews/pmem/fio/4#-MJ7En7A0wA47KfaMRZ0:-MJ7En7B4dpgzrOqK7cV:b-cz9plr) ([raw file](https://github.com/pmem/fio/blob/cb3278e13390609bc9a9483008624e1488daceb8/configure#L2807)):*
> ```
> test
> ```
shall we check also against librpma installed?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[configure, line 2807 at r2](https://reviewable.io/reviews/pmem/fio/4#-MJ7En7A0wA47KfaMRZ0:-MJ7F9XkAeeSJGgLSILg:b-w8ru5h) ([raw file](https://github.com/pmem/fio/blob/cb3278e13390609bc9a9483008624e1488daceb8/configure#L2807)):*
Of course ... and of course in a separate PR.
The comment is above:

> ```
> # XXX librpma specific test needed
> ```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[configure, line 2807 at r2](https://reviewable.io/reviews/pmem/fio/4#-MJ7En7A0wA47KfaMRZ0:-MJ7FW2K5ZnkEmoKjtOc:b-896fix) ([raw file](https://github.com/pmem/fio/blob/cb3278e13390609bc9a9483008624e1488daceb8/configure#L2807)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Of course ... and of course in a separate PR.
The comment is above:

> ```
> # XXX librpma specific test needed
> ```

</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @lukaszstolarczuk)

___
*[configure, line 2806 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7A1fp7o2aGaYLFa7R:-MJ7F9jJ3hiXmZJ8que6:bthpxux) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/configure#L2806)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I guess you support **only** x86_64... (not only you don't support "x86" but also not "ppc" or "sparc64" ;) )
</blockquote></details>

Yeah. I see know. xD but according to the information mentioned above we should check `$cpu != x86_64` and comment accordingly.
___
*[ci/travis-install-librpma.sh, line 10 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7EHp02Dj6beyO2Sex:-MJ7GGU4AulJ-rS7iwga:b-ugc66l) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/ci/travis-install-librpma.sh#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why you checkout `-b` ? why to create new branch?
</blockquote></details>

Yeap. We can do simpler.
___
*[ci/travis-install-librpma.sh, line 16 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7E8bDCyvVK84XnFv6:-MJ7GKn14-lxNuGGcTph:b-8fx2u7) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/ci/travis-install-librpma.sh#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

2? not `$(nproc)`?
</blockquote></details>

:+1:

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @lukaszstolarczuk)

___
*[configure, line 2806 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7A1fp7o2aGaYLFa7R:-MJ7GAaI8besRWwF4lJ6:bhj5rdy) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/configure#L2806)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yeah. I see know. xD but according to the information mentioned above we should check `$cpu != x86_64` and comment accordingly.
</blockquote></details>

I am not sure that only 'x86_64' ... Why not 'ppc64' ? I am sure that librpma 'x86' does not support
___
*[ci/travis-install-librpma.sh, line 10 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7EHp02Dj6beyO2Sex:-MJ7FcFuAFeDbzDKWQtB:b-jnebsg) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/ci/travis-install-librpma.sh#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why you checkout `-b` ? why to create new branch?
</blockquote></details>

Why not? ;-)
I did it to silent the ugly git message about detached-head state, which looks like an error ...
___
*[ci/travis-install-librpma.sh, line 16 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7E8bDCyvVK84XnFv6:-MJ7G8xs4_r4fCfMU1_4:b-896fix) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/ci/travis-install-librpma.sh#L16)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

2? not `$(nproc)`?
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @lukaszstolarczuk)

___
*[ci/travis-install-librpma.sh, line 10 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7EHp02Dj6beyO2Sex:-MJ7GsW_00UcmJyHXwy8:b-896fix) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/ci/travis-install-librpma.sh#L10)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why not? ;-)
I did it to silent the ugly git message about detached-head state, which looks like an error ...
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @janekmi and @lukaszstolarczuk)

___
*[configure, line 2806 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7A1fp7o2aGaYLFa7R:-MJ7HGYL6LHYjLTN65AC:baxxcbh) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/configure#L2806)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I am not sure that only 'x86_64' ... Why not 'ppc64' ? I am sure that librpma 'x86' does not support
</blockquote></details>

(  I am sure that librpma does not support 'x86' )

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @janekmi and @lukaszstolarczuk)

___
*[configure, line 2806 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7A1fp7o2aGaYLFa7R:-MJ7INDp9zgaTyjr6kkz:b-2gdubi) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/configure#L2806)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

(  I am sure that librpma does not support 'x86' )
</blockquote></details>

@lukaszstolarczuk and what about ppc64? why not ppc64?

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @lukaszstolarczuk)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @lukaszstolarczuk)

___
*[configure, line 2806 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7A1fp7o2aGaYLFa7R:-MJ7RwdzDIvIg6GtSnFY:b-a2ujfl) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/configure#L2806)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@lukaszstolarczuk and what about ppc64? why not ppc64?
</blockquote></details>

Changed.
___
*[ci/travis-install.sh, line 46 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7A7VB9q4C6biBZC1T:-MJ7S0mz5CUCcclUgZnH:b-a2ujfl) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/ci/travis-install.sh#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Changed.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @lukaszstolarczuk)

___
*[ci/travis-install.sh, line 46 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7A7VB9q4C6biBZC1T:-MJ7S8nY8k7khtnK9jcj:b-896fix) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/ci/travis-install.sh#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Changed.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4#-:-MJ7TVKX9o2zC0q-oKxM:bdycpsm)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @lukaszstolarczuk)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4#-:-MJ7bzZZAXajaD6Ro8w-:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[configure, line 2807 at r4](https://reviewable.io/reviews/pmem/fio/4#-MJ7erBS6YwwbNJ8wYvF:-MJ7erBS6YwwbNJ8wYvG:bb1rgr3) ([raw file](https://github.com/pmem/fio/blob/8d08283bc35a9353f67d3a9012e7985c26ce1f19/configure#L2807)):*
> ```
> # XXX librpma specific test needed
> # librpma is supported on the 'x86_64' architecture for now
> if test "$cpu" == "x86_64" -a "$libverbs" = "yes" -a "$rdmacm" = "yes" ; then
> ```

you test using `==` and other tests are just `=` - is it ok in configure file?
___
*[ci/travis-install.sh, line 47 at r4](https://reviewable.io/reviews/pmem/fio/4#-MJ7frwc1zTG5N7gmXqW:-MJ7frwc1zTG5N7gmXqX:bv0vh0s) ([raw file](https://github.com/pmem/fio/blob/8d08283bc35a9353f67d3a9012e7985c26ce1f19/ci/travis-install.sh#L47)):*
> ```Shell
> 	sudo apt-get install --no-install-recommends -qq -y "${pkgs[@]}"
> 	# librpma is supported on the 'x86_64' architecture for now
> 	if [[ $CI_TARGET_ARCH == "amd64" ]]; then
> ```

after normalisation (the one, you quoted in some comment above) isn't it `x86_64` instead of `amd64`?
___
*[ci/travis-install-librpma.sh, line 10 at r1](https://reviewable.io/reviews/pmem/fio/4#-MJ7EHp02Dj6beyO2Sex:-MJ7fOOa0rC6-8DCJWjg:b-j9rz7r) ([raw file](https://github.com/pmem/fio/blob/048164dcc9c86b497cef49baa24fc1f38a7adad6/ci/travis-install-librpma.sh#L10)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok, curious solution, I'll remember that :)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @lukaszstolarczuk)

___
*[configure, line 2807 at r4](https://reviewable.io/reviews/pmem/fio/4#-MJ7erBS6YwwbNJ8wYvF:-MJ8MLw97mKuT4boaJ7H:bffu390) ([raw file](https://github.com/pmem/fio/blob/8d08283bc35a9353f67d3a9012e7985c26ce1f19/configure#L2807)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you test using `==` and other tests are just `=` - is it ok in configure file?
</blockquote></details>

Even if it still works, I like consistency. ;-)
___
*[ci/travis-install.sh, line 47 at r4](https://reviewable.io/reviews/pmem/fio/4#-MJ7frwc1zTG5N7gmXqW:-MJ8M77rAr35Tm7Ly6Wc:b-o7ptip) ([raw file](https://github.com/pmem/fio/blob/8d08283bc35a9353f67d3a9012e7985c26ce1f19/ci/travis-install.sh#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

after normalisation (the one, you quoted in some comment above) isn't it `x86_64` instead of `amd64`?
</blockquote></details>

This file for sure mentions amd64 few line above. @ldorau ?

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4#-:-MJ8Po_aE4jKUNU33_li:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @lukaszstolarczuk)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @lukaszstolarczuk)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @lukaszstolarczuk)

___
*[configure, line 2807 at r4](https://reviewable.io/reviews/pmem/fio/4#-MJ7erBS6YwwbNJ8wYvF:-MJAziV9-S0KbBPH0u3C:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8d08283bc35a9353f67d3a9012e7985c26ce1f19/configure#L2807)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Even if it still works, I like consistency. ;-)
</blockquote></details>

Done.
___
*[ci/travis-install.sh, line 47 at r4](https://reviewable.io/reviews/pmem/fio/4#-MJ7frwc1zTG5N7gmXqW:-MJB0Wo_3IOJb22MSG8r:b-9s4eq7) ([raw file](https://github.com/pmem/fio/blob/8d08283bc35a9353f67d3a9012e7985c26ce1f19/ci/travis-install.sh#L47)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This file for sure mentions amd64 few line above. @ldorau ?
</blockquote></details>

This script is run directly on Travis and uses Travis' variables. 'amd64' stands for 'x86_64' in the Travis' nomenclature.
The normalization is done later in the fio's configure stage.

**Review by ldorau — COMMENTED** [review]
Two osx builds fails, because of the osx's repository failure:

```
$ ci/travis-install.sh
+CI_TARGET_ARCH=amd64
+case "$TRAVIS_OS_NAME" in
+brew update

The command "ci/travis-install.sh" failed and exited with 1 during .
Your build has been stopped.
```

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4#-:-MJBC2E26F7EveM5B0k1:biw50wn)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
