### PR TITLE
rpma: add AOF scaffolding

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/211)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/211)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[configure, line 2828 at r1](https://reviewable.io/reviews/pmem/fio/211#-MTehYJkECf0XrbtWzbQ:-MTehYJl28rB_pMeSe4X:bvyt758) ([raw file](https://github.com/pmem/fio/blob/3355821a3583e116d4b710e64be37593c68e9d95/configure#L2828)):*
> ```
>     -a "$librpma" = "yes" -a "$libpmem" = "yes" ; then
>   output_sym "CONFIG_LIBRPMA_APM"
>   output_sym "CONFIG_LIBRPMA_AOF"
> ```

I think it should go next to the GPSPM since it would probably use libprotobuf_c.
___
*[Makefile, line 99 at r1](https://reviewable.io/reviews/pmem/fio/211#-MTehz6u2OJjftb7YIlv:-MTehz6u2OJjftb7YIlw:b-pqiih5) ([raw file](https://github.com/pmem/fio/blob/3355821a3583e116d4b710e64be37593c68e9d95/Makefile#L99)):*
> ```Makefile
> ifdef CONFIG_LIBRPMA_APM
>   librpma_apm_SRCS = engines/librpma_apm.c
>   librpma_common_SRCS = engines/librpma_common.c
> ```

Something is messed up here.
___
*[Makefile, line 110 at r1](https://reviewable.io/reviews/pmem/fio/211#-MTehtwK6NL3iCHzhhbj:-MTehtwLBRIW48JH_qsP:bspkbzb) ([raw file](https://github.com/pmem/fio/blob/3355821a3583e116d4b710e64be37593c68e9d95/Makefile#L110)):*
> ```Makefile
> endif
> ifdef CONFIG_LIBRPMA_AOF
>   librpma_gpspm_SRCS = engines/librpma_aof.c
> ```

gpspm -> aof
___
*[Makefile, line 112 at r1](https://reviewable.io/reviews/pmem/fio/211#-MTei2ZP7wj9O7KT4Wpq:-MTei2ZP7wj9O7KT4Wpr:b3kqx) ([raw file](https://github.com/pmem/fio/blob/3355821a3583e116d4b710e64be37593c68e9d95/Makefile#L112)):*
> ```Makefile
>   librpma_gpspm_SRCS = engines/librpma_aof.c
>   librpma_fio_SRCS = engines/librpma_fio.c
>   librpma_gpspm_LIBS = -lrpma -lpmem
> ```

.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/211)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_aof.c, line 100 at r1](https://reviewable.io/reviews/pmem/fio/211#-MTeldpO-tCu5wuR14XN:-MTeldpO-tCu5wuR14XO:b-fuhp06) ([raw file](https://github.com/pmem/fio/blob/3355821a3583e116d4b710e64be37593c68e9d95/engines/librpma_aof.c#L100)):*
> ```C
> 	.init			= client_init,
> 	.post_init		= client_post_init,
> 	.get_file_size		= client_get_file_size,
> ```

Indentation.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/211)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[configure, line 2828 at r1](https://reviewable.io/reviews/pmem/fio/211#-MTehYJkECf0XrbtWzbQ:-MTet0Bb94VM00haUMav:b-896fix) ([raw file](https://github.com/pmem/fio/blob/3355821a3583e116d4b710e64be37593c68e9d95/configure#L2828)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think it should go next to the GPSPM since it would probably use libprotobuf_c.
</blockquote></details>

Done.
___
*[Makefile, line 99 at r1](https://reviewable.io/reviews/pmem/fio/211#-MTehz6u2OJjftb7YIlv:-MTetZuu8vA18HGcDq0H:b-896fix) ([raw file](https://github.com/pmem/fio/blob/3355821a3583e116d4b710e64be37593c68e9d95/Makefile#L99)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Something is messed up here.
</blockquote></details>

Done.
___
*[Makefile, line 110 at r1](https://reviewable.io/reviews/pmem/fio/211#-MTehtwK6NL3iCHzhhbj:-MTet_YxCsxfJi13avWu:b-896fix) ([raw file](https://github.com/pmem/fio/blob/3355821a3583e116d4b710e64be37593c68e9d95/Makefile#L110)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

gpspm -> aof
</blockquote></details>

Done.
___
*[Makefile, line 112 at r1](https://reviewable.io/reviews/pmem/fio/211#-MTei2ZP7wj9O7KT4Wpq:-MTet_vt83JQry1IKQiS:b-896fix) ([raw file](https://github.com/pmem/fio/blob/3355821a3583e116d4b710e64be37593c68e9d95/Makefile#L112)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[engines/librpma_aof.c, line 100 at r1](https://reviewable.io/reviews/pmem/fio/211#-MTeldpO-tCu5wuR14XN:-MTetlVc1oI8NJ01g_i4:b-tqh4ug) ([raw file](https://github.com/pmem/fio/blob/3355821a3583e116d4b710e64be37593c68e9d95/engines/librpma_aof.c#L100)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Indentation.
</blockquote></details>

All is OK. Reviewable displays it in a wrong way.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/211)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_aof.c, line 100 at r1](https://reviewable.io/reviews/pmem/fio/211#-MTeldpO-tCu5wuR14XN:-MTetwDg6upgWtE2W5az:b-896fix) ([raw file](https://github.com/pmem/fio/blob/3355821a3583e116d4b710e64be37593c68e9d95/engines/librpma_aof.c#L100)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

All is OK. Reviewable displays it in a wrong way.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/211#-:-MTf7WeP5G3gFISfmcQh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/211#-:-MTfHN5UBWhrsLITXgQX:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_aof.c, line 116 at r2](https://reviewable.io/reviews/pmem/fio/211#-MTfH2J96j9VRiziWhVI:-MTfH2J96j9VRiziWhVJ:b36p882) ([raw file](https://github.com/pmem/fio/blob/4d4667a67f419a99392664658d220d8a5504ed94/engines/librpma_aof.c#L116)):*
> ```C
> /* server side implementation */
> ```

Empty line.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/211)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[engines/librpma_aof.c, line 116 at r2](https://reviewable.io/reviews/pmem/fio/211#-MTfH2J96j9VRiziWhVI:-MTfHsH48X8N679IBUbn:b-896fix) ([raw file](https://github.com/pmem/fio/blob/4d4667a67f419a99392664658d220d8a5504ed94/engines/librpma_aof.c#L116)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Empty line.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/211)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/211#-:-MTfIqS6DVCfC-8GqjwD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/211)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
