### PR TITLE
rpma: gpspm: use a ring buffer instead of an array

### PR DESCRIPTION
**Pull request by ldorau**
Using a ring buffer instead of an array we do not need
to copy (memcpy()) data at all.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/107)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/107)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/107#-MQXcs6h1k3fVb6NMsQ1:-MQXcs6h1k3fVb6NMsQ2:b-6w3zbg) (no related file):*
Have you run this change against `bw-th` (e.g. with `SHORT_RUNTIME=1` ;-))?
As a smoke test.

---
___
*[engines/librpma_gpspm.c, line 1088 at r1](https://reviewable.io/reviews/pmem/fio/107#-MQXcCrp-L7JYrtoe0si:-MQXcCrp-L7JYrtoe0sj:b-so9wsd) ([raw file](https://github.com/pmem/fio/blob/3a85ba84f916b72b82a4d8256c3dbc16bbf0db24/engines/librpma_gpspm.c#L1088)):*
> ```C
> 	sd->i_msgs_write = 0;
> 	sd->i_msgs_read = 0;
> 	sd->n_msgs_queued = 0;
> ```

All of these are calloc'ed. No need for zero-initialization.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/107)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/107#-MQXcs6h1k3fVb6NMsQ1:-MQXdpNQ7mSFPtyZ68Qp:b-w29tw8) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Have you run this change against `bw-th` (e.g. with `SHORT_RUNTIME=1` ;-))?
As a smoke test.
</blockquote></details>

Not yet, machines are busy now - the benchmarks are running.

---
___
*[engines/librpma_gpspm.c, line 1088 at r1](https://reviewable.io/reviews/pmem/fio/107#-MQXcCrp-L7JYrtoe0si:-MQXeHzW4kQc698kTV1Q:b-896fix) ([raw file](https://github.com/pmem/fio/blob/3a85ba84f916b72b82a4d8256c3dbc16bbf0db24/engines/librpma_gpspm.c#L1088)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

All of these are calloc'ed. No need for zero-initialization.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/107)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/107#-MQXcs6h1k3fVb6NMsQ1:-MQYAEkq7GtEbPhTJbKL:bymxhsw) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet, machines are busy now - the benchmarks are running.
</blockquote></details>

I recommend running a full 60s bw-th for threads=4. This is the workload which has forced me to introduce this array-based queue implementation in the first place.

---

**Comment by ldorau** [comment]
> > Reviewed 1 of 1 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/pmem/fio/107)_ status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)
> 
> _[a discussion](https://reviewable.io/reviews/pmem/fio/107#-MQXcs6h1k3fVb6NMsQ1:-MQYAEkq7GtEbPhTJbKL:bymxhsw) (no related file):_
> 
> Previously, ldorau (Lukasz Dorau) wrote…
> I recommend running a full 60s bw-th for threads=4. This is the workload which has forced me to introduce this array-based queue implementation in the first place.

Full 60s bw-th:

GPSPM_WRITE_BW-TH_PMEM_bs4096_dp2

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/107)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/107#-MQXcs6h1k3fVb6NMsQ1:-MQYPIRy5DLO_2Hl6Lug:b-4oq847) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Full 60s bw-th:

GPSPM_WRITE_BW-TH_PMEM_bs4096_dp2 
</blockquote></details>

OK, it fails often for 16 threads:

```
[mode: gpspm, op: write, size: 4096, threads: 16, iodepth: 2]
Jan 08 10:28:47.790658 [583275] *ERROR* mr.c: 181: rpma_mr_write: ibv_post_send(src_addr=0xab57b700, rkey=0x1cfb6, dst_addr=0xcc009000, length=4096, lkey=0x47764, wr_id=0x0, opcode=IBV_WR_RDMA_WRITE, send_flags=0) failed: Cannot allocate memory
```

---

**Pull request closed without merging**
