### PR TITLE
rpma: direct_write_to_pmem servers' option

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- ~~#154~~

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/155)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
do we need any changes in example/*.fio files?

> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/155#-:-MRTKJyK12CkqOM7ArGY:b-5nh395)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 139 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRTKZVf1FYMovN-cUYG:-MRTKZVf1FYMovN-cUYH:b-wy9s8s) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma.c#L139)):*
> ```
> 			log_err(
> 					"Direct Write to PMEM not supported by the server (direct_write_to_pmem)\n"
> 					);
> ```
+
"Fio librpma engine will not work until direct write on the server side will be possible"
___
*[engines/librpma_common.c, line 708 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRTL4KMAclitoHmbQRL:-MRTL4KMAclitoHmbQRM:bdrx1za) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma_common.c#L708)):*
> ```
> direct_write_to_pmem
> ```
directwritetopmem

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/155)* status: all files reviewed, 10 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 139 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRTar5p1BjnyFnKgg2y:-MRTar5p1BjnyFnKgg2z:bo7wqlv) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma.c#L139)):*
> ```
>  PMEM not supported
> ```

`PMEM is not supported`
___
*[engines/librpma.c, line 140 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRT_9Zj-O7UpoLV6r2p:-MRT_9Zj-O7UpoLV6r2q:b-rvchwm) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma.c#L140)):*
> ```
> 			log_err(
> 					"Direct Write to PMEM not supported by the server (direct_write_to_pmem)\n"
> 					);
> ```

(style) IMHO two tabs before a message is too many (one is enough ) and the parenthesis should go in the same line:

```
			log_err(
				"Direct Write to PMEM not supported by the server (direct_write_to_pmem)\n");

```
___
*[engines/librpma.c, line 166 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRTb8pDDhxrAAscPeTE:-MRTb8pE7Vp4Zct5bYjA:bmsstcu) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma.c#L166)):*
> ```
> if you are DRAM
> ```

`if you use DRAM`
___
*[engines/librpma.c, line 166 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRTbEpa7AxgtBPhSE6o:-MRTbEpa7AxgtBPhSE6p:b3xd44) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma.c#L166)):*
> ```
> of a PMEM
> ```

`of PMEM`
___
*[engines/librpma.c, line 167 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRTbNzY2_t7Uo99Yhwn:-MRTbNzY2_t7Uo99Yhwo:b-s1w1le) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma.c#L167)):*
> ```
> Remember flushing 
> ```

`Remember that flushing `
___
*[engines/librpma.c, line 168 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRTaXVRCzrTsANvap7v:-MRTaXVSB-SOYtJieJPk:b9j8xop) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma.c#L168)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 		log_info(
> 				"Note: Direct Write to PMEM is not supported by default nor required if you are DRAM instead of a PMEM on the server side.\n"
> 				"Remember flushing to DRAM does not make your data persistent and may be used only for experimental purposes.\n"
> 				);
> ```
</details>


```
		log_info(
			"Note: Direct Write to PMEM is not supported by default nor required if you are DRAM instead of a PMEM on the server side.\n"
			"Remember flushing to DRAM does not make your data persistent and may be used only for experimental purposes.\n");
```
___
*[engines/librpma_common.c, line 712 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRTbhmdE_6rSnZe9-3r:-MRTbhmdE_6rSnZe9-3s:b-b8ek1i) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma_common.c#L712)):*
> ```
> "is direct write to PMEM possible"
> ```

`"is direct write to PMEM possible?"`
or
`"direct write to PMEM is possible"`
___
*[engines/librpma_gpspm.c, line 165 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRTcB-H7GF--lzUBHAw:-MRTcB-H7GF--lzUBHAx:blxeoza) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma_gpspm.c#L165)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 			log_info(
> 					"Note: The server side supports Direct Write to PMEM and it is equipped with PMEM.\n"
> 					"You can use librpma_client and librpma_server engines for better performance instead of GPSPM.\n"
> 					);
> ```
</details>


.

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/155)* status: all files reviewed, 10 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/155)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 139 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRTKZVf1FYMovN-cUYG:-MRUl3xd847kNmjD3u7_:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma.c#L139)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 			log_err(
> 					"Direct Write to PMEM not supported by the server (direct_write_to_pmem)\n"
> 					);
> ```
+
"Fio librpma engine will not work until direct write on the server side will be possible"
</blockquote></details>

Done.
___
*[engines/librpma.c, line 139 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRTar5p1BjnyFnKgg2y:-MRUl8O5BjwGHjfec5PI:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma.c#L139)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  PMEM not supported
> ```

`PMEM is not supported`
</blockquote></details>

Done.
___
*[engines/librpma.c, line 140 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRT_9Zj-O7UpoLV6r2p:-MRUlF2F6CHCRO-j5cvQ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma.c#L140)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 			log_err(
> 					"Direct Write to PMEM not supported by the server (direct_write_to_pmem)\n"
> 					);
> ```

(style) IMHO two tabs before a message is too many (one is enough ) and the parenthesis should go in the same line:

```
			log_err(
				"Direct Write to PMEM not supported by the server (direct_write_to_pmem)\n");

```
</blockquote></details>

Done.
___
*[engines/librpma.c, line 166 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRTb8pDDhxrAAscPeTE:-MRUlNuB9HK1-qhQfTtH:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma.c#L166)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> if you are DRAM
> ```

`if you use DRAM`
</blockquote></details>

Done.
___
*[engines/librpma.c, line 166 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRTbEpa7AxgtBPhSE6o:-MRUlQ4721RsXWEcnlMh:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma.c#L166)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> of a PMEM
> ```

`of PMEM`
</blockquote></details>

Done.
___
*[engines/librpma.c, line 167 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRTbNzY2_t7Uo99Yhwn:-MRUlU59-VYXmLpoC36x:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma.c#L167)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Remember flushing 
> ```

`Remember that flushing `
</blockquote></details>

Done.
___
*[engines/librpma.c, line 168 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRTaXVRCzrTsANvap7v:-MRUlX1e4Iepgh-B_d0R:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma.c#L168)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 		log_info(
> 				"Note: Direct Write to PMEM is not supported by default nor required if you are DRAM instead of a PMEM on the server side.\n"
> 				"Remember flushing to DRAM does not make your data persistent and may be used only for experimental purposes.\n"
> 				);
> ```

```
		log_info(
			"Note: Direct Write to PMEM is not supported by default nor required if you are DRAM instead of a PMEM on the server side.\n"
			"Remember flushing to DRAM does not make your data persistent and may be used only for experimental purposes.\n");
```
</blockquote></details>

Done.
___
*[engines/librpma_common.c, line 708 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRTL4KMAclitoHmbQRL:-MRUlYjs-2SwJYMih6ap:bxk7wea) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma_common.c#L708)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> direct_write_to_pmem
> ```
directwritetopmem
</blockquote></details>

IMHO unreadable. I want to use FIO inconsistent using of underscores to increase readability.
___
*[engines/librpma_common.c, line 712 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRTbhmdE_6rSnZe9-3r:-MRUluKe27Qhf-6_lvDF:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma_common.c#L712)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "is direct write to PMEM possible"
> ```

`"is direct write to PMEM possible?"`
or
`"direct write to PMEM is possible"`
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 165 at r1](https://reviewable.io/reviews/pmem/fio/155#-MRTcB-H7GF--lzUBHAw:-MRUmuM22SCJGi1WSjiJ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e37daba1b37bc2a44710747d0d4c852e32e3345e/engines/librpma_gpspm.c#L165)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 			log_info(
> 					"Note: The server side supports Direct Write to PMEM and it is equipped with PMEM.\n"
> 					"You can use librpma_client and librpma_server engines for better performance instead of GPSPM.\n"
> 					);
> ```

.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/155)* status: all files reviewed, 11 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/155#-MRUoonWD4o3yAnec3Pp:-MRUoonWD4o3yAnec3Pq:b-6ldw7q) (no related file):*
PMem rather than PMEM

---
___
*[engines/librpma_common.c, line 43 at r3](https://reviewable.io/reviews/pmem/fio/155#-MRUp4av9hGP9hdasiJ0:-MRUp4av9hGP9hdasiJ1:b-y6m60j) ([raw file](https://github.com/pmem/fio/blob/437f810db7ae6710cb518000832d3f84b8a32607/engines/librpma_common.c#L43)):*
> ```
> rpma_direct_write_to_pmem
> ```
Remote direct write to PMem (via RDMA) is available
___
*[engines/librpma_common.c, line 46 at r3](https://reviewable.io/reviews/pmem/fio/155#-MRUoY2KCMgfXuClKa7M:-MRUoY2KCMgfXuClKa7N:bldn85a) ([raw file](https://github.com/pmem/fio/blob/437f810db7ae6710cb518000832d3f84b8a32607/engines/librpma_common.c#L46)):*
> ```
> direct write to PMEM from the remote host is possible
> ```
set to true ONLY when direct write to PMem from the remote host is possible

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/155)* status: 0 of 4 files reviewed, 10 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_common.c, line 43 at r3](https://reviewable.io/reviews/pmem/fio/155#-MRUp4av9hGP9hdasiJ0:-MRUucRlA9rOS7Uu60Rx:b-896fix) ([raw file](https://github.com/pmem/fio/blob/437f810db7ae6710cb518000832d3f84b8a32607/engines/librpma_common.c#L43)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_direct_write_to_pmem
> ```
Remote direct write to PMem (via RDMA) is available
</blockquote></details>

Done.
___
*[engines/librpma_common.c, line 46 at r3](https://reviewable.io/reviews/pmem/fio/155#-MRUoY2KCMgfXuClKa7M:-MRUucqwBlBZkuEZDq9-:b-896fix) ([raw file](https://github.com/pmem/fio/blob/437f810db7ae6710cb518000832d3f84b8a32607/engines/librpma_common.c#L46)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> direct write to PMEM from the remote host is possible
> ```
set to true ONLY when direct write to PMem from the remote host is possible
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/155)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/155#-:-MRUy87GCfR1vIG0tjx_:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/155)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 135 at r4](https://reviewable.io/reviews/pmem/fio/155#-MRUxrFb366Mg2Out0Vm:-MRUxrFb366Mg2Out0Vn:b-n23bzi) ([raw file](https://github.com/pmem/fio/blob/785fad6d7d48648c64f00ce3b5bc6e8e3f671ab7/engines/librpma.c#L135)):*
> ```
> side will be possible 
> ```

grammar:

`... side is possible ...` (future_tense until present_tense)
___
*[engines/librpma_common.c, line 46 at r4](https://reviewable.io/reviews/pmem/fio/155#-MRUysHz8KM1cJw9rnNI:-MRUysHz8KM1cJw9rnNJ:b-z0d2lf) ([raw file](https://github.com/pmem/fio/blob/785fad6d7d48648c64f00ce3b5bc6e8e3f671ab7/engines/librpma_common.c#L46)):*
> ```
> Set true ONLY when
> ```

`Set to true ONLY when`
or
`True ONLY when`

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/155)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/155)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 135 at r4](https://reviewable.io/reviews/pmem/fio/155#-MRUxrFb366Mg2Out0Vm:-MRVEIBDBmPCEKZg_rTR:b-896fix) ([raw file](https://github.com/pmem/fio/blob/785fad6d7d48648c64f00ce3b5bc6e8e3f671ab7/engines/librpma.c#L135)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> side will be possible 
> ```

grammar:

`... side is possible ...` (future_tense until present_tense)
</blockquote></details>

Done.
___
*[engines/librpma_common.c, line 46 at r4](https://reviewable.io/reviews/pmem/fio/155#-MRUysHz8KM1cJw9rnNI:-MRVEaHe5u1u8ezykudE:b-896fix) ([raw file](https://github.com/pmem/fio/blob/785fad6d7d48648c64f00ce3b5bc6e8e3f671ab7/engines/librpma_common.c#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Set true ONLY when
> ```

`Set to true ONLY when`
or
`True ONLY when`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/155)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/155#-:-MRVFIl93plYHxZCVG8r:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
