### PR TITLE
rpma: gpspm: set server's queue sizes

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/96)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/96)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 1319 at r1](https://reviewable.io/reviews/pmem/fio/96#-MQHq41gAh0Lxbvi5C1i:-MQHq41h3hJTgAFOV0Vu:beetdp4) ([raw file](https://github.com/pmem/fio/blob/c21ac043c6926e6ab377d59e201139be17ddbb25/engines/librpma_gpspm.c#L1319)):*
> ```
> if (!cfg)
> ```

`if (cfg)`

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/96)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 1319 at r1](https://reviewable.io/reviews/pmem/fio/96#-MQHq41gAh0Lxbvi5C1i:-MQHqnsU0UH0qNC5Yrk1:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c21ac043c6926e6ab377d59e201139be17ddbb25/engines/librpma_gpspm.c#L1319)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> if (!cfg)
> ```

`if (cfg)`
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/96#-:-MQHrzvI2sH9rA2z894G:bdycpsm)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 1319 at r1](https://reviewable.io/reviews/pmem/fio/96#-MQHq41gAh0Lxbvi5C1i:-MQHrmXR9beJcAocBZut:bfo71y7) ([raw file](https://github.com/pmem/fio/blob/c21ac043c6926e6ab377d59e201139be17ddbb25/engines/librpma_gpspm.c#L1319)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

if we create cfg at the beginign of this function (and keep it until the end of this function) then we will not need any if() logic here

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/96)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_gpspm.c, line 1274 at r1](https://reviewable.io/reviews/pmem/fio/96#-MQHsOct5vB5m7wChwy2:-MQHsOct5vB5m7wChwy3:bdf8c4d) ([raw file](https://github.com/pmem/fio/blob/c21ac043c6926e6ab377d59e201139be17ddbb25/engines/librpma_gpspm.c#L1274)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 	ret = rpma_conn_cfg_delete(&cfg);
> 	if (ret) {
> 		rpma_td_verror(td, ret, "rpma_conn_cfg_delete");
> 		goto err_req_delete;
> 	}
> ```
</details>

can we remove this only at the end of this function?

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/96#-:-MQHsnjZ8VVcY4vKoWPY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/96)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 1319 at r1](https://reviewable.io/reviews/pmem/fio/96#-MQHq41gAh0Lxbvi5C1i:-MQHsukF6G2U7aQMw6Hc:bu9e4r5) ([raw file](https://github.com/pmem/fio/blob/c21ac043c6926e6ab377d59e201139be17ddbb25/engines/librpma_gpspm.c#L1319)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

if we create cfg at the beginign of this function (and keep it until the end of this function) then we will not need any if() logic here
</blockquote></details>

We do not need any `if` logic here. It is redundant to be honest. RPMA can handle NULL pointer here.

**Pull request merged**
