### PR TITLE
rpma: remove not required engine flags

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/191)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
@osalyk Have you run all types of workloads on real HW?

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/191#-:-MRxOxUaCG80n6ntA8hq:b-rawyi6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
I've launched:
DRAM/PMEM APM write lat/bw-th
PMEM GPSPM write lat/bw-th

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/191#-:-MRxgLl53IUxiYTYLZZ3:b-8cb4gq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
If you have run both DRAM and PMEM, it should be enough.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/191#-:-MRxkmi96eJo4h_rUqPm:bid8u2s)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/191)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/191#-MRxwfNq2-4slLp6FS4X:-MRxwfNq2-4slLp6FS4Y:b9g8hr5) (no related file):*
How about the servers side?

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/191)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/191#-MRxwfNq2-4slLp6FS4X:-MRxyV0G-VqnSqvBWt4j:b-ocv4i0) (no related file):*
> How about the servers side?
Server side flags had no comment. Therefore, they were not checked.

---

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/191#-:-MRy6OPd2bI1t4O9IjcC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
