### PR TITLE
rpma: errdetails implementation

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/21)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/21)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/21)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 342 at r1](https://reviewable.io/reviews/pmem/fio/21#-MJaT9tA8M6LvWorUywV:-MJaT9tA8M6LvWorUywW:bvffx6n) ([raw file](https://github.com/pmem/fio/blob/e5f13db26c9f644f40fc71eace6ba6317d712c22/engines/librpma.c#L342)):*
> ```
> /* get a string representation of the error */
> ```

/* get **the** string representation of **an** error */
___
*[engines/librpma.c, line 350 at r1](https://reviewable.io/reviews/pmem/fio/21#-MJaT-EHBoEagMUKbeOx:-MJaT-EHBoEagMUKbeOy:b8lypat) ([raw file](https://github.com/pmem/fio/blob/e5f13db26c9f644f40fc71eace6ba6317d712c22/engines/librpma.c#L350)):*
> ```
> /* the FIO frees the returned string when it will become obsolete */
> ```

/* **FIO** frees the returned string when it **becomes** obsolete */

**Review by grom72 — COMMENTED** [review]
:goat: 
but is it needed in this sprint?

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/21#-:-MJadSBu5PN005Mpzk-q:b2rkdut)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
At may be useful in case we will have an issue running our engine. So at the beginning. So it may be helpful in this sprint. ;-)

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/21#-:-MJah8Aq0GxqiyHcl2Rq:b92hfh6)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
Do we assume the librpma return value will be presented somewhere else?

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/21#-:-MJaiILFBBXPhiSLHA0D:biri7tb)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/21)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[engines/librpma.c, line 342 at r1](https://reviewable.io/reviews/pmem/fio/21#-MJaT9tA8M6LvWorUywV:-MJaq0md7dzogassKT7W:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e5f13db26c9f644f40fc71eace6ba6317d712c22/engines/librpma.c#L342)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> /* get a string representation of the error */
> ```

/* get **the** string representation of **an** error */
</blockquote></details>

Done.
___
*[engines/librpma.c, line 350 at r1](https://reviewable.io/reviews/pmem/fio/21#-MJaT-EHBoEagMUKbeOx:-MJaq6R435w8lwSnuULg:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e5f13db26c9f644f40fc71eace6ba6317d712c22/engines/librpma.c#L350)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> /* the FIO frees the returned string when it will become obsolete */
> ```

/* **FIO** frees the returned string when it **becomes** obsolete */
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/21#-:-MJaqRMr5gjWLbEM5tDR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
