### PR TITLE
rpma: --debug=net sets RPMA_LOG_THRESHOLD_AUX to RPMA_LOG_LEVEL_INFO

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/166)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/166)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_common.c, line 170 at r1](https://reviewable.io/reviews/pmem/fio/166#-MRVH5Jc-ntrDnIB9bsb:-MRVH5Jc-ntrDnIB9bsc:b-h0icox) ([raw file](https://github.com/pmem/fio/blob/b8d90f9449ea6229a62440b55914724bcc2ab0ca/engines/librpma_common.c#L170)):*
> ```C
> 	/* --debug=net sets RPMA_LOG_THRESHOLD_AUX to RPMA_LOG_LEVEL_INFO */
> 	log_level_aux = RPMA_LOG_LEVEL_WARNING;
> #ifdef FIO_INC_DEBUG
> ```

Does it require a debug FIO build?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/166)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_common.c, line 170 at r1](https://reviewable.io/reviews/pmem/fio/166#-MRVH5Jc-ntrDnIB9bsb:-MRVHMWg4REqRgdiLFh5:b4756jg) ([raw file](https://github.com/pmem/fio/blob/b8d90f9449ea6229a62440b55914724bcc2ab0ca/engines/librpma_common.c#L170)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Does it require a debug FIO build?
</blockquote></details>

No, it does not. I have tested it.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/166)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_common.c, line 170 at r1](https://reviewable.io/reviews/pmem/fio/166#-MRVH5Jc-ntrDnIB9bsb:-MRVI_Fk0lmwi9oYqsdk:b-4i7q1) ([raw file](https://github.com/pmem/fio/blob/b8d90f9449ea6229a62440b55914724bcc2ab0ca/engines/librpma_common.c#L170)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, it does not. I have tested it.
</blockquote></details>

I meant I recompiled fio without any EXTRA_CFLAGS and it worked.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/166)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_common.c, line 170 at r1](https://reviewable.io/reviews/pmem/fio/166#-MRVH5Jc-ntrDnIB9bsb:-MRVJ5ne6N9qSBEqj4VX:b-rt4xpa) ([raw file](https://github.com/pmem/fio/blob/b8d90f9449ea6229a62440b55914724bcc2ab0ca/engines/librpma_common.c#L170)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I meant I recompiled fio without any EXTRA_CFLAGS and it worked.
</blockquote></details>

... I ran `./configure && make && make install` - all default options

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/166)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/166#-MRVHJ8o9dwZfp2pQkPJ:-MRVHJ8p7NhksOzK8xgK:b8zkctl) (no related file):*
server side is missing

---
___
*[engines/librpma_common.c, line 158 at r1](https://reviewable.io/reviews/pmem/fio/166#-MRVHPPy5GiDQ05fPQRq:-MRVHPPy5GiDQ05fPQRr:b-ug1r6v) ([raw file](https://github.com/pmem/fio/blob/b8d90f9449ea6229a62440b55914724bcc2ab0ca/engines/librpma_common.c#L158)):*
> ```
> enum rpma_log_level log_level_aux;
> ```
 enum rpma_log_level log_level_aux = RPMA_LOG_LEVEL_WARNING;

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/166#-:-MRVKvVA7urqL8PItYpJ:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/166#-MRVHJ8o9dwZfp2pQkPJ:-MRVKw9R3Aq5-Iq5LF7N:b32v57) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

server side is missing
</blockquote></details>

+1

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/166)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/166#-MRVHJ8o9dwZfp2pQkPJ:-MRVNo9DEpTXKKPmeq4u:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

---
___
*[engines/librpma_common.c, line 158 at r1](https://reviewable.io/reviews/pmem/fio/166#-MRVHPPy5GiDQ05fPQRq:-MRVNnbCAK82vVfVw2Oe:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b8d90f9449ea6229a62440b55914724bcc2ab0ca/engines/librpma_common.c#L158)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> enum rpma_log_level log_level_aux;
> ```
 enum rpma_log_level log_level_aux = RPMA_LOG_LEVEL_WARNING;
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/166#-:-MRVOlYe9y6XS4-G_tZ_:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
