### PR TITLE
aof: add option to use the rpma_conn_completion_wait() function

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #253 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/252)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/252)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
Rebased

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/252#-:-MVzu6bn2QkXy3OguAkY:b9x2p3v)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/252#-:-MVzuWta219D2ofu-A9v:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/252#-:-MW4F93Z8UhTm5bKKyEv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
