### PR TITLE
rpma: gpspm: introduce sync mode

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #87

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/88)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/88#-:-MQBs7kr-ytSxvWHbYg8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/88)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 596 at r2](https://reviewable.io/reviews/pmem/fio/88#-MQC5Ljv8Deh3Sv5ZomT:-MQC5Ljw0vnECogY0jnl:bxmexul) ([raw file](https://github.com/pmem/fio/blob/d841e9c2a1976feb925dbe3733981b6e4875edf0/engines/librpma_gpspm.c#L596)):*
> ```
> 		if (cmpl.op == RPMA_OP_RECV)
> 			break;
> 	} while (1);
> ```

```
	} while (cmpl.op != RPMA_OP_RECV);
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/88)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 596 at r2](https://reviewable.io/reviews/pmem/fio/88#-MQC5Ljv8Deh3Sv5ZomT:-MQCHaek6oOgHv3jlj11:bz3zbhb) ([raw file](https://github.com/pmem/fio/blob/d841e9c2a1976feb925dbe3733981b6e4875edf0/engines/librpma_gpspm.c#L596)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 		if (cmpl.op == RPMA_OP_RECV)
> 			break;
> 	} while (1);
> ```

```
	} while (cmpl.op != RPMA_OP_RECV);
```
</blockquote></details>

```
} while (ret == RPMA_E_NO_COMPLETION || cmpl.op != RPMA_OP_RECV);
```

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/88)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 596 at r2](https://reviewable.io/reviews/pmem/fio/88#-MQC5Ljv8Deh3Sv5ZomT:-MQCH1LhDNE8c9w9PGIn:bgqtr8a) ([raw file](https://github.com/pmem/fio/blob/d841e9c2a1976feb925dbe3733981b6e4875edf0/engines/librpma_gpspm.c#L596)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
} while (ret == RPMA_E_NO_COMPLETION || cmpl.op != RPMA_OP_RECV);
```
</blockquote></details>

So it would duplicate check which was already done in the loop body. Don't like this idea.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/88)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 596 at r2](https://reviewable.io/reviews/pmem/fio/88#-MQC5Ljv8Deh3Sv5ZomT:-MQCHmQw0YIWX3vQvBIJ:bdikqxx) ([raw file](https://github.com/pmem/fio/blob/d841e9c2a1976feb925dbe3733981b6e4875edf0/engines/librpma_gpspm.c#L596)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

So it would duplicate check which was already done in the loop body. Don't like this idea.
</blockquote></details>

So maybe add a comment ?

```
} while (1); /* while (ret == RPMA_E_NO_COMPLETION || cmpl.op != RPMA_OP_RECV); */
```

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/88#-:-MQCR4w53vmw4ybbY0MY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
