### PR TITLE
rpma: use completion context to compute addresses of messages' buffers

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #59

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/62)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/62)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/62#-:-MM-c1y51v3kXm-oreQN:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/62)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
Rebased

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/62#-:-MML8AvR9J9AVE4GI3L7:b9x2p3v)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/62#-:-MMP69Zb7Fq1TvhPyi7p:bdycpsm)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 535 at r3](https://reviewable.io/reviews/pmem/fio/62#-MMP5uZY2cX8bbJ9Xp4P:-MMP5uZY2cX8bbJ9Xp4Q:b-umpckl) ([raw file](https://github.com/pmem/fio/blob/b205e215f76ae25d60a421502d550af27396372c/engines/librpma_gpspm.c#L535)):*
> ```
> max_msg_size
> ```
do we have to memorize this value?
max_msg_size ==  td_max_bs(td)/2 
are we going to change this in the future?
___
*[engines/librpma_gpspm.c, line 721 at r3](https://reviewable.io/reviews/pmem/fio/62#-MMP4v-u0AjebAnBH4Cu:-MMP4v-vBoHchmgQryOo:brcq4el) ([raw file](https://github.com/pmem/fio/blob/b205e215f76ae25d60a421502d550af27396372c/engines/librpma_gpspm.c#L721)):*
> ```
> (const void *)(uintptr_t)i)
> ```
Would it be easier to use here pointer to the rcv buffer?
In such a case, less code will be required in server_queue() where send_ptr = recv_ptr - sd->max_msg_size

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/62)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @grom72)

___
*[engines/librpma_gpspm.c, line 535 at r3](https://reviewable.io/reviews/pmem/fio/62#-MMP5uZY2cX8bbJ9Xp4P:-MMPuKaMC_WvrEgsw-Rm:bjhcmg3) ([raw file](https://github.com/pmem/fio/blob/b205e215f76ae25d60a421502d550af27396372c/engines/librpma_gpspm.c#L535)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> max_msg_size
> ```
do we have to memorize this value?
max_msg_size ==  td_max_bs(td)/2 
are we going to change this in the future?
</blockquote></details>

No, we don't. I just didn't want to set it twice. 
I have removed it.
___
*[engines/librpma_gpspm.c, line 721 at r3](https://reviewable.io/reviews/pmem/fio/62#-MMP4v-u0AjebAnBH4Cu:-MMPvV2e8JfnD1A3YL7Q:bpyr6qm) ([raw file](https://github.com/pmem/fio/blob/b205e215f76ae25d60a421502d550af27396372c/engines/librpma_gpspm.c#L721)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> (const void *)(uintptr_t)i)
> ```
Would it be easier to use here pointer to the rcv buffer?
In such a case, less code will be required in server_queue() where send_ptr = recv_ptr - sd->max_msg_size

</blockquote></details>

No, it wouldn't be easier. It would be more complex and more difficult to understand in my opinion, because we also have to compute `send_offset`. The current solution is simpler and more elegant in my opinion.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/62)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/62#-MMQ91ac8_hfVfAuHuqY:-MMQ91ad9oCqlDx1GM3B:bhw3myt) (no related file):*
The changes in this PR seem unrelated to its title. Adjust either the title or the content.

---
___
*[engines/librpma_gpspm.c, line 717 at r4](https://reviewable.io/reviews/pmem/fio/62#-MMQ9AhJ3aNLBg9Xy0kn:-MMQ9AhJ3aNLBg9Xy0ko:b3b7db2) ([raw file](https://github.com/pmem/fio/blob/9f09d47da741fc64dc6f3db980b5a354543ac2a6/engines/librpma_gpspm.c#L717)):*
> ```C
> 	max_msg_size = td_max_bs(td) / 2;
> 	for (i = 0; i < td->o.iodepth; i++) {
> 		size_t offset_recv_msg = (2 * i + 1) * max_msg_size;
> ```

I do not like the idea of calculating the offsets of the messages ad hoc in various places.
Especially it assumes in all of those places we will remember the order of send/recv buffers in the pair.
I recommend creating something like:

```c
#define MAX_MSG_SIZE (512)
#define IO_U_BUF_LEN (2 * MAX_MSG_SIZE)
#define IO_U_BUF_OFF(td, i) \
    (((i) + (td)->o.iodepth_batch - 1) / (td)->o.iodepth_batch) * IO_U_BUF_LEN)

#define SEND_OFFSET (0)
#define RECV_OFFSET (SEND_OFFSET + MAX_MSG_SIZE)
```
which I have proposed for #65.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/62)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/62)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/62#-MMQ91ac8_hfVfAuHuqY:-MMQtMiW2K5gi0AsqIEK:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The changes in this PR seem unrelated to its title. Adjust either the title or the content.
</blockquote></details>

Done.

---
___
*[engines/librpma_gpspm.c, line 717 at r4](https://reviewable.io/reviews/pmem/fio/62#-MMQ9AhJ3aNLBg9Xy0kn:-MMQtRFIEWRZF4QaalJ4:b-896fix) ([raw file](https://github.com/pmem/fio/blob/9f09d47da741fc64dc6f3db980b5a354543ac2a6/engines/librpma_gpspm.c#L717)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not like the idea of calculating the offsets of the messages ad hoc in various places.
Especially it assumes in all of those places we will remember the order of send/recv buffers in the pair.
I recommend creating something like:

```c
#define MAX_MSG_SIZE (512)
#define IO_U_BUF_LEN (2 * MAX_MSG_SIZE)
#define IO_U_BUF_OFF(td, i) \
    (((i) + (td)->o.iodepth_batch - 1) / (td)->o.iodepth_batch) * IO_U_BUF_LEN)

#define SEND_OFFSET (0)
#define RECV_OFFSET (SEND_OFFSET + MAX_MSG_SIZE)
```
which I have proposed for #65.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/62)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/62#-:-MMS6VLT9-NCRSnRbYCZ:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/62)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 35 at r5](https://reviewable.io/reviews/pmem/fio/62#-MMSuBql7fUQxEf-O5KL:-MMSuBql7fUQxEf-O5KM:b-36f2mo) ([raw file](https://github.com/pmem/fio/blob/4f03213c6778387e9316f69bd661a83036db1cf2/engines/librpma_gpspm.c#L35)):*
> ```C
> #define IO_U_BUF_LEN (2 * MAX_MSG_SIZE)
> #define IO_U_BUF_OFF(td, i) \
> 	((((i) + (td)->o.iodepth_batch - 1) / (td)->o.iodepth_batch) * IO_U_BUF_LEN)
> ```

This one is not common. On the server-side, the number of send/recv buffers does not dependents on iodepth_batch.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/62)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 35 at r5](https://reviewable.io/reviews/pmem/fio/62#-MMSuBql7fUQxEf-O5KL:-MMUergT2xHfbEOZqX1e:b-896fix) ([raw file](https://github.com/pmem/fio/blob/4f03213c6778387e9316f69bd661a83036db1cf2/engines/librpma_gpspm.c#L35)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This one is not common. On the server-side, the number of send/recv buffers does not dependents on iodepth_batch.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/62)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/62#-:-MMUfMU48S0ldMLRQQaa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/62)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/62#-MMUfNtP0tOmKmdMKgv3:-MMUfNtQDeKS-LRUBxce:b-nn9sji) (no related file):*
@grom72 please 'rereview' this stuff. I have forced some bigger changes. ;-)

---

**Pull request merged**
