### PR TITLE
rpma: fix indentation in client_cleanup()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/22)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/22#-:-MJa3MYlBHWFRmBLLEja:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/22)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma.c, line 134 at r1](https://reviewable.io/reviews/pmem/fio/22#-MJa6kJJ6CneMUIjnbqx:-MJa6kJJ6CneMUIjnbqy:b-wjv42u) ([raw file](https://github.com/pmem/fio/blob/c538f32c1677d7b6684ed6e2d88a79144749353f/engines/librpma.c#L134)):*
> ```C
> 	ret = rpma_utils_get_ibv_context(o->hostname,
> 				RPMA_UTIL_IBV_CONTEXT_REMOTE,
> 				&dev);
> ```

What do you think about this place?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/22)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 134 at r1](https://reviewable.io/reviews/pmem/fio/22#-MJa6kJJ6CneMUIjnbqx:-MJaLyhn-JUQYsa0ckLz:bhei1va) ([raw file](https://github.com/pmem/fio/blob/c538f32c1677d7b6684ed6e2d88a79144749353f/engines/librpma.c#L134)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What do you think about this place?
</blockquote></details>

`&dev` could be in one line with `RPMA_UTIL_IBV_CONTEXT_REMOTE`, for example.

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/22)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma.c, line 134 at r1](https://reviewable.io/reviews/pmem/fio/22#-MJa6kJJ6CneMUIjnbqx:-MJaO5yE3vO8yeWt21q9:b-ak0ri8) ([raw file](https://github.com/pmem/fio/blob/c538f32c1677d7b6684ed6e2d88a79144749353f/engines/librpma.c#L134)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`&dev` could be in one line with `RPMA_UTIL_IBV_CONTEXT_REMOTE`, for example.
</blockquote></details>

We have three tabs indentation here. Whereas you are replacing 2 tabs with one.
I'm trying to understand the rule. ;-)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/22)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 134 at r1](https://reviewable.io/reviews/pmem/fio/22#-MJa6kJJ6CneMUIjnbqx:-MJaPKBS7m9hDL06XlKQ:b-1vzr7k) ([raw file](https://github.com/pmem/fio/blob/c538f32c1677d7b6684ed6e2d88a79144749353f/engines/librpma.c#L134)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We have three tabs indentation here. Whereas you are replacing 2 tabs with one.
I'm trying to understand the rule. ;-)
</blockquote></details>

The rules can be following:
1) Do not count tabs - the number of tabs does not matter at all ;-)
2) Try to not exceed 80 characters (except of long string messages that should not be broken of course).
3) Too long lines should be broken in the way the resulting code is the most clear to read, for example, the next function's arguments should as close as possible to the previous ones (with respecting 2)).

If something is wrong in this place,  I can submit another PR.

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/22#-:-MJagzPL3Vs_QBNJaGQF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
