### PR TITLE
rpma: use all 80 characters of the line

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/152)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/152)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_common.h, line 147 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTHzSO2anoqLb2EC1s:-MRTHzSO2anoqLb2EC1t:b-7xnj5a) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_common.h#L147)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 	int ret = rpma_read(ccd->conn,
> 			ccd->orig_mr, dst_offset,
> 			ccd->server_mr, src_offset,
> 			io_u->xfer_buflen,
> 			flags, (void *)(uintptr_t)io_u->index);
> ```
</details>

Is there any reason to left this in five instead of three lines?
___
*[engines/librpma_common.h, line 168 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTI7Vc7NFVMDO5Ok6p:-MRTI7Vc7NFVMDO5Ok6q:bl7e8x0) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_common.h#L168)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	int ret = rpma_write(ccd->conn,
> 			ccd->server_mr, dst_offset,
> 			ccd->orig_mr, src_offset,
> 			io_u->xfer_buflen, RPMA_F_COMPLETION_ON_ERROR,
> ```
</details>

.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/152)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_common.c, line 50 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTVGq5BZhuZiMgJ4WO:-MRTVGq62BQON8RfOsxf:b-6izhcd) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_common.c#L50)):*
> ```
> char *port_out)
> ```

Insert at least 2 or 3 tabs before `char *port_out)`, please. 
It does not look good with the same alignment as the inner code:

```
int librpma_common_td_port(const char *port_base_str, struct thread_data *td,
	char *port_out)
{
	unsigned long int port_ul = strtoul(port_base_str, NULL, 10);
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/152)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/152)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_common.h, line 147 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTHzSO2anoqLb2EC1s:-MRTs8XG903iel1OsOvt:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_common.h#L147)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 	int ret = rpma_read(ccd->conn,
> 			ccd->orig_mr, dst_offset,
> 			ccd->server_mr, src_offset,
> 			io_u->xfer_buflen,
> 			flags, (void *)(uintptr_t)io_u->index);
> ```
Is there any reason to left this in five instead of three lines?
</blockquote></details>

Done.
___
*[engines/librpma_common.h, line 168 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTI7Vc7NFVMDO5Ok6p:-MRTsR4WBWWz7nIh7SI7:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_common.h#L168)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 	int ret = rpma_write(ccd->conn,
> 			ccd->server_mr, dst_offset,
> 			ccd->orig_mr, src_offset,
> 			io_u->xfer_buflen, RPMA_F_COMPLETION_ON_ERROR,
> ```
.
</blockquote></details>

Done.
___
*[engines/librpma_common.c, line 50 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTVGq5BZhuZiMgJ4WO:-MRTtwhY5RnweODd-4fe:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_common.c#L50)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> char *port_out)
> ```

Insert at least 2 or 3 tabs before `char *port_out)`, please. 
It does not look good with the same alignment as the inner code:

```
int librpma_common_td_port(const char *port_base_str, struct thread_data *td,
	char *port_out)
{
	unsigned long int port_ul = strtoul(port_base_str, NULL, 10);
```
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/152)* status: 0 of 4 files reviewed, 12 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[engines/librpma_common.c, line 101 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTrBLh2UfVm-V3zKRa:-MRTrBLh2UfVm-V3zKRb:b-rhbly8) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_common.c#L101)):*
> ```
> filename
> ```

`filename` should be in the next line
___
*[engines/librpma_common.c, line 107 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTrNEl8G9s5bJ1E8qs:-MRTrNEl8G9s5bJ1E8qt:bt66g7b) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_common.c#L107)):*
> ```
> log_err("fio: %s is too small to handle so many threads (%zu < %zu)\n",
> ```

Please revert, the line has more than 80 chars - it was OK.
___
*[engines/librpma_common.c, line 219 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTrd0g2MSRRnEs2VCN:-MRTrd0g2MSRRnEs2VCO:b-37ko72) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_common.c#L219)):*
> ```
> log_err("rpma_conn_next_event returned an unexptected event: (%s != RPMA_CONN_ESTABLISHED)\n",
> ```

Please revert, the line has more than 80 chars - it was OK.
___
*[engines/librpma_common.c, line 285 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTriGr8ivA3PfpbWvz:-MRTriGr8ivA3PfpbWw-:bfkfs2n) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_common.c#L285)):*
> ```
> log_err("client_cleanup received an unexpected event (%s != RPMA_CONN_CLOSED)\n",
> ```

.
___
*[engines/librpma_common.c, line 397 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTruUJ72gcqyVICVzP:-MRTruUJ72gcqyVICVzQ:b-j1p4ks) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_common.c#L397)):*
> ```
> log_err("no matching io_u for received completion found (io_u_index=%u)\n",
> ```

.
___
*[engines/librpma_common.c, line 588 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTsITs5o2kkup0m7Zy:-MRTsITs5o2kkup0m7Zz:b-j1p4ks) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_common.c#L588)):*
> ```
> log_err("no matching io_u for received completion found (io_u_index=%u)\n",
> ```

.
___
*[engines/librpma_gpspm.c, line 154 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTtoht1MTGC-lTa4q3:-MRTtohu-MLTq4d4oFLw:bi8or0e) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_gpspm.c#L154)):*
> ```
> log_err("server's RQ size (iodepth) too small to handle the client's workspace requirements (%u < %u)\n",
> ```

.
___
*[engines/librpma_gpspm.c, line 244 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTtwjWDYunIKoq0pXN:-MRTtwjWDYunIKoq0pXO:b3kqx) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_gpspm.c#L244)):*
> ```C
> 	flush_req_size = gpspm_flush_request__get_packed_size(&Flush_req_last);
> 	if (flush_req_size > MAX_MSG_SIZE) {
> 		log_err("Packed flush request size is bigger than available send buffer space (%zu > %d\n",
> ```

.
___
*[engines/librpma_gpspm.c, line 295 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTv9JrBgX6P2GfRtOu:-MRTv9JrBgX6P2GfRtOv:b3kqx) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_gpspm.c#L295)):*
> ```C
> 	flush_req_size = gpspm_flush_request__get_packed_size(&flush_req);
> 	if (flush_req_size > MAX_MSG_SIZE) {
> 		log_err("Packed flush request size is bigger than available send buffer space (%"
> ```

.

**Review by ldorau — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/152)* status: all files reviewed, 11 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/152)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_common.c, line 101 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTrBLh2UfVm-V3zKRa:-MRU0FUP0e1F-XnqOsBY:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_common.c#L101)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> filename
> ```

`filename` should be in the next line
</blockquote></details>

Done.
___
*[engines/librpma_common.c, line 107 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTrNEl8G9s5bJ1E8qs:-MRU-yuXDOnJMtxwweEE:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_common.c#L107)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> log_err("fio: %s is too small to handle so many threads (%zu < %zu)\n",
> ```

Please revert, the line has more than 80 chars - it was OK.
</blockquote></details>

Done.
___
*[engines/librpma_common.c, line 219 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTrd0g2MSRRnEs2VCN:-MRU00Js90NOz6LcHsZy:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_common.c#L219)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> log_err("rpma_conn_next_event returned an unexptected event: (%s != RPMA_CONN_ESTABLISHED)\n",
> ```

Please revert, the line has more than 80 chars - it was OK.
</blockquote></details>

Done.
___
*[engines/librpma_common.c, line 285 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTriGr8ivA3PfpbWvz:-MRU02S-67JFXepjXDjq:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_common.c#L285)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> log_err("client_cleanup received an unexpected event (%s != RPMA_CONN_CLOSED)\n",
> ```

.
</blockquote></details>

Done.
___
*[engines/librpma_common.c, line 397 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTruUJ72gcqyVICVzP:-MRU04W_7DW7VqwKnlu_:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_common.c#L397)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> log_err("no matching io_u for received completion found (io_u_index=%u)\n",
> ```

.
</blockquote></details>

Done.
___
*[engines/librpma_common.c, line 588 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTsITs5o2kkup0m7Zy:-MRU08DSELqCO2OWgvqn:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_common.c#L588)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> log_err("no matching io_u for received completion found (io_u_index=%u)\n",
> ```

.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 154 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTtoht1MTGC-lTa4q3:-MRU0ARK7_8jiuVxxS-v:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_gpspm.c#L154)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> log_err("server's RQ size (iodepth) too small to handle the client's workspace requirements (%u < %u)\n",
> ```

.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 244 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTtwjWDYunIKoq0pXN:-MRU0ClV60sVB0nMHiqs:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_gpspm.c#L244)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 295 at r1](https://reviewable.io/reviews/pmem/fio/152#-MRTv9JrBgX6P2GfRtOu:-MRU0Ehg4Cepts8yU14S:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c257b44fb29606b082bf0d1aaace360bed9cdcd6/engines/librpma_gpspm.c#L295)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/152)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/152#-:-MRU1gk7DdmE8A7_TbHw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
