### PR TITLE
rpma: common: client_options

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/123)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/123#-:-MR4KtlcAr3ismef4W40:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/123)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/123#-MR4Kw815RNBydWZhRgo:-MR4Kw815RNBydWZhRgp:bktn7rl) (no related file):*
Shall we consider also unification of client and server options (e.g. bindname->hostname)

---

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/123#-:-MR4SmxX0XUGmvHcpXZJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/123)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/123#-MR4Kw815RNBydWZhRgo:-MR4Vjq813_iqM4aRoj2:bnhy24a) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we consider also unification of client and server options (e.g. bindname->hostname)
</blockquote></details>

Maybe at some point.

---

**Review by ldorau — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/123)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/123)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
