### PR TITLE
rpma: common: get_file_size

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/128)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/128#-:-MR4hN1y4ilWhhNvsGTY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/128)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_common.c, line 246 at r2](https://reviewable.io/reviews/pmem/fio/128#-MR5WgKY364-DGmYmDQa:-MR5WgKZ42Um8AetGdrD:b-mod23f) ([raw file](https://github.com/pmem/fio/blob/4766489cecc1d25d343b5d4540ffa024d6d32cf3/engines/librpma_common.c#L246)):*
> ```
>     return 0;
> ```

Please replace spaces with a tab.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/128)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_common.c, line 246 at r2](https://reviewable.io/reviews/pmem/fio/128#-MR5WgKY364-DGmYmDQa:-MR5XwZGByCcb-2qYV2j:b-896fix) ([raw file](https://github.com/pmem/fio/blob/4766489cecc1d25d343b5d4540ffa024d6d32cf3/engines/librpma_common.c#L246)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>     return 0;
> ```

Please replace spaces with a tab.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/128#-:-MR61G0CCixU1FxYPBj7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
