### PR TITLE
 rpma: client op scaffolding

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #8

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/7)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/7)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 35 at r1](https://reviewable.io/reviews/pmem/fio/7#-MJQg3m3A_SffBWqnhG9:-MJQg3m45_TBlLelWIKL:b-tp9djs) ([raw file](https://github.com/pmem/fio/blob/48b295f304a8ed4528d943ec9d13315805b64904/engines/librpma.c#L35)):*
> ```
> IP address where server is listening
> ```

"IP address the server is listening on"
___
*[engines/librpma.c, line 45 at r1](https://reviewable.io/reviews/pmem/fio/7#-MJQg977BygpFPOmuxL5:-MJQg977BygpFPOmuxL6:b-sg31co) ([raw file](https://github.com/pmem/fio/blob/48b295f304a8ed4528d943ec9d13315805b64904/engines/librpma.c#L45)):*
> ```
> port where server is listening
> ```

"port the server is listening on"
___
*[engines/librpma.c, line 46 at r1](https://reviewable.io/reviews/pmem/fio/7#-MJQgLgRA8MaUnIXLWhs:-MJQgLgRA8MaUnIXLWht:b-ivyixx) ([raw file](https://github.com/pmem/fio/blob/48b295f304a8ed4528d943ec9d13315805b64904/engines/librpma.c#L46)):*
> ```C
> 		.off1	= offsetof(struct client_options, port),
> 		.help	= "port where server is listening",
> 		.def    = "8080",
> ```

8080 is commonly used, maybe 8765?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/7)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 46 at r1](https://reviewable.io/reviews/pmem/fio/7#-MJQgLgRA8MaUnIXLWhs:-MJQvb_o1TK0yHO1Pfwh:bslufq0) ([raw file](https://github.com/pmem/fio/blob/48b295f304a8ed4528d943ec9d13315805b64904/engines/librpma.c#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

8080 is commonly used, maybe 8765?
</blockquote></details>

https://www.adminsub.net/tcp-udp-port-finder/8765 already used instead of 7204

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/7)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 46 at r1](https://reviewable.io/reviews/pmem/fio/7#-MJQgLgRA8MaUnIXLWhs:-MJQwHzABqJ_eapCVxS-:butnx89) ([raw file](https://github.com/pmem/fio/blob/48b295f304a8ed4528d943ec9d13315805b64904/engines/librpma.c#L46)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

https://www.adminsub.net/tcp-udp-port-finder/8765 already used instead of 7204
</blockquote></details>

Ooo, indeed :-)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/7)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 46 at r1](https://reviewable.io/reviews/pmem/fio/7#-MJQgLgRA8MaUnIXLWhs:-MJR2LvQ2NlDTOCoruh0:bb6l1gk) ([raw file](https://github.com/pmem/fio/blob/48b295f304a8ed4528d943ec9d13315805b64904/engines/librpma.c#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ooo, indeed :-)
</blockquote></details>

7204
___
*[engines/librpma.c, line 86 at r1](https://reviewable.io/reviews/pmem/fio/7#-MJR2_oxEOQEkbdKt-o5:-MJR2_oxEOQEkbdKt-o6:bzgn515) ([raw file](https://github.com/pmem/fio/blob/48b295f304a8ed4528d943ec9d13315805b64904/engines/librpma.c#L86)):*
> ```
> 	 * - posix_mem_align
> ```

Won't it be needed ?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/7)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 35 at r1](https://reviewable.io/reviews/pmem/fio/7#-MJQg3m3A_SffBWqnhG9:-MJR5ko1BDS0zipbaRvq:b-896fix) ([raw file](https://github.com/pmem/fio/blob/48b295f304a8ed4528d943ec9d13315805b64904/engines/librpma.c#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> IP address where server is listening
> ```

"IP address the server is listening on"
</blockquote></details>

Done.
___
*[engines/librpma.c, line 45 at r1](https://reviewable.io/reviews/pmem/fio/7#-MJQg977BygpFPOmuxL5:-MJR5n_Q6-fMBV1mlylP:b-896fix) ([raw file](https://github.com/pmem/fio/blob/48b295f304a8ed4528d943ec9d13315805b64904/engines/librpma.c#L45)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> port where server is listening
> ```

"port the server is listening on"
</blockquote></details>

Done.
___
*[engines/librpma.c, line 46 at r1](https://reviewable.io/reviews/pmem/fio/7#-MJQgLgRA8MaUnIXLWhs:-MJR5qYq987V19GNZu_s:b-896fix) ([raw file](https://github.com/pmem/fio/blob/48b295f304a8ed4528d943ec9d13315805b64904/engines/librpma.c#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

7204
</blockquote></details>

Done.
___
*[engines/librpma.c, line 86 at r1](https://reviewable.io/reviews/pmem/fio/7#-MJR2_oxEOQEkbdKt-o5:-MJR5ukc3KHL3ZRLUNRc:b-xudho2) ([raw file](https://github.com/pmem/fio/blob/48b295f304a8ed4528d943ec9d13315805b64904/engines/librpma.c#L86)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	 * - posix_mem_align
> ```

Won't it be needed ?
</blockquote></details>

Nope. The Fio will do this for us.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/7)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[engines/librpma.c, line 86 at r1](https://reviewable.io/reviews/pmem/fio/7#-MJR2_oxEOQEkbdKt-o5:-MJR7_VI0G6uColgzcTr:b-k1hkpz) ([raw file](https://github.com/pmem/fio/blob/48b295f304a8ed4528d943ec9d13315805b64904/engines/librpma.c#L86)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Nope. The Fio will do this for us.
</blockquote></details>

Great :-D

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/7#-:-MJR7d3o72ODz8LSEnc6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/7#-:-MJRGR7i-AUAFFyIzNAm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
