### PR TITLE
gpspm: add optional use rpma_conn_completion_wait function

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/251)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/251)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk)

___
*[fio.1, line 1918 at r1](https://reviewable.io/reviews/pmem/fio/251#-MVpRtQl72smnzaIY7g3:-MVpRtQl72smnzaIY7g4:b-313y0a) ([raw file](https://github.com/pmem/fio/blob/995549e746ced7ac08e4b65d07b5745cb2196e9a/fio.1#L1918)):*
> ```Roff
> Set to 1 only when Direct Write to PMem from the remote host is possible. Otherwise, set to 0.
> .TP
> .BI (librpma_gpspm_server)completion_wait \fR=\fPbool
> ```

**Fun fact**: It is also already implemented in the APM server because... there is nothing to do. `librpma_*_server`
___
*[fio.1, line 1919 at r1](https://reviewable.io/reviews/pmem/fio/251#-MVpSFRF-f6I1Do1LrPF:-MVpSFRF-f6I1Do1LrPG:b-bvwqfv) ([raw file](https://github.com/pmem/fio/blob/995549e746ced7ac08e4b65d07b5745cb2196e9a/fio.1#L1919)):*
> ```Roff
> .TP
> .BI (librpma_gpspm_server)completion_wait \fR=\fPbool
> Set to 1 if you want to reduce CPU usage. Default: 0.
> ```

Set to 1 to use rpma_conn_completion_wait() instead of polling completions.
___
*[HOWTO, line 2174 at r1](https://reviewable.io/reviews/pmem/fio/251#-MVpSx306xzVCLkC-5G7:-MVpSx306xzVCLkC-5G8:b3kqx) ([raw file](https://github.com/pmem/fio/blob/995549e746ced7ac08e4b65d07b5745cb2196e9a/HOWTO#L2174)):*
> ```
> 	Otherwise, set to 0.
> 
> .. option:: completion_wait=bool : [librpma_gpspm_server]
> ```

.
___
*[HOWTO, line 2176 at r1](https://reviewable.io/reviews/pmem/fio/251#-MVpSwPSB0-FQf4Ra1Y4:-MVpSwPSB0-FQf4Ra1Y5:b3kqx) ([raw file](https://github.com/pmem/fio/blob/995549e746ced7ac08e4b65d07b5745cb2196e9a/HOWTO#L2176)):*
> ```
> .. option:: completion_wait=bool : [librpma_gpspm_server]
> 
> 	Set to 1 if you want to reduce CPU usage. Default: 0.
> ```

.
___
*[engines/librpma_fio.h, line 44 at r1](https://reviewable.io/reviews/pmem/fio/251#-MVpT0Pa6OmgWwkV0XeN:-MVpT0Pa6OmgWwkV0XeO:b3kqx) ([raw file](https://github.com/pmem/fio/blob/995549e746ced7ac08e4b65d07b5745cb2196e9a/engines/librpma_fio.h#L44)):*
> ```objc
> 	/* Direct Write to PMem is possible */
> 	unsigned int direct_write_to_pmem;
> 	/* use the rpma_conn_completion_wait() function */
> ```

.
___
*[engines/librpma_fio.c, line 54 at r1](https://reviewable.io/reviews/pmem/fio/251#-MVpT3-F6lX3NbnOxTPf:-MVpT3-F6lX3NbnOxTPg:b3kqx) ([raw file](https://github.com/pmem/fio/blob/995549e746ced7ac08e4b65d07b5745cb2196e9a/engines/librpma_fio.c#L54)):*
> ```C
> 	{
> 		.name	= "completion_wait",
> 		.lname	= "Use the rpma_conn_completion_wait() function",
> ```

.
___
*[engines/librpma_gpspm.c, line 706 at r1](https://reviewable.io/reviews/pmem/fio/251#-MVpTT5rAOGEP0NbUFFS:-MVpTT5rAOGEP0NbUFFT:bb7bpjw) ([raw file](https://github.com/pmem/fio/blob/995549e746ced7ac08e4b65d07b5745cb2196e9a/engines/librpma_gpspm.c#L706)):*
> ```C
> 				return 0;
> 			} else if (ret != 0) {
> 				librpma_td_verror(td, ret, "rpma_conn_completion_wait");
> ```

_get

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/251)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @janekmi)

___
*[fio.1, line 1918 at r1](https://reviewable.io/reviews/pmem/fio/251#-MVpRtQl72smnzaIY7g3:-MVpWLWm1Egc01bLxL6R:b-896fix) ([raw file](https://github.com/pmem/fio/blob/995549e746ced7ac08e4b65d07b5745cb2196e9a/fio.1#L1918)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

**Fun fact**: It is also already implemented in the APM server because... there is nothing to do. `librpma_*_server`
</blockquote></details>

Done.
___
*[fio.1, line 1919 at r1](https://reviewable.io/reviews/pmem/fio/251#-MVpSFRF-f6I1Do1LrPF:-MVpWXGEDswejdxEUSG8:b-896fix) ([raw file](https://github.com/pmem/fio/blob/995549e746ced7ac08e4b65d07b5745cb2196e9a/fio.1#L1919)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Set to 1 to use rpma_conn_completion_wait() instead of polling completions.
</blockquote></details>

Done.
___
*[HOWTO, line 2174 at r1](https://reviewable.io/reviews/pmem/fio/251#-MVpSx306xzVCLkC-5G7:-MVpWY9O5FN2nKShZx0c:b-896fix) ([raw file](https://github.com/pmem/fio/blob/995549e746ced7ac08e4b65d07b5745cb2196e9a/HOWTO#L2174)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[HOWTO, line 2176 at r1](https://reviewable.io/reviews/pmem/fio/251#-MVpSwPSB0-FQf4Ra1Y4:-MVpWYn910NdjplacC88:b-896fix) ([raw file](https://github.com/pmem/fio/blob/995549e746ced7ac08e4b65d07b5745cb2196e9a/HOWTO#L2176)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[engines/librpma_fio.h, line 44 at r1](https://reviewable.io/reviews/pmem/fio/251#-MVpT0Pa6OmgWwkV0XeN:-MVpWl0UEDhw88YXuowH:b-896fix) ([raw file](https://github.com/pmem/fio/blob/995549e746ced7ac08e4b65d07b5745cb2196e9a/engines/librpma_fio.h#L44)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 54 at r1](https://reviewable.io/reviews/pmem/fio/251#-MVpT3-F6lX3NbnOxTPf:-MVpWscZ7SpQs_Im0aJO:b-896fix) ([raw file](https://github.com/pmem/fio/blob/995549e746ced7ac08e4b65d07b5745cb2196e9a/engines/librpma_fio.c#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 706 at r1](https://reviewable.io/reviews/pmem/fio/251#-MVpTT5rAOGEP0NbUFFS:-MVpWy7B169SJj8LEKxL:b-896fix) ([raw file](https://github.com/pmem/fio/blob/995549e746ced7ac08e4b65d07b5745cb2196e9a/engines/librpma_gpspm.c#L706)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

_get
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/251#-:-MVpYB993nhND0az1D5O:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/251#-:-MVpnm3t7exTizl6DQW8:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
Please see new comments after discussing with @grom72.

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/251#-:-MVq7nz02mkJL2vwVIQ2:bu2rdp4)* status: all files reviewed, 13 unresolved discussions (waiting on @osalyk)

___
*[fio.1, line 1918 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq83B_BVR23XGHT0pH:-MVq83B_BVR23XGHT0pI:bmp0aku) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/fio.1#L1918)):*
> ```Roff
> Set to 1 only when Direct Write to PMem from the remote host is possible. Otherwise, set to 0.
> .TP
> .BI (librpma_*_server)completion_wait \fR=\fPbool
> ```

`busy_wait_polling` +  please negate the logic.
___
*[fio.1, line 1919 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8JJk5N5iO0B2GrdG:-MVq8JJk5N5iO0B2GrdH:b-ptvbnc) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/fio.1#L1919)):*
> ```Roff
> .TP
> .BI (librpma_*_server)completion_wait \fR=\fPbool
> Set to 1 to use rpma_conn_completion_wait() instead of polling completions.
> ```

Set to 0 to wait for completion instead of busy-wait polling completion.
___
*[fio.1, line 1920 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8K5054m0glFJLuOR:-MVq8K5054m0glFJLuOS:b3kr0) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/fio.1#L1920)):*
> ```Roff
> .BI (librpma_*_server)completion_wait \fR=\fPbool
> Set to 1 to use rpma_conn_completion_wait() instead of polling completions.
> Default: 0.
> ```

1
___
*[HOWTO, line 2174 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8PD30tIaZyzTNA-5:-MVq8PD30tIaZyzTNA-6:b3kqx) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/HOWTO#L2174)):*
> ```
> 	Otherwise, set to 0.
> 
> .. option:: completion_wait=bool : [librpma_*_server]
> ```

.
___
*[HOWTO, line 2176 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8PwW3EtttxLEFd3j:-MVq8PwW3EtttxLEFd3k:b3kqx) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/HOWTO#L2176)):*
> ```
> .. option:: completion_wait=bool : [librpma_*_server]
> 
> 	Set to 1 to use rpma_conn_completion_wait() instead of polling completions.
> ```

.
___
*[HOWTO, line 2177 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8QMn0nmr4B7mtLv6:-MVq8QMn0nmr4B7mtLv7:b3kqx) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/HOWTO#L2177)):*
> ```
> 
> 	Set to 1 to use rpma_conn_completion_wait() instead of polling completions.
> 	Default: 0.
> ```

.
___
*[engines/librpma_fio.h, line 44 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8SLnDIvMsFwKw4Oi:-MVq8SLnDIvMsFwKw4Oj:b3kqx) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/engines/librpma_fio.h#L44)):*
> ```objc
> 	/* Direct Write to PMem is possible */
> 	unsigned int direct_write_to_pmem;
> 	/* use rpma_conn_completion_wait() instead of polling completions */
> ```

.
___
*[engines/librpma_fio.h, line 45 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8StL0gUX9GnWwi5d:-MVq8StL0gUX9GnWwi5e:b3kqx) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/engines/librpma_fio.h#L45)):*
> ```objc
> 	unsigned int direct_write_to_pmem;
> 	/* use rpma_conn_completion_wait() instead of polling completions */
> 	unsigned int completion_wait;
> ```

.
___
*[engines/librpma_fio.c, line 53 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8U8o5FKvbtyNxP_p:-MVq8U8o5FKvbtyNxP_q:b3kqx) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/engines/librpma_fio.c#L53)):*
> ```C
> 	},
> 	{
> 		.name	= "completion_wait",
> ```

.
___
*[engines/librpma_fio.c, line 54 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8Uw49NFIcoRQVZXo:-MVq8Uw49NFIcoRQVZXp:b3kqx) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/engines/librpma_fio.c#L54)):*
> ```C
> 	{
> 		.name	= "completion_wait",
> 		.lname	= "use rpma_conn_completion_wait() instead of polling completions",
> ```

.
___
*[engines/librpma_fio.c, line 58 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8Vxz-azK3_6VTIYi:-MVq8Vxz-azK3_6VTIYj:b-7qqe9u) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/engines/librpma_fio.c#L58)):*
> ```C
> 		.off1	= offsetof(struct librpma_fio_options_values,
> 					completion_wait),
> 		.help	= "Set to true if you want to reduce CPU usage",
> ```

false
___
*[engines/librpma_fio.c, line 59 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8X2_CrTWXVZJoAWe:-MVq8X2_CrTWXVZJoAWf:b3kr0) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/engines/librpma_fio.c#L59)):*
> ```C
> 					completion_wait),
> 		.help	= "Set to true if you want to reduce CPU usage",
> 		.def	= "0",
> ```

1
___
*[engines/librpma_gpspm.c, line 691 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8YYDCmrsYAhHyfjo:-MVq8YYDCmrsYAhHyfjp:b-t7fuz8) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/engines/librpma_gpspm.c#L691)):*
> ```C
> 	ret = rpma_conn_completion_get(csd->conn, cmpl);
> 	if (ret == RPMA_E_NO_COMPLETION) {
> 		if (o->completion_wait == 1) {
> ```

Please negate the logic.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/251)* status: 0 of 6 files reviewed, 13 unresolved discussions (waiting on @janekmi)

___
*[fio.1, line 1918 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq83B_BVR23XGHT0pH:-MVq9KEj23UDVNPYmVt5:b-896fix) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/fio.1#L1918)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`busy_wait_polling` +  please negate the logic.
</blockquote></details>

Done.
___
*[fio.1, line 1919 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8JJk5N5iO0B2GrdG:-MVq9Kd9BrAKvwpX1jGI:b-896fix) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/fio.1#L1919)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Set to 0 to wait for completion instead of busy-wait polling completion.
</blockquote></details>

Done.
___
*[fio.1, line 1920 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8K5054m0glFJLuOR:-MVq9N7r1aurtwGVYL7G:b-896fix) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/fio.1#L1920)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

1
</blockquote></details>

Done.
___
*[HOWTO, line 2174 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8PD30tIaZyzTNA-5:-MVq9kXB5L7BQKmV-5-u:b-896fix) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/HOWTO#L2174)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[HOWTO, line 2176 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8PwW3EtttxLEFd3j:-MVq9o0m-I3klahTJUTz:b-896fix) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/HOWTO#L2176)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[HOWTO, line 2177 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8QMn0nmr4B7mtLv6:-MVq9oaeDVpKTTb_CVz0:b-896fix) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/HOWTO#L2177)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[engines/librpma_fio.h, line 44 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8SLnDIvMsFwKw4Oi:-MVqAQLvBjULtwlOCYaQ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/engines/librpma_fio.h#L44)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[engines/librpma_fio.h, line 45 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8StL0gUX9GnWwi5d:-MVqAR8MD0sAR0Ezhczp:b-896fix) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/engines/librpma_fio.h#L45)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 53 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8U8o5FKvbtyNxP_p:-MVqAXwn3G3RXceCFxc-:b-896fix) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/engines/librpma_fio.c#L53)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 54 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8Uw49NFIcoRQVZXo:-MVqAbkN4LClh8K_XTGS:b-896fix) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/engines/librpma_fio.c#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 58 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8Vxz-azK3_6VTIYi:-MVqAgcuCMZbz2S3xY_v:b-896fix) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/engines/librpma_fio.c#L58)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

false
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 59 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8X2_CrTWXVZJoAWe:-MVqAhOC6mKXf8bDPyew:b-896fix) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/engines/librpma_fio.c#L59)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

1
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 691 at r2](https://reviewable.io/reviews/pmem/fio/251#-MVq8YYDCmrsYAhHyfjo:-MVqB5Yi6rJgpYcyRjq5:b-896fix) ([raw file](https://github.com/pmem/fio/blob/39a97913b32a084cc2a3a5246fb8faf203f476ad/engines/librpma_gpspm.c#L691)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please negate the logic.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/251#-:-MVqCthbD8hc79z4NcQ7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
