### PR TITLE
test: test the Fuzzing CI build

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/274)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/274)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by ldorau** [comment]
@blazej-smorawski all CI builds pass here

**Comment by blazej-smorawski** [comment]
@ldorau Yea, I see. Just tried on my branch and it's still failing. Even though I just added some comment https://github.com/pmem/fio/pull/267/files

**Comment by blazej-smorawski** [comment]
Adding comment in engines/libpmem.c causes an error. Now I'll try with the same file as you.

**Comment by blazej-smorawski** [comment]
Still failing. I've got no idea what's going on

**Pull request closed without merging**
