### PR TITLE
rpma: add RPMA_CONN_REJECTED event handling

### PR DESCRIPTION
**Pull request by osalyk**
- [x] https://github.com/pmem/rpma/pull/802

This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/198)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma_fio.c, line 225 at r1](https://reviewable.io/reviews/pmem/fio/198#-MSDVqbAEtELYZZDR9db:-MSDVqbAEtELYZZDR9dc:baiw34q) ([raw file](https://github.com/pmem/fio/blob/4a58156021368f11463905afed7c6ce3556e88c0/engines/librpma_fio.c#L225)):*
> ```
> <=
> ```
<

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_fio.c, line 261 at r1](https://reviewable.io/reviews/pmem/fio/198#-MSDVnvGAJHb90ntHUnw:-MSDVnvGAJHb90ntHUnx:b-ogfhe6) ([raw file](https://github.com/pmem/fio/blob/4a58156021368f11463905afed7c6ce3556e88c0/engines/librpma_fio.c#L261)):*
> ```C
> 
> 		log_err("Wait for the server, try:%d\n",retry);
> 		sleep(5);
> ```

Please give it also a define.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_fio.c, line 225 at r1](https://reviewable.io/reviews/pmem/fio/198#-MSDh1t90EW6M7f1ZTZ4:-MSDh1t90EW6M7f1ZTZ5:bdlop79) ([raw file](https://github.com/pmem/fio/blob/4a58156021368f11463905afed7c6ce3556e88c0/engines/librpma_fio.c#L225)):*
> ```
> for (int retry = 0; retry <= MAX_RETRY; retry++)
> ```
the loop should start after 
```
		if (librpma_fio_td_port(o->port, td, port_td))
			goto err_peer_delete;

```
___
*[engines/librpma_fio.c, line 259 at r1](https://reviewable.io/reviews/pmem/fio/198#-MSDhKuZ3K9phG4dAFTy:-MSDhKuZ3K9phG4dAFTz:bpbcsig) ([raw file](https://github.com/pmem/fio/blob/4a58156021368f11463905afed7c6ce3556e88c0/engines/librpma_fio.c#L259)):*
> ```C
> 		} else if (event == RPMA_CONN_ESTABLISHED)
> 			break;
> ```

```
if(rpma_conn_disconnect(ccd->conn)) {
        (void)rpma_conn_delete(&ccd->conn);
        goto err_peer_delete;
 } else {
        if(rpma_conn_delete(&ccd->conn))
                goto err_peer_delete;
}
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_fio.c, line 225 at r1](https://reviewable.io/reviews/pmem/fio/198#-MSDVqbAEtELYZZDR9db:-MSNAugK4TMqY0QAL0TD:b-896fix) ([raw file](https://github.com/pmem/fio/blob/4a58156021368f11463905afed7c6ce3556e88c0/engines/librpma_fio.c#L225)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> <=
> ```
<
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 225 at r1](https://reviewable.io/reviews/pmem/fio/198#-MSDh1t90EW6M7f1ZTZ4:-MSNAxgN2iWomsqkSALn:b-896fix) ([raw file](https://github.com/pmem/fio/blob/4a58156021368f11463905afed7c6ce3556e88c0/engines/librpma_fio.c#L225)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> for (int retry = 0; retry <= MAX_RETRY; retry++)
> ```
the loop should start after 
```
		if (librpma_fio_td_port(o->port, td, port_td))
			goto err_peer_delete;

```
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 259 at r1](https://reviewable.io/reviews/pmem/fio/198#-MSDhKuZ3K9phG4dAFTy:-MSNAzkE7OJWDuau2Tpv:b-896fix) ([raw file](https://github.com/pmem/fio/blob/4a58156021368f11463905afed7c6ce3556e88c0/engines/librpma_fio.c#L259)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
if(rpma_conn_disconnect(ccd->conn)) {
        (void)rpma_conn_delete(&ccd->conn);
        goto err_peer_delete;
 } else {
        if(rpma_conn_delete(&ccd->conn))
                goto err_peer_delete;
}
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 261 at r1](https://reviewable.io/reviews/pmem/fio/198#-MSDVnvGAJHb90ntHUnw:-MSNBzJUCkVtTkJW_ovc:b-896fix) ([raw file](https://github.com/pmem/fio/blob/4a58156021368f11463905afed7c6ce3556e88c0/engines/librpma_fio.c#L261)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please give it also a define.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma_fio.h, line 29 at r2](https://reviewable.io/reviews/pmem/fio/198#-MSRHdhSDCNbJxD1X7K8:-MSRHdhSDCNbJxD1X7K9:bcvi422) ([raw file](https://github.com/pmem/fio/blob/48fa7aec00c940666cf005aaf70b9753da613b33/engines/librpma_fio.h#L29)):*
> ```
> MAX_RETRY
> ```
LIBRPMA_FIO_RETRY_MAX_NO
___
*[engines/librpma_fio.h, line 32 at r2](https://reviewable.io/reviews/pmem/fio/198#-MSRHHnr1drv2wrHh2y4:-MSRHHnsE1ZxtBkWp60x:bcpa9y9) ([raw file](https://github.com/pmem/fio/blob/48fa7aec00c940666cf005aaf70b9753da613b33/engines/librpma_fio.h#L32)):*
> ```
> #define retry(retry) \
> 	log_err("Wait for the server, try:%d\n", retry), sleep(5);
> ```
```
#define LIBRPMA_FIO_RETRY_DELAY_S 5
```
```#define retry(retry)``` ...  move to librpma_fio.c or do we need this at all?
I guess @janekmi  wants only 5 seconds to be ```#defined```
___
*[engines/librpma_fio.c, line 255 at r2](https://reviewable.io/reviews/pmem/fio/198#-MSRGu_3BbiByHIcelxr:-MSRGu_4BJQgzay18KgO:baq8jaa) ([raw file](https://github.com/pmem/fio/blob/48fa7aec00c940666cf005aaf70b9753da613b33/engines/librpma_fio.c#L255)):*
<details><summary><i alt="summary">Quoted 19 lines of code…</i></summary>

> ```
> 		} else if ((event != RPMA_CONN_ESTABLISHED &&
> 				event != RPMA_CONN_REJECTED) ||
> 				retry == MAX_RETRY - 1) {
> 			log_err(
> 				"rpma_conn_next_event returned an unexptected event: (%s != RPMA_CONN_ESTABLISHED)\n",
> 				rpma_utils_conn_event_2str(event));
> 			goto err_conn_delete;
> 		} else if (event == RPMA_CONN_ESTABLISHED)
> 			break;
> 		if (rpma_conn_disconnect(ccd->conn)) {
> 			(void)rpma_conn_delete(&ccd->conn);
> 			goto err_peer_delete;
> 		} else {
> 			if (rpma_conn_delete(&ccd->conn))
> 				goto err_peer_delete;
> 		}
> 		/* Wait for the server */
> 		retry(retry);
> 	}
> ```
</details>

else if (event == RPMA_CONN_ESTABLISHED)
break;
else if (event ==  RPMA_CONN_REJECTED) {
		if (rpma_conn_disconnect(ccd->conn)) {
			(void)rpma_conn_delete(&ccd->conn);
			goto err_peer_delete;
		} else {
			if (rpma_conn_delete(&ccd->conn))
				goto err_peer_delete;
		}
if(retry < MAX_RETRY - 1) {
/* Wait for the server */
retry(retry);
} else {
			log_err(
				"rpma_conn_next_event returned an unexptected event: (%s)\n",
				rpma_utils_conn_event_2str(event));
			goto err_conn_delete;
}
}
/*and after the loop:*/
if(ccd->conn==NULL) {
log_err("Connection couldn't be established");
goto err_peer_delete;
}
```
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/198#-MSRp7R_0C3_lU-3i3uq:-MSRp7R_0C3_lU-3i3ur:b-oiex50) (no related file):*
The `LIBRPMA_VERSION` in https://github.com/pmem/fio/blob/rpma/ci/actions-install-librpma.sh#L4 will have to be updated.

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[engines/librpma_fio.h, line 29 at r2](https://reviewable.io/reviews/pmem/fio/198#-MSRHdhSDCNbJxD1X7K8:-MSS0ws98npHyA_Ymbfi:b-896fix) ([raw file](https://github.com/pmem/fio/blob/48fa7aec00c940666cf005aaf70b9753da613b33/engines/librpma_fio.h#L29)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> MAX_RETRY
> ```
LIBRPMA_FIO_RETRY_MAX_NO
</blockquote></details>

Done.
___
*[engines/librpma_fio.h, line 32 at r2](https://reviewable.io/reviews/pmem/fio/198#-MSRHHnr1drv2wrHh2y4:-MSS13LN8pD3Hwpcbnl_:b-896fix) ([raw file](https://github.com/pmem/fio/blob/48fa7aec00c940666cf005aaf70b9753da613b33/engines/librpma_fio.h#L32)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> #define retry(retry) \
> 	log_err("Wait for the server, try:%d\n", retry), sleep(5);
> ```
```
#define LIBRPMA_FIO_RETRY_DELAY_S 5
```
```#define retry(retry)``` ...  move to librpma_fio.c or do we need this at all?
I guess @janekmi  wants only 5 seconds to be ```#defined```
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 255 at r2](https://reviewable.io/reviews/pmem/fio/198#-MSRGu_3BbiByHIcelxr:-MSS14_ZEoe-5phYF2_7:b-896fix) ([raw file](https://github.com/pmem/fio/blob/48fa7aec00c940666cf005aaf70b9753da613b33/engines/librpma_fio.c#L255)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 		} else if ((event != RPMA_CONN_ESTABLISHED &&
> 				event != RPMA_CONN_REJECTED) ||
> 				retry == MAX_RETRY - 1) {
> 			log_err(
> 				"rpma_conn_next_event returned an unexptected event: (%s != RPMA_CONN_ESTABLISHED)\n",
> 				rpma_utils_conn_event_2str(event));
> 			goto err_conn_delete;
> 		} else if (event == RPMA_CONN_ESTABLISHED)
> 			break;
> 		if (rpma_conn_disconnect(ccd->conn)) {
> 			(void)rpma_conn_delete(&ccd->conn);
> 			goto err_peer_delete;
> 		} else {
> 			if (rpma_conn_delete(&ccd->conn))
> 				goto err_peer_delete;
> 		}
> 		/* Wait for the server */
> 		retry(retry);
> 	}
> ```
else if (event == RPMA_CONN_ESTABLISHED)
break;
else if (event ==  RPMA_CONN_REJECTED) {
		if (rpma_conn_disconnect(ccd->conn)) {
			(void)rpma_conn_delete(&ccd->conn);
			goto err_peer_delete;
		} else {
			if (rpma_conn_delete(&ccd->conn))
				goto err_peer_delete;
		}
if(retry < MAX_RETRY - 1) {
/* Wait for the server */
retry(retry);
} else {
			log_err(
				"rpma_conn_next_event returned an unexptected event: (%s)\n",
				rpma_utils_conn_event_2str(event));
			goto err_conn_delete;
}
}
/*and after the loop:*/
if(ccd->conn==NULL) {
log_err("Connection couldn't be established");
goto err_peer_delete;
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[engines/librpma_fio.c, line 272 at r3](https://reviewable.io/reviews/pmem/fio/198#-MSS7zRq7VRp1clcpBDz:-MSS7zRrCfYUxCLpQtLv:b-h3tb6g) ([raw file](https://github.com/pmem/fio/blob/7086a2b183993c4f06384b02e20c9d22c0203013/engines/librpma_fio.c#L272)):*
> ```
> break;
> ```
```
conn_drop_and_delete(&ccd->conn);
break;
```

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/198#-MSS8ELI0RA4otIumdIB:-MSS8ELI0RA4otIumdIC:b-o4rn6q) (no related file):*
Please update the implementation according to the solution developed for the RPMA example.

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/198#-MSRp7R_0C3_lU-3i3uq:-MSSEUYxEelDDiExOFjq:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The `LIBRPMA_VERSION` in https://github.com/pmem/fio/blob/rpma/ci/actions-install-librpma.sh#L4 will have to be updated.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/fio/198#-MSS8ELI0RA4otIumdIB:-MSSC86A7M_6yVtZgL6n:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please update the implementation according to the solution developed for the RPMA example.
</blockquote></details>

Done.

---
___
*[engines/librpma_fio.c, line 272 at r3](https://reviewable.io/reviews/pmem/fio/198#-MSS7zRq7VRp1clcpBDz:-MSSC6J70el10vEIwMlL:b-896fix) ([raw file](https://github.com/pmem/fio/blob/7086a2b183993c4f06384b02e20c9d22c0203013/engines/librpma_fio.c#L272)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> break;
> ```
```
conn_drop_and_delete(&ccd->conn);
break;
```
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[ci/actions-install-librpma.sh, line 4 at r4](https://reviewable.io/reviews/pmem/fio/198#-MSSFtWI2ZDc2vXWDtuy:-MSSFtWI2ZDc2vXWDtuz:bg9eb5y) ([raw file](https://github.com/pmem/fio/blob/e3179be012f8633ff7e285e9744730a8ce49f1b5/ci/actions-install-librpma.sh#L4)):*
> ```Shell
> 
> # 01.02.2021 Merge pull request #802 from osalyk/rejected
> LIBRPMA_VERSION=f5ccce39674f6837d788da24b5646329affb8757
> ```

We are getting closer and closer to the next RPMA release. :-)
___
*[engines/librpma_fio.h, line 30 at r4](https://reviewable.io/reviews/pmem/fio/198#-MSSGoeB45KC-psqTDi7:-MSSGoeB45KC-psqTDi8:b78a14e) ([raw file](https://github.com/pmem/fio/blob/e3179be012f8633ff7e285e9744730a8ce49f1b5/engines/librpma_fio.h#L30)):*
> ```objc
> 
> #define LIBRPMA_FIO_RETRY_MAX_NO	10
> #define LIBRPMA_FIO_RETRY_DELAY_S	5
> ```

Why on the public header?
___
*[engines/librpma_fio.h, line 33 at r4](https://reviewable.io/reviews/pmem/fio/198#-MSSGKD14E8_756JPVey:-MSSGKD14E8_756JPVez:b1m3b75) ([raw file](https://github.com/pmem/fio/blob/e3179be012f8633ff7e285e9744730a8ce49f1b5/engines/librpma_fio.h#L33)):*
> ```objc
> 
> static inline void
> conn_drop_and_delete(struct rpma_conn **conn_ptr)
> ```

If this is only used in the librpma_fio.c there is no need to have it here in the public header.
___
*[engines/librpma_fio.c, line 262 at r4](https://reviewable.io/reviews/pmem/fio/198#-MSSGu1rE1jZ7GbCAI4W:-MSSGu1rE1jZ7GbCAI4X:b-oc43lk) ([raw file](https://github.com/pmem/fio/blob/e3179be012f8633ff7e285e9744730a8ce49f1b5/engines/librpma_fio.c#L262)):*
> ```C
> 			conn_drop_and_delete(&ccd->conn);
> 			if (retry < LIBRPMA_FIO_RETRY_MAX_NO - 1) {
> 				log_err("Retrying...\n");
> ```

Since we are logging it from all threads, I think we need the thread number here.
___
*[engines/librpma_fio.c, line 265 at r4](https://reviewable.io/reviews/pmem/fio/198#-MSSH4WE6gsJ8GtA6C_R:-MSSH4WE6gsJ8GtA6C_S:b3kqx) ([raw file](https://github.com/pmem/fio/blob/e3179be012f8633ff7e285e9744730a8ce49f1b5/engines/librpma_fio.c#L265)):*
> ```C
> 				sleep(LIBRPMA_FIO_RETRY_DELAY_S);
> 			} else {
> 				log_err("The retry number exceeded. Closing.\n");
> ```

.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_fio.h, line 30 at r4](https://reviewable.io/reviews/pmem/fio/198#-MSSGoeB45KC-psqTDi7:-MSSHb157bKLfgLQQse4:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e3179be012f8633ff7e285e9744730a8ce49f1b5/engines/librpma_fio.h#L30)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why on the public header?
</blockquote></details>

Done.
___
*[engines/librpma_fio.h, line 33 at r4](https://reviewable.io/reviews/pmem/fio/198#-MSSGKD14E8_756JPVey:-MSSHbaw5VH5mcEccVUx:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e3179be012f8633ff7e285e9744730a8ce49f1b5/engines/librpma_fio.h#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If this is only used in the librpma_fio.c there is no need to have it here in the public header.
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 262 at r4](https://reviewable.io/reviews/pmem/fio/198#-MSSGu1rE1jZ7GbCAI4W:-MSSIw4VA5geZtxojgoK:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e3179be012f8633ff7e285e9744730a8ce49f1b5/engines/librpma_fio.c#L262)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since we are logging it from all threads, I think we need the thread number here.
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 265 at r4](https://reviewable.io/reviews/pmem/fio/198#-MSSH4WE6gsJ8GtA6C_R:-MSSIwnwE2xvfGhtlVZb:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e3179be012f8633ff7e285e9744730a8ce49f1b5/engines/librpma_fio.c#L265)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[engines/librpma_fio.c, line 245 at r4](https://reviewable.io/reviews/pmem/fio/198#-MSSHOv-AhePqas_Xh3u:-MSSHOv0Af4AajB7wsRB:bxw9w7) ([raw file](https://github.com/pmem/fio/blob/e3179be012f8633ff7e285e9744730a8ce49f1b5/engines/librpma_fio.c#L245)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 		/*
> 		 * connect the connection request
> 		 * and obtain the connection object
> 		 */
> ```
</details>


Full sentence please.
___
*[engines/librpma_fio.c, line 249 at r4](https://reviewable.io/reviews/pmem/fio/198#-MSSImOw4xmrHZc7ngTV:-MSSImOw4xmrHZc7ngTW:b-6upqy1) ([raw file](https://github.com/pmem/fio/blob/e3179be012f8633ff7e285e9744730a8ce49f1b5/engines/librpma_fio.c#L249)):*
> ```
> 			(void) rpma_conn_req_delete(&req);
> 			break;
> ```

Why not `goto err_req_delete`?
___
*[engines/librpma_fio.c, line 256 at r4](https://reviewable.io/reviews/pmem/fio/198#-MSSIu894nkCai8kd-Mk:-MSSIu894nkCai8kd-Ml:bc4cfgu) ([raw file](https://github.com/pmem/fio/blob/e3179be012f8633ff7e285e9744730a8ce49f1b5/engines/librpma_fio.c#L256)):*
> ```
> 			conn_drop_and_delete(&ccd->conn);
> 			break;
> ```

Why not `goto err_conn_delete`? And `conn_drop_and_delete()` can be removed at all then.
We are mixing two styles of error handlin now ...

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[engines/librpma_fio.c, line 245 at r4](https://reviewable.io/reviews/pmem/fio/198#-MSSHOv-AhePqas_Xh3u:-MSSKLF64pIrj7XL617v:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e3179be012f8633ff7e285e9744730a8ce49f1b5/engines/librpma_fio.c#L245)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 		/*
> 		 * connect the connection request
> 		 * and obtain the connection object
> 		 */
> ```

Full sentence please.
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 249 at r4](https://reviewable.io/reviews/pmem/fio/198#-MSSImOw4xmrHZc7ngTV:-MSSKiWJ5lgvk-JGfwml:b-rkipqg) ([raw file](https://github.com/pmem/fio/blob/e3179be012f8633ff7e285e9744730a8ce49f1b5/engines/librpma_fio.c#L249)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 			(void) rpma_conn_req_delete(&req);
> 			break;
> ```

Why not `goto err_req_delete`?
</blockquote></details>

"goto from inside the loop in no critical error situation is not good solution see my proposal in pmem/fio/198"
Commentary from https://github.com/pmem/fio/pull/198

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198#-:-MSSMoV78ZuSJNK-WL84:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

**Review by ldorau — APPROVED** [review]
:goat: 

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198#-:-MSSMurDEm-PuPtj43fw:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_fio.c, line 249 at r4](https://reviewable.io/reviews/pmem/fio/198#-MSSImOw4xmrHZc7ngTV:-MSSMlHDCNRDoOo__tU6:bhlog2w) ([raw file](https://github.com/pmem/fio/blob/e3179be012f8633ff7e285e9744730a8ce49f1b5/engines/librpma_fio.c#L249)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

"goto from inside the loop in no critical error situation is not good solution see my proposal in pmem/fio/198"
Commentary from https://github.com/pmem/fio/pull/198
</blockquote></details>

OK. We will discuss it later.
___
*[engines/librpma_fio.c, line 256 at r4](https://reviewable.io/reviews/pmem/fio/198#-MSSIu894nkCai8kd-Mk:-MSSMsXH1LeuRghwHtiX:bhlog2w) ([raw file](https://github.com/pmem/fio/blob/e3179be012f8633ff7e285e9744730a8ce49f1b5/engines/librpma_fio.c#L256)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 			conn_drop_and_delete(&ccd->conn);
> 			break;
> ```

Why not `goto err_conn_delete`? And `conn_drop_and_delete()` can be removed at all then.
We are mixing two styles of error handlin now ...
</blockquote></details>

OK. We will discuss it later.

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/198)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Pull request merged**
