### PR TITLE
rpma: implement client_cleanup

### PR DESCRIPTION
**Pull request by osalyk**
- [x] #58

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/61)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/61)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_gpspm.c, line 343 at r1](https://reviewable.io/reviews/pmem/fio/61#-MLwom-Q4rmyb-vcPV1W:-MLwom-Q4rmyb-vcPV1X:bvr7cw) ([raw file](https://github.com/pmem/fio/blob/e6a8e4717493bcb98bd32d7280d017111c4309ba/engines/librpma_gpspm.c#L343)):*
> ```C
> 	if ((ret = rpma_mr_dereg(&cd->orig_mr)))
> 		rpma_td_verror(td, ret, "rpma_mr_dereg");
> ```

comment missing
___
*[engines/librpma_gpspm.c, line 347 at r1](https://reviewable.io/reviews/pmem/fio/61#-MLwonaR2gPkKSqQ8Ze7:-MLwonaR2gPkKSqQ8Ze8:bmdw7im) ([raw file](https://github.com/pmem/fio/blob/e6a8e4717493bcb98bd32d7280d017111c4309ba/engines/librpma_gpspm.c#L347)):*
> ```C
> 		rpma_td_verror(td, ret, "rpma_mr_dereg");
> 
> 	/* delete the iou's memory registration */
> ```

not applicable?
___
*[engines/librpma_gpspm.c, line 371 at r1](https://reviewable.io/reviews/pmem/fio/61#-MLwpLJiBnnb304RfjlQ:-MLwpLJiBnnb304RfjlR:b2zff15) ([raw file](https://github.com/pmem/fio/blob/e6a8e4717493bcb98bd32d7280d017111c4309ba/engines/librpma_gpspm.c#L371)):*
> ```C
> 	if ((ret = rpma_peer_delete(&cd->peer)))
> 		rpma_td_verror(td, ret, "rpma_peer_delete");
> ```

free(cd->io_us_msgs)?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/61)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 343 at r1](https://reviewable.io/reviews/pmem/fio/61#-MLwom-Q4rmyb-vcPV1W:-MLwuIab2-bPDhHmEGEo:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e6a8e4717493bcb98bd32d7280d017111c4309ba/engines/librpma_gpspm.c#L343)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

comment missing
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 347 at r1](https://reviewable.io/reviews/pmem/fio/61#-MLwonaR2gPkKSqQ8Ze7:-MLwuto0D-ut16JRrRxX:bd4sz8a) ([raw file](https://github.com/pmem/fio/blob/e6a8e4717493bcb98bd32d7280d017111c4309ba/engines/librpma_gpspm.c#L347)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

not applicable?
</blockquote></details>

we create the server's memory representation in client_init() hook
___
*[engines/librpma_gpspm.c, line 371 at r1](https://reviewable.io/reviews/pmem/fio/61#-MLwpLJiBnnb304RfjlQ:-MLwvZlW9IDTE72hw5c1:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e6a8e4717493bcb98bd32d7280d017111c4309ba/engines/librpma_gpspm.c#L371)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

free(cd->io_us_msgs)?
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/61)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma_gpspm.c, line 374 at r2](https://reviewable.io/reviews/pmem/fio/61#-MLwwSxIBxPqXtExbkR8:-MLwwSxJ0C1hsWfglK_d:b-780zhe) ([raw file](https://github.com/pmem/fio/blob/5afa84f216fbca71a26bf699e3ba0d97ac192f8c/engines/librpma_gpspm.c#L374)):*
> ```
> /* free message buffers registration */
> ```

`/* free message buffers */`

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/61)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_gpspm.c, line 374 at r2](https://reviewable.io/reviews/pmem/fio/61#-MLwwSxIBxPqXtExbkR8:-MLwxd7MD4vrU26k3uA1:b-896fix) ([raw file](https://github.com/pmem/fio/blob/5afa84f216fbca71a26bf699e3ba0d97ac192f8c/engines/librpma_gpspm.c#L374)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> /* free message buffers registration */
> ```

`/* free message buffers */`
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/61)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[engines/librpma_gpspm.c, line 341 at r2](https://reviewable.io/reviews/pmem/fio/61#-MLwxZzpD3ii2945e7tX:-MLwxZzpD3ii2945e7tY:b-2z9m0e) ([raw file](https://github.com/pmem/fio/blob/5afa84f216fbca71a26bf699e3ba0d97ac192f8c/engines/librpma_gpspm.c#L341)):*
> ```
> /* delete the iou's memory registration */
> ```

```
/* deregister the iou's memory */
```

?
___
*[engines/librpma_gpspm.c, line 345 at r2](https://reviewable.io/reviews/pmem/fio/61#-MLwxsP49gGaSKaNC_bE:-MLwxsP49gGaSKaNC_bF:b-4jpuey) ([raw file](https://github.com/pmem/fio/blob/5afa84f216fbca71a26bf699e3ba0d97ac192f8c/engines/librpma_gpspm.c#L345)):*
> ```
> /* delete the messaging buffer memory registration */
> ```

```
/* deregister the messaging buffer memory */
```

?

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/61)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @osalyk)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/61)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/61#-:-MLxcoJw2Znlu3y5cF22:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

___
*[engines/librpma_gpspm.c, line 347 at r1](https://reviewable.io/reviews/pmem/fio/61#-MLwonaR2gPkKSqQ8Ze7:-MLxcd6_83OJzgBwRm4V:b-58pm4r) ([raw file](https://github.com/pmem/fio/blob/e6a8e4717493bcb98bd32d7280d017111c4309ba/engines/librpma_gpspm.c#L347)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

we create the server's memory representation in client_init() hook
</blockquote></details>

I see we have named identically this step for librpma.c engine. So let's be it. ;-)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/61)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/61#-:-MM-NgkAAVLXMOJVqbAp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
