### PR TITLE
 rpma: gpspm: empty the SQ before sending the last message

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #87
- [x] #88
- [x] #89

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/90)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/90)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 243 at r1](https://reviewable.io/reviews/pmem/fio/90#-MQBvrptBReiTtBDQd_8:-MQBvrpu55H0ZrILC9BE:b-k9t733) ([raw file](https://github.com/pmem/fio/blob/e8d8d4814bf6010418b2e1cdeccd948177f09ca6/engines/librpma_gpspm.c#L243)):*
> ```
> * 2
> ```
do we need this?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/90)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_gpspm.c, line 243 at r1](https://reviewable.io/reviews/pmem/fio/90#-MQBvrptBReiTtBDQd_8:-MQCgvFgDe-BcZzhajBw:b-5vyexk) ([raw file](https://github.com/pmem/fio/blob/e8d8d4814bf6010418b2e1cdeccd948177f09ca6/engines/librpma_gpspm.c#L243)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> * 2
> ```
do we need this?
</blockquote></details>

Have you read the comment above?

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/90)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 461 at r2](https://reviewable.io/reviews/pmem/fio/90#-MQCiTss4O9g3A1yAfyf:-MQCiTss4O9g3A1yAfyg:b-e2u5co) ([raw file](https://github.com/pmem/fio/blob/6077ba7fc08f36b97d0d4f82f9986143c3e3eee9/engines/librpma_gpspm.c#L461)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 	if (flush_req_size > MAX_MSG_SIZE) {
> 		log_err(
> 			"Packed flush request size is bigger than available send buffer space (%zu > %d\n",
> 			flush_req_size, MAX_MSG_SIZE);
> 	}
> ```
</details>


Can we proceed further if `(flush_req_size > MAX_MSG_SIZE)` ?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/90)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 448 at r2](https://reviewable.io/reviews/pmem/fio/90#-MQCiC8oA12lUWPyruPZ:-MQCiC8p1J3TPuuWg5Yf:bhju66v) ([raw file](https://github.com/pmem/fio/blob/6077ba7fc08f36b97d0d4f82f9986143c3e3eee9/engines/librpma_gpspm.c#L448)):*
> ```
> break;
> ```
shall we try to send anything in case of error or shall we just deregister memory and close connection?
___
*[engines/librpma_gpspm.c, line 468 at r2](https://reviewable.io/reviews/pmem/fio/90#-MQCj0nA4ahajbgPv6QI:-MQCj0nA4ahajbgPv6QJ:b-q8wvl4) ([raw file](https://github.com/pmem/fio/blob/6077ba7fc08f36b97d0d4f82f9986143c3e3eee9/engines/librpma_gpspm.c#L468)):*
> ```
> rpma_send
> ```
shall we wait for any completion for these send before we unregister memory and shutdown connection?

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/90)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/90)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 468 at r2](https://reviewable.io/reviews/pmem/fio/90#-MQCj0nA4ahajbgPv6QI:-MQCjldkENUHZlcw-LBy:b-tzxc7j) ([raw file](https://github.com/pmem/fio/blob/6077ba7fc08f36b97d0d4f82f9986143c3e3eee9/engines/librpma_gpspm.c#L468)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_send
> ```
shall we wait for any completion for these send before we unregister memory and shutdown connection?
</blockquote></details>

I think it is not needed, it is `client_cleanup()`

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/90)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 448 at r2](https://reviewable.io/reviews/pmem/fio/90#-MQCiC8oA12lUWPyruPZ:-MQCnZ1G-oNBfvU_ST5N:b-cu5vpb) ([raw file](https://github.com/pmem/fio/blob/6077ba7fc08f36b97d0d4f82f9986143c3e3eee9/engines/librpma_gpspm.c#L448)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> break;
> ```
shall we try to send anything in case of error or shall we just deregister memory and close connection?
</blockquote></details>

I have added a notice above. Please verify.
___
*[engines/librpma_gpspm.c, line 461 at r2](https://reviewable.io/reviews/pmem/fio/90#-MQCiTss4O9g3A1yAfyf:-MQCnkafBaiXLkzsYP_g:b-kwrfrh) ([raw file](https://github.com/pmem/fio/blob/6077ba7fc08f36b97d0d4f82f9986143c3e3eee9/engines/librpma_gpspm.c#L461)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	if (flush_req_size > MAX_MSG_SIZE) {
> 		log_err(
> 			"Packed flush request size is bigger than available send buffer space (%zu > %d\n",
> 			flush_req_size, MAX_MSG_SIZE);
> 	}
> ```

Can we proceed further if `(flush_req_size > MAX_MSG_SIZE)` ?
</blockquote></details>

No. We should quit in this case. Another PR is required.
___
*[engines/librpma_gpspm.c, line 468 at r2](https://reviewable.io/reviews/pmem/fio/90#-MQCj0nA4ahajbgPv6QI:-MQCnv861wxln5p7m-2z:bpd4p76) ([raw file](https://github.com/pmem/fio/blob/6077ba7fc08f36b97d0d4f82f9986143c3e3eee9/engines/librpma_gpspm.c#L468)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I think it is not needed, it is `client_cleanup()`
</blockquote></details>

No. After the return from `rpma_send()` the transfer from the local memory is already done.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/90)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma_gpspm.c, line 448 at r2](https://reviewable.io/reviews/pmem/fio/90#-MQCiC8oA12lUWPyruPZ:-MQCof6TCI33PbY1ExOv:bw4rwfn) ([raw file](https://github.com/pmem/fio/blob/6077ba7fc08f36b97d0d4f82f9986143c3e3eee9/engines/librpma_gpspm.c#L448)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I have added a notice above. Please verify.
</blockquote></details>

but shall we first cleanup the completion queue until we get no-completion?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/90)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 448 at r2](https://reviewable.io/reviews/pmem/fio/90#-MQCiC8oA12lUWPyruPZ:-MQCpOtUE7gQ5mC4F3UM:bhcpf89) ([raw file](https://github.com/pmem/fio/blob/6077ba7fc08f36b97d0d4f82f9986143c3e3eee9/engines/librpma_gpspm.c#L448)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

but shall we first cleanup the completion queue until we get no-completion?
</blockquote></details>

Yes, we can. It will **additionally** increase a chance of sending the termination notice successfully.
Maybe part of another PR. Not very urgent in my opinion.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/90)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 461 at r2](https://reviewable.io/reviews/pmem/fio/90#-MQCiTss4O9g3A1yAfyf:-MQCsXI470suWnZ4LMti:b-w2gpip) ([raw file](https://github.com/pmem/fio/blob/6077ba7fc08f36b97d0d4f82f9986143c3e3eee9/engines/librpma_gpspm.c#L461)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No. We should quit in this case. Another PR is required.
</blockquote></details>

Because `rpma_send()` is not called now, but you have changed it - so this PR introduces the change that `rpma_send()` is called even if the size is too big ....

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/90)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 461 at r2](https://reviewable.io/reviews/pmem/fio/90#-MQCiTss4O9g3A1yAfyf:-MQCuJZA2BlIzGWIabiE:b-meliu1) ([raw file](https://github.com/pmem/fio/blob/6077ba7fc08f36b97d0d4f82f9986143c3e3eee9/engines/librpma_gpspm.c#L461)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Because `rpma_send()` is not called now, but you have changed it - so this PR introduces the change that `rpma_send()` is called even if the size is too big ....
</blockquote></details>

I think it should stay in the `else` branch as it was before.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/90)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 461 at r2](https://reviewable.io/reviews/pmem/fio/90#-MQCiTss4O9g3A1yAfyf:-MQCukAEBTO0-TONYNKW:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6077ba7fc08f36b97d0d4f82f9986143c3e3eee9/engines/librpma_gpspm.c#L461)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I think it should stay in the `else` branch as it was before.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/90)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/90#-:-MQCv2hw76JtxIvSFNjc:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/90#-:-MQD2uSu6Ph_srO1WzRU:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Pull request merged**
