### PR TITLE
rpma: introduce librpma_common_client_data

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/120)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/120#-:-MR4GPdbBArkGBxHELFJ:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_common.h, line 70 at r1](https://reviewable.io/reviews/pmem/fio/120#-MR4F5XT3kAOFuzzeW_7:-MR4F5XT3kAOFuzzeW_8:bd2m8vc) ([raw file](https://github.com/pmem/fio/blob/cfb7ab11e41e130a8b59545f16784c0bd394fedd/engines/librpma_common.h#L70)):*
> ```
> *client_data
> ```
*private

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/120)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/120)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_common.h, line 70 at r1](https://reviewable.io/reviews/pmem/fio/120#-MR4F5XT3kAOFuzzeW_7:-MR4SB7IAv_O3obnlSaN:b-xsq74h) ([raw file](https://github.com/pmem/fio/blob/cfb7ab11e41e130a8b59545f16784c0bd394fedd/engines/librpma_common.h#L70)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> *client_data
> ```
*private
</blockquote></details>

*client_data :-)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/120#-:-MR4SGi804DwJ6Wr_RPq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/120#-:-MR4UrPuBYX_K6uMmHox:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
