### PR TITLE
rpma: .fio example file with real values for latency measurement

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/195)

### CODE REVIEW

**Comment by ldorau** [comment]
Please rebase

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/195)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[examples/librpma_gpspm-client.fio, line 14 at r1](https://reviewable.io/reviews/pmem/fio/195#-MS3EHOW42n2yNrx2wtB:-MS3EHOW42n2yNrx2wtC:b3tfx8w) ([raw file](https://github.com/pmem/fio/blob/09aa8327353b4351807c6fbb9da73b7d1dfeb366/examples/librpma_gpspm-client.fio#L14)):*
> ```
> connection
> ```

connectionS
___
*[examples/librpma_gpspm-client.fio, line 17 at r1](https://reviewable.io/reviews/pmem/fio/195#-MS3ER8T4evZkvFUgsY7:-MS3ER8T4evZkvFUgsY8:b-4u6jg7) ([raw file](https://github.com/pmem/fio/blob/09aa8327353b4351807c6fbb9da73b7d1dfeb366/examples/librpma_gpspm-client.fio#L17)):*
> ```
> # total # of ious
> ```

`# total number of ious`
___
*[examples/librpma_gpspm-client.fio, line 18 at r1](https://reviewable.io/reviews/pmem/fio/195#-MS3EVcWD-6L9Wg3g9oI:-MS3EVcWD-6L9Wg3g9oJ:btyc2vu) ([raw file](https://github.com/pmem/fio/blob/09aa8327353b4351807c6fbb9da73b7d1dfeb366/examples/librpma_gpspm-client.fio#L18)):*
> ```
>  # of ious to submit at once
> ```

` # number of ious to be submitted at once`
___
*[examples/librpma_gpspm-server.fio, line 26 at r1](https://reviewable.io/reviews/pmem/fio/195#-MS3FA5I67BE1Uc2dgZo:-MS3FA5I67BE1Uc2dgZp:b-2wyftc) ([raw file](https://github.com/pmem/fio/blob/09aa8327353b4351807c6fbb9da73b7d1dfeb366/examples/librpma_gpspm-server.fio#L26)):*
> ```
> filename=filename=malloc
> ```

???

**Review by osalyk — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/195#-:-MS3GKNBDr1Kv_MqpUPi:b-896fix)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[examples/librpma_gpspm-client.fio, line 14 at r1](https://reviewable.io/reviews/pmem/fio/195#-MS3EHOW42n2yNrx2wtB:-MS3FX2gD62D86Jfrs1Y:b-896fix) ([raw file](https://github.com/pmem/fio/blob/09aa8327353b4351807c6fbb9da73b7d1dfeb366/examples/librpma_gpspm-client.fio#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> connection
> ```

connectionS
</blockquote></details>

Done.
___
*[examples/librpma_gpspm-client.fio, line 17 at r1](https://reviewable.io/reviews/pmem/fio/195#-MS3ER8T4evZkvFUgsY7:-MS3F_qL3kBd2_GUDq3p:b-896fix) ([raw file](https://github.com/pmem/fio/blob/09aa8327353b4351807c6fbb9da73b7d1dfeb366/examples/librpma_gpspm-client.fio#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> # total # of ious
> ```

`# total number of ious`
</blockquote></details>

Done.
___
*[examples/librpma_gpspm-client.fio, line 18 at r1](https://reviewable.io/reviews/pmem/fio/195#-MS3EVcWD-6L9Wg3g9oI:-MS3Fd2UAy_j9ixHpp2Z:b-896fix) ([raw file](https://github.com/pmem/fio/blob/09aa8327353b4351807c6fbb9da73b7d1dfeb366/examples/librpma_gpspm-client.fio#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  # of ious to submit at once
> ```

` # number of ious to be submitted at once`
</blockquote></details>

Done.
___
*[examples/librpma_gpspm-server.fio, line 26 at r1](https://reviewable.io/reviews/pmem/fio/195#-MS3FA5I67BE1Uc2dgZo:-MS3FgzW-cwQLW-0owPE:b-896fix) ([raw file](https://github.com/pmem/fio/blob/09aa8327353b4351807c6fbb9da73b7d1dfeb366/examples/librpma_gpspm-server.fio#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> filename=filename=malloc
> ```

???
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/195)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[examples/librpma_gpspm-client.fio, line 18 at r1](https://reviewable.io/reviews/pmem/fio/195#-MS3EVcWD-6L9Wg3g9oI:-MS3GTS25nmDabE3kMXB:bxtvnig) ([raw file](https://github.com/pmem/fio/blob/09aa8327353b4351807c6fbb9da73b7d1dfeb366/examples/librpma_gpspm-client.fio#L18)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

 to be submitted
___
*[examples/librpma_gpspm-server.fio, line 27 at r2](https://reviewable.io/reviews/pmem/fio/195#-MS3GhpK0BdWoeRFHHFD:-MS3GhpK0BdWoeRFHHFE:bh1vw4i) ([raw file](https://github.com/pmem/fio/blob/189bc1e296a4a60740ad3adfc98a6c68459f7839/examples/librpma_gpspm-server.fio#L27)):*
> ```
> # filename=/dev/dax1.0
> ```

Is it needed ?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/195)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[examples/librpma_gpspm-server.fio, line 27 at r2](https://reviewable.io/reviews/pmem/fio/195#-MS3GhpK0BdWoeRFHHFD:-MS3IVBh7L1qXfMTCsDU:b-u2fgmq) ([raw file](https://github.com/pmem/fio/blob/189bc1e296a4a60740ad3adfc98a6c68459f7839/examples/librpma_gpspm-server.fio#L27)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> # filename=/dev/dax1.0
> ```

Is it needed ?
</blockquote></details>

As an example.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/195)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

___
*[examples/librpma_gpspm-server.fio, line 27 at r2](https://reviewable.io/reviews/pmem/fio/195#-MS3GhpK0BdWoeRFHHFD:-MS3JHz69d4J7uogjgNc:b32w0x) ([raw file](https://github.com/pmem/fio/blob/189bc1e296a4a60740ad3adfc98a6c68459f7839/examples/librpma_gpspm-server.fio#L27)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

As an example.
</blockquote></details>

OK

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/195#-:-MS3JL5q2muROA_QpmoN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/195)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[examples/librpma_apm-client.fio, line 1 at r3](https://reviewable.io/reviews/pmem/fio/195#-MS7Ly5h03fKSYgG54v2:-MS7Ly5h03fKSYgG54v3:bi462a9) ([raw file](https://github.com/pmem/fio/blob/b8f7e2334d1f28863998184d88cb21b35cf728ad/examples/librpma_apm-client.fio#L1)):*
> ```
> # Example of the librpma_apm client job
> ```

`librpma_apm_client`
___
*[examples/librpma_apm-client.fio, line 19 at r3](https://reviewable.io/reviews/pmem/fio/195#-MS7Li6E83UNBy6GydhI:-MS7Li6E83UNBy6GydhJ:bn2ygla) ([raw file](https://github.com/pmem/fio/blob/b8f7e2334d1f28863998184d88cb21b35cf728ad/examples/librpma_apm-client.fio#L19)):*
> ```
> iodepth=2 # total number of ious
> iodepth_batch_submit=1 # number of ious to be submitted at once
> rw=write # [read/write/randread/randwrite/readwrite/rw]
> ```

These braces seem unnecessary `[]`.
___
*[examples/librpma_gpspm-client.fio, line 1 at r3](https://reviewable.io/reviews/pmem/fio/195#-MS7M21Y6tn--B42ezqi:-MS7M21Y6tn--B42ezqj:b-jzpbfq) ([raw file](https://github.com/pmem/fio/blob/b8f7e2334d1f28863998184d88cb21b35cf728ad/examples/librpma_gpspm-client.fio#L1)):*
> ```
> # Example of the librpma_gpspm-client job
> ```

`librpma_gpspm_client`
___
*[examples/librpma_gpspm-client.fio, line 19 at r3](https://reviewable.io/reviews/pmem/fio/195#-MS7KW8C6o-2PGY0aRXQ:-MS7KW8DB64Tiq84WTgP:b-kz4phr) ([raw file](https://github.com/pmem/fio/blob/b8f7e2334d1f28863998184d88cb21b35cf728ad/examples/librpma_gpspm-client.fio#L19)):*
> ```
> iodepth=2 # total number of ious
> iodepth_batch_submit=1 # number of ious to be submitted at once
> rw=[write/randwrite]
> ```

`rw=write # write/randwrite`

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/195)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

___
*[examples/librpma_gpspm-server.fio, line 1 at r3](https://reviewable.io/reviews/pmem/fio/195#-MS7N7O69fGJwM_dxN8l:-MS7N7O69fGJwM_dxN8m:b-9imbzc) ([raw file](https://github.com/pmem/fio/blob/b8f7e2334d1f28863998184d88cb21b35cf728ad/examples/librpma_gpspm-server.fio#L1)):*
> ```
> # Example of the librpma_gpspm-server job
> ```

`librpma_gpspm_server` + please also fix in the apm server example

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/195)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[examples/librpma_apm-client.fio, line 1 at r3](https://reviewable.io/reviews/pmem/fio/195#-MS7Ly5h03fKSYgG54v2:-MS7NZuI3JGDH6_vgnTI:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b8f7e2334d1f28863998184d88cb21b35cf728ad/examples/librpma_apm-client.fio#L1)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`librpma_apm_client`
</blockquote></details>

Done.
___
*[examples/librpma_apm-client.fio, line 19 at r3](https://reviewable.io/reviews/pmem/fio/195#-MS7Li6E83UNBy6GydhI:-MS7NfJJCi_MOSNgOYkj:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b8f7e2334d1f28863998184d88cb21b35cf728ad/examples/librpma_apm-client.fio#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

These braces seem unnecessary `[]`.
</blockquote></details>

Done.
___
*[examples/librpma_gpspm-client.fio, line 1 at r3](https://reviewable.io/reviews/pmem/fio/195#-MS7M21Y6tn--B42ezqi:-MS7btjs3farjqz0gQiD:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b8f7e2334d1f28863998184d88cb21b35cf728ad/examples/librpma_gpspm-client.fio#L1)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`librpma_gpspm_client`
</blockquote></details>

Done.
___
*[examples/librpma_gpspm-client.fio, line 19 at r3](https://reviewable.io/reviews/pmem/fio/195#-MS7KW8C6o-2PGY0aRXQ:-MS7bzGZEAtS-DnRhjhU:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b8f7e2334d1f28863998184d88cb21b35cf728ad/examples/librpma_gpspm-client.fio#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`rw=write # write/randwrite`
</blockquote></details>

Done.
___
*[examples/librpma_gpspm-server.fio, line 1 at r3](https://reviewable.io/reviews/pmem/fio/195#-MS7N7O69fGJwM_dxN8l:-MS7c-gqD_QlFgRshutX:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b8f7e2334d1f28863998184d88cb21b35cf728ad/examples/librpma_gpspm-server.fio#L1)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`librpma_gpspm_server` + please also fix in the apm server example
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/195)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/195#-:-MS7ptHK99xNH5F31dKI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
