### PR TITLE
rpma: fix printing of connection establishment information after retries

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/237)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/237#-:-MUUDZ_T5rzLt5PMEZW1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/237)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/237#-MU_e3fWE_f3anrJc3Bq:-MU_e3fWE_f3anrJc3Br:b5ciahv) (no related file):*
1. This change should go to another branch: https://github.com/pmem/fio/tree/rpma AND
2. It should be later cherry-picked to this branch. For an example of the naming convention, we have introduced for easier finding the cherry-picked commits please see e.g. https://github.com/pmem/fio/pull/234

---

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/237)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Comment by osalyk** [comment]
#238

**Pull request closed without merging**
