### PR TITLE
rpma: print out those logs only in thread #1

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/197)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/197#-:-MS7lKHl9TsWerve1r_w:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/197)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_apm.c, line 108 at r1](https://reviewable.io/reviews/pmem/fio/197#-MS7vLOx0urjbivPNGtV:-MS7vLOx0urjbivPNGtW:bxbj2kk) ([raw file](https://github.com/pmem/fio/blob/0001d26964b2f33a4ca4aa4a2dcf804fe05fc6f8/engines/librpma_apm.c#L108)):*
> ```C
> 	if (ccd->server_mr_flush_type == RPMA_FLUSH_TYPE_PERSISTENT) {
> 		if (!ccd->ws->direct_write_to_pmem && td->thread_number == 1) {
> 			log_err(
> ```

This additional conditional should only prevent from printing the log message. It should not prevent from going to `err_cleanup_common`.
___
*[engines/librpma_gpspm.c, line 150 at r1](https://reviewable.io/reviews/pmem/fio/197#-MS7vrH3Bd3nvfUJfb-o:-MS7vrH3Bd3nvfUJfb-p:b-seovta) ([raw file](https://github.com/pmem/fio/blob/0001d26964b2f33a4ca4aa4a2dcf804fe05fc6f8/engines/librpma_gpspm.c#L150)):*
> ```C
> 	if (ccd->ws->direct_write_to_pmem) {
> 		if (ccd->server_mr_flush_type == RPMA_FLUSH_TYPE_PERSISTENT &&
> 		    td->thread_number == 1) {
> ```

Since these conditions only control printing the log message, I think it should be the part of the first, not the second one.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/197)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_apm.c, line 108 at r1](https://reviewable.io/reviews/pmem/fio/197#-MS7vLOx0urjbivPNGtV:-MS8760Q2aSYsDyObnah:b-bngiru) ([raw file](https://github.com/pmem/fio/blob/0001d26964b2f33a4ca4aa4a2dcf804fe05fc6f8/engines/librpma_apm.c#L108)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This additional conditional should only prevent from printing the log message. It should not prevent from going to `err_cleanup_common`.
</blockquote></details>

Oh, that's right, I missed it. Done.
___
*[engines/librpma_gpspm.c, line 150 at r1](https://reviewable.io/reviews/pmem/fio/197#-MS7vrH3Bd3nvfUJfb-o:-MS87jZH4jt5NuQgxf5-:byclr0n) ([raw file](https://github.com/pmem/fio/blob/0001d26964b2f33a4ca4aa4a2dcf804fe05fc6f8/engines/librpma_gpspm.c#L150)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since these conditions only control printing the log message, I think it should be the part of the first, not the second one.
</blockquote></details>

Merged to one `if`. Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/197#-:-MS8AyJtBV7F_tQP3j5V:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/197)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_apm.c, line 132 at r1](https://reviewable.io/reviews/pmem/fio/197#-MS89petAV6RUtAGU9zo:-MS89petAV6RUtAGU9zp:b-i92d1s) ([raw file](https://github.com/pmem/fio/blob/0001d26964b2f33a4ca4aa4a2dcf804fe05fc6f8/engines/librpma_apm.c#L132)):*
> ```
>else if (td->thread_number == 1) {
>...
> ```
```
else { 
if (td->thread_number == 1) 
...
```
To clarify that this condition is only related to the message.
To avoid the situation @janekmi pointed above.

**Pull request merged**
