### PR TITLE
rpma: allow server to handle multiple connections

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/37)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37)* status: 1 of 2 files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37#-:-MKeG96jAbvHPKuFLd_W:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
@grom72 @osalyk please review

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37#-:-MKeIfxL4ztirOCpdGNH:bg7id4e)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37#-:-MKeOhMjBmyKy6EaUroa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 771 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeDyAM88sldbKszhy2:-MKeDyAM88sldbKszhy3:b-wkdb71) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L771)):*
> ```
> td->o.iodepth = o->num_conns;
> ```
do we need a separate

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma.c, line 771 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeDyAM88sldbKszhy2:-MKeSLswDzLXFPC2-tF8:b-2kkmu3) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L771)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> td->o.iodepth = o->num_conns;
> ```
do we need a separate 
</blockquote></details>

what separate?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 771 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeDyAM88sldbKszhy2:-MKeSaZUBguBybshE6ol:b-n14wxt) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L771)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

what separate?
</blockquote></details>

do we need a separate parameter? can we use iodepth directly?
___
*[engines/librpma.c, line 887 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeSAd8Aw31mNHHWk-B:-MKeSAd8Aw31mNHHWk-C:b-latizq) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L887)):*
> ```
> server_conn_init
> ```
can we use a different name as it is not a part of server_init?
___
*[examples/librpma-server.fio, line 20 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeRgUSCq-EdWig67A2:-MKeRgUSCq-EdWig67A3:b-336sz7) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/examples/librpma-server.fio#L20)):*
> ```
> num_conns
> ```
conn_num ?

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/librpma-server.fio, line 20 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeRgUSCq-EdWig67A2:-MKeTLiI9BbbuCsI8DzS:bmpslfm) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/examples/librpma-server.fio#L20)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> num_conns
> ```
conn_num ?
</blockquote></details>

I am for `num_conns` the most important (it is a **number**) should go first.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 887 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeSAd8Aw31mNHHWk-B:-MKeTjVwD5rvns252TPG:b-gnbkes) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L887)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> server_conn_init
> ```
can we use a different name as it is not a part of server_init?
</blockquote></details>

But it is an init of the connection, so IMHO `server_conn_init`is OK. What name do you propose?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[engines/librpma.c, line 771 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeDyAM88sldbKszhy2:-MKeUmgqBVe0Ytypzt0w:bk7m58r) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L771)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

do we need a separate parameter? can we use iodepth directly?
</blockquote></details>

Sure we can. But I do not like the idea of adding a new meaning for well-defined options.

Adding a new option does not cost us anything. But I don't mind reusing another well matching option if you find one.
___
*[engines/librpma.c, line 887 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeSAd8Aw31mNHHWk-B:-MKeVfS04yz6SW-eQHJ9:b-8vrl3f) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L887)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

But it is an init of the connection, so IMHO `server_conn_init`is OK. What name do you propose?
</blockquote></details>

We can always use another name. What is your proposition?
___
*[examples/librpma-server.fio, line 20 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeRgUSCq-EdWig67A2:-MKeVnAO6Xscq_LUUVyp:b-nzy5ne) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/examples/librpma-server.fio#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I am for `num_conns` the most important (it is a **number**) should go first.
</blockquote></details>

I was inspired by `numjobs`. :-)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 887 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeSAd8Aw31mNHHWk-B:-MKeW8mg9kXIR8-QR0eC:b-g6i4jc) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L887)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We can always use another name. What is your proposition?
</blockquote></details>

_init is somehow reserved for .init hook of fio
what about serv_conn_establish?
___
*[engines/librpma.c, line 981 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeUlph87aR4qZ-ozrp:-MKeUlph87aR4qZ-ozrq:b-l8s5or) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L981)):*
> ```
> "example_common_data.data_offset too small to describe connection's workspace offset"
> ```
"io data size too small to accept the connection"
___
*[engines/librpma.c, line 986 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeUBS20uyn4QbUNe4u:-MKeUBS20uyn4QbUNe4v:b8t1nc0) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L986)):*
> ```
> sd->data.data_offset += bs
> ```
this function will be called only one time - do we need to memorize data_offset at all? or is it enough just to have a local variable to monitor overflow?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 771 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeDyAM88sldbKszhy2:-MKeX9kq5MXNEzKdo2xN:b-jroris) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L771)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Sure we can. But I do not like the idea of adding a new meaning for well-defined options.

Adding a new option does not cost us anything. But I don't mind reusing another well matching option if you find one.
</blockquote></details>

but we do this in the line above - in a similar way rdma converts hostname into a filename

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 771 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeDyAM88sldbKszhy2:-MKeXx8d9qsDf2W6LPAt:b-arsfl3) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L771)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

but we do this in the line above - in a similar way rdma converts hostname into a filename
</blockquote></details>

I would like to have a clear interpretation "what connection num stand in term of FIO on the server-side" is it iodepth?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 932 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeYGASD3F-jmQYZ8U2:-MKeYGASD3F-jmQYZ8U3:bk5b52h) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L932)):*
> ```
> server_conn_cleanup
> ```
server_conn_shutdown

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 887 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeSAd8Aw31mNHHWk-B:-MKhmTQJAX8HZeTxogsv:bn91k87) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L887)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

_init is somehow reserved for .init hook of fio
what about serv_conn_establish?
</blockquote></details>

`serv_conn_establish` can be
___
*[engines/librpma.c, line 932 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeYGASD3F-jmQYZ8U2:-MKhmcP19GvPyLZj5E79:b32w0x) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L932)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> server_conn_cleanup
> ```
server_conn_shutdown
</blockquote></details>

OK

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 887 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeSAd8Aw31mNHHWk-B:-MKiDvdA-JaPLYA4DcFS:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L887)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`serv_conn_establish` can be
</blockquote></details>

Done.
___
*[engines/librpma.c, line 932 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeYGASD3F-jmQYZ8U2:-MKiE-vF9FfcIR552oxE:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L932)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.
___
*[engines/librpma.c, line 981 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeUlph87aR4qZ-ozrp:-MKiE4Vl9gpsG4FDtY29:b-ut4dd3) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L981)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> "example_common_data.data_offset too small to describe connection's workspace offset"
> ```
"io data size too small to accept the connection"
</blockquote></details>

No, no, no. The field in the structure is too small to store the value of the offset. That's it.
Please discuss it in detail in #40.
___
*[engines/librpma.c, line 986 at r1](https://reviewable.io/reviews/pmem/fio/37#-MKeUBS20uyn4QbUNe4u:-MKiESOW6yj1njygDrhx:b-8e07ws) ([raw file](https://github.com/pmem/fio/blob/d3e3e8ce42bc46d1739f52b62fb30f6ad1deb337/engines/librpma.c#L986)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> sd->data.data_offset += bs
> ```
this function will be called only one time - do we need to memorize data_offset at all? or is it enough just to have a local variable to monitor overflow?
</blockquote></details>

It is not about this value but collecting all values which will be sent to another end of the connection.
They are collected in:
- server_open_file and
- server_queue

I see no point in storing values collected in `server_open_file` and here rewriting them to a new local structure.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/37#-:-MKiFn4M1BsP4K5HVD1w:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
