### PR TITLE
aof: add client_hw_init()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/240)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/240)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/240)* status: all files reviewed, 7 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_aof.c, line 247 at r1](https://reviewable.io/reviews/pmem/fio/240#-MUiPEpp8yyuZvfr9wWr:-MUiPEpqAuLdk3zkvr7s:brr5go7) ([raw file](https://github.com/pmem/fio/blob/46f5447580732371b5fcd170d864c203df60f3a0/engines/librpma_aof.c#L247)):*
> ```C
> 
> 	/* allocate client's data */
> 	cd = calloc(1, sizeof(*cd));
> ```

It seems not needed for the hw mode.
___
*[engines/librpma_aof.c, line 256 at r1](https://reviewable.io/reviews/pmem/fio/240#-MUiUFBC9IvBnzfa5TTv:-MUiUFBC9IvBnzfa5TTw:b-c2ugyt) ([raw file](https://github.com/pmem/fio/blob/46f5447580732371b5fcd170d864c203df60f3a0/engines/librpma_aof.c#L256)):*
> Each AOF update is a sequence of FLUSH + ATOMIC_WRITE + FLUSH.
___
*[engines/librpma_aof.c, line 261 at r1](https://reviewable.io/reviews/pmem/fio/240#-MUiQXvx1MkyO3P4NurW:-MUiQXvx1MkyO3P4NurX:bt2f3j2) ([raw file](https://github.com/pmem/fio/blob/46f5447580732371b5fcd170d864c203df60f3a0/engines/librpma_aof.c#L261)):*
> ```C
> 		write_num = 1; /* atomic WRITE */
> 		flush_num = 2; /* FLUSH */
> 		cd->msg_num = 0; /* no SENDs */
> ```

```c
write_num = 1; /* WRITE */
update_num = 1; /* AOF update */
```
___
*[engines/librpma_aof.c, line 271 at r1](https://reviewable.io/reviews/pmem/fio/240#-MUiVSsFCaaujaAJUJHG:-MUiVSsFCaaujaAJUJHH:b-chvs9m) ([raw file](https://github.com/pmem/fio/blob/46f5447580732371b5fcd170d864c203df60f3a0/engines/librpma_aof.c#L271)):*
> ```C
> 		flush_num = 2 * LIBRPMA_FIO_CEIL(td->o.iodepth,
> 				td->o.iodepth_batch);
> 		cd->msg_num = 0; /* no SENDs */
> ```

```c
write_num = td->o.iodepth; /* WRITE * N */
/*
 * AOF update * B where:
 * - B == ceil(iodepth / iodepth_batch)
 *   which is the number of batches for N writes
 */
update_num = LIBRPMA_FIO_CEIL(td->o.iodepth,
        td->o.iodepth_batch);
```
___
*[engines/librpma_aof.c, line 283 at r1](https://reviewable.io/reviews/pmem/fio/240#-MUiVZfT9iLkF7FhL6y2:-MUiVZfT9iLkF7FhL6y3:bda0xsr) ([raw file](https://github.com/pmem/fio/blob/46f5447580732371b5fcd170d864c203df60f3a0/engines/librpma_aof.c#L283)):*
> ```C
> 	 * Calculate the required queue sizes where:
> 	 * - the send queue (SQ) has to be big enough to accommodate
> 	 *   all io_us (WRITEs) and all flushes (READs)
> ```

... and all AOF updates (FLUSH + ATOMIC_WRITE + FLUSH).
___
*[engines/librpma_aof.c, line 288 at r1](https://reviewable.io/reviews/pmem/fio/240#-MUiVwq78IrBQnNnF4-k:-MUiVwq78IrBQnNnF4-l:b-tin19) ([raw file](https://github.com/pmem/fio/blob/46f5447580732371b5fcd170d864c203df60f3a0/engines/librpma_aof.c#L288)):*
> ```C
> 	 *   success and error completions (sq_size)
> 	 */
> 	if ((ret = rpma_conn_cfg_set_sq_size(cfg, write_num + flush_num))) {
> ```

`write_num + 3 * update_num`
___
*[engines/librpma_aof.c, line 296 at r1](https://reviewable.io/reviews/pmem/fio/240#-MUiW0bN4I5Htb1tsq7l:-MUiW0bN4I5Htb1tsq7m:b3kqx) ([raw file](https://github.com/pmem/fio/blob/46f5447580732371b5fcd170d864c203df60f3a0/engines/librpma_aof.c#L296)):*
> ```C
> 		goto err_cfg_delete;
> 	}
> 	if ((ret = rpma_conn_cfg_set_cq_size(cfg, write_num + flush_num))) {
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/240)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma_aof.c, line 247 at r1](https://reviewable.io/reviews/pmem/fio/240#-MUiPEpp8yyuZvfr9wWr:-MUjtSP06FuhZofjyjYC:b-896fix) ([raw file](https://github.com/pmem/fio/blob/46f5447580732371b5fcd170d864c203df60f3a0/engines/librpma_aof.c#L247)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems not needed for the hw mode.
</blockquote></details>

Done.
___
*[engines/librpma_aof.c, line 256 at r1](https://reviewable.io/reviews/pmem/fio/240#-MUiUFBC9IvBnzfa5TTv:-MUjuB3h8RWD2d3IqVKR:b-896fix) ([raw file](https://github.com/pmem/fio/blob/46f5447580732371b5fcd170d864c203df60f3a0/engines/librpma_aof.c#L256)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> Each AOF update is a sequence of FLUSH + ATOMIC_WRITE + FLUSH.
</blockquote></details>

Done.
___
*[engines/librpma_aof.c, line 261 at r1](https://reviewable.io/reviews/pmem/fio/240#-MUiQXvx1MkyO3P4NurW:-MUjuE2aAaJOgcfbpukX:b-896fix) ([raw file](https://github.com/pmem/fio/blob/46f5447580732371b5fcd170d864c203df60f3a0/engines/librpma_aof.c#L261)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
write_num = 1; /* WRITE */
update_num = 1; /* AOF update */
```
</blockquote></details>

Done.
___
*[engines/librpma_aof.c, line 271 at r1](https://reviewable.io/reviews/pmem/fio/240#-MUiVSsFCaaujaAJUJHG:-MUjunLFESEBaVTa8CeH:b-896fix) ([raw file](https://github.com/pmem/fio/blob/46f5447580732371b5fcd170d864c203df60f3a0/engines/librpma_aof.c#L271)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
write_num = td->o.iodepth; /* WRITE * N */
/*
 * AOF update * B where:
 * - B == ceil(iodepth / iodepth_batch)
 *   which is the number of batches for N writes
 */
update_num = LIBRPMA_FIO_CEIL(td->o.iodepth,
        td->o.iodepth_batch);
```
</blockquote></details>

Done.
___
*[engines/librpma_aof.c, line 283 at r1](https://reviewable.io/reviews/pmem/fio/240#-MUiVZfT9iLkF7FhL6y2:-MUjubzj5vZxINjZAGeg:b-896fix) ([raw file](https://github.com/pmem/fio/blob/46f5447580732371b5fcd170d864c203df60f3a0/engines/librpma_aof.c#L283)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... and all AOF updates (FLUSH + ATOMIC_WRITE + FLUSH).
</blockquote></details>

Done.
___
*[engines/librpma_aof.c, line 288 at r1](https://reviewable.io/reviews/pmem/fio/240#-MUiVwq78IrBQnNnF4-k:-MUjui_M5P8-FgrN8ljI:b-896fix) ([raw file](https://github.com/pmem/fio/blob/46f5447580732371b5fcd170d864c203df60f3a0/engines/librpma_aof.c#L288)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`write_num + 3 * update_num`
</blockquote></details>

Done.
___
*[engines/librpma_aof.c, line 296 at r1](https://reviewable.io/reviews/pmem/fio/240#-MUiW0bN4I5Htb1tsq7l:-MUjujXeDKKud0WhX_zJ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/46f5447580732371b5fcd170d864c203df60f3a0/engines/librpma_aof.c#L296)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/240#-:-MUlwO4t9znW-JQPi58Y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/240#-:-MUlxQsX9CWAbleJnihG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
