### PR TITLE
rpma: align up td->orig_buffer

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/25)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/25#-:-MJbMvXe8nau0WRE-tZl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 222 at r1](https://reviewable.io/reviews/pmem/fio/25#-MJbMn8k17ogsBuKqlqf:-MJbMn8k17ogsBuKqlqg:b-fbkgav) ([raw file](https://github.com/pmem/fio/blob/f3d422ed7c746aeaafed67f9b721decd1a79cc00/engines/librpma.c#L222)):*
> ```
> so the FIO alignes
> ```

`so FIO alignes` (no `the`)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/25#-:-MJbQ1NN-1E7Hb3yqN5M:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/25#-:-MJeqD2DA26Ey7WoMfXg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/25)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
@grom72 please review

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/25#-:-MJfAkBj4xuF_OpkjWy-:bgjoyzx)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/25#-:-MJjcZxSEkfA5xU9bz1l:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
