### PR TITLE
aof: introduce the 2nd mode (server)

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/229)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/229)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_aof.c, line 809 at r1](https://reviewable.io/reviews/pmem/fio/229#-MUStAiJ7t2KDlz1vEL_:-MUStAiKA0nkjq5oJ3Xe:b-ex29nh) ([raw file](https://github.com/pmem/fio/blob/442959bda00a7d9d288921752c0598bc1ab8acef/engines/librpma_aof.c#L809)):*
> ```
> /* * */
> ```

```
/* see the (*) notice below */
```
___
*[engines/librpma_aof.c, line 820 at r1](https://reviewable.io/reviews/pmem/fio/229#-MUStVbB6ZIaxB59VZJP:-MUStVbC-pVrJoL-HaWZ:b-an4ll7) ([raw file](https://github.com/pmem/fio/blob/442959bda00a7d9d288921752c0598bc1ab8acef/engines/librpma_aof.c#L820)):*
> ```
> * *) the actual
> ```

```
* (*) the actual
```

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/229)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_aof.c, line 809 at r1](https://reviewable.io/reviews/pmem/fio/229#-MUStAiJ7t2KDlz1vEL_:-MUT97OG4TgE2UMdi2ik:b-896fix) ([raw file](https://github.com/pmem/fio/blob/442959bda00a7d9d288921752c0598bc1ab8acef/engines/librpma_aof.c#L809)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> /* * */
> ```

```
/* see the (*) notice below */
```
</blockquote></details>

Done.
___
*[engines/librpma_aof.c, line 820 at r1](https://reviewable.io/reviews/pmem/fio/229#-MUStVbB6ZIaxB59VZJP:-MUT97zODqcuPacdKPoh:b-896fix) ([raw file](https://github.com/pmem/fio/blob/442959bda00a7d9d288921752c0598bc1ab8acef/engines/librpma_aof.c#L820)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> * *) the actual
> ```

```
* (*) the actual
```
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/229)* status: 1 of 3 files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/229)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/229#-:-MUTfR6T8Hgs12vpH9IT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/229#-:-MUTrjEZ3G2PeI2OSZ9W:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/229)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
