### PR TITLE
rpma: scaffolding of the GPSPM variant of the librpma engine

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/47)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/47)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[Makefile, line 109 at r1](https://reviewable.io/reviews/pmem/fio/47#-MLSC0yE5QUWYxEFFXyL:-MLSC0yE5QUWYxEFFXyM:bwtj24y) ([raw file](https://github.com/pmem/fio/blob/9d77f0335a32f0234fa0ca817ada46eab93851aa/Makefile#L109)):*
> ```Makefile
> ifdef CONFIG_LIBRPMA_GPSPM
>   librpma_SRCS = engines/librpma_gpspm.c
>   librpma_LIBS = -lrpma -lpmem
> ```

You are overwriting these two variables.
___
*[options.c, line 1887 at r1](https://reviewable.io/reviews/pmem/fio/47#-MLSCBxU6E50Njwbfrv8:-MLSCBxU6E50Njwbfrv9:b-ve45s7) ([raw file](https://github.com/pmem/fio/blob/9d77f0335a32f0234fa0ca817ada46eab93851aa/options.c#L1887)):*
> ```C
> #ifdef CONFIG_LIBRPMA_GPSPM
> 			  { .ival = "librpma_gpspm",
> 			    .help = "librpma IO engine in GPSPM mode",
> ```

Here we have an engine specific help which we can provide for our engines.
___
*[examples/librpma_gpspm-client.fio, line 13 at r1](https://reviewable.io/reviews/pmem/fio/47#-MLSCw_cCbKR6V3fYy0s:-MLSCw_cCbKR6V3fYy0t:bldtz1h) ([raw file](https://github.com/pmem/fio/blob/9d77f0335a32f0234fa0ca817ada46eab93851aa/examples/librpma_gpspm-client.fio#L13)):*
> ```
> thread
> 
> # The client will get a remote memory region description after establishing
> ```

Please add XXX here. We are going to see how it comes up.
___
*[examples/librpma_gpspm-server.fio, line 13 at r1](https://reviewable.io/reviews/pmem/fio/47#-MLSD0_S80qyRQs_dumE:-MLSD0_S80qyRQs_dumF:b2nhrub) ([raw file](https://github.com/pmem/fio/blob/9d77f0335a32f0234fa0ca817ada46eab93851aa/examples/librpma_gpspm-server.fio#L13)):*
> ```
> thread
> 
> # The server side spawns a single thread, opens and registers the whole
> ```

XXX

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/47)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[options.c, line 1887 at r1](https://reviewable.io/reviews/pmem/fio/47#-MLSCBxU6E50Njwbfrv8:-MLSDKYF8hT1OvRz68CX:b-c4cqlp) ([raw file](https://github.com/pmem/fio/blob/9d77f0335a32f0234fa0ca817ada46eab93851aa/options.c#L1887)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Here we have an engine specific help which we can provide for our engines.
</blockquote></details>

Yes, and I added `in GPSPM mode`

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/47)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[Makefile, line 109 at r1](https://reviewable.io/reviews/pmem/fio/47#-MLSC0yE5QUWYxEFFXyL:-MLSEItxBfdHMUtzhwFI:b-896fix) ([raw file](https://github.com/pmem/fio/blob/9d77f0335a32f0234fa0ca817ada46eab93851aa/Makefile#L109)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are overwriting these two variables.
</blockquote></details>

Done.
___
*[examples/librpma_gpspm-client.fio, line 13 at r1](https://reviewable.io/reviews/pmem/fio/47#-MLSCw_cCbKR6V3fYy0s:-MLSDnKn2lHaxq-udhXD:b-896fix) ([raw file](https://github.com/pmem/fio/blob/9d77f0335a32f0234fa0ca817ada46eab93851aa/examples/librpma_gpspm-client.fio#L13)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add XXX here. We are going to see how it comes up.
</blockquote></details>

Done.
___
*[examples/librpma_gpspm-server.fio, line 13 at r1](https://reviewable.io/reviews/pmem/fio/47#-MLSD0_S80qyRQs_dumE:-MLSDvoaBw86W6MgINUR:b-896fix) ([raw file](https://github.com/pmem/fio/blob/9d77f0335a32f0234fa0ca817ada46eab93851aa/examples/librpma_gpspm-server.fio#L13)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

XXX
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/47)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[examples/librpma_gpspm-client.fio, line 24 at r2](https://reviewable.io/reviews/pmem/fio/47#-MLSFwLTCeA3ocSJrsv3:-MLSFwLTCeA3ocSJrsv4:b-uilbn3) ([raw file](https://github.com/pmem/fio/blob/16e7c950657d056a4b7f7fa946077af5e388d94e/examples/librpma_gpspm-client.fio#L24)):*
> ```
> iodepth=[total # of ious]
> iodepth_batch_submit=[# of ious to submit at once]
> readwrite=[read/randread]
> ```

what about write? ;)
readwrite=[read/write/randread/randwrite/readwrite/rw]

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/47)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[examples/librpma_gpspm-client.fio, line 24 at r2](https://reviewable.io/reviews/pmem/fio/47#-MLSFwLTCeA3ocSJrsv3:-MLSHewD2QePkcApcAvU:bf7hjgx) ([raw file](https://github.com/pmem/fio/blob/16e7c950657d056a4b7f7fa946077af5e388d94e/examples/librpma_gpspm-client.fio#L24)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

what about write? ;)
readwrite=[read/write/randread/randwrite/readwrite/rw]
</blockquote></details>

Done.

@osalyk It should be fixed also in https://github.com/pmem/fio/pull/43 in examples/librpma-client.fio

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/47#-:-MLSIQPC0sl3EvGMGGt1:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[examples/librpma_gpspm-client.fio, line 24 at r2](https://reviewable.io/reviews/pmem/fio/47#-MLSFwLTCeA3ocSJrsv3:-MLSIEUp3n8vZFyezhIh:b2nhlkv) ([raw file](https://github.com/pmem/fio/blob/16e7c950657d056a4b7f7fa946077af5e388d94e/examples/librpma_gpspm-client.fio#L24)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.

@osalyk It should be fixed also in https://github.com/pmem/fio/pull/43 in examples/librpma-client.fio
</blockquote></details>

Ok

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/47#-:-MLSY-iY8ZhXjWd-N1Sq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
