### PR TITLE
rpma: add rpma_mr_advise calling

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/258)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/258)* status: 0 of 1 files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/258)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/fio/258#-MjdBbcT6YIp1yo_U07L:-MjdBbcT6YIp1yo_U07M:b92l1du) (no related file):*
Do **NOT** merge !!!

The current version of librpma installed in the docker images of this repo does not support the rpma_mr_advise() API:
https://github.com/ldorau/fio/runs/3609414673

---
*[a discussion](https://reviewable.io/reviews/pmem/fio/258#-MjdCGBeBAJ0xhJyEgzS:-MjdCGBeBAJ0xhJyEgzT:b-9gdfrj) (no related file):*
The CI builds haven't been started, because they were disabled. I have just enabled them.
@ewanglong please re-push this PR:
```
$ git commit -a --amend --reset-author --no-edit
$ git push ...
```

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/258)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/fio/258#-MjdBbcT6YIp1yo_U07L:-MjdIx-C8u5FFLoVLWUU:b-4oqtc9) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Do **NOT** merge !!!

The current version of librpma installed in the docker images of this repo does not support the rpma_mr_advise() API:
https://github.com/ldorau/fio/runs/3609414673
</blockquote></details>

The fix for this issue is ready now: https://github.com/pmem/fio/pull/259

This PR reqiures:
- [x] https://github.com/pmem/fio/pull/259

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/258)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/258)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/258#-MjdCGBeBAJ0xhJyEgzS:-MjlQYEv5kboh7HU-w3P:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The CI builds haven't been started, because they were disabled. I have just enabled them.
@ewanglong please re-push this PR:
```
$ git commit -a --amend --reset-author --no-edit
$ git push ...
```

</blockquote></details>

Done.

---
___
*[engines/librpma_fio.c, line 943 at r1](https://reviewable.io/reviews/pmem/fio/258#-MjiLxLK-HJnCN-K5QB8:-MjlTvi96DQ0eTHYNqrW:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e4723695ad017abf840502637185fb9c4f23e971/engines/librpma_fio.c#L943)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE

Ref: https://manpages.debian.org/testing/libibverbs-dev/ibv_advise_mr.3.en.html
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 944 at r1](https://reviewable.io/reviews/pmem/fio/258#-MjiM3rn4HiYZ60tR70N:-MjlTw9aERq941dikd-X:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e4723695ad017abf840502637185fb9c4f23e971/engines/librpma_fio.c#L944)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

IBV_ADVISE_MR_FLAG_FLUSH

Ref: https://manpages.debian.org/testing/libibverbs-dev/ibv_advise_mr.3.en.html
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 948 at r1](https://reviewable.io/reviews/pmem/fio/258#-MjiMVlbBCzig1Mmwd4x:-MjlVU8b4ZbwRZa2TPVQ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e4723695ad017abf840502637185fb9c4f23e971/engines/librpma_fio.c#L948)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
goto err_mr_dereg;
```
</blockquote></details>

Done.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/258)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/258#-MjdBbcT6YIp1yo_U07L:-MjlXfk5EZg3f4GOIVaE:b32w0x) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The fix for this issue is ready now: https://github.com/pmem/fio/pull/259

This PR reqiures:
- [ ] https://github.com/pmem/fio/pull/259
</blockquote></details>

OK

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/258)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/258#-:-MjmglyZ9SBmPXsYgCBU:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/258#-:-Mjmm9Eo61F3ICmLigXX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
