### PR TITLE
rpma: setup, open_file and close_file hooks impl

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #10 

This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/9)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9)* status: 0 of 1 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/pmem/fio/9#-MJTkVw_DXbhaJvf1e5W:-MJTkVwa0lN9xsRkpdcK:b-1ee3dg) (no related file):*
Please note I had to rebase my change on to #10.

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9)* status: 0 of 1 files reviewed, all discussions resolved

___
*[engines/librpma.c, line 185 at r3](https://reviewable.io/reviews/pmem/fio/9#-MJUNAuP1T4cfgoUoRob:-MJUNAuP1T4cfgoUoRoc:b-3guswi) ([raw file](https://github.com/pmem/fio/blob/364344f7db78a126b70a359885e368a91658e11e/engines/librpma.c#L185)):*
> ```C
> 	if (add_file(td, "server", 0, 0) != 1)
> 		goto err_conn_disconnect;
> ```

When no `filename` is provided FIO generates a file name on its own. So at this point, we have one file guaranteed.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 240 at r5](https://reviewable.io/reviews/pmem/fio/9#-MJWdnoJEXMys59DD3F1:-MJWdnoJEXMys59DD3F2:badbl8v) ([raw file](https://github.com/pmem/fio/blob/03123142e0a25b272a18b177253e831315e3d91a/engines/librpma.c#L240)):*
> ```
> 	if ((ret = rpma_mr_remote_get_size(cd->server_mr, &f->real_file_size)))
> 		return ret;
> 	return 0;
> ```
return rpma_mr_remote_get_size(cd->server_mr, &f->real_file_size); ?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma.c, line 240 at r5](https://reviewable.io/reviews/pmem/fio/9#-MJWdnoJEXMys59DD3F1:-MJWgLBZ8UwuCrzVnlDx:b-epj4ij) ([raw file](https://github.com/pmem/fio/blob/03123142e0a25b272a18b177253e831315e3d91a/engines/librpma.c#L240)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

> ```
> 	if ((ret = rpma_mr_remote_get_size(cd->server_mr, &f->real_file_size)))
> 		return ret;
> 	return 0;
> ```
return rpma_mr_remote_get_size(cd->server_mr, &f->real_file_size); ?
</blockquote></details>

Yeah... now it should make more sense.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[engines/librpma.c, line 78 at r7](https://reviewable.io/reviews/pmem/fio/9#-MJWguqr2Yi5f9ZsaVbZ:-MJWguqr2Yi5f9ZsaVb_:b9hcncx) ([raw file](https://github.com/pmem/fio/blob/044a35bc998428b419bd27e853db8e23dce9ce44/engines/librpma.c#L78)):*
> ```
> 	/* an RPMA connection to the server */
> 	struct rpma_conn *conn;
> ```

Duplicated

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9#-:-MJWj-sIAQe2T-yrY7Zt:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 170 at r7](https://reviewable.io/reviews/pmem/fio/9#-MJWl2Nb9GhUhUnlW4ZN:-MJWl2NcC5HfFrb5qAL9:b-bxi07j) ([raw file](https://github.com/pmem/fio/blob/044a35bc998428b419bd27e853db8e23dce9ce44/engines/librpma.c#L170)):*
> ```
> get connections private data send from the server
> ```

get the connection's private data sent from the server
___
*[engines/librpma.c, line 171 at r8](https://reviewable.io/reviews/pmem/fio/9#-MJWmuOz1E0Ahm3jz7oS:-MJWmuOz1E0Ahm3jz7oT:b-9fvn9i) ([raw file](https://github.com/pmem/fio/blob/05fdf21a69ee78e652c82ad483de939397d3301d/engines/librpma.c#L171)):*
> ```
> create server's memory representation 
> ```

create the server's memory representation

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 29 at r9](https://reviewable.io/reviews/pmem/fio/9#-MJWpSITEIZfsgGN7qoS:-MJWpSITEIZfsgGN7qoT:b-nvad7) ([raw file](https://github.com/pmem/fio/blob/a5ff5fc3a067405400e2a1dd54400601610b9aa7/engines/librpma.c#L29)):*
> ```
> struct example_common_data {
> ```

Is it a good name here? `example_...` ?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 78 at r7](https://reviewable.io/reviews/pmem/fio/9#-MJWguqr2Yi5f9ZsaVbZ:-MJWp7oQ98NOmQofN46k:b-896fix) ([raw file](https://github.com/pmem/fio/blob/044a35bc998428b419bd27e853db8e23dce9ce44/engines/librpma.c#L78)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	/* an RPMA connection to the server */
> 	struct rpma_conn *conn;
> ```

Duplicated
</blockquote></details>

Done.
___
*[engines/librpma.c, line 170 at r7](https://reviewable.io/reviews/pmem/fio/9#-MJWl2Nb9GhUhUnlW4ZN:-MJWpFG-3kx6JSr2XIVz:b-896fix) ([raw file](https://github.com/pmem/fio/blob/044a35bc998428b419bd27e853db8e23dce9ce44/engines/librpma.c#L170)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> get connections private data send from the server
> ```

get the connection's private data sent from the server
</blockquote></details>

Done.
___
*[engines/librpma.c, line 171 at r8](https://reviewable.io/reviews/pmem/fio/9#-MJWmuOz1E0Ahm3jz7oS:-MJWpI6u18-pms8QW0aj:b-896fix) ([raw file](https://github.com/pmem/fio/blob/05fdf21a69ee78e652c82ad483de939397d3301d/engines/librpma.c#L171)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> create server's memory representation 
> ```

create the server's memory representation 
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 170 at r7](https://reviewable.io/reviews/pmem/fio/9#-MJWl2Nb9GhUhUnlW4ZN:-MJWpiyj84kMNFLrQPoV:bb7og0t) ([raw file](https://github.com/pmem/fio/blob/044a35bc998428b419bd27e853db8e23dce9ce44/engines/librpma.c#L170)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sent

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 29 at r9](https://reviewable.io/reviews/pmem/fio/9#-MJWpSITEIZfsgGN7qoS:-MJWpiws0IhZEPSCRKg6:b8iejgv) ([raw file](https://github.com/pmem/fio/blob/a5ff5fc3a067405400e2a1dd54400601610b9aa7/engines/librpma.c#L29)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> struct example_common_data {
> ```

Is it a good name here? `example_...` ?
</blockquote></details>

Yes. The name is so bad so it makes us delete it soon. ;-)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9#-:-MJWr0890oH1AJXVYoAM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 253 at r11](https://reviewable.io/reviews/pmem/fio/9#-MJWtEBl7yLOU0n_bKI-:-MJWtEBl7yLOU0n_bKI0:bl4k4j7) ([raw file](https://github.com/pmem/fio/blob/bdd7eb9ee9dbb17b87b7544fbbda406bc81137f7/engines/librpma.c#L253)):*
> ```
> client_close_file
> ```
do we need this?
seems to be unnecessary

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma.c, line 253 at r11](https://reviewable.io/reviews/pmem/fio/9#-MJWtEBl7yLOU0n_bKI-:-MJWuYiRDLu18YSVlJnK:b-ra4mqm) ([raw file](https://github.com/pmem/fio/blob/bdd7eb9ee9dbb17b87b7544fbbda406bc81137f7/engines/librpma.c#L253)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> client_close_file
> ```
do we need this?
seems to be unnecessary
</blockquote></details>

The same as open_file. We have to make sure fio won't try to do this on its own.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 253 at r11](https://reviewable.io/reviews/pmem/fio/9#-MJWtEBl7yLOU0n_bKI-:-MJWvXIYCP-6QLXPhhCr:b-o83b1) ([raw file](https://github.com/pmem/fio/blob/bdd7eb9ee9dbb17b87b7544fbbda406bc81137f7/engines/librpma.c#L253)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The same as open_file. We have to make sure fio won't try to do this on its own.
</blockquote></details>

no, this is an optional call and there is no alternative/generic close_file

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma.c, line 253 at r11](https://reviewable.io/reviews/pmem/fio/9#-MJWtEBl7yLOU0n_bKI-:-MJWyLhwCCbJ3Z1WqCdx:blgoyyg) ([raw file](https://github.com/pmem/fio/blob/bdd7eb9ee9dbb17b87b7544fbbda406bc81137f7/engines/librpma.c#L253)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

no, this is an optional call and there is no alternative/generic close_file
</blockquote></details>

Sometimes it is called unconditionally when the file is just open.
I think we can consider removing it when the debugger will confirm it is obsolete.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/9#-:-MJWydFnBy5H8J1Dq4EU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
