### PR TITLE
rpma: server op scaffolding

### PR DESCRIPTION
**Pull request by janekmi**
Required:

- [x] #8

This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/6)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 136 at r1](https://reviewable.io/reviews/pmem/fio/6#-MJPwdbA2URe-nGXakUk:-MJPwdbB9V1VkAmIpu4u:brytao9) ([raw file](https://github.com/pmem/fio/blob/b35a0f5effc0b7dbdfd335c1a9541326cf3795e4/engines/librpma.c#L136)):*
> ```
> 8080
> ```
8080 is one of the default HTTP ports. Let's do something not used anywhere else e.g. 7204

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 136 at r1](https://reviewable.io/reviews/pmem/fio/6#-MJPwdbA2URe-nGXakUk:-MJQEyPmEKwVmplYwWV4:b48uijx) ([raw file](https://github.com/pmem/fio/blob/b35a0f5effc0b7dbdfd335c1a9541326cf3795e4/engines/librpma.c#L136)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 8080
> ```
8080 is one of the default HTTP ports. Let's do something not used anywhere else e.g. 7204
</blockquote></details>

or 8765 ;-)
___
*[engines/librpma.c, line 157 at r1](https://reviewable.io/reviews/pmem/fio/6#-MJQFImd6ej5t9EQ7haP:-MJQFImd6ej5t9EQ7haQ:b-eq8p30) ([raw file](https://github.com/pmem/fio/blob/b35a0f5effc0b7dbdfd335c1a9541326cf3795e4/engines/librpma.c#L157)):*
> ```
> endpoing
> ```

endpoint

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 157 at r1](https://reviewable.io/reviews/pmem/fio/6#-MJQFImd6ej5t9EQ7haP:-MJQu4_O1CPFeS8CI-_L:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b35a0f5effc0b7dbdfd335c1a9541326cf3795e4/engines/librpma.c#L157)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> endpoing
> ```

endpoint
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6#-:-MJQvpCA-fPPDgYPgudz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma.c, line 136 at r1](https://reviewable.io/reviews/pmem/fio/6#-MJPwdbA2URe-nGXakUk:-MJR0Y_V5BlO634B5NlE:bb6l1gk) ([raw file](https://github.com/pmem/fio/blob/b35a0f5effc0b7dbdfd335c1a9541326cf3795e4/engines/librpma.c#L136)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

or 8765 ;-)
</blockquote></details>

7204
___
*[engines/librpma.c, line 157 at r3](https://reviewable.io/reviews/pmem/fio/6#-MJR0cgbCUO2IyU9F3ZC:-MJR0cgbCUO2IyU9F3ZD:b-eq8p30) ([raw file](https://github.com/pmem/fio/blob/225549692c1f9fd48a96bf96d2fb6e1dd785249f/engines/librpma.c#L157)):*
> ```
> endpoing
> ```

endpoint

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma.c, line 136 at r1](https://reviewable.io/reviews/pmem/fio/6#-MJPwdbA2URe-nGXakUk:-MJQwtubClvMoLN7cSom:b-ahotzq) ([raw file](https://github.com/pmem/fio/blob/b35a0f5effc0b7dbdfd335c1a9541326cf3795e4/engines/librpma.c#L136)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

or 8765 ;-)
</blockquote></details>

7204 is better
___
*[engines/librpma.c, line 177 at r2](https://reviewable.io/reviews/pmem/fio/6#-MJQx3Mh1DaN_tm8QRot:-MJQx3Mh1DaN_tm8QRou:b-d4jcuq) ([raw file](https://github.com/pmem/fio/blob/5c8adf76f34570486d690ea7d2269f47112cce88/engines/librpma.c#L177)):*
> ```
> server_post_init
> ```
shall we use post_init to register memory?
___
*[engines/librpma.c, line 210 at r2](https://reviewable.io/reviews/pmem/fio/6#-MJQyDndBMi_NqMp1KL7:-MJQyDndBMi_NqMp1KL8:b-36ikb) ([raw file](https://github.com/pmem/fio/blob/6ce453d8e254fa0c74c74fd0ff3cd9cae6f886b7/engines/librpma.c#L210)):*
> ```
> server_cleanup
> ```
mr_dereg
close_connection ??

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 136 at r1](https://reviewable.io/reviews/pmem/fio/6#-MJPwdbA2URe-nGXakUk:-MJR0oDL26GLVAf7m_Vf:b-sxttqa) ([raw file](https://github.com/pmem/fio/blob/b35a0f5effc0b7dbdfd335c1a9541326cf3795e4/engines/librpma.c#L136)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

7204 is better
</blockquote></details>

much better

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 136 at r1](https://reviewable.io/reviews/pmem/fio/6#-MJPwdbA2URe-nGXakUk:-MJRASe_5su5s1fbWk6b:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b35a0f5effc0b7dbdfd335c1a9541326cf3795e4/engines/librpma.c#L136)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

much better
</blockquote></details>

Done.
___
*[engines/librpma.c, line 177 at r2](https://reviewable.io/reviews/pmem/fio/6#-MJQx3Mh1DaN_tm8QRot:-MJRAhxiDqnAGjr6FSI8:bhyy5i4) ([raw file](https://github.com/pmem/fio/blob/5c8adf76f34570486d690ea7d2269f47112cce88/engines/librpma.c#L177)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> server_post_init
> ```
shall we use post_init to register memory?
</blockquote></details>

I think registering file's memory falls naturally into `open_file()` hook the same as unregistering the memory should go to `close_file()`.
___
*[engines/librpma.c, line 210 at r2](https://reviewable.io/reviews/pmem/fio/6#-MJQyDndBMi_NqMp1KL7:-MJRBF85EFN_ugnWXczp:b-mx15o4) ([raw file](https://github.com/pmem/fio/blob/6ce453d8e254fa0c74c74fd0ff3cd9cae6f886b7/engines/librpma.c#L210)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> server_cleanup
> ```
mr_dereg
close_connection ??
</blockquote></details>

Opening and closing a connection is done in `queue()` hook.
The connection has to be closed before closing a file.
___
*[engines/librpma.c, line 157 at r3](https://reviewable.io/reviews/pmem/fio/6#-MJR0cgbCUO2IyU9F3ZC:-MJRAXM82-6LfUnoHMVj:b-896fix) ([raw file](https://github.com/pmem/fio/blob/225549692c1f9fd48a96bf96d2fb6e1dd785249f/engines/librpma.c#L157)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> endpoing
> ```

endpoint
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 136 at r1](https://reviewable.io/reviews/pmem/fio/6#-MJPwdbA2URe-nGXakUk:-MJRCLV52t4dxljZ0UW9:b-8nyi3w) ([raw file](https://github.com/pmem/fio/blob/b35a0f5effc0b7dbdfd335c1a9541326cf3795e4/engines/librpma.c#L136)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done
___
*[engines/librpma.c, line 157 at r3](https://reviewable.io/reviews/pmem/fio/6#-MJR0cgbCUO2IyU9F3ZC:-MJRCNsA4a1kas1tfGi9:b-8nyi3w) ([raw file](https://github.com/pmem/fio/blob/225549692c1f9fd48a96bf96d2fb6e1dd785249f/engines/librpma.c#L157)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 136 at r1](https://reviewable.io/reviews/pmem/fio/6#-MJPwdbA2URe-nGXakUk:-MJRDD14-bb5g2xnw9-j:b-uisbfk) ([raw file](https://github.com/pmem/fio/blob/b35a0f5effc0b7dbdfd335c1a9541326cf3795e4/engines/librpma.c#L136)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not done
</blockquote></details>

Sorry, I forgot to push. ;-)
___
*[engines/librpma.c, line 157 at r3](https://reviewable.io/reviews/pmem/fio/6#-MJR0cgbCUO2IyU9F3ZC:-MJRDMde67q3Ag7-1hbn:b3kqx) ([raw file](https://github.com/pmem/fio/blob/225549692c1f9fd48a96bf96d2fb6e1dd785249f/engines/librpma.c#L157)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not done
</blockquote></details>

.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 177 at r2](https://reviewable.io/reviews/pmem/fio/6#-MJQx3Mh1DaN_tm8QRot:-MJRGY8uEnn6-xuVO6lc:btwib77) ([raw file](https://github.com/pmem/fio/blob/5c8adf76f34570486d690ea7d2269f47112cce88/engines/librpma.c#L177)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think registering file's memory falls naturally into `open_file()` hook the same as unregistering the memory should go to `close_file()`.
</blockquote></details>

I think about the same solution on both sides ...
___
*[engines/librpma.c, line 210 at r2](https://reviewable.io/reviews/pmem/fio/6#-MJQyDndBMi_NqMp1KL7:-MJRDUV987d07fCzg1LM:b-cvfq3k) ([raw file](https://github.com/pmem/fio/blob/6ce453d8e254fa0c74c74fd0ff3cd9cae6f886b7/engines/librpma.c#L210)):*
> queue()
???

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[engines/librpma.c, line 177 at r2](https://reviewable.io/reviews/pmem/fio/6#-MJQx3Mh1DaN_tm8QRot:-MK59URV41Tcn9oU3SrV:b-896fix) ([raw file](https://github.com/pmem/fio/blob/5c8adf76f34570486d690ea7d2269f47112cce88/engines/librpma.c#L177)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I think about the same solution on both sides ...
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6#-:-MK5AOVy0XOhQVnYvBhK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
