### PR TITLE
rpma: download archive of librpma using curl

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/209)

### CODE REVIEW

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/209#-:-MTeLY828vqwLL5wsO-S:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/209)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[ci/actions-install-librpma.sh, line 10 at r1](https://reviewable.io/reviews/pmem/fio/209#-MTeLZSOEU0OJQrx6ZL-:-MTeLZSOEU0OJQrx6ZL0:b-7ha7gl) ([raw file](https://github.com/pmem/fio/blob/ef88325133d18f614c08543400a75d53e53e0444/ci/actions-install-librpma.sh#L10)):*
> ```Shell
> 
> # install librpma
> curl -L --output $ZIP_FILE https://github.com/pmem/rpma/archive/${LIBRPMA_VERSION}.zip
> ```

wget?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/209)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @janekmi)

___
*[ci/actions-install-librpma.sh, line 10 at r1](https://reviewable.io/reviews/pmem/fio/209#-MTeLZSOEU0OJQrx6ZL-:-MTeQ5yZAzyWmICHjnrX:bb6un1j) ([raw file](https://github.com/pmem/fio/blob/ef88325133d18f614c08543400a75d53e53e0444/ci/actions-install-librpma.sh#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

wget?
</blockquote></details>

Done

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/209#-:-MTeRWGhA8B-CFwVAoTM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/209#-:-MTeTAW2CV8VXsqKYIcy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/209)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
