### PR TITLE
rpma: add GitHub Actions and retire Travis

### PR DESCRIPTION
**Pull request by ldorau**
See: https://github.com/axboe/fio/pull/1157

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/193)

### CODE REVIEW

**Comment by ldorau** [comment]
The GHA build of this PR is here: https://github.com/ldorau/fio/actions/runs/512419328

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 9 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/193#-:-MRzN1d71trw3nUKwKVF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/193)* status: all files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/pmem/fio/193#-MS-hbGT4twffYoP8bW0:-MS-hbGT4twffYoP8bW1:b51pew7) (no related file):*
I'm afraid the librpma engines are not built yet, I do not know why, I will investigate it tomorrow. 

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/193)* status: all files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/pmem/fio/193#-MS-hbGT4twffYoP8bW0:-MS1eIeu8elxhDW9g8Yv:b70r4na) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I'm afraid the librpma engines are not built yet, I do not know why, I will investigate it tomorrow. 
</blockquote></details>

libpmem is not detected by fio for unknown reason ...

---

**Review by ldorau — COMMENTED** [review]
The GHA build of this PR is here: https://github.com/ldorau/fio/actions/runs/514654493

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/193#-:-MS2BG05DIJzjgNa_BFv:b-std0se)* status: 5 of 12 files reviewed, all discussions resolved (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/193#-MS-hbGT4twffYoP8bW0:-MS2BAWVBU_foy26jX4c:b-886gsx) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

libpmem is not detected by fio for unknown reason ...
</blockquote></details>

Fixed

---

**Review by janekmi — COMMENTED** [review]
> Reviewed 3 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/193)* status: 8 of 12 files reviewed, all discussions resolved (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
> Reviewed 4 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/193)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[ci/actions-build.sh, line 29 at r5](https://reviewable.io/reviews/pmem/fio/193#-MS2phi44g8U4Qc_GAxt:-MS2phi44g8U4Qc_GAxu:b-pstrgg) ([raw file](https://github.com/pmem/fio/blob/a6eacab5aab69386a51640b79531e9f29ddb0d0e/ci/actions-build.sh#L29)):*
> ```Shell
>                             "--enable-cuda"
>                             "--enable-libiscsi"
>                         )
> ```

Indentation is messed up here. But NVM.
___
*[ci/actions-install.sh, line 30 at r5](https://reviewable.io/reviews/pmem/fio/193#-MS2ppaV7leJbb1_ZeI_:-MS2ppaV7leJbb1_ZeIa:b-l6i80y) ([raw file](https://github.com/pmem/fio/blob/a6eacab5aab69386a51640b79531e9f29ddb0d0e/ci/actions-install.sh#L30)):*
> ```Shell
>     )
>     if [ "${CI_EVENT}" == "schedule" ]; then
> 	pkgs+=(
> ```

A single tab among spaces.
___
*[ci/actions-install.sh, line 59 at r5](https://reviewable.io/reviews/pmem/fio/193#-MS2ptAnEtp1IRYUDf3S:-MS2ptAnEtp1IRYUDf3T:b3kqx) ([raw file](https://github.com/pmem/fio/blob/a6eacab5aab69386a51640b79531e9f29ddb0d0e/ci/actions-install.sh#L59)):*
> ```Shell
>                     nvidia-cuda-dev
> 		)
> 	    fi
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/193)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[ci/actions-build.sh, line 29 at r5](https://reviewable.io/reviews/pmem/fio/193#-MS2phi44g8U4Qc_GAxt:-MS2utvz1OdpDVIpUin7:b-6gs2si) ([raw file](https://github.com/pmem/fio/blob/a6eacab5aab69386a51640b79531e9f29ddb0d0e/ci/actions-build.sh#L29)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Indentation is messed up here. But NVM.
</blockquote></details>

Why? What is wrong here?
___
*[ci/actions-install.sh, line 30 at r5](https://reviewable.io/reviews/pmem/fio/193#-MS2ppaV7leJbb1_ZeI_:-MS2vLBn6DfXTHg0Q45o:b-886gsx) ([raw file](https://github.com/pmem/fio/blob/a6eacab5aab69386a51640b79531e9f29ddb0d0e/ci/actions-install.sh#L30)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A single tab among spaces.
</blockquote></details>

Fixed
___
*[ci/actions-install.sh, line 59 at r5](https://reviewable.io/reviews/pmem/fio/193#-MS2ptAnEtp1IRYUDf3S:-MS2vMV08S0wbdD_WTQj:b-886gsx) ([raw file](https://github.com/pmem/fio/blob/a6eacab5aab69386a51640b79531e9f29ddb0d0e/ci/actions-install.sh#L59)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Fixed

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/193)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/193)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[ci/actions-build.sh, line 29 at r5](https://reviewable.io/reviews/pmem/fio/193#-MS2phi44g8U4Qc_GAxt:-MS30ISo43SeENNxldZB:b-4q2qgl) ([raw file](https://github.com/pmem/fio/blob/a6eacab5aab69386a51640b79531e9f29ddb0d0e/ci/actions-build.sh#L29)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why? What is wrong here?
</blockquote></details>

I saw tabs here. Mirage. ;-)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/193#-:-MS39xSY3_z7EP5dUAuf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
