### PR TITLE
rpma: rename bindname/hostname -> serverip

### PR DESCRIPTION
**Pull request by grom72**
config file: rename bindname/hostname -> serverip
config structure variable hostname/bindname -> server_ip

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/148)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/148)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_common.c, line 676 at r1](https://reviewable.io/reviews/pmem/fio/148#-MRPsFoO89uLoGcqvRU4:-MRPsFoO89uLoGcqvRU5:b-d9r6f5) ([raw file](https://github.com/pmem/fio/blob/2b55b068fbcfe40c5eb0683a57b6b1e3e135c0c4/engines/librpma_common.c#L676)):*
> ```
> port to: listen
> ```

`port to listen` - no `:`

**Review by ldorau — APPROVED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/148)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_common.c, line 676 at r1](https://reviewable.io/reviews/pmem/fio/148#-MRPsFoO89uLoGcqvRU4:-MRPsFoO89uLoGcqvRU5:b-d9r6f5) ([raw file](https://github.com/pmem/fio/blob/2b55b068fbcfe40c5eb0683a57b6b1e3e135c0c4/engines/librpma_common.c#L676)):*
> ```
> port to: listen
> ```

`port to listen` - no `:`

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/148)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72)

___
*[engines/librpma_common.h, line 43 at r1](https://reviewable.io/reviews/pmem/fio/148#-MRPynAh9sZmL1igBW2i:-MRPynAh9sZmL1igBW2j:bps6wrv) ([raw file](https://github.com/pmem/fio/blob/3866cad65ad5bffa9dbc8f66d79025f5c76a6630/engines/librpma_common.h#L43)):*
> ```objc
> };
> 
> /* clients' common */
> ```

This comment is still valid. Please return it.
___
*[engines/librpma_common.h, line 201 at r1](https://reviewable.io/reviews/pmem/fio/148#-MRPyxLu3JXoBqwhoHAq:-MRPyxLu3JXoBqwhoHAr:b-z97p3w) ([raw file](https://github.com/pmem/fio/blob/2b55b068fbcfe40c5eb0683a57b6b1e3e135c0c4/engines/librpma_common.h#L201)):*
> ```objc
> };
> 
> extern struct fio_option librpma_common_fio_options[];
> ```

common-common part is above client's common. Please move it there.
___
*[engines/librpma_common.c, line 676 at r1](https://reviewable.io/reviews/pmem/fio/148#-MRPzWJe3E_SS9V_Gm_E:-MRPzWJe3E_SS9V_Gm_F:b8z0aob) ([raw file](https://github.com/pmem/fio/blob/2b55b068fbcfe40c5eb0683a57b6b1e3e135c0c4/engines/librpma_common.c#L676)):*
> ```C
> 		.type	= FIO_OPT_STR_STORE,
> 		.off1	= offsetof(struct librpma_common_options, port),
> 		.help	= "port to: listen on for incoming connections/connect to for outgoing connection",
> ```

TBH it is more and more `base_port`. To be addressed by another PR.
___
*[engines/librpma_common.c, line 684 at r1](https://reviewable.io/reviews/pmem/fio/148#-MRPzEro9n3IoRcM4l9a:-MRPzEro9n3IoRcM4l9b:b-oh2rn1) ([raw file](https://github.com/pmem/fio/blob/2b55b068fbcfe40c5eb0683a57b6b1e3e135c0c4/engines/librpma_common.c#L684)):*
> ```C
> 		.name	= NULL,
> 	},
> };
> ```

Please move to the beginning of this file. Having it between client and server makes no sense.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/148)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_common.h, line 43 at r1](https://reviewable.io/reviews/pmem/fio/148#-MRPynAh9sZmL1igBW2i:-MRQ38_89GrHwZ8ArtI9:b-896fix) ([raw file](https://github.com/pmem/fio/blob/3866cad65ad5bffa9dbc8f66d79025f5c76a6630/engines/librpma_common.h#L43)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This comment is still valid. Please return it.
</blockquote></details>

Done.
___
*[engines/librpma_common.h, line 201 at r1](https://reviewable.io/reviews/pmem/fio/148#-MRPyxLu3JXoBqwhoHAq:-MRQ36SU4YbkmmpjuGls:b-896fix) ([raw file](https://github.com/pmem/fio/blob/2b55b068fbcfe40c5eb0683a57b6b1e3e135c0c4/engines/librpma_common.h#L201)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

common-common part is above client's common. Please move it there.
</blockquote></details>

Done.
___
*[engines/librpma_common.c, line 684 at r1](https://reviewable.io/reviews/pmem/fio/148#-MRPzEro9n3IoRcM4l9a:-MRQ35SbBIA5vnMZpdE7:b-896fix) ([raw file](https://github.com/pmem/fio/blob/2b55b068fbcfe40c5eb0683a57b6b1e3e135c0c4/engines/librpma_common.c#L684)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please move to the beginning of this file. Having it between client and server makes no sense.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/148)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[engines/librpma_common.h, line 76 at r2](https://reviewable.io/reviews/pmem/fio/148#-MRQ3w3c7unWiY7czWIZ:-MRQ3w3d1kd8Abd4pTAO:bd3p1i7) ([raw file](https://github.com/pmem/fio/blob/62f18829e5de641ae1974ba04fba49ef1129362b/engines/librpma_common.h#L76)):*
> ```objc
> void librpma_common_free(struct librpma_common_mem *mem);
> 
> extern struct fio_option librpma_common_fio_options[];
> ```

This array is related to the struct above. I recommend keeping them together.
___
*[engines/librpma_common.c, line 30 at r2](https://reviewable.io/reviews/pmem/fio/148#-MRQ4kv33GUAjfNuT9xZ:-MRQ4kv33GUAjfNuT9x_:b-h8rigq) ([raw file](https://github.com/pmem/fio/blob/62f18829e5de641ae1974ba04fba49ef1129362b/engines/librpma_common.c#L30)):*
> ```C
> 		.off1	= offsetof(struct librpma_common_options, server_ip),
> 		.help	= "IP address the server is listening on",
> 		.def    = "",
> ```

Tab instead of spaces.
___
*[engines/librpma_common.c, line 40 at r2](https://reviewable.io/reviews/pmem/fio/148#-MRQ4nOQAW9g0_rllFLk:-MRQ4nOQAW9g0_rllFLl:b3kqx) ([raw file](https://github.com/pmem/fio/blob/62f18829e5de641ae1974ba04fba49ef1129362b/engines/librpma_common.c#L40)):*
> ```C
> 		.off1	= offsetof(struct librpma_common_options, port),
> 		.help	= "port the server is listening on",
> 		.def    = "7204",
> ```

.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/148)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_common.c, line 30 at r2](https://reviewable.io/reviews/pmem/fio/148#-MRQ4kv33GUAjfNuT9xZ:-MRQ6UvS4s0F0jLVUgew:b-896fix) ([raw file](https://github.com/pmem/fio/blob/62f18829e5de641ae1974ba04fba49ef1129362b/engines/librpma_common.c#L30)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Tab instead of spaces.
</blockquote></details>

Done.
___
*[engines/librpma_common.c, line 40 at r2](https://reviewable.io/reviews/pmem/fio/148#-MRQ4nOQAW9g0_rllFLk:-MRQ6V_n7WsrssymXVB_:b-896fix) ([raw file](https://github.com/pmem/fio/blob/62f18829e5de641ae1974ba04fba49ef1129362b/engines/librpma_common.c#L40)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/148)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/148#-:-MRQ83E8AjCUmn81BMsc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/148)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/148#-:-MRQCcm47-NCnH4KSkFJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
