### PR TITLE
rpma: replace libpmem with libpmem2 in librpma_gpspm

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/279)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: 0 of 7 files reviewed, 2 unresolved discussions (waiting on @haichangsi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/279#-Mx4DtjqBLlsDVD7RPaJ:-Mx4Dtjr4rsRGG_t6YRY:b-ujmq67) (no related file):*
Rebase please

---
*[a discussion](https://reviewable.io/reviews/pmem/fio/279#-Mx4DvxG1jf206NZMlLg:-Mx4DvxG1jf206NZMlLh:bywfzz) (no related file):*
We have to wait with merging this patch until libpmem2 is included (as a package) in most of popular Linux distributions, so that fio does not require building and installing whole PMDK from sources (@lplewa @kilobyte).

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[engines/librpma_gpspm.c, line 598 at r1](https://reviewable.io/reviews/pmem/fio/279#-Mx4F6Mt24SXOinqfO3l:-Mx4F6Mu-SW5XyZCf9yg:bvafvqk) ([raw file](https://github.com/pmem/fio/blob/c290aa981a8e26a6ec4fd067882d3f301f6fdc10/engines/librpma_gpspm.c#L598)):*
> ```C
> 	if (IS_NOT_THE_LAST_MESSAGE(flush_req)) {
> 		op_ptr = csd->ws_ptr + flush_req->offset;
> 		persist = pmem2_get_persist_fn(td->map);
> ```

What is `td->map` ? Where and when have you set it?

AFAIK you have saved the mapping in the different structure:

```c
void librpma_fio_free(struct librpma_fio_mem *mem)
{
	if (mem->size_mmap) {
		pmem2_map_delete(&mem->map);
....
```



_Code quote:_
```C
(td->map);
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/279#-Mx4DvxG1jf206NZMlLg:-Mx4dh542_BrGr-NapaD:bfugqxw) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We have to wait with merging this patch until libpmem2 is included (as a package) in most of popular Linux distributions, so that fio does not require building and installing whole PMDK from sources (@lplewa @kilobyte).
</blockquote></details>

@haichangsi Another solution can be applied - please change this PR so that fio could use libpmem if libpmem2 is not available in OS.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)

___
*[engines/librpma_gpspm.c, line 598 at r1](https://reviewable.io/reviews/pmem/fio/279#-MyHhAwD9gq_VAwEkaiy:-MyHhAwE16iw8NnHLtqL:bx61w9c) ([raw file](https://github.com/pmem/fio/blob/c290aa981a8e26a6ec4fd067882d3f301f6fdc10/engines/librpma_gpspm.c#L598)):*
> ```C
> 	if (IS_NOT_THE_LAST_MESSAGE(flush_req)) {
> 		op_ptr = csd->ws_ptr + flush_req->offset;
> 		persist = pmem2_get_persist_fn(td->map);
> ```

`server_qe_process()` is not a good place to call `pmem2_get_persist_fn` (`pmem2_get_persist_fn` should be called only once)



_Code quote:_
```C
pmem2_get_persist_fn(
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/279#-Mx4DtjqBLlsDVD7RPaJ:-MyJU4TJ6Twnvsu4-Gnq:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/fio/279#-Mx4DvxG1jf206NZMlLg:-MyJU4Gy3gc2_5LsMiTZ:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@haichangsi Another solution can be applied - please change this PR so that fio could use libpmem if libpmem2 is not available in OS.
</blockquote></details>

Done.

---
___
*[engines/librpma_gpspm.c, line 598 at r1](https://reviewable.io/reviews/pmem/fio/279#-Mx4F6Mt24SXOinqfO3l:-MyJTteA4kHga_yfWSab:ba3vv3) ([raw file](https://github.com/pmem/fio/blob/c290aa981a8e26a6ec4fd067882d3f301f6fdc10/engines/librpma_gpspm.c#L598)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What is `td->map` ? Where and when have you set it?

AFAIK you have saved the mapping in the different structure:

```c
void librpma_fio_free(struct librpma_fio_mem *mem)
{
	if (mem->size_mmap) {
		pmem2_map_delete(&mem->map);
....
```

</blockquote></details>

It was just an idea to avoid passing struct librpma_fio_mem. Done.
___
*[engines/librpma_gpspm.c, line 598 at r1](https://reviewable.io/reviews/pmem/fio/279#-MyHhAwD9gq_VAwEkaiy:-MyJU34r3Hhnki2XdJqp:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c290aa981a8e26a6ec4fd067882d3f301f6fdc10/engines/librpma_gpspm.c#L598)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`server_qe_process()` is not a good place to call `pmem2_get_persist_fn` (`pmem2_get_persist_fn` should be called only once)
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @haichangsi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/279#-Mx4DtjqBLlsDVD7RPaJ:-MyMv7SG1VYzqx88CKKZ:b-r2olrn) (no related file):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Rebase again please.

---
___
*[engines/librpma_gpspm.c, line 611 at r3](https://reviewable.io/reviews/pmem/fio/279#-MyMuwrPEyU2uXvEzojf:-MyMuwrPEyU2uXvEzojg:b-jdpnkd) ([raw file](https://github.com/pmem/fio/blob/80f140fc36d43e800d994713490548438a6877fa/engines/librpma_gpspm.c#L611)):*
> ```C
> 	if (IS_NOT_THE_LAST_MESSAGE(flush_req)) {
> 		op_ptr = csd->ws_ptr + flush_req->offset;
> #ifdef CONFIG_LIBPMEM2_INSTALLED	
> ```

please remove white characters at the end



_Code quote:_
```C
LED··
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 4 of 9 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[engines/librpma_gpspm.c, line 598 at r1](https://reviewable.io/reviews/pmem/fio/279#-Mx4F6Mt24SXOinqfO3l:-MyMwopc-c1y9Dw74tcl:bno969i) ([raw file](https://github.com/pmem/fio/blob/c290aa981a8e26a6ec4fd067882d3f301f6fdc10/engines/librpma_gpspm.c#L598)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

It was just an idea to avoid passing struct librpma_fio_mem. Done.
</blockquote></details>

It is OK now.

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/279#-Mx4DtjqBLlsDVD7RPaJ:-MyMxLLI36CJo5YtSJcU:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase again please.
</blockquote></details>

Done.

---
___
*[engines/librpma_gpspm.c, line 611 at r3](https://reviewable.io/reviews/pmem/fio/279#-MyMuwrPEyU2uXvEzojf:-MyMxKO6EBgoBR4wC21C:b-896fix) ([raw file](https://github.com/pmem/fio/blob/80f140fc36d43e800d994713490548438a6877fa/engines/librpma_gpspm.c#L611)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

please remove white characters at the end
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279#-:-MyMx_yw24U8w550_-fl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279#-:-MyNIt4v1xW800j2SvpX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/279#-MyNQT7WDYlzTi6d6YMS:-MyNQT7X07Ez9EC94tzT:b-zeix6e) (no related file):*
Is it so that ```pmem_persist``` has the same parameters? 
Can we use the same function pointer in both cases?

---

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/fio/279#-MyNQT7WDYlzTi6d6YMS:-MyQmqhN-tFqpJNUWHOC:b-o9kiov) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Is it so that ```pmem_persist``` has the same parameters? 
Can we use the same function pointer in both cases?

</blockquote></details>

Yes, they have the same parameters, but `pmem_persist` is NOT of the `pmem2_persist_fn` type - `pmem2_persist_fn` is only libpmem2 type, so you would have to add two `#else` to use the same pointer in both cases:

https://github.com/ldorau/fio/commit/0feeaf88142d30bd9c9341ec2947f1a68c1d774b

I'm not sure it's worth. We can leave it as is for me.

---
___
*[engines/librpma_gpspm.c, line 412 at r4](https://reviewable.io/reviews/pmem/fio/279#-MyNQuh79w5dh-TKliLq:-MyQnfVw96RwB6Vwre2Y:byq4l2z) ([raw file](https://github.com/pmem/fio/blob/1e0cf6c72d8bb6d8082dc62e8b9408044e0e97e4/engines/librpma_gpspm.c#L412)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

#ifdef CONFIG_LIBPMEM2_INSTALLED
	/* get libpmem2 persist function from pmem2_map */
	sd->persist = pmem2_get_persist_fn(csd->mem.map);
#else
	sd->persist = pmem_persist;
#endif
</blockquote></details>

@grom72  It is not enough. You would have to add also this:
```c
#ifdef CONFIG_LIBPMEM2_INSTALLED
	/* libpmem2 persist function from pmem2_map */
	pmem2_persist_fn persist;
#else
	void (*persist)(const void *addr, size_t len);
#endif
```

I'm not sure it's worth. We can leave it as is for me.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[engines/librpma_gpspm.c, line 412 at r4](https://reviewable.io/reviews/pmem/fio/279#-MyNQuh79w5dh-TKliLq:-MyQokZe2QAh9db744H3:b-dmvjbs) ([raw file](https://github.com/pmem/fio/blob/1e0cf6c72d8bb6d8082dc62e8b9408044e0e97e4/engines/librpma_gpspm.c#L412)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72  It is not enough. You would have to add also this:
```c
#ifdef CONFIG_LIBPMEM2_INSTALLED
	/* libpmem2 persist function from pmem2_map */
	pmem2_persist_fn persist;
#else
	void (*persist)(const void *addr, size_t len);
#endif
```

I'm not sure it's worth. We can leave it as is for me.
</blockquote></details>

Or even:

```c
typedef void (*pmem_persist_fn)(const void *addr, size_t len);

#ifdef CONFIG_LIBPMEM2_INSTALLED
	/* libpmem2 persist function from pmem2_map */
	pmem2_persist_fn persist;
#else
	pmem_persist_fn persist;
#endif
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/279#-MyNQT7WDYlzTi6d6YMS:-MyQwm5GCkitsLR2M8Uo:bip9htq) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, they have the same parameters, but `pmem_persist` is NOT of the `pmem2_persist_fn` type - `pmem2_persist_fn` is only libpmem2 type, so you would have to add two `#else` to use the same pointer in both cases:

https://github.com/ldorau/fio/commit/0feeaf88142d30bd9c9341ec2947f1a68c1d774b

I'm not sure it's worth. We can leave it as is for me.

</blockquote></details>

```
typedef void (*librpma_fio_persist_fn)(const void *ptr, size_t size);

struct server_data {
	...
	librpma_fio_persist_fnpersist;
};
```

```
#ifdef CONFIG_LIBPMEM2_INSTALLED
/* get libpmem2 persist function from pmem2_map */
	sd->persist = pmem2_get_persist_fn(csd->mem.map);
#else
	sd->persist = pmem_persist;
#endif
```

```
	sd->persist(op_ptr, flush_req->length);
```



_Suggestion (from engines/librpma_gpspm.c):_
```C
#ifdef CONFIG_LIBPMEM2_INSTALLED
		sd->persist(op_ptr, flush_req->length);
#else
		pmem_persist(op_ptr, flush_req->length);
#endif
```

---

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/279#-MyNQT7WDYlzTi6d6YMS:-MyQzkyM2akUHw454Adx:b-qpv3gk) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
typedef void (*librpma_fio_persist_fn)(const void *ptr, size_t size);

struct server_data {
	...
	librpma_fio_persist_fnpersist;
};
```

```
#ifdef CONFIG_LIBPMEM2_INSTALLED
/* get libpmem2 persist function from pmem2_map */
	sd->persist = pmem2_get_persist_fn(csd->mem.map);
#else
	sd->persist = pmem_persist;
#endif
```

```
	sd->persist(op_ptr, flush_req->length);
```


</blockquote></details>

OK, that's fine.

---

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/279#-MyNQT7WDYlzTi6d6YMS:-MyR-0dxBBwr5cIYNoIL:b-w1ou53) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, that's fine.
</blockquote></details>

@haichangsi Could you apply this change?

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[engines/librpma_gpspm.c, line 382 at r4](https://reviewable.io/reviews/pmem/fio/279#-MyR7K41104rX_h03m89:-MyR7K41104rX_h03m8A:b-i502j6) ([raw file](https://github.com/pmem/fio/blob/1e0cf6c72d8bb6d8082dc62e8b9408044e0e97e4/engines/librpma_gpspm.c#L382)):*
> ```C
> 
> #ifdef CONFIG_LIBPMEM2_INSTALLED
> 	/* libpmem2 persist function from pmem2_map */
> ```

```c
	/* libpmem/libpmem2 persist function */
	librpma_fio_persist_fn persist;
```

and before above:

```c
typedef void (*librpma_fio_persist_fn)(const void *ptr, size_t size);
```



_Code quote:_
```C
#ifdef CONFIG_LIBPMEM2_INSTALLED
	/* libpmem2 persist function from pmem2_map */
	pmem2_persist_fn persist;
#endif
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/279#-MyNQT7WDYlzTi6d6YMS:-MyRdMaO42iSifLL91IF:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@haichangsi Could you apply this change?
</blockquote></details>

Done.

---
___
*[engines/librpma_gpspm.c, line 382 at r4](https://reviewable.io/reviews/pmem/fio/279#-MyR7K41104rX_h03m89:-MyRdJLQ2DHRa_9RrnDQ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1e0cf6c72d8bb6d8082dc62e8b9408044e0e97e4/engines/librpma_gpspm.c#L382)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
	/* libpmem/libpmem2 persist function */
	librpma_fio_persist_fn persist;
```

and before above:

```c
typedef void (*librpma_fio_persist_fn)(const void *ptr, size_t size);
```

</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279#-:-MyRkw8pDuKbKW0YIfnL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279#-:-MyRuTkRBk0tSSNtDlOy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 9 files at r2, 6 of 7 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
