### PR TITLE
rpma: gpspm: rework the commit flow to similar as APM has

### PR DESCRIPTION
**Pull request by janekmi**
XXX probably the message buffer handling is not correct with only this change.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/87)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/87#-:-MQBqcnm4yvHkesvJ3Bb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/87)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 497 at r1](https://reviewable.io/reviews/pmem/fio/87#-MQBzFME6qTqkl8WOiL8:-MQBzFME6qTqkl8WOiL9:b-9izdxz) ([raw file](https://github.com/pmem/fio/blob/201251a3205ccb8ad49048526b9f8076411a75c2/engines/librpma_gpspm.c#L497)):*
> ```
> (void *)(uintptr_t)io_u->index);
> ```

Where is it used?

I see only that completions of failed operations are not handled:

```
	/* if io_us has completed with an error */
	if (cmpl.op_status != IBV_WC_SUCCESS) {
		td->error = cmpl.op_status;
		return -1;
	}
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/87)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 616 at r1](https://reviewable.io/reviews/pmem/fio/87#-MQC-f1P00M2JIfVBW20:-MQC-f1P00M2JIfVBW21:bvyli54) ([raw file](https://github.com/pmem/fio/blob/201251a3205ccb8ad49048526b9f8076411a75c2/engines/librpma_gpspm.c#L616)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 			/* when the io_u's are sequential and
> 			 * the current io_u is not the last one and
> 			 * the next one is also a write operation
> 			 * the flush can be postponed by one io_u and
> 			 * cover all of them which build a continuous
> 			 * sequence
> 			 */
> ```
</details>


Full sentence please:

```
/* (no text here)
 * Full
 * sentence.
 */
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/87)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/87)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 497 at r1](https://reviewable.io/reviews/pmem/fio/87#-MQBzFME6qTqkl8WOiL8:-MQC0JUC4pEgy05NujFm:b-uzkzzh) ([raw file](https://github.com/pmem/fio/blob/201251a3205ccb8ad49048526b9f8076411a75c2/engines/librpma_gpspm.c#L497)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> (void *)(uintptr_t)io_u->index);
> ```

Where is it used?

I see only that completions of failed operations are not handled:

```
	/* if io_us has completed with an error */
	if (cmpl.op_status != IBV_WC_SUCCESS) {
		td->error = cmpl.op_status;
		return -1;
	}
```
</blockquote></details>

It is not used. Probably we could map this failed completions with particular io_u. But currently, it is not done anyway.
___
*[engines/librpma_gpspm.c, line 616 at r1](https://reviewable.io/reviews/pmem/fio/87#-MQC-f1P00M2JIfVBW20:-MQC1IJq0MdFPTeabpNj:b-896fix) ([raw file](https://github.com/pmem/fio/blob/201251a3205ccb8ad49048526b9f8076411a75c2/engines/librpma_gpspm.c#L616)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 			/* when the io_u's are sequential and
> 			 * the current io_u is not the last one and
> 			 * the next one is also a write operation
> 			 * the flush can be postponed by one io_u and
> 			 * cover all of them which build a continuous
> 			 * sequence
> 			 */
> ```

Full sentence please:

```
/* (no text here)
 * Full
 * sentence.
 */
```

</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/87)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/87#-:-MQC3ILM6opoA9iDHvZJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
