### PR TITLE
rpma: implement server_init

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #50

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/53)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/53)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 224 at r1](https://reviewable.io/reviews/pmem/fio/53#-MLixwqR3Ta9N-E4wgtb:-MLixwqR3Ta9N-E4wgtc:betzbw1) ([raw file](https://github.com/pmem/fio/blob/6b13147004c07ec3dc5603f84a1231c727d5fe95/engines/librpma_gpspm.c#L224)):*
> ```C
> 	/* configure logging thresholds to see more details */
> 	rpma_log_set_threshold(RPMA_LOG_THRESHOLD, RPMA_LOG_LEVEL_DEBUG);
> 	rpma_log_set_threshold(RPMA_LOG_THRESHOLD_AUX, RPMA_LOG_LEVEL_DEBUG);
> ```

These are the log levels we have used for the basic librpma engine. How come?
___
*[engines/librpma_gpspm.c, line 233 at r1](https://reviewable.io/reviews/pmem/fio/53#-MLiyF5p9V2aVebLhpI2:-MLiyF5p9V2aVebLhpI3:b-ufxsff) ([raw file](https://github.com/pmem/fio/blob/6b13147004c07ec3dc5603f84a1231c727d5fe95/engines/librpma_gpspm.c#L233)):*
> ```C
> 	}
> 
> 	/* obtain an IBV context for a remote IP address */
> ```

I believe on the server's side we should assume the IP address is a local one.
___
*[engines/librpma_gpspm.c, line 263 at r1](https://reviewable.io/reviews/pmem/fio/53#-MLiyVKqEif9X0D11SIT:-MLiyVKqEif9X0D11SIU:b-veuq88) ([raw file](https://github.com/pmem/fio/blob/6b13147004c07ec3dc5603f84a1231c727d5fe95/engines/librpma_gpspm.c#L263)):*
> ```C
> 	 * connections the server will handle and...
> 	 */
> 	td->o.iodepth = o->num_conns;
> ```

Not true. Get rid of the assignment.
___
*[engines/librpma_gpspm.c, line 268 at r1](https://reviewable.io/reviews/pmem/fio/53#-MLiycjW9U-xpeM1AzGs:-MLiycjW9U-xpeM1AzGt:b3kqx) ([raw file](https://github.com/pmem/fio/blob/6b13147004c07ec3dc5603f84a1231c727d5fe95/engines/librpma_gpspm.c#L268)):*
> ```C
> 	 * ... a single io_u size has to be equal to the assumed workspace size.
> 	 */
> 	td->o.max_bs[DDIR_READ] = td->o.size;
> ```

.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/53)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_gpspm.c, line 263 at r1](https://reviewable.io/reviews/pmem/fio/53#-MLiyVKqEif9X0D11SIT:-MLkqhG48CbeFnTBw5w-:b-u7hiy2) ([raw file](https://github.com/pmem/fio/blob/6b13147004c07ec3dc5603f84a1231c727d5fe95/engines/librpma_gpspm.c#L263)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not true. Get rid of the assignment.
</blockquote></details>

iodpeth will represent the number of flushes to be buffered by RNIC/librpma before they are consumed by the server with persist() (or flush()/drain() in the future).

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/53)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 224 at r1](https://reviewable.io/reviews/pmem/fio/53#-MLixwqR3Ta9N-E4wgtb:-MLlBO8g0LosoLQ3Tl0K:b-wjn1em) ([raw file](https://github.com/pmem/fio/blob/6b13147004c07ec3dc5603f84a1231c727d5fe95/engines/librpma_gpspm.c#L224)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

These are the log levels we have used for the basic librpma engine. How come?
</blockquote></details>

I do not understand the question: " How come?"
I have corrected the error levels. 
___
*[engines/librpma_gpspm.c, line 233 at r1](https://reviewable.io/reviews/pmem/fio/53#-MLiyF5p9V2aVebLhpI2:-MLlBeHFBGLhcd--XXSO:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6b13147004c07ec3dc5603f84a1231c727d5fe95/engines/librpma_gpspm.c#L233)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I believe on the server's side we should assume the IP address is a local one.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 263 at r1](https://reviewable.io/reviews/pmem/fio/53#-MLiyVKqEif9X0D11SIT:-MLlBr677Vwe8drCI1kX:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6b13147004c07ec3dc5603f84a1231c727d5fe95/engines/librpma_gpspm.c#L263)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

iodpeth will represent the number of flushes to be buffered by RNIC/librpma before they are consumed by the server with persist() (or flush()/drain() in the future).
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 268 at r1](https://reviewable.io/reviews/pmem/fio/53#-MLiycjW9U-xpeM1AzGs:-MLlBtDHBkVn4gvGX7vH:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6b13147004c07ec3dc5603f84a1231c727d5fe95/engines/librpma_gpspm.c#L268)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/53)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/53)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/53#-:-MLmPkVF6hRBOBY_7zkI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
OK for now
I have some questions that I move to #55

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/53#-:-MLmdb5oDJaFFkHdTPJM:b-s200qj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/53#-:-MLme4Cs6PBKwMbjLRGe:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
