### PR TITLE
rpma: remove several goto from server shutdown related routines

### PR DESCRIPTION
**Pull request by grom72**
Several goto seems to be unnecessary

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/44)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/44)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/44)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma.c, line 1056 at r1](https://reviewable.io/reviews/pmem/fio/44#-MKofK-Z-6f5QIZECyCs:-MKofK-Z-6f5QIZECyCt:bw6cvkt) ([raw file](https://github.com/pmem/fio/blob/9a9a6b067baabc50aa48d7abe15572eeae325100/engines/librpma.c#L1056)):*
> ```
> 	}
> 	else if (event != RPMA_CONN_CLOSED) {
> ```

in one line please:

```
	} else if (event != RPMA_CONN_CLOSED) {
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/44)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 1056 at r1](https://reviewable.io/reviews/pmem/fio/44#-MKofK-Z-6f5QIZECyCs:-MKopPuE6gA3dSKyGSTd:b-896fix) ([raw file](https://github.com/pmem/fio/blob/9a9a6b067baabc50aa48d7abe15572eeae325100/engines/librpma.c#L1056)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	}
> 	else if (event != RPMA_CONN_CLOSED) {
> ```

in one line please:

```
	} else if (event != RPMA_CONN_CLOSED) {
```
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/44)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/44)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[engines/librpma.c, line 1084 at r2](https://reviewable.io/reviews/pmem/fio/44#-MKsRzubAfj9nUGyYZri:-MKsRzubAfj9nUGyYZrj:b-j5jj3d) ([raw file](https://github.com/pmem/fio/blob/1b01e0db461d486e07a228dfad53f68b4c080d54/engines/librpma.c#L1084)):*
> ```
> if( NULL
> ```

`if (NULL`
___
*[engines/librpma.c, line 1084 at r2](https://reviewable.io/reviews/pmem/fio/44#-MKsSs5t9FfNMtiJ9oUX:-MKsSs5t9FfNMtiJ9oUY:b-lthegz) ([raw file](https://github.com/pmem/fio/blob/1b01e0db461d486e07a228dfad53f68b4c080d54/engines/librpma.c#L1084)):*
> ```
> if( NULL == (conns[i] = server_conn_establish(td)))
> ```

It reduces the readability of the code. One line less and less readable code - is it worth it?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/44)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 1084 at r2](https://reviewable.io/reviews/pmem/fio/44#-MKsRzubAfj9nUGyYZri:-ML7_tkoEHE-uUHfP0YX:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1b01e0db461d486e07a228dfad53f68b4c080d54/engines/librpma.c#L1084)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> if( NULL
> ```

`if (NULL`
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/44)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/44)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/44#-:-ML7bYmd4ab0KegbNPYk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/44)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/44#-:-MLCEPpg6BHrrlFrJEzm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/44)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/44#-:-MLhGiyxCjzdjYqIZQgg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
