### PR TITLE
implement client_init

### PR DESCRIPTION
**Pull request by osalyk**
- [x] #52

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/54)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/54)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_gpspm.c, line 186 at r1](https://reviewable.io/reviews/pmem/fio/54#-MLmRfNu2ZOBIJSdkxWG:-MLmRfNu2ZOBIJSdkxWH:b-6jnzok) ([raw file](https://github.com/pmem/fio/blob/782630d14264bc53967fda0cf2c4b58d22f6bd18/engines/librpma_gpspm.c#L186)):*
> ```C
> 		rpma_td_verror(td, ret, "rpma_conn_cfg_delete");
> 		goto err_peer_delete;
> 	}
> ```

You can not delete `cfg` before using it.
___
*[engines/librpma_gpspm.c, line 209 at r1](https://reviewable.io/reviews/pmem/fio/54#-MLmSPGN-_DqN89PB9xV:-MLmSPGN-_DqN89PB9xW:b-ezkvom) ([raw file](https://github.com/pmem/fio/blob/782630d14264bc53967fda0cf2c4b58d22f6bd18/engines/librpma_gpspm.c#L209)):*
> ```C
> 		log_err(
> 			"rpma_conn_next_event returned an unexptected event: (%s != RPMA_CONN_ESTABLISHED)\n",
> 			rpma_utils_conn_event_2str(event));
> ```

We have to set `ret` value here e.g. `ret = -1` otherwise the `init()` hook may end up with success unintentionally.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/54)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 186 at r1](https://reviewable.io/reviews/pmem/fio/54#-MLmRfNu2ZOBIJSdkxWG:-MLmXQpQBhQLctn9Dxai:b-896fix) ([raw file](https://github.com/pmem/fio/blob/782630d14264bc53967fda0cf2c4b58d22f6bd18/engines/librpma_gpspm.c#L186)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can not delete `cfg` before using it.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 209 at r1](https://reviewable.io/reviews/pmem/fio/54#-MLmSPGN-_DqN89PB9xV:-MLmXkHO2qp0gBl5sA7X:b-896fix) ([raw file](https://github.com/pmem/fio/blob/782630d14264bc53967fda0cf2c4b58d22f6bd18/engines/librpma_gpspm.c#L209)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We have to set `ret` value here e.g. `ret = -1` otherwise the `init()` hook may end up with success unintentionally.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/54#-:-MLmbn-S1soyp5BWQlLO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/54#-:-MLmd--b4u7l_O91aA0V:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
