### PR TITLE
rpma: common: get_io_u_index() skip

### PR DESCRIPTION
**Pull request by janekmi**
- get_io_u_index() is getting three possible return values:
    - (-1) - on error
    - ( 0) - skip
    - ( 1) - on success
- client_getevents_process() fix by taking into account
  the mentioned above possibility

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/150)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_common.c, line 575 at r1](https://reviewable.io/reviews/pmem/fio/150#-MRPteIFBz5o0L3EW-k3:-MRPteIFBz5o0L3EW-k4:bxrl2f5) ([raw file](https://github.com/pmem/fio/blob/90389412b1b44affda767c86522e16c5b121592a/engines/librpma_common.c#L575)):*
> ```
> 	if (cmpl.op == RPMA_OP_SEND)
> 		++ccd->op_send_completed;
> ```
what about other completions that previously force "return 0"?
___
*[engines/librpma_gpspm.c, line 317 at r1](https://reviewable.io/reviews/pmem/fio/150#-MRPsNt345AoMzo5ra_y:-MRPsNt345AoMzo5ra_z:b3xpw2w) ([raw file](https://github.com/pmem/fio/blob/90389412b1b44affda767c86522e16c5b121592a/engines/librpma_gpspm.c#L317)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> /*
>  * RETURN VALUE
>  * - ( 1) - on success
>  * - ( 0) - skip
>  * - (-1) - on error
>  */
> ```
</details>

to be added to librpma_common.h

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_common.c, line 575 at r1](https://reviewable.io/reviews/pmem/fio/150#-MRPteIFBz5o0L3EW-k3:-MRPu6wvCOe5FPP31I1w:b4vp9qq) ([raw file](https://github.com/pmem/fio/blob/90389412b1b44affda767c86522e16c5b121592a/engines/librpma_common.c#L575)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 	if (cmpl.op == RPMA_OP_SEND)
> 		++ccd->op_send_completed;
> ```
what about other completions that previously force "return 0"?
</blockquote></details>

the previous implementation was more user-friendly

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_common.c, line 575 at r1](https://reviewable.io/reviews/pmem/fio/150#-MRPteIFBz5o0L3EW-k3:-MRQ-Iuz8RTYawpbHDGH:bymd8st) ([raw file](https://github.com/pmem/fio/blob/90389412b1b44affda767c86522e16c5b121592a/engines/librpma_common.c#L575)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

the previous implementation was more user-friendly
</blockquote></details>

Completion is further validated by the `get_io_u_index()` function if it is required.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[engines/librpma_gpspm.c, line 317 at r1](https://reviewable.io/reviews/pmem/fio/150#-MRPsNt345AoMzo5ra_y:-MRQ-rX5759U7vJ3R8Fu:blcy8se) ([raw file](https://github.com/pmem/fio/blob/90389412b1b44affda767c86522e16c5b121592a/engines/librpma_gpspm.c#L317)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> /*
>  * RETURN VALUE
>  * - ( 1) - on success
>  * - ( 0) - skip
>  * - (-1) - on error
>  */
> ```
to be added to librpma_common.h
</blockquote></details>

Next to the function type definition or the function pointer field in the `struct librpma_common_client_data`?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_common.c, line 575 at r1](https://reviewable.io/reviews/pmem/fio/150#-MRPteIFBz5o0L3EW-k3:-MRQ1JRQBpOTyQalHIjT:b-annkb3) ([raw file](https://github.com/pmem/fio/blob/90389412b1b44affda767c86522e16c5b121592a/engines/librpma_common.c#L575)):*
> ```
> get_io_u_index
> ```
function name does not says that ...
___
*[engines/librpma_gpspm.c, line 317 at r1](https://reviewable.io/reviews/pmem/fio/150#-MRPsNt345AoMzo5ra_y:-MRQ1PKO8dFHMn0UBS7T:b2nign6) ([raw file](https://github.com/pmem/fio/blob/90389412b1b44affda767c86522e16c5b121592a/engines/librpma_gpspm.c#L317)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Next to the function type definition or the function pointer field in the `struct librpma_common_client_data`?
</blockquote></details>

yes

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[engines/librpma_common.c, line 575 at r1](https://reviewable.io/reviews/pmem/fio/150#-MRPteIFBz5o0L3EW-k3:-MRQ4yKZ6slYA3_9_uXX:bw54qa5) ([raw file](https://github.com/pmem/fio/blob/90389412b1b44affda767c86522e16c5b121592a/engines/librpma_common.c#L575)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> get_io_u_index
> ```
function name does not says that ...
</blockquote></details>

`getevents` does neither. xD
Besides, this is no how this game works. If you do not like the name you have to propose something.
___
*[engines/librpma_gpspm.c, line 317 at r1](https://reviewable.io/reviews/pmem/fio/150#-MRPsNt345AoMzo5ra_y:-MRQ5NjC93Aq-lMpB2CG:bpp6v3q) ([raw file](https://github.com/pmem/fio/blob/90389412b1b44affda767c86522e16c5b121592a/engines/librpma_gpspm.c#L317)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

yes
</blockquote></details>

Question: a OR b.
Answer: yes.

There is no point in putting this comment everywhere. It will get out of sync in on time.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_common.c, line 575 at r1](https://reviewable.io/reviews/pmem/fio/150#-MRPteIFBz5o0L3EW-k3:-MRQ6gHq09zmKb9toN2v:b-fgk4ea) ([raw file](https://github.com/pmem/fio/blob/90389412b1b44affda767c86522e16c5b121592a/engines/librpma_common.c#L575)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`getevents` does neither. xD
Besides, this is no how this game works. If you do not like the name you have to propose something.
</blockquote></details>

get_io_u_index is about getting index, not about completion handling.
completion handling was implemented in getevent_process
you could also compare apm and gpspm implementations
perhaps 
``` 
	if (cmpl->op != RPMA_OP_RECV)
		return 1;
``` 
is not needed inside ```get_io_u_index``` and shall be tested outside 
___
*[engines/librpma_gpspm.c, line 317 at r1](https://reviewable.io/reviews/pmem/fio/150#-MRPsNt345AoMzo5ra_y:-MRQ7cRiDul9JdRfO-nS:b-qshq47) ([raw file](https://github.com/pmem/fio/blob/90389412b1b44affda767c86522e16c5b121592a/engines/librpma_gpspm.c#L317)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Question: a OR b.
Answer: yes.

There is no point in putting this comment everywhere. It will get out of sync in on time.
</blockquote></details>

next to function type.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150#-:-MRQ8mOsBQjCbByJgl9t:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_common.c, line 398 at r2](https://reviewable.io/reviews/pmem/fio/150#-MRRKWSm60OPIDjdNAvs:-MRRKWSn6b4cyaio3Aq2:b1a2u66) ([raw file](https://github.com/pmem/fio/blob/348407e00e9e825dd575205804ce32b15f99aea7/engines/librpma_common.c#L398)):*
> ```
> 	if ((ret = ccd->get_io_u_index(&cmpl, &io_u_index)) != 1)
> 		goto err;
> ```

What do you need `ret` for? It is not used.
This should be enough:

```
	if (ccd->get_io_u_index(&cmpl, &io_u_index) != 1)
		goto err;
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_common.c, line 398 at r2](https://reviewable.io/reviews/pmem/fio/150#-MRRKWSm60OPIDjdNAvs:-MRU2xKN4reHtkzRYqRd:b-896fix) ([raw file](https://github.com/pmem/fio/blob/348407e00e9e825dd575205804ce32b15f99aea7/engines/librpma_common.c#L398)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	if ((ret = ccd->get_io_u_index(&cmpl, &io_u_index)) != 1)
> 		goto err;
> ```

What do you need `ret` for? It is not used.
This should be enough:

```
	if (ccd->get_io_u_index(&cmpl, &io_u_index) != 1)
		goto err;
```
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150#-:-MRU2yXD3McjCOsF0TH5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/150)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
