### PR TITLE
rpma: implement server_cleanup

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #50 
- [x] #53
- [x] #55

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/56)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/56)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 335 at r1](https://reviewable.io/reviews/pmem/fio/56#-MLmWvk-7CCQMrzWTLb5:-MLmWvk-7CCQMrzWTLb6:b-b63dks) ([raw file](https://github.com/pmem/fio/blob/2dc5a9896793f7e8187f8b80d0f06851df74c859/engines/librpma_gpspm.c#L335)):*
> ```
> td_max_bs
> ```
how do we calculate bs size?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/56)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_gpspm.c, line 335 at r1](https://reviewable.io/reviews/pmem/fio/56#-MLmWvk-7CCQMrzWTLb5:-MLmZImvCoPYxNH8Naac:bq3m3p2) ([raw file](https://github.com/pmem/fio/blob/2dc5a9896793f7e8187f8b80d0f06851df74c859/engines/librpma_gpspm.c#L335)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> td_max_bs
> ```
how do we calculate bs size?
</blockquote></details>

FIO allows setting a range for block size. During benchmarking the FIO will pick the block size for each particular io_u.
When you want to be prepared for handling any possible block size `td_max_bs()` allows getting the maximum possible value.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/56)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 387 at r1](https://reviewable.io/reviews/pmem/fio/56#-MLm_QXD5MBmlVsabYnr:-MLm_QXD5MBmlVsabYns:b-hyku8m) ([raw file](https://github.com/pmem/fio/blob/2dc5a9896793f7e8187f8b80d0f06851df74c859/engines/librpma_gpspm.c#L387)):*
> ```C
> 	/* free the peer */
> 	if ((ret = rpma_peer_delete(&sd->peer)))
> 		rpma_td_verror(td, ret, "rpma_peer_delete");
> ```

We have to free sd don't you think? ;-)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/56)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 335 at r1](https://reviewable.io/reviews/pmem/fio/56#-MLmWvk-7CCQMrzWTLb5:-MLmaQnf3dEWVfnAn8po:b-y1jnw0) ([raw file](https://github.com/pmem/fio/blob/2dc5a9896793f7e8187f8b80d0f06851df74c859/engines/librpma_gpspm.c#L335)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

FIO allows setting a range for block size. During benchmarking the FIO will pick the block size for each particular io_u.
When you want to be prepared for handling any possible block size `td_max_bs()` allows getting the maximum possible value.
</blockquote></details>

Done -> moved to proper PR

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/56)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 387 at r1](https://reviewable.io/reviews/pmem/fio/56#-MLm_QXD5MBmlVsabYnr:-MLmcYWk2nAfX2oECytM:b-7cbpyr) ([raw file](https://github.com/pmem/fio/blob/2dc5a9896793f7e8187f8b80d0f06851df74c859/engines/librpma_gpspm.c#L387)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We have to free sd don't you think? ;-)
</blockquote></details>

Right :-)

**Comment by ldorau** [comment]
Rebased

**Review by janekmi — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/56#-:-MLms-0B2viU9PJ2cAJi:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/56#-:-MLn9RK5AS70l4VUtqug:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/56)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/56)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/56#-MLvqZpA4Te7Nx7HFHAW:-MLvqZpBCQCBiJWCN_Cq:bw0l8hj) (no related file):*
Please undraft.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/56)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/56#-MLvqZpA4Te7Nx7HFHAW:-MLvql343g0WTY-vYCKa:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please undraft.
</blockquote></details>

Done.

---

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/56)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
