### PR TITLE
rpma: rename bindname/hostname -> serverip (rework)

### PR DESCRIPTION
**Pull request by janekmi**
**Note**: clients' options and servers' options can not be merged because a new server-specific option is planned. Sorry.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/154)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
no-problem - the alternative solution could be to have a common structure but ignore direct-write-to-pmem on the client side

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/154#-:-MRRCN9cBpaBSJXWiT1A:b-dc9e70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/154#-:-MRTQcKY-KvIhrNMHs6u:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/154#-:-MRTXEUP89ktsuMrsMmX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/154#-:-MRTq0F0AurCM43bEWeZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
@janekmi please rebase

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/154#-:-MRTyRSEDHeNR8as6qw8:b-f7mnt4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Comment by janekmi** [comment]
We have agreed offline to keep both servers' and clients' options together.

**Pull request closed without merging**
