### PR TITLE
rpma: fix client_io_write dst offset calculation

### PR DESCRIPTION
**Pull request by janekmi**
**Note**: The issue being fixed might affect bandwidth(threads) scalability.

@grom72 @ldorau @osalyk

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/72)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/72)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/72#-:-MPmbYuDBX7jX_yoFJrX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/72#-:-MPn9kml85dCNJ8ygVbG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Comment by janekmi** [comment]
This PR increases bandwidth between 3-17% for writing to PMEM.

compare

**Pull request merged**
