### PR TITLE
rpma: make sure fail is communicated to FIO

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/108)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/108#-:-MQqgOB16q1zyU-WipJm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/108)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 407 at r1](https://reviewable.io/reviews/pmem/fio/108#-MQuSPJW7io820eREds3:-MQuSPJW7io820eREds4:bj7yz0g) ([raw file](https://github.com/pmem/fio/blob/79786926ed5469881fc2fb4417cd33f749b9a817/engines/librpma_gpspm.c#L407)):*
> ```
> return (ret != 0 ? ret : 1);
> ```
return 1; //to indicate an error
___
*[engines/librpma_gpspm.c, line 1112 at r1](https://reviewable.io/reviews/pmem/fio/108#-MQuX_yJ8WeTbrUlJ_-o:-MQuX_yJ8WeTbrUlJ_-p:blsxbl7) ([raw file](https://github.com/pmem/fio/blob/79786926ed5469881fc2fb4417cd33f749b9a817/engines/librpma_gpspm.c#L1112)):*
> ```
> return (ret != 0 ? ret : 1);
> ```
.
___
*[engines/librpma_gpspm.c, line 1370 at r1](https://reviewable.io/reviews/pmem/fio/108#-MQuY5Oj-NQyeUA1Utq7:-MQuY5Oj-NQyeUA1Utq8:b1xq0yd) ([raw file](https://github.com/pmem/fio/blob/79786926ed5469881fc2fb4417cd33f749b9a817/engines/librpma_gpspm.c#L1370)):*
> ```
> (ret != 0 ? ret : 1);
> ```
.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/108)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 374 at r1](https://reviewable.io/reviews/pmem/fio/108#-MQu_5DrE-sFJsju0UjX:-MQu_5DrE-sFJsju0UjY:bdhariv) ([raw file](https://github.com/pmem/fio/blob/79786926ed5469881fc2fb4417cd33f749b9a817/engines/librpma.c#L374)):*
> ```
> return (ret != 0 ? ret : 1);
> ```
return 1;

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/108)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 374 at r1](https://reviewable.io/reviews/pmem/fio/108#-MQu_5DrE-sFJsju0UjX:-MQvmFgmEWlVktBkoHRn:b-896fix) ([raw file](https://github.com/pmem/fio/blob/79786926ed5469881fc2fb4417cd33f749b9a817/engines/librpma.c#L374)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> return (ret != 0 ? ret : 1);
> ```
return 1;
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 407 at r1](https://reviewable.io/reviews/pmem/fio/108#-MQuSPJW7io820eREds3:-MQvmIL5-qWVgzmma9TU:b-896fix) ([raw file](https://github.com/pmem/fio/blob/79786926ed5469881fc2fb4417cd33f749b9a817/engines/librpma_gpspm.c#L407)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> return (ret != 0 ? ret : 1);
> ```
return 1; //to indicate an error
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 1112 at r1](https://reviewable.io/reviews/pmem/fio/108#-MQuX_yJ8WeTbrUlJ_-o:-MQvmJOb4zKwPQ44sbnu:b-896fix) ([raw file](https://github.com/pmem/fio/blob/79786926ed5469881fc2fb4417cd33f749b9a817/engines/librpma_gpspm.c#L1112)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> return (ret != 0 ? ret : 1);
> ```
.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 1370 at r1](https://reviewable.io/reviews/pmem/fio/108#-MQuY5Oj-NQyeUA1Utq7:-MQvmKGZD3aeyIYmasUy:b-896fix) ([raw file](https://github.com/pmem/fio/blob/79786926ed5469881fc2fb4417cd33f749b9a817/engines/librpma_gpspm.c#L1370)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> (ret != 0 ? ret : 1);
> ```
.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/108#-:-MQvnE_e1DkVqhoqciEP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/108)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
