### PR TITLE
rpma: gpspm: enrich iodepth description in the server example file

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/92)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/92)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/librpma_gpspm-server.fio, line 21 at r1](https://reviewable.io/reviews/pmem/fio/92#-MQBwLwZ2nux0ItZzYAi:-MQBwLwZ2nux0ItZzYAj:b5eatfz) ([raw file](https://github.com/pmem/fio/blob/839b9fd6b96fb011393b2868ca1426ff1b1ce84e/examples/librpma_gpspm-server.fio#L21)):*
> ```
> iodepth=[total # of ious (in sync with the client side)]
> ```
shall this be configurable at all? 
do we plan to do this automatically when we have con_req_get_private_data() available?

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/92)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[examples/librpma_gpspm-server.fio, line 19 at r1](https://reviewable.io/reviews/pmem/fio/92#-MQC67S2Db8NIQfL3I10:-MQC67S2Db8NIQfL3I11:b-40f7x1) ([raw file](https://github.com/pmem/fio/blob/839b9fd6b96fb011393b2868ca1426ff1b1ce84e/examples/librpma_gpspm-server.fio#L19)):*
> ```
> to client-side 
> ```

`to the client side `

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/92)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[examples/librpma_gpspm-server.fio, line 19 at r1](https://reviewable.io/reviews/pmem/fio/92#-MQC67S2Db8NIQfL3I10:-MQCdE109FQ50HZAXrOJ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/839b9fd6b96fb011393b2868ca1426ff1b1ce84e/examples/librpma_gpspm-server.fio#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> to client-side 
> ```

`to the client side `
</blockquote></details>

Done.
___
*[examples/librpma_gpspm-server.fio, line 21 at r1](https://reviewable.io/reviews/pmem/fio/92#-MQBwLwZ2nux0ItZzYAi:-MQCcl3q7sEZaim2l80o:brrefdk) ([raw file](https://github.com/pmem/fio/blob/839b9fd6b96fb011393b2868ca1426ff1b1ce84e/examples/librpma_gpspm-server.fio#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> iodepth=[total # of ious (in sync with the client side)]
> ```
shall this be configurable at all? 
do we plan to do this automatically when we have con_req_get_private_data() available?
</blockquote></details>

Yes, we "plan". If we will have enough time for this.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/92)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/librpma_gpspm-server.fio, line 19 at r2](https://reviewable.io/reviews/pmem/fio/92#-MQCdnjL90KXFphVX0Uf:-MQCdnjM5wl1r-OuEJZZ:b-kwk9xi) ([raw file](https://github.com/pmem/fio/blob/142d309c9c685e974122b815e5c5fa0037e25d98/examples/librpma_gpspm-server.fio#L19)):*
> ```
> client-side
> ```

`client side`

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/92#-:-MQCfMX-3F9P2nvY1RNX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/92)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/librpma_gpspm-server.fio, line 19 at r2](https://reviewable.io/reviews/pmem/fio/92#-MQCdnjL90KXFphVX0Uf:-MQChbIR5ikKh_684mcf:b-896fix) ([raw file](https://github.com/pmem/fio/blob/142d309c9c685e974122b815e5c5fa0037e25d98/examples/librpma_gpspm-server.fio#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> client-side
> ```

`client side`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/92)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/92#-:-MQChgmrAxODPiNY2f6q:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
