### PR TITLE
rpma: common: client_commit

### PR DESCRIPTION
**Pull request by janekmi**
**Note**: This change silently introduces read for GPSPM async workloads which requires verification.

Requires:
- [x] #130
- [x] #131

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/132)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/132#-:-MR9mke-1h4IqnPSwGTL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/132)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/132)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[engines/librpma_common.c, line 365 at r2](https://reviewable.io/reviews/pmem/fio/132#-MRKN6EzDtR3lEfsvGDf:-MRKN6EzDtR3lEfsvGDg:b56q24g) ([raw file](https://github.com/pmem/fio/blob/e6aea6a7bd57797dcebaa84a11d8c3047641190f/engines/librpma_common.c#L365)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 		if (cmpl.op == RPMA_OP_SEND)
> 			++ccd->op_send_completed;
> 		else
> 			break;
> 	} while (1);
> ```
</details>

```
if (cmpl.op == RPMA_OP_SEND) {
	++ccd->op_send_completed;
        continue;
}
}while(cmpl.op_status == IBV_WC_SUCCESS)
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/132)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/132)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_common.c, line 365 at r2](https://reviewable.io/reviews/pmem/fio/132#-MRKN6EzDtR3lEfsvGDf:-MRKR5vq9JtnGIY3txoW:b-7uw81f) ([raw file](https://github.com/pmem/fio/blob/e6aea6a7bd57797dcebaa84a11d8c3047641190f/engines/librpma_common.c#L365)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 		if (cmpl.op == RPMA_OP_SEND)
> 			++ccd->op_send_completed;
> 		else
> 			break;
> 	} while (1);
> ```
```
if (cmpl.op == RPMA_OP_SEND) {
	++ccd->op_send_completed;
        continue;
}
}while(cmpl.op_status == IBV_WC_SUCCESS)
```
</blockquote></details>

We have already discussed this issue. `cmpl.op` will be in an undetermined state if `ret == RPMA_E_NO_COMPLETION`.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/132)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_common.c, line 365 at r2](https://reviewable.io/reviews/pmem/fio/132#-MRKN6EzDtR3lEfsvGDf:-MRKRsWQ4UOu73ec2W1s:b541yqf) ([raw file](https://github.com/pmem/fio/blob/e6aea6a7bd57797dcebaa84a11d8c3047641190f/engines/librpma_common.c#L365)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We have already discussed this issue. `cmpl.op` will be in an undetermined state if `ret == RPMA_E_NO_COMPLETION`.
</blockquote></details>

while(ret == RPMA_E_NO_COMPLETION || cmpl.op_status == IBV_WC_SUCCESS)

**Review by ldorau — APPROVED** [review]
:lgtm: please rebase

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/132#-:-MRKnxYuCaYkjRjbotrP:bdtt1ez)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/132)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
