### PR TITLE
rpma: common: servers' open_file and close_file scaffolding

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #140

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/142)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/142)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_common.c, line 536 at r1](https://reviewable.io/reviews/pmem/fio/142#-MRKvJA05PLk3r863PsH:-MRKvJA05PLk3r863PsI:b-bgi7hd) ([raw file](https://github.com/pmem/fio/blob/6579a8c4024610f5abde7e932184837560d02919/engines/librpma_common.c#L536)):*
> ```
> void librpma_common_server_cleanup(struct thread_data *td)
> ```

`librpma_common_server_cleanup()` can take `csd` (instead of `td`) as an argument (see below)
___
*[engines/librpma_gpspm.c, line 687 at r1](https://reviewable.io/reviews/pmem/fio/142#-MRKueJY3ZiGjpXToxC2:-MRKueJZ4dLaapE9qDeH:bzaczrm) ([raw file](https://github.com/pmem/fio/blob/6579a8c4024610f5abde7e932184837560d02919/engines/librpma_gpspm.c#L687)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 	if (csd == NULL)
> 		return;
> 	sd = csd->server_data;
> 	librpma_common_server_cleanup(td);
> 	if (sd == NULL)
> 		return;
> ```
</details>


It looks a bit strange. IMHO it is better:

`librpma_common_server_cleanup()` can take `csd` (instead of `td`) as an argument and then it could look like this:

```
	if (csd == NULL)
		return;

	librpma_common_server_cleanup(csd);

	sd = csd->server_data;
	if (sd == NULL)
		return;
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/142)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 687 at r1](https://reviewable.io/reviews/pmem/fio/142#-MRKueJY3ZiGjpXToxC2:-MRKzwvt0McOaxBh1poS:bgiidmw) ([raw file](https://github.com/pmem/fio/blob/6579a8c4024610f5abde7e932184837560d02919/engines/librpma_gpspm.c#L687)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	if (csd == NULL)
> 		return;
> 	sd = csd->server_data;
> 	librpma_common_server_cleanup(td);
> 	if (sd == NULL)
> 		return;
> ```

It looks a bit strange. IMHO it is better:

`librpma_common_server_cleanup()` can take `csd` (instead of `td`) as an argument and then it could look like this:

```
	if (csd == NULL)
		return;

	librpma_common_server_cleanup(csd);

	sd = csd->server_data;
	if (sd == NULL)
		return;
```
</blockquote></details>

I meant:

```
	if (csd == NULL)
		return;

	sd = csd->server_data;

	librpma_common_server_cleanup(csd);

	if (sd == NULL)
		return;
```

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/142#-:-MRL9LL6DOwydW8NYLrG:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_common.c, line 536 at r1](https://reviewable.io/reviews/pmem/fio/142#-MRKvJA05PLk3r863PsH:-MRL8K9n11rW-Ro69_Qc:bo252pv) ([raw file](https://github.com/pmem/fio/blob/6579a8c4024610f5abde7e932184837560d02919/engines/librpma_common.c#L536)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> void librpma_common_server_cleanup(struct thread_data *td)
> ```

`librpma_common_server_cleanup()` can take `csd` (instead of `td`) as an argument (see below)
</blockquote></details>

@ldorau - what about **td** in librpma_td() function call:
```
librpma_td_verror(td, ...
```
___
*[engines/librpma_gpspm.c, line 687 at r1](https://reviewable.io/reviews/pmem/fio/142#-MRKueJY3ZiGjpXToxC2:-MRL8slkAnxedoGG6eHT:b7yr9bs) ([raw file](https://github.com/pmem/fio/blob/6579a8c4024610f5abde7e932184837560d02919/engines/librpma_gpspm.c#L687)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I meant:

```
	if (csd == NULL)
		return;

	sd = csd->server_data;

	librpma_common_server_cleanup(csd);

	if (sd == NULL)
		return;
```
</blockquote></details>

td is needed inside for error handling

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/142)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_gpspm.c, line 690 at r1](https://reviewable.io/reviews/pmem/fio/142#-MRLn5GN8Qx4KAviJkoy:-MRLn5GN8Qx4KAviJkoz:bi4pf46) ([raw file](https://github.com/pmem/fio/blob/6579a8c4024610f5abde7e932184837560d02919/engines/librpma_gpspm.c#L690)):*
> ```
> 	/* rpma_mr_dereg(messaging buffer from DRAM) */
> 	if ((ret = rpma_mr_dereg(&sd->msg_mr)))
> 		librpma_td_verror(td, ret, "rpma_mr_dereg");
> ```
This should be done before librpma_common_server_cleanup() as the peer is deleted inside it.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/142)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_common.c, line 536 at r1](https://reviewable.io/reviews/pmem/fio/142#-MRKvJA05PLk3r863PsH:-MROTBBo6tnCxHihZiMT:bh7snz8) ([raw file](https://github.com/pmem/fio/blob/6579a8c4024610f5abde7e932184837560d02919/engines/librpma_common.c#L536)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@ldorau - what about **td** in librpma_td() function call:
```
librpma_td_verror(td, ...
```

</blockquote></details>

Right, didn't notice that ...
___
*[engines/librpma_gpspm.c, line 687 at r1](https://reviewable.io/reviews/pmem/fio/142#-MRKueJY3ZiGjpXToxC2:-MROTJDj2_wGPU3a7VuI:b-81la7d) ([raw file](https://github.com/pmem/fio/blob/6579a8c4024610f5abde7e932184837560d02919/engines/librpma_gpspm.c#L687)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

td is needed inside for error handling
</blockquote></details>

Right

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/142)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_gpspm.c, line 690 at r1](https://reviewable.io/reviews/pmem/fio/142#-MRLn5GN8Qx4KAviJkoy:-MROUSLh7l-BcjJeTkuQ:biv5ffy) ([raw file](https://github.com/pmem/fio/blob/6579a8c4024610f5abde7e932184837560d02919/engines/librpma_gpspm.c#L690)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 	/* rpma_mr_dereg(messaging buffer from DRAM) */
> 	if ((ret = rpma_mr_dereg(&sd->msg_mr)))
> 		librpma_td_verror(td, ret, "rpma_mr_dereg");
> ```
This should be done before librpma_common_server_cleanup() as the peer is deleted inside it.
</blockquote></details>

+1

I would move `librpma_common_server_cleanup(td);` to the end of this function (as the last call).

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/142)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 690 at r1](https://reviewable.io/reviews/pmem/fio/142#-MRLn5GN8Qx4KAviJkoy:-MROiQ6gDDskbQobw185:b32v57) ([raw file](https://github.com/pmem/fio/blob/6579a8c4024610f5abde7e932184837560d02919/engines/librpma_gpspm.c#L690)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1

I would move `librpma_common_server_cleanup(td);` to the end of this function (as the last call).
</blockquote></details>

+1

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/142)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 690 at r1](https://reviewable.io/reviews/pmem/fio/142#-MRLn5GN8Qx4KAviJkoy:-MRP3Og11kSxcxJuop19:b32v57) ([raw file](https://github.com/pmem/fio/blob/6579a8c4024610f5abde7e932184837560d02919/engines/librpma_gpspm.c#L690)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

+1

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/142)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 690 at r1](https://reviewable.io/reviews/pmem/fio/142#-MRLn5GN8Qx4KAviJkoy:-MRP3TwwBQbIJiUmWfHZ:b-6oi5m1) ([raw file](https://github.com/pmem/fio/blob/6579a8c4024610f5abde7e932184837560d02919/engines/librpma_gpspm.c#L690)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

+1
</blockquote></details>

To be fixed

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/142#-:-MRP3aHh8YmbrqBUUh4-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/142)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_gpspm.c, line 690 at r1](https://reviewable.io/reviews/pmem/fio/142#-MRLn5GN8Qx4KAviJkoy:-MRPVGV3BHaepDdy_BJV:b-8sgggk) ([raw file](https://github.com/pmem/fio/blob/6579a8c4024610f5abde7e932184837560d02919/engines/librpma_gpspm.c#L690)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

To be fixed
</blockquote></details>

#145

**Pull request merged**
