### PR TITLE
common: slim down # of tests to reduce regular build time

### PR DESCRIPTION
**Pull request by janekmi**
|Before [minutes]|After [minutes]|
|---|---|
|~14|~4|

This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/16)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/16#-:-MJXAbP_D7fOluRegDGH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
OK
I do understand that this is a local change only in our repo

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/16#-:-MJXBoUl02XGXN0hDSRv:b-gn8g6v)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/16#-:-MJXBz5l5kt5GXbePECl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/16)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
Just to speed up the development ;-)

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/16#-:-MJXC77k14Plaz31OeBx:b-krtafn)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/16#-:-MJXD8ze-J-rv1IwPPyn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
