### PR TITLE
aof: add client_hw_io_append()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/241)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/241)* status: all files reviewed, 6 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_aof.c, line 424 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUimT2V4sIuxRmCJBMk:-MUimT2V4sIuxRmCJBMl:bct9fbn) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L424)):*
> ```C
> 	size_t io_u_buf_off = IO_U_NEXT_BUF_OFF_CLIENT(cd);
> 	size_t pointer_offset = io_u_buf_off + SEND_OFFSET;
> 	uint64_t *pointer_ptr = (uint64_t *)cd->io_us_msgs + pointer_offset;
> ```

I thought the pointer is at the end of the memory region.
___
*[engines/librpma_aof.c, line 432 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUimkxACAqykXj9-UQg:-MUimkxACAqykXj9-UQh:b-jqc9i5) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L432)):*
> ```C
> 	if ((ret = rpma_flush(ccd->conn, ccd->server_mr, first_io_u->offset, len,
> 			ccd->server_mr_flush_type, RPMA_F_COMPLETION_ON_ERROR,
> 			(void *)(uintptr_t)last_io_u->index))) {
> ```

No need for op_context;
___
*[engines/librpma_aof.c, line 443 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUipAcL9fmBqkHhdxc3:-MUipAcL9fmBqkHhdxc4:bo6buuv) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L443)):*
> ```C
> 
> 	if ((ret = rpma_write_atomic(ccd->conn, ccd->server_mr, dst_offset,
> 			cd->msg_mr, src_offset, RPMA_F_COMPLETION_ON_ERROR,
> ```

`ccd->orig_mr` I guess.
___
*[engines/librpma_aof.c, line 444 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUipN5OBpZRoEY58VIh:-MUipN5OBpZRoEY58VIi:bm0i70k) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L444)):*
> ```C
> 	if ((ret = rpma_write_atomic(ccd->conn, ccd->server_mr, dst_offset,
> 			cd->msg_mr, src_offset, RPMA_F_COMPLETION_ON_ERROR,
> 			(void *)(uintptr_t)last_io_u->index))) {
> ```

No op_context needed.
___
*[engines/librpma_aof.c, line 450 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUipX_p3y-qvyIy-870:-MUipX_p3y-qvyIy-871:b-dl40j) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L450)):*
> ```C
> 
> 	/* flush the AOF pointer */
> 	if ((ret = rpma_flush(ccd->conn, ccd->server_mr, first_io_u->offset, len,
> ```

dst_offset?
___
*[engines/librpma_aof.c, line 457 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUiqVGD2DVq9bPy2NV7:-MUiqVGD2DVq9bPy2NV8:b-1dba6) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L457)):*
> ```C
> 	}
> 
> 	/* XXX what about counters ? */
> ```

No counters needed. No SENDs. No RECVs. No counters. :-)
When you will collect a completion for the last FLUSH operation you are sure all of the previous operations are done so you can put another set into the SQ. That's it. For reference, you can always take a look at the APM engine. No counters there. :-)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/241)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_aof.c, line 424 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUimT2V4sIuxRmCJBMk:-MUjUat-3eAcV8NBQ4RD:b-qeymyu) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L424)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I thought the pointer is at the end of the memory region.
</blockquote></details>

Yes, it is, see the `dst_offset`argument of `rpma_write_atomic()` below:

```
dst_offset = ccd->ws_size; /* destination offset of the AOF pointer */
```

Here you have only the address in the local memory where its value will be stored.
___
*[engines/librpma_aof.c, line 432 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUimkxACAqykXj9-UQg:-MUjVaxt3JSbJ7JBh8ek:bhyb595) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L432)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No need for op_context;
</blockquote></details>

But what if `rpma_flush()` fails? How will we know which io_u failed?
___
*[engines/librpma_aof.c, line 443 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUipAcL9fmBqkHhdxc3:-MUjW3AKAgx8tXbYpkL9:bh8fkwg) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L443)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`ccd->orig_mr` I guess.
</blockquote></details>

No, it is correct: `cd->msg_mr`. The value of the AOF pointer is stored in the messaging memory - see your first comment:

```
uint64_t *pointer_ptr = (uint64_t *)cd->io_us_msgs + pointer_offset;
```
___
*[engines/librpma_aof.c, line 444 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUipN5OBpZRoEY58VIh:-MUjWTLgBTdf43zPhglY:b-7q4lgw) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L444)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No op_context needed.
</blockquote></details>

But what if `rpma_write_atomic()` fails? How will we know which io_u failed?
___
*[engines/librpma_aof.c, line 450 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUipX_p3y-qvyIy-870:-MUjWpavBDvLpJwGlGKn:b-m1wgtc) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L450)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

dst_offset?
</blockquote></details>

Do you mean to set: `dst_offset = first_io_u->offset;` and to use `dst_offset` instead of `first_io_u->offset` here?
___
*[engines/librpma_aof.c, line 457 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUiqVGD2DVq9bPy2NV7:-MUjWszt4GOgAyCu8sSw:bhzz3hm) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L457)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No counters needed. No SENDs. No RECVs. No counters. :-)
When you will collect a completion for the last FLUSH operation you are sure all of the previous operations are done so you can put another set into the SQ. That's it. For reference, you can always take a look at the APM engine. No counters there. :-)
</blockquote></details>

Great! :-D

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/241)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_aof.c, line 443 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUipAcL9fmBqkHhdxc3:-MUjb6CAC9VNKEx0E-il:b7qcebc) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L443)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

A value of the AOF pointer has to be stored in the registered memory ... so it could be `ccd->orig_mr` but there should be a  space reserved for this pointer ...
</blockquote></details>

... but there is no such space ....

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/241)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_aof.c, line 424 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUimT2V4sIuxRmCJBMk:-MUj_YqiDBBpJxTxTmG1:bcnqdp4) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L424)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, it is, see the `dst_offset`argument of `rpma_write_atomic()` below:

```
dst_offset = ccd->ws_size; /* destination offset of the AOF pointer */
```

Here you have only the address in the local memory where its value will be stored.

</blockquote></details>

Yeah. You are right on the client-side it has to be stored somewhere. Good catch.

1. You have to allocate it since it is not initialized for the hw mode yet.
2. Please consider using another variable name:
- either rename it so it will sound more general OR
- have another variable for this purpose

In this function, it is not related to io_us either to the messaging.
___
*[engines/librpma_aof.c, line 443 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUipAcL9fmBqkHhdxc3:-MUjaSxZ57tkCF9JdP6S:b-dlhch8) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L443)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, it is correct: `cd->msg_mr`. The value of the AOF pointer is stored in the messaging memory - see your first comment:

```
uint64_t *pointer_ptr = (uint64_t *)cd->io_us_msgs + pointer_offset;
```

</blockquote></details>

It is should not recall the messaging. Please. xD
___
*[engines/librpma_aof.c, line 450 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUipX_p3y-qvyIy-870:-MUjamSf7WXBYIEX9K5K:br7vo5a) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L450)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Do you mean to set: `dst_offset = first_io_u->offset;` and to use `dst_offset` instead of `first_io_u->offset` here?
</blockquote></details>

I mean you should flush the same range you are writing to. So having a dedicated variable storing an already calculated write offset, it makes perfect sense to reuse it for the flush.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/241)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_aof.c, line 443 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUipAcL9fmBqkHhdxc3:-MUjcH8y-8MqcoM_-mS-:b-k5r6kq) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L443)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is should not recall the messaging. Please. xD
</blockquote></details>

OK, but anyway a value of the AOF pointer has to be stored in the registered memory .

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/241)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_aof.c, line 450 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUipX_p3y-qvyIy-870:-MUjkkJxCZG75BggOrY3:by4ou2j) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L450)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I mean you should flush the same range you are writing to. So having a dedicated variable storing an already calculated write offset, it makes perfect sense to reuse it for the flush.
</blockquote></details>

Right, I forgot to correct the arguments of the second flush ... - they were just a copy-paste of the first one :-)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/241)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_aof.c, line 424 at r1](https://reviewable.io/reviews/pmem/fio/241#-MUimT2V4sIuxRmCJBMk:-MUjsaMNClChwFfkXDIU:b-ykqo38) ([raw file](https://github.com/pmem/fio/blob/1eef1701ec212e7496035b6455ca565c82fd08a7/engines/librpma_aof.c#L424)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yeah. You are right on the client-side it has to be stored somewhere. Good catch.

1. You have to allocate it since it is not initialized for the hw mode yet.
2. Please consider using another variable name:
- either rename it so it will sound more general OR
- have another variable for this purpose

In this function, it is not related to io_us either to the messaging.
</blockquote></details>

Maybe like that?

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/241)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_fio.c, line 391 at r3](https://reviewable.io/reviews/pmem/fio/241#-MUm-KQLEiQCjPN89zBM:-MUm-KQLEiQCjPN89zBN:bjlz1pv) ([raw file](https://github.com/pmem/fio/blob/ee7f40707144d4bc06ff53b960c739c3ce774ba9/engines/librpma_fio.c#L391)):*
> ```C
> 	mr_reg_size = ccd->io_us_size + sizeof(uint64_t);
> 
> 	if ((ret = rpma_mr_reg(ccd->peer, ccd->orig_buffer_aligned, mr_reg_size,
> ```

You assume that after the required io_us space there for sure is an additional 64 bits.
Do you have an argument supporting this assumption?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/241)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_fio.c, line 391 at r3](https://reviewable.io/reviews/pmem/fio/241#-MUm-KQLEiQCjPN89zBM:-MUmKyD30s1yavmSIzk6:b-896fix) ([raw file](https://github.com/pmem/fio/blob/ee7f40707144d4bc06ff53b960c739c3ce774ba9/engines/librpma_fio.c#L391)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You assume that after the required io_us space there for sure is an additional 64 bits.
Do you have an argument supporting this assumption?
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/241#-:-MUmZxhy5zIFgmfY8UWl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_aof.c, line 523 at r4](https://reviewable.io/reviews/pmem/fio/241#-MUmXkz8Du3-7bYOvmQV:-MUmXkz9CpbbCgwGOAC_:bcexjiq) ([raw file](https://github.com/pmem/fio/blob/c4485ec4aa9a2b1877b0269d215a95ee05ca0ca7/engines/librpma_aof.c#L523)):*
> ```C
> 		free(cd->aof_ptr);
> 		return -1;
> 	}
> ```

**Discussing**: It can be done in the `client_hw_init()`. No need for introducing another hook.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/241)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_aof.c, line 523 at r4](https://reviewable.io/reviews/pmem/fio/241#-MUmXkz8Du3-7bYOvmQV:-MUm_EAf7ZYTT8OojRWu:bahqonm) ([raw file](https://github.com/pmem/fio/blob/c4485ec4aa9a2b1877b0269d215a95ee05ca0ca7/engines/librpma_aof.c#L523)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

**Discussing**: It can be done in the `client_hw_init()`. No need for introducing another hook.
</blockquote></details>

So why is it done in a separate hook in case of the SW version?

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/241)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_aof.c, line 523 at r4](https://reviewable.io/reviews/pmem/fio/241#-MUmXkz8Du3-7bYOvmQV:-MUmg5-Z3P3fkmnvxqgQ:bf8ca9m) ([raw file](https://github.com/pmem/fio/blob/c4485ec4aa9a2b1877b0269d215a95ee05ca0ca7/engines/librpma_aof.c#L523)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

So why is it done in a separate hook in case of the SW version?
</blockquote></details>

Great question. It is not needed in that case either. I think it may be a result of evolution from registering an io_u_buffer to registering an independently allocated buffer that can be registered at any time.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/241)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[engines/librpma_aof.c, line 523 at r4](https://reviewable.io/reviews/pmem/fio/241#-MUmXkz8Du3-7bYOvmQV:-MUmlGg19Y9hWqZVib5b:b8eire8) ([raw file](https://github.com/pmem/fio/blob/c4485ec4aa9a2b1877b0269d215a95ee05ca0ca7/engines/librpma_aof.c#L523)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Great question. It is not needed in that case either. I think it may be a result of evolution from registering an io_u_buffer to registering an independently allocated buffer that can be registered at any time.
</blockquote></details>

OK, I can move all things to the _init() hook.

**Comment by ldorau** [comment]
> **Discussing**: It can be done in the `client_hw_init()`. No need for introducing another hook.
>

@janekmi Moved all things to the _init() hook. Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/241#-:-MUmu1WcBTn5UK65dgdc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/241#-:-MUnCR475B1rfUaa0iZ5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
