### PR TITLE
rpma: enhance rpma_mr_advise calling

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/260)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/260)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)

___
*[engines/librpma_fio.c, line 946 at r1](https://reviewable.io/reviews/pmem/fio/260#-Mkd7YA-0_X4QCPsfcdm:-Mkd7YA0EbnQOw0oET6P:bxd44qt) ([raw file](https://github.com/pmem/fio/blob/a6b1077a37330e7bc88a40fb9b25b6a16c8dc368/engines/librpma_fio.c#L946)):*
> ```C
> 			IBV_ADVISE_MR_FLAG_FLUSH))) {
> 		librpma_td_verror(td, ret, "rpma_mr_advise");
> 		/* invalid argument is an error */
> ```

an invalid...
___
*[engines/librpma_fio.c, line 948 at r1](https://reviewable.io/reviews/pmem/fio/260#-Mkd7lf44RTB3--KAv-U:-Mkd7lf44RTB3--KAv-V:b-1mf046) ([raw file](https://github.com/pmem/fio/blob/a6b1077a37330e7bc88a40fb9b25b6a16c8dc368/engines/librpma_fio.c#L948)):*
Please add a comment here:

> Note: Having rpma_mr_advise(3) failed because of RPMA_E_NOSUPP or RPMA_E_PROVIDER may come with a performance penalty but it is not a showstopper for running the benchmark.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/260)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_fio.c, line 946 at r1](https://reviewable.io/reviews/pmem/fio/260#-Mkd7YA-0_X4QCPsfcdm:-Mke9mn12n6-e-sRKaUC:b-896fix) ([raw file](https://github.com/pmem/fio/blob/a6b1077a37330e7bc88a40fb9b25b6a16c8dc368/engines/librpma_fio.c#L946)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

an invalid...
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 948 at r1](https://reviewable.io/reviews/pmem/fio/260#-Mkd7lf44RTB3--KAv-U:-Mke9nIH1O4poTxsnqqO:b-896fix) ([raw file](https://github.com/pmem/fio/blob/a6b1077a37330e7bc88a40fb9b25b6a16c8dc368/engines/librpma_fio.c#L948)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add a comment here:

> Note: Having rpma_mr_advise(3) failed because of RPMA_E_NOSUPP or RPMA_E_PROVIDER may come with a performance penalty but it is not a showstopper for running the benchmark.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/260)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[engines/librpma_fio.c, line 903 at r2](https://reviewable.io/reviews/pmem/fio/260#-Mkezo2-1yq1Dm2C9DAY:-Mkezo2-1yq1Dm2C9DAZ:b-t5teox) ([raw file](https://github.com/pmem/fio/blob/3c98909d2d91c32709eff5c2ea596454e420c8e1/engines/librpma_fio.c#L903)):*
> ```
> log_err
> ```
___
*[engines/librpma_fio.c, line 954 at r2](https://reviewable.io/reviews/pmem/fio/260#-Mkf-ZPKA0TpiwC4rRrq:-Mkf-ZPKA0TpiwC4rRrr:b-s8k1r6) ([raw file](https://github.com/pmem/fio/blob/3c98909d2d91c32709eff5c2ea596454e420c8e1/engines/librpma_fio.c#L954)):*
> ```C
> 		 * or RPMA_E_PROVIDER may come with a performance penalty but it
> 		 * is not a showstopper for running the benchmark.
> 		 */
> ```

Shall we also put an explicit message in log_info()? Having this information in the code does not help end user while getting into the trouble with low rpmem performance.

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/260)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong and @janekmi)

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/260)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[engines/librpma_fio.c, line 954 at r2](https://reviewable.io/reviews/pmem/fio/260#-Mkf-ZPKA0TpiwC4rRrq:-MkjH4GC9ouBGjuBVIp6:b-896fix) ([raw file](https://github.com/pmem/fio/blob/3c98909d2d91c32709eff5c2ea596454e420c8e1/engines/librpma_fio.c#L954)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do agree. We can wrap this very message into `log_err()` + the notice why we do not use the `log_info()`.

Ref: https://github.com/pmem/fio/blob/rpma/engines/librpma_apm.c#L136
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/260)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong and @grom72)

___
*[engines/librpma_fio.c, line 954 at r2](https://reviewable.io/reviews/pmem/fio/260#-Mkf-ZPKA0TpiwC4rRrq:-MkkacyWEfYPOz2u6Yxi:bhna7gh) ([raw file](https://github.com/pmem/fio/blob/3c98909d2d91c32709eff5c2ea596454e420c8e1/engines/librpma_fio.c#L954)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please replace the tab here with a space: `RPMA_E_NOSUPP	or` ;-)
___
*[engines/librpma_fio.c, line 950 at r3](https://reviewable.io/reviews/pmem/fio/260#-Mkkb1eiBbjcTIEohooO:-Mkkb1eiBbjcTIEohooP:bv1d7pg) ([raw file](https://github.com/pmem/fio/blob/855fe11f5c2dbc0641718e191e5b704a80de2e42/engines/librpma_fio.c#L950)):*
> ```C
> 			goto err_mr_dereg;
> 
> 		log_err("Note: Having rpma_mr_advise(3) failed because of RPMA_E_NOSUPP	or RPMA_E_PROVIDER may come with a performance penalty but it is not a showstopper for running the benchmark.\n");
> ```

Please add a note before the `log_err()` call:

```c
/* XXX log_info mixes with the JSON output */
```

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/260)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_fio.c, line 954 at r2](https://reviewable.io/reviews/pmem/fio/260#-Mkf-ZPKA0TpiwC4rRrq:-MkkccnE4KKOskEPRjwx:b-896fix) ([raw file](https://github.com/pmem/fio/blob/3c98909d2d91c32709eff5c2ea596454e420c8e1/engines/librpma_fio.c#L954)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please replace the tab here with a space: `RPMA_E_NOSUPP	or` ;-)
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 950 at r3](https://reviewable.io/reviews/pmem/fio/260#-Mkkb1eiBbjcTIEohooO:-Mkkcb_6CATLQvbFa_ZV:b-896fix) ([raw file](https://github.com/pmem/fio/blob/855fe11f5c2dbc0641718e191e5b704a80de2e42/engines/librpma_fio.c#L950)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add a note before the `log_err()` call:

```c
/* XXX log_info mixes with the JSON output */
```
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/260#-:-Mkkr-UV7RvKx5W8BigK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/260)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/260#-:-MklAF9F13cl47bLTsZa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/260#-:-MklEGrh066nIPBy10-j:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/260)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
