### PR TITLE
examples: add thread & create_serialize

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/12)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/12)* status: 0 of 1 files reviewed, all discussions resolved

___
*[examples/librpma-client.fio, line 4 at r1](https://reviewable.io/reviews/pmem/fio/12#-MJUQ8ax8de2WwZtmW_F:-MJUQ8ax8de2WwZtmW_G:b-7tqo6e) ([raw file](https://github.com/pmem/fio/blob/261d6b8ac9f7bd9651d597ecdb0eef86c4fadfe9/examples/librpma-client.fio#L4)):*
> ```
> 
> # The engine requires some options to work correctly:
> # - thread XXX some initiation steps are synchronized between threads
> ```

1. It greatly improves debugging possibilities.
2. Probably in the following sprints we will have interthread synchronization which obviously does not work for processes

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/12)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[examples/librpma-client.fio, line 17 at r1](https://reviewable.io/reviews/pmem/fio/12#-MJWqoXg1eIwqsAAKfOk:-MJWqoXg1eIwqsAAKfOl:bwvivvc) ([raw file](https://github.com/pmem/fio/blob/261d6b8ac9f7bd9651d597ecdb0eef86c4fadfe9/examples/librpma-client.fio#L17)):*
> ```
> create_serialize=0
> ```
do not follow why we need this. but we can fix this later
___
*[examples/librpma-client.fio, line 20 at r1](https://reviewable.io/reviews/pmem/fio/12#-MJWrnri71WlrK1sfefw:-MJWrnri71WlrK1sfefx:b-sz08y) ([raw file](https://github.com/pmem/fio/blob/261d6b8ac9f7bd9651d597ecdb0eef86c4fadfe9/examples/librpma-client.fio#L20)):*
> ```
> iodepth_batch_submit=[# of ious to submit at once]
> ```
what is an effort to implement this?
___
*[examples/librpma-client.fio, line 23 at r1](https://reviewable.io/reviews/pmem/fio/12#-MJWrMJW9mHWE_3JN35_:-MJWrMJW9mHWE_3JN35a:bra46wg) ([raw file](https://github.com/pmem/fio/blob/261d6b8ac9f7bd9651d597ecdb0eef86c4fadfe9/examples/librpma-client.fio#L23)):*
> ```
> size
> ```
mmap as an option to use PMEm locally otherwise we do not need this

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/12#-:-MJWrr8e5FXeh-_D1aZB:bdycpsm)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/12)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/12)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[examples/librpma-client.fio, line 17 at r1](https://reviewable.io/reviews/pmem/fio/12#-MJWqoXg1eIwqsAAKfOk:-MJX8BmC5PWSbPWl4YRO:bmke41d) ([raw file](https://github.com/pmem/fio/blob/261d6b8ac9f7bd9651d597ecdb0eef86c4fadfe9/examples/librpma-client.fio#L17)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> create_serialize=0
> ```
do not follow why we need this. but we can fix this later
</blockquote></details>

Otherwise, `setup()` hook is called before `init()` etc.
We need this as long as we assume a certain order in which hooks are called and we have dependencies between them.
___
*[examples/librpma-client.fio, line 20 at r1](https://reviewable.io/reviews/pmem/fio/12#-MJWrnri71WlrK1sfefw:-MJX8RwvDU4fUMJ9yXcM:b-2e5gjo) ([raw file](https://github.com/pmem/fio/blob/261d6b8ac9f7bd9651d597ecdb0eef86c4fadfe9/examples/librpma-client.fio#L20)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> iodepth_batch_submit=[# of ious to submit at once]
> ```
what is an effort to implement this?
</blockquote></details>

effort = 0.

Probably it will work right out of the box.
___
*[examples/librpma-client.fio, line 23 at r1](https://reviewable.io/reviews/pmem/fio/12#-MJWrMJW9mHWE_3JN35_:-MJX8cvC1sVRk3faJJAP:bivclla) ([raw file](https://github.com/pmem/fio/blob/261d6b8ac9f7bd9651d597ecdb0eef86c4fadfe9/examples/librpma-client.fio#L23)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> size
> ```
mmap as an option to use PMEm locally otherwise we do not need this
</blockquote></details>

This parameter is here to inspire FIO to do a certain amount of work on the remote memory.
Do you want to say it should be replaced with `io_size`? I think so too. :-)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/12)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[examples/librpma-client.fio, line 23 at r1](https://reviewable.io/reviews/pmem/fio/12#-MJWrMJW9mHWE_3JN35_:-MJX9Nay3zsWFGIOQYnw:bqgbzjc) ([raw file](https://github.com/pmem/fio/blob/261d6b8ac9f7bd9651d597ecdb0eef86c4fadfe9/examples/librpma-client.fio#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This parameter is here to inspire FIO to do a certain amount of work on the remote memory.
Do you want to say it should be replaced with `io_size`? I think so too. :-)
</blockquote></details>

I have mixed up... It is here for the reason stated in the comment.
I agree it is not needed during this sprint.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/12)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[examples/librpma-client.fio, line 23 at r1](https://reviewable.io/reviews/pmem/fio/12#-MJWrMJW9mHWE_3JN35_:-MJXANKcCZEq1bLu7YYq:b2ngnl1) ([raw file](https://github.com/pmem/fio/blob/261d6b8ac9f7bd9651d597ecdb0eef86c4fadfe9/examples/librpma-client.fio#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I have mixed up... It is here for the reason stated in the comment.
I agree it is not needed during this sprint.
</blockquote></details>

#18

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/12)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/12)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/12)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/librpma-client.fio, line 23 at r1](https://reviewable.io/reviews/pmem/fio/12#-MJWrMJW9mHWE_3JN35_:-MJXBBXf8URPH6fFHs7o:b-r5msvq) ([raw file](https://github.com/pmem/fio/blob/261d6b8ac9f7bd9651d597ecdb0eef86c4fadfe9/examples/librpma-client.fio#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

#18
</blockquote></details>

sorry my fault and misinterpretation
we need size or io_size otherwise how do we define stop condition for benchmark?

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/12)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/12)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/librpma-client.fio, line 23 at r1](https://reviewable.io/reviews/pmem/fio/12#-MJWrMJW9mHWE_3JN35_:-MJXEUZv3UiGNomAen3T:bcvgqrg) ([raw file](https://github.com/pmem/fio/blob/261d6b8ac9f7bd9651d597ecdb0eef86c4fadfe9/examples/librpma-client.fio#L23)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

sorry my fault and misinterpretation
we need size or io_size otherwise how do we define stop condition for benchmark?
</blockquote></details>

You are right. xD #18 to be closed.

**Pull request merged**
