### PR TITLE
rpma: scaffolding of the GPSPM client

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/52)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/52)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_gpspm.c, line 93 at r1](https://reviewable.io/reviews/pmem/fio/52#-MLiWhT9Ex9c9VPAOqAi:-MLiWhTA-IeKsB4XGQ3T:behqd) ([raw file](https://github.com/pmem/fio/blob/69f7c80bd8f0cee6d1d656d15e5e28bed37d1d7a/engines/librpma_gpspm.c#L93)):*
> ```C
> 	 * - create new peer
> 	 * - create a connection request (o->hostname, o->port) and connect it
> 	 */
> ```

- get memory region  from server
- setup memory for send() (including protobuf context)
___
*[engines/librpma_gpspm.c, line 100 at r1](https://reviewable.io/reviews/pmem/fio/52#-MLiVHyq-ak5Z79UAmZ9:-MLiVHyrATtcAXZBN7Rt:b-8qwt7d) ([raw file](https://github.com/pmem/fio/blob/69f7c80bd8f0cee6d1d656d15e5e28bed37d1d7a/engines/librpma_gpspm.c#L100)):*
> ```
> rpma_send
> ```
do we need any send() at startup 
or shall we only register memory here?

Why do we need post_init on the client's side?
___
*[engines/librpma_gpspm.c, line 108 at r1](https://reviewable.io/reviews/pmem/fio/52#-MLiX_MQ0RH0PsiCrJvR:-MLiX_MQ0RH0PsiCrJvS:bz3sbg4) ([raw file](https://github.com/pmem/fio/blob/69f7c80bd8f0cee6d1d656d15e5e28bed37d1d7a/engines/librpma_gpspm.c#L108)):*
> ```C
> {
> 	/*
> 	 * - rpma_mr_dereg
> ```

- disconnect
___
*[engines/librpma_gpspm.c, line 145 at r1](https://reviewable.io/reviews/pmem/fio/52#-MLiY7qvB79kapSpl2la:-MLiY7qvB79kapSpl2lb:b-c0rcyq) ([raw file](https://github.com/pmem/fio/blob/69f7c80bd8f0cee6d1d656d15e5e28bed37d1d7a/engines/librpma_gpspm.c#L145)):*
> ```C
> 	 * - execute all io_us from queued[]
> 	 * - move executed io_us to flight[]
> 	 */
> ```

shall we assume more than one flush after several writes offsets?

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/52)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72)

___
*[engines/librpma_gpspm.c, line 93 at r1](https://reviewable.io/reviews/pmem/fio/52#-MLiWhT9Ex9c9VPAOqAi:-MLi_yUTCTVgcsJgdK7J:b-glwn5r) ([raw file](https://github.com/pmem/fio/blob/69f7c80bd8f0cee6d1d656d15e5e28bed37d1d7a/engines/librpma_gpspm.c#L93)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

- get memory region  from server
- setup memory for send() (including protobuf context)
</blockquote></details>

AD1. Yes.
AD2. No. Memory for send is prepared by the FIO framework.
___
*[engines/librpma_gpspm.c, line 100 at r1](https://reviewable.io/reviews/pmem/fio/52#-MLiVHyq-ak5Z79UAmZ9:-MLiahBXAW0EKlZgjjeG:bldz2i8) ([raw file](https://github.com/pmem/fio/blob/69f7c80bd8f0cee6d1d656d15e5e28bed37d1d7a/engines/librpma_gpspm.c#L100)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_send
> ```
do we need any send() at startup 
or shall we only register memory here?

Why do we need post_init on the client's side?
</blockquote></details>

`rpma_send()` here does not make any sense.
The `post_init()` hook on the client's side is needed to register the buffers, prepared by the FIO, for `rpma_send()`.
___
*[engines/librpma_gpspm.c, line 108 at r1](https://reviewable.io/reviews/pmem/fio/52#-MLiX_MQ0RH0PsiCrJvR:-MLiazLP2dvodNegOWce:b32v57) ([raw file](https://github.com/pmem/fio/blob/69f7c80bd8f0cee6d1d656d15e5e28bed37d1d7a/engines/librpma_gpspm.c#L108)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

- disconnect
</blockquote></details>

+1
___
*[engines/librpma_gpspm.c, line 145 at r1](https://reviewable.io/reviews/pmem/fio/52#-MLiY7qvB79kapSpl2la:-MLibMsFE6-rGK4tpyi3:b-rkpx0e) ([raw file](https://github.com/pmem/fio/blob/69f7c80bd8f0cee6d1d656d15e5e28bed37d1d7a/engines/librpma_gpspm.c#L145)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

shall we assume more than one flush after several writes offsets?
</blockquote></details>

For random asynchronous writes: yes.
But it is the voice of the future.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/52)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 93 at r1](https://reviewable.io/reviews/pmem/fio/52#-MLiWhT9Ex9c9VPAOqAi:-MLl7iUc4fyxZirv6LCM:b-896fix) ([raw file](https://github.com/pmem/fio/blob/69f7c80bd8f0cee6d1d656d15e5e28bed37d1d7a/engines/librpma_gpspm.c#L93)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

AD1. Yes.
AD2. No. Memory for send is prepared by the FIO framework.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 100 at r1](https://reviewable.io/reviews/pmem/fio/52#-MLiVHyq-ak5Z79UAmZ9:-MLl8V3W0U8vrMBwRv6i:b-896fix) ([raw file](https://github.com/pmem/fio/blob/69f7c80bd8f0cee6d1d656d15e5e28bed37d1d7a/engines/librpma_gpspm.c#L100)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`rpma_send()` here does not make any sense.
The `post_init()` hook on the client's side is needed to register the buffers, prepared by the FIO, for `rpma_send()`.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 108 at r1](https://reviewable.io/reviews/pmem/fio/52#-MLiX_MQ0RH0PsiCrJvR:-MLl8iAP1HJLh34MgZsT:b-896fix) ([raw file](https://github.com/pmem/fio/blob/69f7c80bd8f0cee6d1d656d15e5e28bed37d1d7a/engines/librpma_gpspm.c#L108)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/52)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/52#-:-MLlKCHvAlABayNHaPKl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/52)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/52#-:-MLm55Cw4dSXPZVHoZom:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
