### PR TITLE
rpma: print 'Note' only when direct_write_to_pmem is set

### PR DESCRIPTION
**Pull request by yangx-jy**
Signed-off-by: Xiao Yang <yangx.jy@cn.fujitsu.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/203)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/203)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/203)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
@janekmi please review

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/203#-:-MScAK3eAOSKrQV73tO-:b-f79qgk)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/203#-:-MScAPhGDzXgTyze0qPD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/203)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[engines/librpma_apm.c, line 133 at r1](https://reviewable.io/reviews/pmem/fio/203#-MSgIwqk-bSoWOj5mKZK:-MSgIwqk-bSoWOj5mKZL:b77duzm) ([raw file](https://github.com/pmem/fio/blob/d803bbd5fba6f88cd6830c81ee0dcebafed07897/engines/librpma_apm.c#L133)):*
> ```C
> 
> 		(void) rpma_peer_cfg_delete(&pcfg);
> 	} else if (ccd->ws->direct_write_to_pmem && td->thread_number == 1) {
> ```

I would argue the sole aim of this notice is to remember to the end-user that using APM engines with DRAM does not give the actual performance values of APM-style persistency.

I do not want to have the end-user to set `direct_write_to_pmem=1` to silent the notice. Having `direct_write_to_pmem=1` as well as having `direct_write_to_pmem=0` (or having a system configuration effectively meaning one have this or opposite *Direct Write to PMem* capabilities to be exact) when using DRAM as the target of the operation, may have its own value as an experiment.

For details on *Direct Write to PMem* please see pmem/rpma#842.

**Comment by yangx-jy** [comment]
___
*[engines/librpma_apm.c, line 133 at r1](https://reviewable.io/reviews/pmem/fio/203#-MSgIwqk-bSoWOj5mKZK:-MSgY1lv5DyGK4GAx_SV:bp4heof) ([raw file](https://github.com/pmem/fio/blob/d803bbd5fba6f88cd6830c81ee0dcebafed07897/engines/librpma_apm.c#L133)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I would argue the sole aim of this notice is to remember to the end-user that using APM engines with DRAM does not give the actual performance values of APM-style persistency.

I do not want to have the end-user to set `direct_write_to_pmem=1` to silent the notice. Having `direct_write_to_pmem=1` as well as having `direct_write_to_pmem=0` (or having a system configuration effectively meaning one have this or opposite *Direct Write to PMem* capabilities to be exact) when using DRAM as the target of the operation, may have its own value as an experiment.

For details on *Direct Write to PMem* please see pmem/rpma#842.
</blockquote></details>

Hi,

Do you mean that you do not want to have the end-user to set direct_write_to_pmem=0 to silent the notice?
I think it is just a hint that setting direct_write_to_pmem=1 is not useful for DRAM, and we still can set direct_write_to_pmem to 0 or 1 for DRAM.

Besd Regards,
Xiao Yang

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/203)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[engines/librpma_apm.c, line 133 at r1](https://reviewable.io/reviews/pmem/fio/203#-MSgIwqk-bSoWOj5mKZK:-MSgvJab1MLwlzGd-ISu:br0asg3) ([raw file](https://github.com/pmem/fio/blob/d803bbd5fba6f88cd6830c81ee0dcebafed07897/engines/librpma_apm.c#L133)):*
> a hint that setting direct_write_to_pmem=1 is not useful for DRAM

This is what I'm NOT sure of. I can imagine someone would like to measure DRAM vs PMem performance in exactly the same conditions. So it is kind of useful for experimental purposes.

**Comment by yangx-jy** [comment]
___
*[engines/librpma_apm.c, line 133 at r1](https://reviewable.io/reviews/pmem/fio/203#-MSgIwqk-bSoWOj5mKZK:-MSjmN0UA88baRFlIe66:b-n9e8wd) ([raw file](https://github.com/pmem/fio/blob/d803bbd5fba6f88cd6830c81ee0dcebafed07897/engines/librpma_apm.c#L133)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> a hint that setting direct_write_to_pmem=1 is not useful for DRAM

This is what I'm NOT sure of. I can imagine someone would like to measure DRAM vs PMem performance in exactly the same conditions. So it is kind of useful for experimental purposes.
</blockquote></details>

Hi @janekmi 
 
Thanks for sharing your opinion.  OK,  we keep it for now.

Best Regards,
Xiao Yang

**Pull request closed without merging**
