### PR TITLE
rename prefix _commmon_ to _fio_

### PR DESCRIPTION
**Pull request by grom72**
Proposal to change "common" prefix into "fio"

Requires:
- [x] #188

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/189)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/189)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/fio/189#-MRszGIeBhZwU_R55fXD:-MRszGIf9O2RBiYepvCg:bb76mu4) (no related file):*
Why?

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/189)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/189#-MRszGIeBhZwU_R55fXD:-MRt6ANWB-ZY4t5wI02Q:b-h2qy5k) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Having two engines `librpma_apm` and `librpma_gpspm` I would leave `_common_` part in all file names, Makefile, configure and their variables, but I would remove it from the C-code.

---

**Review by ldorau — COMMENTED** [review]
@grom72 Please rebase

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/189#-:-MRt7ale7majTRB9L0p1:btr0ke1)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/189)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/189#-MRszGIeBhZwU_R55fXD:-MRto_ZM9-UIgkSBcaNe:bvm00iy) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Having two engines `librpma_apm` and `librpma_gpspm` I would leave `_common_` part in all file names, Makefile, configure and their variables, but I would remove it from the C-code.
</blockquote></details>

librpma_fio_ gives a clear message - this is librpma for fio "common" layer

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/189)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/189#-MRszGIeBhZwU_R55fXD:-MRtoU_75GZALA52EjUb:bsndro7) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

librpma_fio_ gives a clear message - this is librpma for fio "common" layer
</blockquote></details>

I consider matching the public part of the compilation module matching with its name a good practice. And I am very reluctant to drop this idea. I think we can not drop the suffix entirely (because `librpma.h` is not a good name for a local header) whereas `_common` is too long. I think we can live with short yet meaningless suffix e.g. `_abc` or `_fio`. @ldorau what do you think?

---

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/189)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_fio.h, line 33 at r2](https://reviewable.io/reviews/pmem/fio/189#-MRtq0XY-h9C2EXop9Te:-MRtq0XY-h9C2EXop9Tf:bgslul5) ([raw file](https://github.com/pmem/fio/blob/95f21709320e6d7bb17cd73ab46f00877a1f80dd/engines/librpma_fio.h#L33)):*
> ```objc
> 
> /* common option structure for server and client */
> struct librpma_fio_private_options {
> ```

Why private?
___
*[engines/librpma_fio.h, line 248 at r2](https://reviewable.io/reviews/pmem/fio/189#-MRtqRnVBvZi04pMEw4F:-MRtqRnVBvZi04pMEw4G:b-867xyf) ([raw file](https://github.com/pmem/fio/blob/95f21709320e6d7bb17cd73ab46f00877a1f80dd/engines/librpma_fio.h#L248)):*
> ```objc
> 		struct rpma_conn_req *conn_req);
> 
> extern struct fio_option librpma_fio_server_options[];
> ```

Please remove.

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/189)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma_fio.h, line 33 at r2](https://reviewable.io/reviews/pmem/fio/189#-MRtq0XY-h9C2EXop9Te:-MRu2hTj-dQ0bC_Cf6ka:b-8zkrkb) ([raw file](https://github.com/pmem/fio/blob/95f21709320e6d7bb17cd73ab46f00877a1f80dd/engines/librpma_fio.h#L33)):*
> ```
> librpma_fio_private_options
> ```
librpma_fio_options already used below

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/189)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/189#-MRszGIeBhZwU_R55fXD:-MRu5UcK36lyFRydYgbU:b-e87k1m) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I consider matching the public part of the compilation module matching with its name a good practice. And I am very reluctant to drop this idea. I think we can not drop the suffix entirely (because `librpma.h` is not a good name for a local header) whereas `_common` is too long. I think we can live with short yet meaningless suffix e.g. `_abc` or `_fio`. @ldorau what do you think?
</blockquote></details>

OK, let it be, let it be ... ;-)

---
___
*[engines/librpma_fio.h, line 2 at r2](https://reviewable.io/reviews/pmem/fio/189#-MRu5ePB16W0if_HFVtw:-MRu5ePB16W0if_HFVtx:b-z8r6gx) ([raw file](https://github.com/pmem/fio/blob/95f21709320e6d7bb17cd73ab46f00877a1f80dd/engines/librpma_fio.h#L2)):*
> ```
> engine's
> ```

`engines'`
___
*[engines/librpma_fio.c, line 2 at r2](https://reviewable.io/reviews/pmem/fio/189#-MRu5qdNDH25VaVqV_q2:-MRu5qdNDH25VaVqV_q3:b-yvip6v) ([raw file](https://github.com/pmem/fio/blob/95f21709320e6d7bb17cd73ab46f00877a1f80dd/engines/librpma_fio.c#L2)):*
> ```
> engine's
> ```

.
___
*[engines/librpma_fio.c, line 2 at r2](https://reviewable.io/reviews/pmem/fio/189#-MRu5u50CthNXoOINfqQ:-MRu5u50CthNXoOINfqR:b-vzms83) ([raw file](https://github.com/pmem/fio/blob/95f21709320e6d7bb17cd73ab46f00877a1f80dd/engines/librpma_fio.c#L2)):*
> ```
>  common.
> ```

Maybe `common part.`?  - 'common' is an adjective, not a noun.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/189)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_fio.h, line 248 at r2](https://reviewable.io/reviews/pmem/fio/189#-MRtqRnVBvZi04pMEw4F:-MRu7JfK5hP4G8xXkYHd:b73826k) ([raw file](https://github.com/pmem/fio/blob/95f21709320e6d7bb17cd73ab46f00877a1f80dd/engines/librpma_fio.h#L248)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

why?
</blockquote></details>

It is an artifact. Only this declaration remains.

**Review by janekmi — CHANGES_REQUESTED** [review]
Please rebase.

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/189#-:-MRu7dS_7-nccaMY3PLd:b-8cioiv)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_fio.h, line 2 at r2](https://reviewable.io/reviews/pmem/fio/189#-MRu7i4B9pywGDImGvAY:-MRu7i4B9pywGDImGvAZ:b-pfg6i7) ([raw file](https://github.com/pmem/fio/blob/95f21709320e6d7bb17cd73ab46f00877a1f80dd/engines/librpma_fio.h#L2)):*
> ```objc
> /*
>  * librpma_fio: librpma and librpma_gpspm engine's common header
> ```

librpma_apm

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/189)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma_fio.h, line 2 at r2](https://reviewable.io/reviews/pmem/fio/189#-MRu5ePB16W0if_HFVtw:-MRuKbo49zQzLfEbBYHE:b-896fix) ([raw file](https://github.com/pmem/fio/blob/95f21709320e6d7bb17cd73ab46f00877a1f80dd/engines/librpma_fio.h#L2)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> engine's
> ```

`engines'`
</blockquote></details>

Done.
___
*[engines/librpma_fio.h, line 2 at r2](https://reviewable.io/reviews/pmem/fio/189#-MRu7i4B9pywGDImGvAY:-MRuKcB07qyrpAzKG7qB:b-896fix) ([raw file](https://github.com/pmem/fio/blob/95f21709320e6d7bb17cd73ab46f00877a1f80dd/engines/librpma_fio.h#L2)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

librpma_apm
</blockquote></details>

Done.
___
*[engines/librpma_fio.h, line 33 at r2](https://reviewable.io/reviews/pmem/fio/189#-MRtq0XY-h9C2EXop9Te:-MRuKdvs6jx-g3WsmuSe:b-896fix) ([raw file](https://github.com/pmem/fio/blob/95f21709320e6d7bb17cd73ab46f00877a1f80dd/engines/librpma_fio.h#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I would put here `struct librpma_fio_options` wheres the extern I would recommend naming e.g. `librpma_fio_options_description`?
</blockquote></details>

Done.
___
*[engines/librpma_fio.h, line 47 at r2](https://reviewable.io/reviews/pmem/fio/189#-MRu98aF82D01-Ql04Kj:-MRuKgDd53B7sACyuqKY:b-896fix) ([raw file](https://github.com/pmem/fio/blob/95f21709320e6d7bb17cd73ab46f00877a1f80dd/engines/librpma_fio.h#L47)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
extern struct fio_option librpma_fio_options_description[];
```
</blockquote></details>

Done.
___
*[engines/librpma_fio.h, line 248 at r2](https://reviewable.io/reviews/pmem/fio/189#-MRtqRnVBvZi04pMEw4F:-MRuKgfXEI0bFwwggA5i:b-896fix) ([raw file](https://github.com/pmem/fio/blob/95f21709320e6d7bb17cd73ab46f00877a1f80dd/engines/librpma_fio.h#L248)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is an artifact. Only this declaration remains.
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 2 at r2](https://reviewable.io/reviews/pmem/fio/189#-MRu5qdNDH25VaVqV_q2:-MRuKiI2EHeFqGCscrUk:b-896fix) ([raw file](https://github.com/pmem/fio/blob/95f21709320e6d7bb17cd73ab46f00877a1f80dd/engines/librpma_fio.c#L2)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> engine's
> ```

.
</blockquote></details>

Done.
___
*[engines/librpma_fio.c, line 2 at r2](https://reviewable.io/reviews/pmem/fio/189#-MRu5u50CthNXoOINfqQ:-MRuKjB8DOQ0Uv9y_6AV:b-896fix) ([raw file](https://github.com/pmem/fio/blob/95f21709320e6d7bb17cd73ab46f00877a1f80dd/engines/librpma_fio.c#L2)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  common.
> ```

Maybe `common part.`?  - 'common' is an adjective, not a noun.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/189)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/189)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/189)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi and @ldorau)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/189)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/189)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/189#-:-MRuNUNA5Ce79bJdnMza:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/189#-:-MRuNd068PtbwEEpIv9S:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
