### PR TITLE
aof: add librpma_aof_* examples

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/246)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/246)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[examples/librpma_aof-client.fio, line 15 at r1](https://reviewable.io/reviews/pmem/fio/246#-MUre57M99mQa7qJUDH1:-MUre57M99mQa7qJUDH2:b-hkhgg2) ([raw file](https://github.com/pmem/fio/blob/00a77b2d9fc427b75ce7972813852111195a0b4d/examples/librpma_aof-client.fio#L15)):*
> ```
> [client]
> mode=sw #software-based (using SEND/RECV) commission of an append
> #mode=hw #hardware-based (using FLUSH/ATOMIC_WRITE/FLUSH) execution of an append
> ```

```
# 'sw' for software-based (using SEND/RECV) commission of an append
# 'hw' for hardware-based (using FLUSH/ATOMIC_WRITE/FLUSH) execution of an append
mode=sw
```
___
*[examples/librpma_aof-client.fio, line 21 at r1](https://reviewable.io/reviews/pmem/fio/246#-MUrdKia0oojF-PQcaop:-MUrdKia0oojF-PQcaoq:b-1kkeen) ([raw file](https://github.com/pmem/fio/blob/00a77b2d9fc427b75ce7972813852111195a0b4d/examples/librpma_aof-client.fio#L21)):*
> ```
> iodepth=2 # total number of ious
> iodepth_batch_submit=1 # number of ious to be submitted at once
> rw=write # write
> ```

This comment introduces not much new information. ;-)
___
*[examples/librpma_aof-server.fio, line 21 at r1](https://reviewable.io/reviews/pmem/fio/246#-MUreNYYEY4bfo4bKHsi:-MUreNYYEY4bfo4bKHsj:b-xzfxqf) ([raw file](https://github.com/pmem/fio/blob/00a77b2d9fc427b75ce7972813852111195a0b4d/examples/librpma_aof-server.fio#L21)):*
> ```
> [server]
> mode=sw #software-based (using SEND/RECV) commission of an append
> #mode=hw #hardware-based (using FLUSH/ATOMIC_WRITE/FLUSH) execution of an append
> ```

```
# 'sw' for software-based (using SEND/RECV) commission of an append
# 'hw' for hardware-based (using FLUSH/ATOMIC_WRITE/FLUSH) execution of an append
# 'hw' requires 'direct_write_to_pmem=1'
mode=sw
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/246)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[examples/librpma_aof-client.fio, line 15 at r1](https://reviewable.io/reviews/pmem/fio/246#-MUre57M99mQa7qJUDH1:-MUrhjvT4mxJzSWgxee4:b-896fix) ([raw file](https://github.com/pmem/fio/blob/00a77b2d9fc427b75ce7972813852111195a0b4d/examples/librpma_aof-client.fio#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
# 'sw' for software-based (using SEND/RECV) commission of an append
# 'hw' for hardware-based (using FLUSH/ATOMIC_WRITE/FLUSH) execution of an append
mode=sw
```
</blockquote></details>

Done.
___
*[examples/librpma_aof-client.fio, line 21 at r1](https://reviewable.io/reviews/pmem/fio/246#-MUrdKia0oojF-PQcaop:-MUrhnb7DP1BGaRjadDX:b-896fix) ([raw file](https://github.com/pmem/fio/blob/00a77b2d9fc427b75ce7972813852111195a0b4d/examples/librpma_aof-client.fio#L21)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This comment introduces not much new information. ;-)
</blockquote></details>

Done.
___
*[examples/librpma_aof-server.fio, line 21 at r1](https://reviewable.io/reviews/pmem/fio/246#-MUreNYYEY4bfo4bKHsi:-MUrhw_gCUgA_Crmx_vR:b-896fix) ([raw file](https://github.com/pmem/fio/blob/00a77b2d9fc427b75ce7972813852111195a0b4d/examples/librpma_aof-server.fio#L21)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
# 'sw' for software-based (using SEND/RECV) commission of an append
# 'hw' for hardware-based (using FLUSH/ATOMIC_WRITE/FLUSH) execution of an append
# 'hw' requires 'direct_write_to_pmem=1'
mode=sw
```
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/246#-:-MUrnY639szK72sOmDRw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/246)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[examples/librpma_aof-client.fio, line 6 at r2](https://reviewable.io/reviews/pmem/fio/246#-MUs3BpGANza2afx5j0u:-MUs3BpGANza2afx5j0v:b-nwzlb5) ([raw file](https://github.com/pmem/fio/blob/2ad3b3cb48edaca073daae95533b67c934f55428/examples/librpma_aof-client.fio#L6)):*
> ```
> #IP
> ```

add a space: `# IP`
___
*[examples/librpma_aof-server.fio, line 7 at r2](https://reviewable.io/reviews/pmem/fio/246#-MUs3VoL0tuV9tTv0gM6:-MUs3VoL0tuV9tTv0gM7:bhsag2r) ([raw file](https://github.com/pmem/fio/blob/2ad3b3cb48edaca073daae95533b67c934f55428/examples/librpma_aof-server.fio#L7)):*
> ```
> #IP
> ```

.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/246)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/246#-:-MUs3yM12LZzovrFaiKM:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/246)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/246)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[examples/librpma_aof-client.fio, line 6 at r2](https://reviewable.io/reviews/pmem/fio/246#-MUs3BpGANza2afx5j0u:-MUs5ipjEgdfjV6AahO2:b-896fix) ([raw file](https://github.com/pmem/fio/blob/2ad3b3cb48edaca073daae95533b67c934f55428/examples/librpma_aof-client.fio#L6)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> #IP
> ```

add a space: `# IP`
</blockquote></details>

Done.
___
*[examples/librpma_aof-server.fio, line 7 at r2](https://reviewable.io/reviews/pmem/fio/246#-MUs3VoL0tuV9tTv0gM6:-MUs5nHIA32TpTRMPmm2:b-896fix) ([raw file](https://github.com/pmem/fio/blob/2ad3b3cb48edaca073daae95533b67c934f55428/examples/librpma_aof-server.fio#L7)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> #IP
> ```

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/246)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/246#-:-MUwKL1O9boAkPBUTfkj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
