### PR TITLE
examples: librpma client and server - sprint 01

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/5)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/5)* status: all files reviewed, 10 unresolved discussions (waiting on @janekmi)

___
*[examples/librpma-client.fio, line 1 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQjAh86LdnV8jyYpIa:-MJQjAh86LdnV8jyYpIb:bhpz1uf) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-client.fio#L1)):*
> ```
> Example librpma
> ```

Example of the librpma
___
*[examples/librpma-client.fio, line 4 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQjXG5DpfzOfiBdEz3:-MJQjXG5DpfzOfiBdEz4:b-y4pcv5) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-client.fio#L4)):*
> ```
> server's listening IP address
> ```

IP address the server is listening on
___
*[examples/librpma-client.fio, line 5 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQjbOO1z_KnvFPgrWM:-MJQjbOO1z_KnvFPgrWN:bagz0wj) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-client.fio#L5)):*
> ```
> server's listening port
> ```

port the server is listening on
___
*[examples/librpma-client.fio, line 6 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQjM0fDpZJ5NEeXKyi:-MJQjM0fDpZJ5NEeXKyj:b-ixfyn) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-client.fio#L6)):*
> ```
> hostname=[server's listening IP address] 
> port=[server's listening port]
> ```

`threads` ? (with a comment why - Is it required or optional?)
___
*[examples/librpma-client.fio, line 8 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQjiMIDbTSFngxBOnC:-MJQjiMIDbTSFngxBOnD:babeed1) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-client.fio#L8)):*
> ```
> # The client after establishing a connection will get a remote memory region
> # description. 
> ```

The client will get a remote memory region description after establishing a connection.
___
*[examples/librpma-server.fio, line 1 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQjDFeCCS-t426nnWP:-MJQjDFeCCS-t426nnWQ:b-3mv8ka) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-server.fio#L1)):*
> ```
>  Example librpma
> ```

.
___
*[examples/librpma-server.fio, line 4 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQkHLS0tGqKRX_p51u:-MJQkHLS0tGqKRX_p51v:b-yvh2mt) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-server.fio#L4)):*
> ```
> IP to listen on
> ```

IP address to listen on
___
*[examples/librpma-server.fio, line 7 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQkLm3CvqPtjsCTrhR:-MJQkLm3CvqPtjsCTrhS:b-x75rkk) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-server.fio#L7)):*
> ```
> will spawn
> ```

spawns
___
*[examples/librpma-server.fio, line 8 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQkPMh-wZe6keJ7cL1:-MJQkPMh-wZe6keJ7cL2:b-2hkwx8) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-server.fio#L8)):*
> ```
> will accept
> ```

accepts
___
*[examples/librpma-server.fio, line 9 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQkSNa4Y4l7L3Wtz6l:-MJQkSNa4Y4l7L3Wtz6m:b-im7ucs) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-server.fio#L9)):*
> ```
> close
> ```

closes

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/5)* status: 0 of 2 files reviewed, 10 unresolved discussions (waiting on @ldorau)

___
*[examples/librpma-client.fio, line 1 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQjAh86LdnV8jyYpIa:-MJQlONuDEkdxtvkJvpl:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-client.fio#L1)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Example librpma
> ```

Example of the librpma
</blockquote></details>

Done.
___
*[examples/librpma-client.fio, line 4 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQjXG5DpfzOfiBdEz3:-MJQl_Zt-GAzN_czs1Yz:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-client.fio#L4)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> server's listening IP address
> ```

IP address the server is listening on
</blockquote></details>

Done.
___
*[examples/librpma-client.fio, line 5 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQjbOO1z_KnvFPgrWM:-MJQlejU1YvgcxIIVfMe:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-client.fio#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> server's listening port
> ```

port the server is listening on
</blockquote></details>

Done.
___
*[examples/librpma-client.fio, line 6 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQjM0fDpZJ5NEeXKyi:-MJQlgYtELvyoguOs1OX:b-fr6o6y) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-client.fio#L6)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`threads` ? (with a comment why - Is it required or optional?)
</blockquote></details>

No. For this sprint, we will have a single thread.
___
*[examples/librpma-client.fio, line 8 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQjiMIDbTSFngxBOnC:-MJQmKDZAfuLUKWlFi5b:b-3iyn73) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-client.fio#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> # The client after establishing a connection will get a remote memory region
> # description. 
> ```

The client will get a remote memory region description after establishing a connection.

</blockquote></details>

This sentence is from the world where we will have more than one connection. I will fix it for #2.
___
*[examples/librpma-server.fio, line 1 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQjDFeCCS-t426nnWP:-MJQoAv23B7WEmZFMTr7:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-server.fio#L1)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  Example librpma
> ```

.
</blockquote></details>

Done.
___
*[examples/librpma-server.fio, line 4 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQkHLS0tGqKRX_p51u:-MJQoBrm3peYdRg4q2q5:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-server.fio#L4)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> IP to listen on
> ```

IP address to listen on
</blockquote></details>

Done.
___
*[examples/librpma-server.fio, line 7 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQkLm3CvqPtjsCTrhR:-MJQoHDE3GfW2-ZlIRvW:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-server.fio#L7)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> will spawn
> ```

spawns
</blockquote></details>

Done.
___
*[examples/librpma-server.fio, line 8 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQkPMh-wZe6keJ7cL1:-MJQoJXWCfHz-h9QNWex:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-server.fio#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> will accept
> ```

accepts
</blockquote></details>

Done.
___
*[examples/librpma-server.fio, line 9 at r1](https://reviewable.io/reviews/pmem/fio/5#-MJQkSNa4Y4l7L3Wtz6l:-MJQoL0L6TRpvMBMBjlR:b-896fix) ([raw file](https://github.com/pmem/fio/blob/6f88c0b44087240696cb82f89b75fa9d2918eb83/examples/librpma-server.fio#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> close
> ```

closes
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/5)* status: all files reviewed, 12 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[examples/librpma-client.fio, line 10 at r2](https://reviewable.io/reviews/pmem/fio/5#-MJQw7yTEzaCjIm3EPVW:-MJQw7yU2QsPBJ5XCNek:bix4uj0) ([raw file](https://github.com/pmem/fio/blob/af03acaba28469618f3668d514ce5121fe98938a/examples/librpma-client.fio#L10)):*
> ```
> clients
> ```
client
___
*[examples/librpma-server.fio, line 12 at r2](https://reviewable.io/reviews/pmem/fio/5#-MJQvwaM1M8nMI9LLaBg:-MJQvwaN9c5RQIlUmCvX:b-gt72pg) ([raw file](https://github.com/pmem/fio/blob/af03acaba28469618f3668d514ce5121fe98938a/examples/librpma-server.fio#L12)):*
> ```
> [server]
> filename=[XXX device dax or an existing fsdax file]
> ```
Shall we use mmap instead of file? - or sleep it for this sprint?

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/5)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/5)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[examples/librpma-client.fio, line 10 at r2](https://reviewable.io/reviews/pmem/fio/5#-MJQw7yTEzaCjIm3EPVW:-MJR5-h9BMiQXy9Bl8ls:b-896fix) ([raw file](https://github.com/pmem/fio/blob/af03acaba28469618f3668d514ce5121fe98938a/examples/librpma-client.fio#L10)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> clients
> ```
client
</blockquote></details>

Done.
___
*[examples/librpma-server.fio, line 12 at r2](https://reviewable.io/reviews/pmem/fio/5#-MJQvwaM1M8nMI9LLaBg:-MJR4SYx6_45N7OVP8Ft:b-z3q0s2) ([raw file](https://github.com/pmem/fio/blob/af03acaba28469618f3668d514ce5121fe98938a/examples/librpma-server.fio#L12)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> [server]
> filename=[XXX device dax or an existing fsdax file]
> ```
Shall we use mmap instead of file? - or sleep it for this sprint?
</blockquote></details>

Really, opening a file using `pmem_map_file()` is so easy I can not imagine doing it any easier.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/5)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/5)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[examples/librpma-client.fio, line 10 at r2](https://reviewable.io/reviews/pmem/fio/5#-MJQw7yTEzaCjIm3EPVW:-MJRB7n_896n_MCRCH2W:b-ttapas) ([raw file](https://github.com/pmem/fio/blob/af03acaba28469618f3668d514ce5121fe98938a/examples/librpma-client.fio#L10)):*
> ```
> [client]
> ```
OK 
but seems to be not needed tag
___
*[examples/librpma-server.fio, line 12 at r2](https://reviewable.io/reviews/pmem/fio/5#-MJQvwaM1M8nMI9LLaBg:-MJRBOTp92agHE2kVu0a:b6vhk3u) ([raw file](https://github.com/pmem/fio/blob/af03acaba28469618f3668d514ce5121fe98938a/examples/librpma-server.fio#L12)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Really, opening a file using `pmem_map_file()` is so easy I can not imagine doing it any easier.
</blockquote></details>

OK 
not needed now, but I understand we can follow  libpmem fio engine

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/5#-:-MJRFH1b0wetvgBBFSVb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/5)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[examples/librpma-client.fio, line 10 at r2](https://reviewable.io/reviews/pmem/fio/5#-MJQw7yTEzaCjIm3EPVW:-MJRFY39DA5exzRFxzCp:bc8che0) ([raw file](https://github.com/pmem/fio/blob/af03acaba28469618f3668d514ce5121fe98938a/examples/librpma-client.fio#L10)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> [client]
> ```
OK 
but seems to be not needed tag
</blockquote></details>

As far as I know, fio requires at least a single job section otherwise no job would be started.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/5#-:-MJRHI2ZD_yWp-fMY0EZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/5#-:-MJRJ2L7ANv_IO3Ga5uU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
