### PR TITLE
rpma: common: server_data, server_init & server_cleanup

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/140)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/140)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_common.h, line 136 at r1](https://reviewable.io/reviews/pmem/fio/140#-MRK_a6wDXxXD-XOACmH:-MRK_a6xANi3DlIAPSOv:b-8uxep8) ([raw file](https://github.com/pmem/fio/blob/22c3c608b9fa353826d5a3f4a92fa88353b1d661/engines/librpma_common.h#L136)):*
> ```
> client
> ```
```server``` ?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/140)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_common.h, line 136 at r1](https://reviewable.io/reviews/pmem/fio/140#-MRK_a6wDXxXD-XOACmH:-MRKapqB2BnR_PLX2ZTd:b-896fix) ([raw file](https://github.com/pmem/fio/blob/22c3c608b9fa353826d5a3f4a92fa88353b1d661/engines/librpma_common.h#L136)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> client
> ```
```server``` ?
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/140#-:-MRKayMm564FlHUb-TjF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/140)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/140#-:-MRKhNA448-7iahlDSMa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
please rebase

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/140#-:-MRKhPJoBWVVtayDt6_A:bymv1jp)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/140)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/140)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/140#-:-MRKqln34jougatjm6SA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
