### PR TITLE
rpma: implement client_post_init()

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/14)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
Great job! Only one small fix needed. :+1: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/14#-:-MJWCfDM8YnL5_qWRM1i:b-zfhflb)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma.c, line 23 at r1](https://reviewable.io/reviews/pmem/fio/14#-MJWCMrcA8xe_IukQ_1X:-MJWCMrcA8xe_IukQ_1Y:b-8fx2u7) ([raw file](https://github.com/pmem/fio/blob/11a08df0edcb70b55dd75a1c3425be822cecbee7/engines/librpma.c#L23)):*
> ```C
> 
> #define rpma_td_verror(td, err, func) \
> 	td_vmsg((td), (err), rpma_err_2str(err), (func))
> ```

:+1: 
___
*[engines/librpma.c, line 63 at r1](https://reviewable.io/reviews/pmem/fio/14#-MJWCR-w2DEf0bBLVDML:-MJWCR-w2DEf0bBLVDMM:b-8zjfjy) ([raw file](https://github.com/pmem/fio/blob/11a08df0edcb70b55dd75a1c3425be822cecbee7/engines/librpma.c#L63)):*
> ```C
> 	/* ious's base address memory registration (td->orig_buffer) */
> 	struct rpma_mr_local *orig_mr;
> ```

Redundant new line.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/14)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 63 at r1](https://reviewable.io/reviews/pmem/fio/14#-MJWCR-w2DEf0bBLVDML:-MJWDJM73g7rN7RUBTgO:b-896fix) ([raw file](https://github.com/pmem/fio/blob/11a08df0edcb70b55dd75a1c3425be822cecbee7/engines/librpma.c#L63)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Redundant new line.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/14#-:-MJWDqQf3RB2ngNjnlJ_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/14#-:-MJW_gW58Haws2kyINky:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/14)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
