### PR TITLE
rpma: common: client_cleanup

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #120 
- [x] #123
- [x] #124
- [x] #133

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/125)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/125)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 237 at r2](https://reviewable.io/reviews/pmem/fio/125#-MR5wo8m1j-9rCy2XkP4:-MR5wo8m1j-9rCy2XkP5:bz67d52) ([raw file](https://github.com/pmem/fio/blob/f4e5a1e2083ecdc57c64d3a89ccb6392d463f511/engines/librpma.c#L237)):*
> ```
> librpma_common_client_cleanup(td);
> ```
shall we first clean ccd->client_data?
___
*[engines/librpma_gpspm.c, line 311 at r2](https://reviewable.io/reviews/pmem/fio/125#-MR5xE2A79JJkvwDbIdb:-MR5xE2A79JJkvwDbIdc:bofkz5u) ([raw file](https://github.com/pmem/fio/blob/f4e5a1e2083ecdc57c64d3a89ccb6392d463f511/engines/librpma_gpspm.c#L311)):*
> ```
> librpma_common_client_cleanup(td);
> ```
. (in normal case client_cleanup will free the whole ccd)

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/125#-:-MR63eND1kZcaryPu4X5:bdycpsm)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/125#-:-MR64MTSEjv-l3u1TzkM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/125)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_common.c, line 282 at r3](https://reviewable.io/reviews/pmem/fio/125#-MRJMAZ73lbEaq2vdtKM:-MRJMAZ73lbEaq2vdtKN:b-ftquo9) ([raw file](https://github.com/pmem/fio/blob/420ab481e9efb7c8f29fbdfa29cae5ec15b1b659/engines/librpma_common.c#L282)):*
> ```
> 	free(ccd->io_us_completed);
> }
> ```

It seems that `free(ccd)` is missing here.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/125)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 110 at r3](https://reviewable.io/reviews/pmem/fio/125#-MRJQU1H-7-TSMmTPrTL:-MRJQU1H-7-TSMmTPrTM:bscpf1d) ([raw file](https://github.com/pmem/fio/blob/420ab481e9efb7c8f29fbdfa29cae5ec15b1b659/engines/librpma_gpspm.c#L110)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 	ccd = calloc(1, sizeof(struct librpma_common_client_data));
> 	if (ccd == NULL) {
> 		td_verror(td, errno, "calloc");
> 		return 1;
> 	}
> ```
</details>


It should be removed too.
___
*[engines/librpma_gpspm.c, line 114 at r3](https://reviewable.io/reviews/pmem/fio/125#-MRJQYMa1CW6rZViRAs_:-MRJQYMa1CW6rZViRAsa:b-dp18de) ([raw file](https://github.com/pmem/fio/blob/420ab481e9efb7c8f29fbdfa29cae5ec15b1b659/engines/librpma_gpspm.c#L114)):*
> ```
> free(ccd);
> ```

It should be removed too.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/125)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_common.c, line 234 at r3](https://reviewable.io/reviews/pmem/fio/125#-MRJZyc84sgt5uO4CY6H:-MRJZyc84sgt5uO4CY6I:b-urtn5d) ([raw file](https://github.com/pmem/fio/blob/420ab481e9efb7c8f29fbdfa29cae5ec15b1b659/engines/librpma_common.c#L234)):*
> ```
> free(ccd->io_us_queued);
> ```
```
if(ccd->io_us_queued) 
    free(ccd->io_us_queued);
...
```
and above any calloc failed can be handled by same 
```
goto err_free_io_u_queues:
```
instead of  
```
goto err_free_ccd;
```
___
*[engines/librpma_common.c, line 282 at r3](https://reviewable.io/reviews/pmem/fio/125#-MRJMAZ73lbEaq2vdtKM:-MRJ_YURERPz_TKLRyx2:b2ngthb) ([raw file](https://github.com/pmem/fio/blob/420ab481e9efb7c8f29fbdfa29cae5ec15b1b659/engines/librpma_common.c#L282)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	free(ccd->io_us_completed);
> }
> ```

It seems that `free(ccd)` is missing here.
</blockquote></details>

+1
___
*[engines/librpma_gpspm.c, line 311 at r3](https://reviewable.io/reviews/pmem/fio/125#-MRJa0k88_6FMIuWhtaN:-MRJa0k96RzMzgfJ5c0X:b3vs08y) ([raw file](https://github.com/pmem/fio/blob/420ab481e9efb7c8f29fbdfa29cae5ec15b1b659/engines/librpma_gpspm.c#L311)):*
> ```
> 	free(ccd->client_data);
> ```
free either inside librpma_common_client_cleanup or at least after it

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/125)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 237 at r2](https://reviewable.io/reviews/pmem/fio/125#-MR5wo8m1j-9rCy2XkP4:-MRJbux3EumAuSIrTqjq:boqon95) ([raw file](https://github.com/pmem/fio/blob/f4e5a1e2083ecdc57c64d3a89ccb6392d463f511/engines/librpma.c#L237)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> librpma_common_client_cleanup(td);
> ```
shall we first clean ccd->client_data?
</blockquote></details>

If we assume common has nothing to do with this field e.g. like FIO does with the engine's private data, we should not. It is the APM/GPSPM business to use this field properly.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/125)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_common.c, line 234 at r3](https://reviewable.io/reviews/pmem/fio/125#-MRJZyc84sgt5uO4CY6H:-MRJeN348eccADM1ikto:b-2sf3x7) ([raw file](https://github.com/pmem/fio/blob/420ab481e9efb7c8f29fbdfa29cae5ec15b1b659/engines/librpma_common.c#L234)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> free(ccd->io_us_queued);
> ```
```
if(ccd->io_us_queued) 
    free(ccd->io_us_queued);
...
```
and above any calloc failed can be handled by same 
```
goto err_free_io_u_queues:
```
instead of  
```
goto err_free_ccd;
```
</blockquote></details>

You recommend removing three lines and adding three lines here for what reason?
___
*[engines/librpma_common.c, line 282 at r3](https://reviewable.io/reviews/pmem/fio/125#-MRJMAZ73lbEaq2vdtKM:-MRJdI-g5BLV_Njn5Xe-:b-896fix) ([raw file](https://github.com/pmem/fio/blob/420ab481e9efb7c8f29fbdfa29cae5ec15b1b659/engines/librpma_common.c#L282)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 110 at r3](https://reviewable.io/reviews/pmem/fio/125#-MRJQU1H-7-TSMmTPrTL:-MRJd_gBBZaPjOrWiP4H:b-896fix) ([raw file](https://github.com/pmem/fio/blob/420ab481e9efb7c8f29fbdfa29cae5ec15b1b659/engines/librpma_gpspm.c#L110)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	ccd = calloc(1, sizeof(struct librpma_common_client_data));
> 	if (ccd == NULL) {
> 		td_verror(td, errno, "calloc");
> 		return 1;
> 	}
> ```

It should be removed too.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 114 at r3](https://reviewable.io/reviews/pmem/fio/125#-MRJQYMa1CW6rZViRAs_:-MRJdfg_BexX6hyF1bYn:b-896fix) ([raw file](https://github.com/pmem/fio/blob/420ab481e9efb7c8f29fbdfa29cae5ec15b1b659/engines/librpma_gpspm.c#L114)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> free(ccd);
> ```

It should be removed too.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 311 at r3](https://reviewable.io/reviews/pmem/fio/125#-MRJa0k88_6FMIuWhtaN:-MRJdy7M0EPYk13hv1Di:bisrd4q) ([raw file](https://github.com/pmem/fio/blob/420ab481e9efb7c8f29fbdfa29cae5ec15b1b659/engines/librpma_gpspm.c#L311)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 	free(ccd->client_data);
> ```
free either inside librpma_common_client_cleanup or at least after it
</blockquote></details>

Why after? What is the point? Do you have no problem with the same order in the APM implementation?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/125)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_common.c, line 234 at r3](https://reviewable.io/reviews/pmem/fio/125#-MRJZyc84sgt5uO4CY6H:-MRJjA2r84s8IQT_ci9T:b-804x9t) ([raw file](https://github.com/pmem/fio/blob/420ab481e9efb7c8f29fbdfa29cae5ec15b1b659/engines/librpma_common.c#L234)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You recommend removing three lines and adding three lines here for what reason?
</blockquote></details>

for simplicity and only one place for error handling

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/125)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_common.c, line 234 at r3](https://reviewable.io/reviews/pmem/fio/125#-MRJZyc84sgt5uO4CY6H:-MRJkCpn-fshq7U4Wbj8:b-896fix) ([raw file](https://github.com/pmem/fio/blob/420ab481e9efb7c8f29fbdfa29cae5ec15b1b659/engines/librpma_common.c#L234)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

for simplicity and only one place for error handling
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/125#-:-MRJli553ELX-7iQTQhY:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/125#-:-MRJniU08wSRVq3stHkL:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 4 files at r5, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/125)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/125#-:-MRJvhdBEr9qJPcOhZzg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
