### PR TITLE
rpma: start listening ASAP

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/117)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/117)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/117#-:-MR-tGQr34WxWJ4juBJo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/117#-:-MR-uu670NR_bw5Div_K:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
@janekmi please rebase

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/117#-:-MR-uwxw0-tN1FqgKp5M:b-f7mnt4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/117)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 1158 at r2](https://reviewable.io/reviews/pmem/fio/117#-MR-zLUn-FoylzLMFm88:-MR-zLUn-FoylzLMFm89:bpji1sv) ([raw file](https://github.com/pmem/fio/blob/a8508a4a2b463dca2226bbe90cd411fb499d620c/engines/librpma_gpspm.c#L1158)):*
> ```
> rpma_td_verror(td, ret, "rpma_ep_listen");
> ```

Why isn't it `librpma_td_verror()` ?
___
*[engines/librpma_gpspm.c, line 1196 at r2](https://reviewable.io/reviews/pmem/fio/117#-MR-zS-91KK8hNb65OdH:-MR-zS-91KK8hNb65OdI:b-ecliel) ([raw file](https://github.com/pmem/fio/blob/a8508a4a2b463dca2226bbe90cd411fb499d620c/engines/librpma_gpspm.c#L1196)):*
> ```
> rpma_td_verror(td, ret, "rpma_conn_cfg_new");
> ```

.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/117)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 1158 at r2](https://reviewable.io/reviews/pmem/fio/117#-MR-zLUn-FoylzLMFm88:-MR0-sh9919kePK2LUq7:b-896fix) ([raw file](https://github.com/pmem/fio/blob/a8508a4a2b463dca2226bbe90cd411fb499d620c/engines/librpma_gpspm.c#L1158)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rpma_td_verror(td, ret, "rpma_ep_listen");
> ```

Why isn't it `librpma_td_verror()` ?
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 1196 at r2](https://reviewable.io/reviews/pmem/fio/117#-MR-zS-91KK8hNb65OdH:-MR0-oFg1pk4II1kEQ5v:b-896fix) ([raw file](https://github.com/pmem/fio/blob/a8508a4a2b463dca2226bbe90cd411fb499d620c/engines/librpma_gpspm.c#L1196)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rpma_td_verror(td, ret, "rpma_conn_cfg_new");
> ```

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/117#-:-MR02pCf39Q162HSYiA6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
