### PR TITLE
rpma: add RPMA engines option

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/194)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/194)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

___
*[fio.1, line 1903 at r1](https://reviewable.io/reviews/pmem/fio/194#-MS326n72SGPTX4uR-mw:-MS31i5B1BIs1Ycu0Vei:b-gyzn9u) ([raw file](https://github.com/pmem/fio/blob/519ad3aca839c11a874106abd2c629b9151c00bf/fio.1#L1903)):*
> ```Roff
> ports.
> .TP
> .BI (rdma, librpma_apm, librpma_gpspm)port
> ```

If we would like to be specific we should enumerate all engines with both variants (client and server). I think we can use wildcards here `librpma_*`. Broad enough, concise and sticks to reality.
___
*[fio.1, line 1912 at r1](https://reviewable.io/reviews/pmem/fio/194#-MS32cxhB3HdO6ccCraI:-MS32cxhB3HdO6ccCraJ:b-xvwlev) ([raw file](https://github.com/pmem/fio/blob/519ad3aca839c11a874106abd2c629b9151c00bf/fio.1#L1912)):*
> ```Roff
> and must be omitted unless it is a valid UDP multicast address.
> .TP
> .BI (librpma_apm, librpma_gpspm)serverip \fR=\fPstr
> ```

`librpma_*`
___
*[fio.1, line 1915 at r1](https://reviewable.io/reviews/pmem/fio/194#-MS32hP10rjmdVLnz-jM:-MS32hP10rjmdVLnz-jN:bilqe4a) ([raw file](https://github.com/pmem/fio/blob/519ad3aca839c11a874106abd2c629b9151c00bf/fio.1#L1915)):*
> ```Roff
> The IP address to use for RDMA-CM based I/O.
> .TP
> .BI (librpma_apm, librpma_gpspm)direct_write_to_pmem \fR=\fPint
> ```

`librpma_*_server`?
___
*[fio.1, line 1915 at r1](https://reviewable.io/reviews/pmem/fio/194#-MS32ijz7vd30grTgS1p:-MS32ijz7vd30grTgS1q:bb7dsof) ([raw file](https://github.com/pmem/fio/blob/519ad3aca839c11a874106abd2c629b9151c00bf/fio.1#L1915)):*
> ```Roff
> The IP address to use for RDMA-CM based I/O.
> .TP
> .BI (librpma_apm, librpma_gpspm)direct_write_to_pmem \fR=\fPint
> ```

bool
___
*[fio.1, line 1916 at r1](https://reviewable.io/reviews/pmem/fio/194#-MS33Q1oCb5lA9aH4Yxf:-MS33Q1oCb5lA9aH4Yxg:b9nke27) ([raw file](https://github.com/pmem/fio/blob/519ad3aca839c11a874106abd2c629b9151c00bf/fio.1#L1916)):*
> Has to be specified. No default.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/194)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[fio.1, line 1903 at r1](https://reviewable.io/reviews/pmem/fio/194#-MS326n72SGPTX4uR-mw:-MS38AeS0MBXWE8WL40k:b-896fix) ([raw file](https://github.com/pmem/fio/blob/519ad3aca839c11a874106abd2c629b9151c00bf/fio.1#L1903)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If we would like to be specific we should enumerate all engines with both variants (client and server). I think we can use wildcards here `librpma_*`. Broad enough, concise and sticks to reality.
</blockquote></details>

Done.
___
*[fio.1, line 1912 at r1](https://reviewable.io/reviews/pmem/fio/194#-MS32cxhB3HdO6ccCraI:-MS38E10-LZ4K0gRPoPW:b-896fix) ([raw file](https://github.com/pmem/fio/blob/519ad3aca839c11a874106abd2c629b9151c00bf/fio.1#L1912)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`librpma_*`
</blockquote></details>

Done.
___
*[fio.1, line 1915 at r1](https://reviewable.io/reviews/pmem/fio/194#-MS32hP10rjmdVLnz-jM:-MS38JkkBvd-c3-YN9DV:b-896fix) ([raw file](https://github.com/pmem/fio/blob/519ad3aca839c11a874106abd2c629b9151c00bf/fio.1#L1915)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`librpma_*_server`?
</blockquote></details>

Done.
___
*[fio.1, line 1915 at r1](https://reviewable.io/reviews/pmem/fio/194#-MS32ijz7vd30grTgS1p:-MS38V1016MHzP5DpLfa:b-896fix) ([raw file](https://github.com/pmem/fio/blob/519ad3aca839c11a874106abd2c629b9151c00bf/fio.1#L1915)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

bool
</blockquote></details>

Done.
___
*[fio.1, line 1916 at r1](https://reviewable.io/reviews/pmem/fio/194#-MS33Q1oCb5lA9aH4Yxf:-MS39Ig-4f3O-VrO93BZ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/519ad3aca839c11a874106abd2c629b9151c00bf/fio.1#L1916)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> Has to be specified. No default.
</blockquote></details>

Done.

**Comment by ldorau** [comment]
Please rebase

**Review by osalyk — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/194#-:-MS3DFy5CA5mbbGXO6CF:b-896fix)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/194)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/194#-:-MS3F5zN9OYWcSnkAffn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/194)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[fio.1, line 1913 at r2](https://reviewable.io/reviews/pmem/fio/194#-MS3Fa6hBiMSarCelFCV:-MS3Fa6hBiMSarCelFCW:b-lvolv2) ([raw file](https://github.com/pmem/fio/blob/f5517b6ed55a80576d0cca940309b6fc2882f7c6/fio.1#L1913)):*
> ```
>  to use for
> ```

 to be used for

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/194)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[fio.1, line 1913 at r2](https://reviewable.io/reviews/pmem/fio/194#-MS3Fa6hBiMSarCelFCV:-MS3Hc803hI3icqmvlGg:b-896fix) ([raw file](https://github.com/pmem/fio/blob/f5517b6ed55a80576d0cca940309b6fc2882f7c6/fio.1#L1913)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  to use for
> ```

 to be used for
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/194)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/194#-:-MS3IDLy3KseiJ27f_ol:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
