### PR TITLE
rpma: define the last message the client has to send when it is done

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #62

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/64)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/64)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/64#-MMQA2Hz-CuSlSOE_RgJ:-MMQA2Hz-CuSlSOE_RgK:bf3ub2h) (no related file):*
Because it is a protocol between client and server I suggest creating a define or const for the client with all required values in a place called "when_the_client_is_done_it_has_to_send_this_message". ;-)

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/64)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/64#-MMQA2Hz-CuSlSOE_RgJ:-MMR0UBSEXSsF1303t93:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Because it is a protocol between client and server I suggest creating a define or const for the client with all required values in a place called "when_the_client_is_done_it_has_to_send_this_message". ;-)
</blockquote></details>

Done.

---

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/64)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 51 at r2](https://reviewable.io/reviews/pmem/fio/64#-MMSvOpUDAwua6I_MnH_:-MMSvOpUDAwua6I_MnHa:b9a7s9a) ([raw file](https://github.com/pmem/fio/blob/ef3f7934ebd511ac3e6d014f244d93b8b5f85959/engines/librpma_gpspm.c#L51)):*
> ```C
> #define IS_NOT_THE_LAST_MESSAGE(flush_req) \
> 	(flush_req->length != Flush_req_last.length || \
> 	flush_req->offset != Flush_req_last.offset)
> ```

Don't you think it will be easier to comprehend a simple condition instead of something which starts from `is not`?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/64)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 51 at r2](https://reviewable.io/reviews/pmem/fio/64#-MMSvOpUDAwua6I_MnH_:-MMUg-rmDmsXSgMtbNh3:b-w3l1jw) ([raw file](https://github.com/pmem/fio/blob/ef3f7934ebd511ac3e6d014f244d93b8b5f85959/engines/librpma_gpspm.c#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Don't you think it will be easier to comprehend a simple condition instead of something which starts from `is not`?
</blockquote></details>

Yes, I agree that it would be easier to comprehend, but I think the current code is faster, because only one condition (`flush_req->length != Flush_req_last.length`) will be evaluated in most cases now, while after the change two conditions will have to be evaluated always: `(flush_req->length == Flush_req_last.length && flush_req->offset == Flush_req_last.offset)`.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/64#-:-MM_aon93-hI0laBuA5X:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/64#-:-MM_bdUl00eBKOxSjuLs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
