### PR TITLE
rpma: do not use memory allocation hooks

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/110)

### CODE REVIEW

**Comment by ldorau** [comment]
The APM server fails for DAX devices with the "failed getting offset" error:
```
Starting 1 thread
io       726304 invalidate librpma_server cache /dev/dax1.0
io       726304 io_u 0x7f265003a680, failed getting offset
io       726304 io_u 0x7f265003a680, setting file failed
io       726304 get_io_u failed
io       726304 close ioengine librpma_server
io       726304 free ioengine librpma_server
```

**Comment by ldorau** [comment]
It works OK now

**Comment by ldorau** [comment]
It is connected with: https://github.com/pmem/rpma/pull/740

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/110)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 1174 at r1](https://reviewable.io/reviews/pmem/fio/110#-MQrOHt96pc1w57ES4v8:-MQrOHtA0ykE4m4XE2IP:blaljs9) ([raw file](https://github.com/pmem/fio/blob/caabe7f73cef33c2e5299449a7c403aa2d965753/engines/librpma.c#L1174)):*
> ```
> return (ret != 0 ? ret : 1);
> ```
```
return 1;
```
Do we need any error indication here? Or just 0 for OK and 1 for error?
___
*[examples/librpma-server.fio, line 21 at r1](https://reviewable.io/reviews/pmem/fio/110#-MQrOtdp44OGacqyaclr:-MQrOtdp44OGacqyacls:btolneu) ([raw file](https://github.com/pmem/fio/blob/caabe7f73cef33c2e5299449a7c403aa2d965753/examples/librpma-server.fio#L21)):*
> ```
> malloc
> ```
would it be possible to use just "" (empty string) instead of malloc?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/110)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[engines/librpma.c, line 1174 at r1](https://reviewable.io/reviews/pmem/fio/110#-MQrOHt96pc1w57ES4v8:-MQuW0g845oq8FZWWdBv:bagkvzz) ([raw file](https://github.com/pmem/fio/blob/caabe7f73cef33c2e5299449a7c403aa2d965753/engines/librpma.c#L1174)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> return (ret != 0 ? ret : 1);
> ```
```
return 1;
```
Do we need any error indication here? Or just 0 for OK and 1 for error?
</blockquote></details>

Just like in https://github.com/pmem/fio/pull/108 - it is always better to pass the real error value, because it can be used in the upper layers (or printed out at least).
___
*[examples/librpma-server.fio, line 21 at r1](https://reviewable.io/reviews/pmem/fio/110#-MQrOtdp44OGacqyaclr:-MQuV6xc88RjTD3KDanG:b-jliu9y) ([raw file](https://github.com/pmem/fio/blob/caabe7f73cef33c2e5299449a7c403aa2d965753/examples/librpma-server.fio#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> malloc
> ```
would it be possible to use just "" (empty string) instead of malloc?
</blockquote></details>

Probably not, because fio creates and inserts its own name, something like `server0.0`.

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/110#-:-MQunUxi1dXUEqZYXcUu:bdycpsm)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 1174 at r1](https://reviewable.io/reviews/pmem/fio/110#-MQrOHt96pc1w57ES4v8:-MQumIOi40DAlcwET_kN:byadkek) ([raw file](https://github.com/pmem/fio/blob/caabe7f73cef33c2e5299449a7c403aa2d965753/engines/librpma.c#L1174)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Just like in https://github.com/pmem/fio/pull/108 - it is always better to pass the real error value, because it can be used in the upper layers (or printed out at least).
</blockquote></details>

Fio does not use feedback from tis function in any way:
```
if (td->io_ops->open_file(td, f)) 
```
___
*[examples/librpma-server.fio, line 21 at r1](https://reviewable.io/reviews/pmem/fio/110#-MQrOtdp44OGacqyaclr:-MQunCG43_KACF571l57:b-iz0ors) ([raw file](https://github.com/pmem/fio/blob/caabe7f73cef33c2e5299449a7c403aa2d965753/examples/librpma-server.fio#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Probably not, because fio creates and inserts its own name, something like `server0.0`.
</blockquote></details>

What about an alternative solution that malloc is used as a fallback if the file does not provide access to PMem?

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/110)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 1124 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQunirM9BCtn-HHJIlj:-MQunirN5Hysq_69lh-4:blgf3ve) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1124)):*
> ```
> f->real_file_size = io_us_size;
> ```
according to fio source code (filesetup.c L1016):
	/*
	 * Find out physical size of files or devices for this thread,
	 * before we determine I/O size and range of our targets.
	 * If ioengine defines a setup() method, it's responsible for
	 * opening the files and setting f->real_file_size to indicate
	 * the valid range for that file.
	 */
and there is an example cross-stripe-verify.fio that shows how to split one file into several chunks

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/110)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 1174 at r1](https://reviewable.io/reviews/pmem/fio/110#-MQrOHt96pc1w57ES4v8:-MQuqL7a7D6lw_KM_zMn:b-6km4ks) ([raw file](https://github.com/pmem/fio/blob/caabe7f73cef33c2e5299449a7c403aa2d965753/engines/librpma.c#L1174)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Fio does not use feedback from tis function in any way:
```
if (td->io_ops->open_file(td, f)) 
```
</blockquote></details>

So the current code is correct. It is safer and easier to use the always-correct-formula.
___
*[engines/librpma.c, line 1124 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQunirM9BCtn-HHJIlj:-MQup_zW-fqv05-ITF-4:b-8n0l6l) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1124)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> f->real_file_size = io_us_size;
> ```
according to fio source code (filesetup.c L1016):
	/*
	 * Find out physical size of files or devices for this thread,
	 * before we determine I/O size and range of our targets.
	 * If ioengine defines a setup() method, it's responsible for
	 * opening the files and setting f->real_file_size to indicate
	 * the valid range for that file.
	 */
and there is an example cross-stripe-verify.fio that shows how to split one file into several chunks


</blockquote></details>

What do you mean? What is wrong here? Why? What chunks?
___
*[examples/librpma-server.fio, line 21 at r1](https://reviewable.io/reviews/pmem/fio/110#-MQrOtdp44OGacqyaclr:-MQur4TQ3VTHTrF1hSiM:bm46ut3) ([raw file](https://github.com/pmem/fio/blob/caabe7f73cef33c2e5299449a7c403aa2d965753/examples/librpma-server.fio#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

What about an alternative solution that malloc is used as a fallback if the file does not provide access to PMem?
</blockquote></details>

@janekmi what do you think about it?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/110)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[examples/librpma-server.fio, line 21 at r1](https://reviewable.io/reviews/pmem/fio/110#-MQrOtdp44OGacqyaclr:-MQv2uR-3_tYgpyGxmOd:bjkgdgk) ([raw file](https://github.com/pmem/fio/blob/caabe7f73cef33c2e5299449a7c403aa2d965753/examples/librpma-server.fio#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@janekmi what do you think about it?
</blockquote></details>

@grom72 I think it is not a good idea. If someone wants PMEM, they should get PMEM, not a silent fallback to DRAM. If someone wants DRAM, they should explicitly set `filename=malloc`.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/110)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma.c, line 1174 at r1](https://reviewable.io/reviews/pmem/fio/110#-MQrOHt96pc1w57ES4v8:-MQvRwrxEzUNaoDa2syX:b32w0x) ([raw file](https://github.com/pmem/fio/blob/caabe7f73cef33c2e5299449a7c403aa2d965753/engines/librpma.c#L1174)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

So the current code is correct. It is safer and easier to use the always-correct-formula.
</blockquote></details>

OK
___
*[engines/librpma.c, line 1124 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQunirM9BCtn-HHJIlj:-MQvQjHzENvYavlMZcPW:b-9mzi25) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1124)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What do you mean? What is wrong here? Why? What chunks?
</blockquote></details>

The point is that perhaps real_file_name is set too late. 
___
*[examples/librpma-server.fio, line 21 at r1](https://reviewable.io/reviews/pmem/fio/110#-MQrOtdp44OGacqyaclr:-MQvSD3TDdzC42hoRQ8U:b32w0x) ([raw file](https://github.com/pmem/fio/blob/caabe7f73cef33c2e5299449a7c403aa2d965753/examples/librpma-server.fio#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 I think it is not a good idea. If someone wants PMEM, they should get PMEM, not a silent fallback to DRAM. If someone wants DRAM, they should explicitly set `filename=malloc`.
</blockquote></details>

OK

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[engines/librpma.c, line 1124 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQunirM9BCtn-HHJIlj:-MQvU8lWDYhRJkGwPKxx:bo9f1qf) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1124)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

The point is that perhaps real_file_name is set too late. 
</blockquote></details>

But we do not implement `setup()` and it works. 
Without this line `f->real_file_size` was equal 0 and the server failed but __after__ this function, so it does not seem to set too late.

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[examples/librpma-server.fio, line 21 at r1](https://reviewable.io/reviews/pmem/fio/110#-MQrOtdp44OGacqyaclr:-MQvmfdX2x-UHBM7L0e9:bgqnah) ([raw file](https://github.com/pmem/fio/blob/caabe7f73cef33c2e5299449a7c403aa2d965753/examples/librpma-server.fio#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

OK
</blockquote></details>

I agree with @ldorau.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/110#-:-MQvnjg_7Oes8kHhnMGQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
Rebased and conflicts resolved.

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/110#-:-MQvw4y1AW8cYA72GKaT:b-tvwn13)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @grom72 and @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/110)* status: all files reviewed, 11 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 980 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQvw3l1Dhmn8O4TZVUU:-MQvw3l1Dhmn8O4TZVUV:ba4j08c) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L980)):*
> ```C
> 	 * ... a single io_u size has to be equal to the assumed workspace size.
> 	 */
> 	td->o.max_bs[DDIR_READ] = td->o.size;
> ```

Not needed any more.
___
*[engines/librpma.c, line 1046 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQvupQM217uwsCDjF9p:-MQvupQM217uwsCDjF9q:b-xbb7dh) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1046)):*
> ```C
> 	 */
> 	mem_aligned = PTR_ALIGN(mem_ptr, page_mask) + td->o.mem_align;
> 	size_aligned = size_mmap - (mem_aligned - mem_ptr);
> ```

`pmem_map_file()` returns aligned pointer. Not required.
___
*[engines/librpma.c, line 1069 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQvv4P32JwM5tsIo5jb:-MQvv4P32JwM5tsIo5jc:b-r9ijve) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1069)):*
> ```C
> 	int ret;
> 
> 	alignment = td->o.mem_align ? td->o.mem_align : page_size;
> ```

The alignment here is needed only for the sake of memory registration (unaligned memory can not be registered).
I think we should just use here `page_size`.
___
*[engines/librpma.c, line 1088 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQvvheq58mbqASCJ4uh:-MQvvheq58mbqASCJ4ui:b-7mq6ae) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1088)):*
> ```C
> 
> 	if (sd == NULL)
> 		return;
> ```

Is it possible?
___
*[engines/librpma.c, line 1100 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQvvpDLCdZQz3ltcEWz:-MQvvpDLCdZQz3ltcEX-:bsl0ltt) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1100)):*
> ```C
> 	struct server_data *sd =  td->io_ops_data;
> 	struct rpma_mr_local *mr;
> 	char *io_us_ptr = NULL;
> ```

Part of this change is dropping overall binding the memory with io_u. `mem_ptr`?
___
*[engines/librpma.c, line 1110 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQvwZEtDjXIGG5CNxI_:-MQvwZEu0QFFEt0BTp_0:b-w5vt1o) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1110)):*
> ```C
> 	}
> 
> 	io_us_size = (unsigned long long)td_max_bs(td) *
> ```

Instead of `td_max_bs(td)` please use `td->o.size` directly.
___
*[engines/librpma.c, line 1175 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQvuLymBV6eOwpxpBJh:-MQvuLymBV6eOwpxpBJi:b4a5eas) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1175)):*
> ```C
> 	server_free(td);
> 
> 	return (ret != 0 ? ret : 1);
> ```

`return 1`
___
*[engines/librpma.c, line 988 at r3](https://reviewable.io/reviews/pmem/fio/110#-MQvwrbR4f5H7WJL-cQG:-MQvwrbR4f5H7WJL-cQH:ba4j08c) ([raw file](https://github.com/pmem/fio/blob/286959348cf84116caa1865dd2143d30bb1ddda9/engines/librpma.c#L988)):*
> ```C
> 	 * at this level.
> 	 */
> 	td->o.iodepth = td->thread_number;
> ```

Not needed any more.
___
*[engines/librpma.c, line 1124 at r3](https://reviewable.io/reviews/pmem/fio/110#-MQvx4Pq8tqev-9rF4UG:-MQvx4Pq8tqev-9rF4UH:b-ndaviw) ([raw file](https://github.com/pmem/fio/blob/286959348cf84116caa1865dd2143d30bb1ddda9/engines/librpma.c#L1124)):*
> ```C
> 	}
> 
> 	io_us_size = (unsigned long long)td_max_bs(td) *
> ```

io_u is not applicable any more.
___
*[engines/librpma.c, line 1125 at r3](https://reviewable.io/reviews/pmem/fio/110#-MQvwxWu1azGZowJnFC5:-MQvwxWu1azGZowJnFC6:bbafii6) ([raw file](https://github.com/pmem/fio/blob/286959348cf84116caa1865dd2143d30bb1ddda9/engines/librpma.c#L1125)):*
> ```C
> 
> 	io_us_size = (unsigned long long)td_max_bs(td) *
> 			(unsigned long long)td->o.iodepth;
> ```

Instead of `td->o.iodepth` please use `td->o.thread_number` directly.
___
*[engines/librpma.c, line 1240 at r3](https://reviewable.io/reviews/pmem/fio/110#-MQvxXx0DWP1yZdk6rnJ:-MQvxXx0DWP1yZdk6rnK:b-hz226c) ([raw file](https://github.com/pmem/fio/blob/286959348cf84116caa1865dd2143d30bb1ddda9/engines/librpma.c#L1240)):*
> ```C
> 	int ret;
> 	int rv;
> ```

`server_free(td);`?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/110)* status: all files reviewed, 11 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 980 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQvw3l1Dhmn8O4TZVUU:-MQvySNHC5noF7emmBxi:b-2eori8) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L980)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed any more.
</blockquote></details>

I did not change anything here - AFAIK it is not a part of my PR
___
*[engines/librpma.c, line 988 at r3](https://reviewable.io/reviews/pmem/fio/110#-MQvwrbR4f5H7WJL-cQG:-MQvyJSk3jkzkK0C3V1n:b-2eori8) ([raw file](https://github.com/pmem/fio/blob/286959348cf84116caa1865dd2143d30bb1ddda9/engines/librpma.c#L988)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed any more.
</blockquote></details>

I did not change anything here - AFAIK it is not a part of my PR

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/110)* status: all files reviewed, 11 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 980 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQvw3l1Dhmn8O4TZVUU:-MQw2O-rChZmLaFeqa6T:ba3dfob) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L980)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I did not change anything here - AFAIK it is not a part of my PR
</blockquote></details>

Removed
___
*[engines/librpma.c, line 1046 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQvupQM217uwsCDjF9p:-MQvzdeoA7B2dZ89OHbr:b-896fix) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1046)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`pmem_map_file()` returns aligned pointer. Not required.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 1069 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQvv4P32JwM5tsIo5jb:-MQvzoQ8DrOPmv7pE1KY:b-896fix) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1069)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The alignment here is needed only for the sake of memory registration (unaligned memory can not be registered).
I think we should just use here `page_size`.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 1088 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQvvheq58mbqASCJ4uh:-MQvztqN0CUwah2h1Dwn:b98dd4o) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1088)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Is it possible?
</blockquote></details>

AFAIR it happened some time ago
___
*[engines/librpma.c, line 1100 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQvvpDLCdZQz3ltcEWz:-MQw-j5q8M-dyejlta2t:b-896fix) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1100)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Part of this change is dropping overall binding the memory with io_u. `mem_ptr`?
</blockquote></details>

Done.
___
*[engines/librpma.c, line 1110 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQvwZEtDjXIGG5CNxI_:-MQw2bD0-OFI-17kG_ML:b-896fix) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1110)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Instead of `td_max_bs(td)` please use `td->o.size` directly.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 1175 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQvuLymBV6eOwpxpBJh:-MQw-yuK5qsaGrlSeMJM:b-txaquw) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1175)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`return 1`
</blockquote></details>

Why not `return (ret != 0 ? ret : 1);` ? There was a discussion on this with @grom72 .
___
*[engines/librpma.c, line 988 at r3](https://reviewable.io/reviews/pmem/fio/110#-MQvwrbR4f5H7WJL-cQG:-MQw2Mc66Qo4_0IqalJI:ba3dfob) ([raw file](https://github.com/pmem/fio/blob/286959348cf84116caa1865dd2143d30bb1ddda9/engines/librpma.c#L988)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I did not change anything here - AFAIK it is not a part of my PR
</blockquote></details>

Removed
___
*[engines/librpma.c, line 1124 at r3](https://reviewable.io/reviews/pmem/fio/110#-MQvx4Pq8tqev-9rF4UG:-MQw34n1DDFTqMHaDho3:b-896fix) ([raw file](https://github.com/pmem/fio/blob/286959348cf84116caa1865dd2143d30bb1ddda9/engines/librpma.c#L1124)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

io_u is not applicable any more.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 1125 at r3](https://reviewable.io/reviews/pmem/fio/110#-MQvwxWu1azGZowJnFC5:-MQw35vF56l3ySGvJs3q:b-896fix) ([raw file](https://github.com/pmem/fio/blob/286959348cf84116caa1865dd2143d30bb1ddda9/engines/librpma.c#L1125)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Instead of `td->o.iodepth` please use `td->o.thread_number` directly.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 1240 at r3](https://reviewable.io/reviews/pmem/fio/110#-MQvxXx0DWP1yZdk6rnJ:-MQw0EAIBhKMrdW-016_:b-896fix) ([raw file](https://github.com/pmem/fio/blob/286959348cf84116caa1865dd2143d30bb1ddda9/engines/librpma.c#L1240)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`server_free(td);`?
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/110)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 1175 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQvuLymBV6eOwpxpBJh:-MQw5-8j5-0Mi0k30K3O:b-75a8kl) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1175)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why not `return (ret != 0 ? ret : 1);` ? There was a discussion on this with @grom72 .
</blockquote></details>

Ok. Maybe we will unify this at some point.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/110)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma.c, line 1088 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQvvheq58mbqASCJ4uh:-MQw4VMH-Y8WmozVMXUi:bej4d5l) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1088)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

AFAIR it happened some time ago
</blockquote></details>

If you want to be on the safe side I think this condition should be checked directly in the hooks using this auxiliary function.
Here it does not make much sense since you will get SIGSEGV before even this function is called.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/110)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 1088 at r2](https://reviewable.io/reviews/pmem/fio/110#-MQvvheq58mbqASCJ4uh:-MQw8V14DOAU_B2J8emf:bjtmwk1) ([raw file](https://github.com/pmem/fio/blob/844cd4ad10eaae7f5186bff057a63ba0b957bf20/engines/librpma.c#L1088)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If you want to be on the safe side I think this condition should be checked directly in the hooks using this auxiliary function.
Here it does not make much sense since you will get SIGSEGV before even this function is called.
</blockquote></details>

You are right. I've got something mixed up. Removed.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/110#-:-MQw9FPD3VjU6H63l_PO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
