### PR TITLE
rpma: allow the server to kill all connections on error

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/41)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/41)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/41)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 1009 at r1](https://reviewable.io/reviews/pmem/fio/41#-MKifo4H1rFqlRo5xdrq:-MKifo4IBSfejyQNqXpg:boig9xw) ([raw file](https://github.com/pmem/fio/blob/862e8235764f8041d6f9ceffcf92384bc149684c/engines/librpma.c#L1009)):*
> ```
> after
> ```

of

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/41#-:-MKifwT23joz-Qy38ig2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/41)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/41)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
@osalyk @grom72 please review

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/41#-:-MKj1ehI1WdfH3gAhoxI:b-ki7n6a)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/41)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 988 at r1](https://reviewable.io/reviews/pmem/fio/41#-MKiYt_M68MwRwIWudDW:-MKiYt_M68MwRwIWudDX:b-ptdv0l) ([raw file](https://github.com/pmem/fio/blob/862e8235764f8041d6f9ceffcf92384bc149684c/engines/librpma.c#L988)):*
> ```C
> 		sd->data.data_offset += bs;
> 	}
> ```

if(i<o->num_conn)  
   goto err_disconnect;
___
*[engines/librpma.c, line 1003 at r1](https://reviewable.io/reviews/pmem/fio/41#-MKjGa1F7C0w7Q0XMrE6:-MKjGa1F7C0w7Q0XMrE7:b-afw8qk) ([raw file](https://github.com/pmem/fio/blob/862e8235764f8041d6f9ceffcf92384bc149684c/engines/librpma.c#L1003)):*
> ```C
> 
> err_disconnect:
> 	/* close all connections */
> ```

some error message for fio will be very helpful
___
*[engines/librpma.c, line 1032 at r2](https://reviewable.io/reviews/pmem/fio/41#-MKjBOBU-lvJJMZTZwms:-MKjBOBU-lvJJMZTZwmt:bxx5gsp) ([raw file](https://github.com/pmem/fio/blob/61894cf1f287ffd78100f1903cab36b8d6e3634a/engines/librpma.c#L1032)):*
> ```
> goto err_disconnect;
> ```
```
break;
```
instead and see comment below

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/41)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 988 at r1](https://reviewable.io/reviews/pmem/fio/41#-MKiYt_M68MwRwIWudDW:-MKjq-an7JSDYHD2u-0V:b3kqx) ([raw file](https://github.com/pmem/fio/blob/862e8235764f8041d6f9ceffcf92384bc149684c/engines/librpma.c#L988)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

if(i<o->num_conn)  
   goto err_disconnect;
</blockquote></details>

.
___
*[engines/librpma.c, line 1003 at r1](https://reviewable.io/reviews/pmem/fio/41#-MKjGa1F7C0w7Q0XMrE6:-MKjqbwQ3OHomCNQtPA2:b-b4do4r) ([raw file](https://github.com/pmem/fio/blob/862e8235764f8041d6f9ceffcf92384bc149684c/engines/librpma.c#L1003)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

some error message for fio will be very helpful
</blockquote></details>

All cases now have error messages. Note some of them are done in `server_conn_establish`.
___
*[engines/librpma.c, line 1032 at r2](https://reviewable.io/reviews/pmem/fio/41#-MKjBOBU-lvJJMZTZwms:-MKjps7L-Iml0m-jQdvd:bpg52xb) ([raw file](https://github.com/pmem/fio/blob/61894cf1f287ffd78100f1903cab36b8d6e3634a/engines/librpma.c#L1032)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> goto err_disconnect;
> ```
```
break;
```
instead and see comment below
</blockquote></details>

Hm, more code, and the same effect. What is the point?

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/41)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/41)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 1032 at r2](https://reviewable.io/reviews/pmem/fio/41#-MKjBOBU-lvJJMZTZwms:-MKjwxHH8LDAmeaZR6Uh:byr419k) ([raw file](https://github.com/pmem/fio/blob/61894cf1f287ffd78100f1903cab36b8d6e3634a/engines/librpma.c#L1032)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Hm, more code, and the same effect. What is the point?
</blockquote></details>

goto to from the inside of the loop :(

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/41)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 1032 at r2](https://reviewable.io/reviews/pmem/fio/41#-MKjBOBU-lvJJMZTZwms:-MKkoK1l4SRQeyf1Z39m:b-5l8gl1) ([raw file](https://github.com/pmem/fio/blob/61894cf1f287ffd78100f1903cab36b8d6e3634a/engines/librpma.c#L1032)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

goto to from the inside of the loop :( 
</blockquote></details>

Didn't like it either. Thought it is easier to follow.
But since we both are bothered about this I have changed it.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/41)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/41#-:-MKkzwRh0w7d-XHiT-ac:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/41)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
