### PR TITLE
rpma: send the last flush request 'Flush_req_last' in client_cleanup()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/68)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/68)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 366 at r1](https://reviewable.io/reviews/pmem/fio/68#-MMaRr7F9kmysuwGCbtp:-MMaRr7F9kmysuwGCbtq:bkgmc7d) ([raw file](https://github.com/pmem/fio/blob/110b4ff52093c842da5b6b4edc5743463e01f9ea/engines/librpma_gpspm.c#L366)):*
> ```C
> 		log_err(
> 			"Packed flush request size is bigger than available send buffer space (%zu > %d\n",
> 			flush_req_size,	MAX_MSG_SIZE);
> ```

space instead of tab
___
*[engines/librpma_gpspm.c, line 369 at r1](https://reviewable.io/reviews/pmem/fio/68#-MMaRl8510O_qiyBdrZF:-MMaRl867J2XGxvrF6AP:b-m1aw8i) ([raw file](https://github.com/pmem/fio/blob/110b4ff52093c842da5b6b4edc5743463e01f9ea/engines/librpma_gpspm.c#L369)):*
> ```C
> 	}
> 
> 	send_offset = 0;
> ```

Isn't redundancy?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/68)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_gpspm.c, line 366 at r1](https://reviewable.io/reviews/pmem/fio/68#-MMaRr7F9kmysuwGCbtp:-MMaSf0LDyfsPNCwI_wq:b-896fix) ([raw file](https://github.com/pmem/fio/blob/110b4ff52093c842da5b6b4edc5743463e01f9ea/engines/librpma_gpspm.c#L366)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

space instead of tab
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 369 at r1](https://reviewable.io/reviews/pmem/fio/68#-MMaRl8510O_qiyBdrZF:-MMaSfXB7mlvzbBUWToa:b9e6w6z) ([raw file](https://github.com/pmem/fio/blob/110b4ff52093c842da5b6b4edc5743463e01f9ea/engines/librpma_gpspm.c#L369)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Isn't redundancy?
</blockquote></details>

Yes, it is :-) Fixed.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/68)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_gpspm.c, line 369 at r1](https://reviewable.io/reviews/pmem/fio/68#-MMaRl8510O_qiyBdrZF:-MMaSuZL0X_Uyz85Bftw:b-896fix) ([raw file](https://github.com/pmem/fio/blob/110b4ff52093c842da5b6b4edc5743463e01f9ea/engines/librpma_gpspm.c#L369)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, it is :-) Fixed.
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/68#-:-MMaTeNf4NAXmdZ6msQ9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/68)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 368 at r2](https://reviewable.io/reviews/pmem/fio/68#-MMahvxBBlfJmIcNVbZ0:-MMahvxCEq9JcAowEZtY:bicfl2o) ([raw file](https://github.com/pmem/fio/blob/c04e3ea13cd6cf483eee3d86e2e5828b929b31fa/engines/librpma_gpspm.c#L368)):*
> ```C
> 	}
> 
> 	send_ptr = cd->io_us_msgs + SEND_OFFSET;
> ```

SEND_OFFSET = 0 
not needed.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/68)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma_gpspm.c, line 368 at r2](https://reviewable.io/reviews/pmem/fio/68#-MMahvxBBlfJmIcNVbZ0:-MMbAk2049tbnb6JAb_d:b50kzrk) ([raw file](https://github.com/pmem/fio/blob/c04e3ea13cd6cf483eee3d86e2e5828b929b31fa/engines/librpma_gpspm.c#L368)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

SEND_OFFSET = 0 
not needed.
</blockquote></details>

you never know ... let's keep it here

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/68)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[engines/librpma_gpspm.c, line 353 at r2](https://reviewable.io/reviews/pmem/fio/68#-MMbEtW_0ByjCAioYGOk:-MMbEtW_0ByjCAioYGOl:bfu71wr) ([raw file](https://github.com/pmem/fio/blob/c04e3ea13cd6cf483eee3d86e2e5828b929b31fa/engines/librpma_gpspm.c#L353)):*
> ```
> send_ptr
> ```
send_buffer
___
*[engines/librpma_gpspm.c, line 366 at r2](https://reviewable.io/reviews/pmem/fio/68#-MMbFTBTAnd0_LAIlo4U:-MMbFS31BHFgz_ryF_4-:b3b8fxf) ([raw file](https://github.com/pmem/fio/blob/c04e3ea13cd6cf483eee3d86e2e5828b929b31fa/engines/librpma_gpspm.c#L366)):*
> ```C
> 			"Packed flush request size is bigger than available send buffer space (%zu > %d\n",
> 			flush_req_size, MAX_MSG_SIZE);
> 	}
> ```

Shall we skip sending "last flush req" if the message is too big?

else { 


...
}

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/68)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/68#-MMbGUHIDhPHXBcrW0SU:-MMbGUHIDhPHXBcrW0SV:b-kchz8w) (no related file):*
What will be the server reaction if the client is terminated and Flush_req_last is not sent?

---

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/68)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/68#-MMbGUHIDhPHXBcrW0SU:-MMcGiQl2nlHP8EPK67E:bxqeo93) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

What will be the server reaction if the client is terminated and Flush_req_last is not sent?
</blockquote></details>

The server will hang. @ldorau probably it will be good to think about some kind of a timeout on the server side.

---
___
*[engines/librpma_gpspm.c, line 353 at r2](https://reviewable.io/reviews/pmem/fio/68#-MMbEtW_0ByjCAioYGOk:-MMcGwDLBvcVqXcCnIsm:b33p05a) ([raw file](https://github.com/pmem/fio/blob/c04e3ea13cd6cf483eee3d86e2e5828b929b31fa/engines/librpma_gpspm.c#L353)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> send_ptr
> ```
send_buffer
</blockquote></details>

Please name it consequently. If we are sure what @grom72 suggests is a better naming, please propose renaming in another PR.
___
*[engines/librpma_gpspm.c, line 366 at r2](https://reviewable.io/reviews/pmem/fio/68#-MMbFTBTAnd0_LAIlo4U:-MMcHMJ-5DihHPaoZBC8:b-ougsr6) ([raw file](https://github.com/pmem/fio/blob/c04e3ea13cd6cf483eee3d86e2e5828b929b31fa/engines/librpma_gpspm.c#L366)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we skip sending "last flush req" if the message is too big?

else { 


...
}
</blockquote></details>

We should.
___
*[engines/librpma_gpspm.c, line 368 at r2](https://reviewable.io/reviews/pmem/fio/68#-MMahvxBBlfJmIcNVbZ0:-MMcFiELDv4GArOEeLkG:boe9fjc) ([raw file](https://github.com/pmem/fio/blob/c04e3ea13cd6cf483eee3d86e2e5828b929b31fa/engines/librpma_gpspm.c#L368)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

you never know ... let's keep it here
</blockquote></details>

We are using variable / constant instead of the value directly because:
- reading just this line you have no idea why you are adding here 0 or not adding anything
    - SEND_OFFSET conveys meaning
- when at some point you decide to change the order of messages it will be damn hard to track all places where you have to add MAX_MSG_SIZE instead of adding 0 or not adding anything and vice versa.
    - using a constant allows for easy adjustments

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/68)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/fio/68#-MMbGUHIDhPHXBcrW0SU:-MMpapfy70ZcLsoQNdza:b-pkxqsy) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The server will hang. @ldorau probably it will be good to think about some kind of a timeout on the server side.
</blockquote></details>

OK, I will think about it

---
___
*[engines/librpma_gpspm.c, line 353 at r2](https://reviewable.io/reviews/pmem/fio/68#-MMbEtW_0ByjCAioYGOk:-MMpaneD4QtHS67Apjzk:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c04e3ea13cd6cf483eee3d86e2e5828b929b31fa/engines/librpma_gpspm.c#L353)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please name it consequently. If we are sure what @grom72 suggests is a better naming, please propose renaming in another PR.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 366 at r2](https://reviewable.io/reviews/pmem/fio/68#-MMbFTBTAnd0_LAIlo4U:-MMp__Et4TrpERqUx0uu:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c04e3ea13cd6cf483eee3d86e2e5828b929b31fa/engines/librpma_gpspm.c#L366)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We should.
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/68)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/68)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/68#-MMbGUHIDhPHXBcrW0SU:-MMpjicdCKkFyUusj-FU:b-47whjq) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, I will think about it
</blockquote></details>

Does the connection will be broken in such a situation and we will receive a negative response from rec CQ?

---

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/68#-:-MMpl7gu3YrqjvbVunrw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/68)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/fio/68#-MMbGUHIDhPHXBcrW0SU:-MMpoolc3UvO_NZjQqhi:b-qde9ww) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Does the connection will be broken in such a situation and we will receive a negative response from rec CQ?
</blockquote></details>

While hanging the connection is up and the server is waiting for the completion at the beginning of `server_queue()`

---

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/68#-:-MMuRXzx02pgb2s1nd45:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Pull request merged**
