### PR TITLE
ci: update LIBRPMA_VERSION to support rpma_mr_advise()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/259)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/259#-:-Mjdm2BC2VSW3tfYelQ5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/259)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[ci/actions-install-librpma.sh, line 10 at r1](https://reviewable.io/reviews/pmem/fio/259#-Mje7_H38smtIlylwC2t:-Mje7_H38smtIlylwC2u:bm0ausb) ([raw file](https://github.com/pmem/fio/blob/5b064cf3b1d368d7bb376a75d5c3f22f46f46f4f/ci/actions-install-librpma.sh#L10)):*
> ```Shell
> 
> # install pylint3 required by librpma
> sudo apt-get install --no-install-recommends -qq -y pylint3
> ```

I think it will be better to turn off `TEST_PYTHON_TOOLS` instead of requiring pylint where the library itself does not require it.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/259)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[ci/actions-install-librpma.sh, line 10 at r1](https://reviewable.io/reviews/pmem/fio/259#-Mje7_H38smtIlylwC2t:-MjmAsH88l53tNdpiiWT:b-896fix) ([raw file](https://github.com/pmem/fio/blob/5b064cf3b1d368d7bb376a75d5c3f22f46f46f4f/ci/actions-install-librpma.sh#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think it will be better to turn off `TEST_PYTHON_TOOLS` instead of requiring pylint where the library itself does not require it.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/259#-:-MjmgFg64SzXbkV5UvYf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
