### PR TITLE
rpma: return -1 instead of 1 in case of an error

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #146

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/147)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/147)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 242 at r1](https://reviewable.io/reviews/pmem/fio/147#-MRPoWItAa07n9DQtXOY:-MRPoWItAa07n9DQtXOZ:bvdszrw) ([raw file](https://github.com/pmem/fio/blob/1428ef6698d61cf0c5f95d6ba33f2a77dc98350d/engines/librpma.c#L242)):*
> ```
> 1
> ```
-1
___
*[engines/librpma.c, line 282 at r1](https://reviewable.io/reviews/pmem/fio/147#-MRPoOIs8X40BxqppCqU:-MRPoOIs8X40BxqppCqV:bvdszrw) ([raw file](https://github.com/pmem/fio/blob/1428ef6698d61cf0c5f95d6ba33f2a77dc98350d/engines/librpma.c#L282)):*
> ```
> 1
> ```
-1
___
*[engines/librpma.c, line 282 at r1](https://reviewable.io/reviews/pmem/fio/147#-MRPogRk6BMqe93ixerg:-MRPogRk6BMqe93ixerh:b14upam) ([raw file](https://github.com/pmem/fio/blob/1428ef6698d61cf0c5f95d6ba33f2a77dc98350d/engines/librpma.c#L282)):*
> ```
> (ret != 0 ? ret : 1);
> ```
@janekmi - do we still need this or is it return ret enough?

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/147)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/147)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[engines/librpma.c, line 242 at r1](https://reviewable.io/reviews/pmem/fio/147#-MRPoWItAa07n9DQtXOY:-MRPrAqr4oKzMjvSrn8W:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1428ef6698d61cf0c5f95d6ba33f2a77dc98350d/engines/librpma.c#L242)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 1
> ```
-1
</blockquote></details>

Done.
___
*[engines/librpma.c, line 282 at r1](https://reviewable.io/reviews/pmem/fio/147#-MRPoOIs8X40BxqppCqU:-MRPrDOmEsytCFgb5A_D:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1428ef6698d61cf0c5f95d6ba33f2a77dc98350d/engines/librpma.c#L282)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 1
> ```
-1
</blockquote></details>

Done.
___
*[engines/librpma.c, line 282 at r1](https://reviewable.io/reviews/pmem/fio/147#-MRPogRk6BMqe93ixerg:-MRPrHxOAmoNEhnoX1-d:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1428ef6698d61cf0c5f95d6ba33f2a77dc98350d/engines/librpma.c#L282)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> (ret != 0 ? ret : 1);
> ```
@janekmi - do we still need this or is it return ret enough?
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/147#-:-MRQ8MZiBe8HSPygZo93:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
@grom72 rebased

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/147#-:-MRRJLXe8um4NFso3wGo:bnran3z)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/147)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/147)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
