### PR TITLE
rpma: common: server's mr flush type

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- ~~#154~~
- [x] #155

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/156)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/156#-:-MRTRkB71DRAHUbwOq0e:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/156#-MRTRcwM6txxeJW3c8l1:-MRTRcwM6txxeJW3c8l2:bb7qlku) (no related file):*
Shall we consider splitting both engines into separate client and server files?

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/156)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Comment by ldorau** [comment]
@janekmi please rebase

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/156)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm: please rebase

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/156#-:-MRVR_pg0k1-B3NnhRxw:bdtt1ez)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/156)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
