### PR TITLE
rpma: add libprotobuf-c files with GPSPM flush request and response

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/51)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/51)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/51#-MLhR_EZ8NOE7FA1s4Zc:-MLhR_EZ8NOE7FA1s4Zd:b-aiiwhb) (no related file):*
I think all files related to our specific engine should start with the prefix e.g. librpma_gpspm...

---
___
*[engines/GPSPM_flush.pb-c.h, line 4 at r1](https://reviewable.io/reviews/pmem/fio/51#-MLhRo7KEnyJT__A9g6O:-MLhRo7KEnyJT__A9g6P:b-yyf5n8) ([raw file](https://github.com/pmem/fio/blob/e6160582509032c46569201c94527169942ba74c/engines/GPSPM_flush.pb-c.h#L4)):*
> ```objc
> /* Copyright 2020, Intel Corporation */
> 
> /* Generated by the protocol buffer compiler.  DO NOT EDIT! */
> ```

`  ` -> ` `
___
*[engines/GPSPM_flush.pb-c.c, line 4 at r1](https://reviewable.io/reviews/pmem/fio/51#-MLhRzFaCKGj-f70cT1t:-MLhRzFaCKGj-f70cT1u:b3kqx) ([raw file](https://github.com/pmem/fio/blob/e6160582509032c46569201c94527169942ba74c/engines/GPSPM_flush.pb-c.c#L4)):*
> ```C
> /* Copyright 2020, Intel Corporation */
> 
> /* Generated by the protocol buffer compiler.  DO NOT EDIT! */
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/51)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/51#-MLhR_EZ8NOE7FA1s4Zc:-MLhWN7Y0yUoRGmuEyOH:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think all files related to our specific engine should start with the prefix e.g. librpma_gpspm...
</blockquote></details>

Done.

---
___
*[engines/GPSPM_flush.pb-c.h, line 4 at r1](https://reviewable.io/reviews/pmem/fio/51#-MLhRo7KEnyJT__A9g6O:-MLhUZ832eLX15lEPr-U:bfhzik1) ([raw file](https://github.com/pmem/fio/blob/e6160582509032c46569201c94527169942ba74c/engines/GPSPM_flush.pb-c.h#L4)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`  ` -> ` `
</blockquote></details>

I do not unserstand what "` `-> ` `" means ? ....

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/51)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/GPSPM_flush.pb-c.c, line 4 at r1](https://reviewable.io/reviews/pmem/fio/51#-MLhRzFaCKGj-f70cT1t:-MLhXkUd7hV0LjBLh-Kx:b3kqx) ([raw file](https://github.com/pmem/fio/blob/e6160582509032c46569201c94527169942ba74c/engines/GPSPM_flush.pb-c.c#L4)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/51#-:-MLhYnhf5TzduJkP-N83:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[engines/GPSPM_flush.pb-c.h, line 4 at r1](https://reviewable.io/reviews/pmem/fio/51#-MLhRo7KEnyJT__A9g6O:-MLhYeKn-19vFnwxrOHK:b-ivecor) ([raw file](https://github.com/pmem/fio/blob/e6160582509032c46569201c94527169942ba74c/engines/GPSPM_flush.pb-c.h#L4)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I do not unserstand what "` `-> ` `" means ? ....
</blockquote></details>

You had too many spaces here.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/51)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm_flush.proto, line 3 at r2](https://reviewable.io/reviews/pmem/fio/51#-MLhxBT9EkI0JVYKB5QN:-MLhxBT9EkI0JVYKB5QO:bihs0vj) ([raw file](https://github.com/pmem/fio/blob/b0b506f00336de8de88dc78822308343db588b84/engines/librpma_gpspm_flush.proto#L3)):*
> ```
> message GPSPM_flush_request
> ```
shall we have a sequence of that?

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/51)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/51)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_gpspm_flush.proto, line 3 at r2](https://reviewable.io/reviews/pmem/fio/51#-MLhxBT9EkI0JVYKB5QN:-MLiWyYlAO6HK1p9Xa7w:b-whnhoi) ([raw file](https://github.com/pmem/fio/blob/b0b506f00336de8de88dc78822308343db588b84/engines/librpma_gpspm_flush.proto#L3)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> message GPSPM_flush_request
> ```
shall we have a sequence of that?
</blockquote></details>

Maybe at some point. But this is needed only for random asynchronous writes which are not the matter of this particular sprint.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/51)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm_flush.proto, line 3 at r2](https://reviewable.io/reviews/pmem/fio/51#-MLhxBT9EkI0JVYKB5QN:-MLiYOFg0MyGTy9tqv28:b-yd5vod) ([raw file](https://github.com/pmem/fio/blob/b0b506f00336de8de88dc78822308343db588b84/engines/librpma_gpspm_flush.proto#L3)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Maybe at some point. But this is needed only for random asynchronous writes which are not the matter of this particular sprint.
</blockquote></details>

How then we could implement different io_depth? Do we assume sequential only access?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/51)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm_flush.proto, line 3 at r2](https://reviewable.io/reviews/pmem/fio/51#-MLhxBT9EkI0JVYKB5QN:-MLiZyYGBINmWrM3QQBZ:b-klrci1) ([raw file](https://github.com/pmem/fio/blob/b0b506f00336de8de88dc78822308343db588b84/engines/librpma_gpspm_flush.proto#L3)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

How then we could implement different io_depth? Do we assume sequential only access?
</blockquote></details>

If we have only one simple structure of flush I suggest not introducing protobuff this sprint - it is not needed.

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/51)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm_flush.proto, line 3 at r2](https://reviewable.io/reviews/pmem/fio/51#-MLhxBT9EkI0JVYKB5QN:-MLidURNCkQY3oNjWM3a:b-4lakqo) ([raw file](https://github.com/pmem/fio/blob/b0b506f00336de8de88dc78822308343db588b84/engines/librpma_gpspm_flush.proto#L3)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

If we have only one simple structure of flush I suggest not introducing protobuff this sprint - it is not needed.
</blockquote></details>

Not using libprotobuf-c is always an option. I think we can leave it to @ldorau. He is taking care of the server I think.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/51)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_gpspm_flush.proto, line 3 at r2](https://reviewable.io/reviews/pmem/fio/51#-MLhxBT9EkI0JVYKB5QN:-MLifj7J5yrygh83w291:bypbu0i) ([raw file](https://github.com/pmem/fio/blob/b0b506f00336de8de88dc78822308343db588b84/engines/librpma_gpspm_flush.proto#L3)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not using libprotobuf-c is always an option. I think we can leave it to @ldorau. He is taking care of the server I think.
</blockquote></details>

GPSPM server cannot be tested using the 09 example without libprotobuf-c.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/51#-:-MLijiiI0Cl90Pvx2-7P:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
