### PR TITLE
rpma: gpspm: rework queue handling

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] 87
- [x] 88

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/89)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/89)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 67 at r1](https://reviewable.io/reviews/pmem/fio/89#-MQBvOpz4OSY4I6VEJc6:-MQBvOpz4OSY4I6VEJc7:b-5q5cjr) ([raw file](https://github.com/pmem/fio/blob/eeac8a27ae9dd864213dde846e16cc42c94ba79e/engines/librpma_gpspm.c#L67)):*
> ```
> #define IO_U_NEXT_BUF_OFF_CLIENT(cd) \
>     (IO_U_BUF_LEN * ((cd->msg_curr++) % cd->msg_num))
> ```
what is the purpose of this define?
___
*[engines/librpma_gpspm.c, line 219 at r1](https://reviewable.io/reviews/pmem/fio/89#-MQBuRcy3HY77j-RYCVF:-MQBuRcy3HY77j-RYCVG:b-1pyybr) ([raw file](https://github.com/pmem/fio/blob/eeac8a27ae9dd864213dde846e16cc42c94ba79e/engines/librpma_gpspm.c#L219)):*
> ```
> cd->msg_num = td->o.iodepth / td->o.iodepth_batch + 1;
> ```
cd->msg_num = (td->o.iodepth  +   td->o.iodepth_batch - 1)/ td->o.iodepth_batch;

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/89)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 216 at r1](https://reviewable.io/reviews/pmem/fio/89#-MQCSgW264RWwc8oRgWg:-MQCSgW264RWwc8oRgWh:b-os2od5) ([raw file](https://github.com/pmem/fio/blob/eeac8a27ae9dd864213dde846e16cc42c94ba79e/engines/librpma_gpspm.c#L216)):*
> ```
> 			 * - B == ceil(iodepth / iodepth_batch) ~=
> 			 *   iodepth / iodepth_batch + 1
> ```

```
			 * - B == ceil(iodepth / iodepth_batch)
```
___
*[engines/librpma_gpspm.c, line 219 at r1](https://reviewable.io/reviews/pmem/fio/89#-MQBuRcy3HY77j-RYCVF:-MQCSUt87asu1r6gwZKf:bk6dqyh) ([raw file](https://github.com/pmem/fio/blob/eeac8a27ae9dd864213dde846e16cc42c94ba79e/engines/librpma_gpspm.c#L219)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> cd->msg_num = td->o.iodepth / td->o.iodepth_batch + 1;
> ```
cd->msg_num = (td->o.iodepth  +   td->o.iodepth_batch - 1)/ td->o.iodepth_batch;
</blockquote></details>

```
cd->msg_num = CEIL(td->o.iodepth, td->o.iodepth_batch)
```

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/89)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma_gpspm.c, line 219 at r1](https://reviewable.io/reviews/pmem/fio/89#-MQBuRcy3HY77j-RYCVF:-MQCbj4K0uh_HWNquaAv:b-896fix) ([raw file](https://github.com/pmem/fio/blob/eeac8a27ae9dd864213dde846e16cc42c94ba79e/engines/librpma_gpspm.c#L219)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
cd->msg_num = CEIL(td->o.iodepth, td->o.iodepth_batch)
```

</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/89)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 67 at r1](https://reviewable.io/reviews/pmem/fio/89#-MQBvOpz4OSY4I6VEJc6:-MQCcOx04_fIuS-_nKsV:b-896fix) ([raw file](https://github.com/pmem/fio/blob/eeac8a27ae9dd864213dde846e16cc42c94ba79e/engines/librpma_gpspm.c#L67)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> #define IO_U_NEXT_BUF_OFF_CLIENT(cd) \
>     (IO_U_BUF_LEN * ((cd->msg_curr++) % cd->msg_num))
> ```
what is the purpose of this define?
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 216 at r1](https://reviewable.io/reviews/pmem/fio/89#-MQCSgW264RWwc8oRgWg:-MQCbvwm7dnhinsSwVPP:b-896fix) ([raw file](https://github.com/pmem/fio/blob/eeac8a27ae9dd864213dde846e16cc42c94ba79e/engines/librpma_gpspm.c#L216)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 			 * - B == ceil(iodepth / iodepth_batch) ~=
> 			 *   iodepth / iodepth_batch + 1
> ```

```
			 * - B == ceil(iodepth / iodepth_batch)
```
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/89)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/89#-:-MQCetsH6tAscImZxPts:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/89)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 522 at r2](https://reviewable.io/reviews/pmem/fio/89#-MQCeqgjCRlpGblJM25k:-MQCeqgjCRlpGblJM25l:b-utr4wg) ([raw file](https://github.com/pmem/fio/blob/5ca14fe7543d383acec6a40d2961dcc16a1cc320/engines/librpma_gpspm.c#L522)):*
> ```
> NULL
> ```
is it because we do not interpret particular io failures but shutdown fio engine in case of any error?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/89)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_gpspm.c, line 522 at r2](https://reviewable.io/reviews/pmem/fio/89#-MQCeqgjCRlpGblJM25k:-MQCfSdM75mq2j1BZly3:b-iizypf) ([raw file](https://github.com/pmem/fio/blob/5ca14fe7543d383acec6a40d2961dcc16a1cc320/engines/librpma_gpspm.c#L522)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> NULL
> ```
is it because we do not interpret particular io failures but shutdown fio engine in case of any error?
</blockquote></details>

We do not collect nor interpret completions for writes. It was changed a moment ago by another PR. It is not part of this change.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/89#-:-MQCftuoC4NjbjG-mIcv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/89)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
