### PR TITLE
rpma: use num_jobs instead of num_conns

### PR DESCRIPTION
**Pull request by janekmi**
- spawns multiple threads
- each thread creates a peer, an endpoint and a memory registration

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/109)

### CODE REVIEW

**Comment by janekmi** [comment]
bw_th

**Review by grom72 — COMMENTED** [review]
How does it look for more threads 32?64?
It seems that performance degradation starts from 16 threads

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/109#-:-MQrkt0d5tdg9PmQAmiZ:b-egkkjs)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 117 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQrnVFm84QHgKpPYJaf:-MQrnVFm84QHgKpPYJag:b-e795jn) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L117)):*
> ```
> port_out[0] = '\0';
> ```
```
*port_out = `\0`;
```
___
*[engines/librpma.c, line 124 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQrnlMM7cZovCI8NbHw:-MQrnlMM7cZovCI8NbHx:b358jp8) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L124)):*
> ```
> 	port_ul += td->thread_number - 1;
> 	if (port_ul >= UINT_MAX) {
> ```
```
if (port_ul >= (UINT_MAX -  td->thread_number - 1)  {
     port_ul += td->thread_number - 1;
} else {
```

___
*[engines/librpma.c, line 902 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQroExE3D4ZhVpy6SAM:-MQroExE3D4ZhVpy6SAN:bx7z3nd) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L902)):*
> ```
> port
> ```
```
base_port
```
___
*[engines/librpma.c, line 1006 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQroPnOAuJb6FslKhjh:-MQroPnOAuJb6FslKhji:b-dh7bg7) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L1006)):*
> ```
> leve
> ```
level
___
*[engines/librpma.c, line 1172 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQrm5UL6ohHEE1gPtyB:-MQrm5UL6ohHEE1gPtyC:b-a5p1ji) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L1172)):*
> ```
> |= ret
> ```
```
= 1
```
will be enough just to indicate that an error occurred
same below ...

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/109)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[examples/librpma-server.fio, line 13 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQusb_yDbWUk5nr8P1W:-MQusb_yDbWUk5nr8P1X:b-kwk9xi) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/examples/librpma-server.fio#L13)):*
> ```
> client-side
> ```

`client side`

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/109)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 123 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQuucpc6N8OxqCR5seT:-MQuucpc6N8OxqCR5seU:bm24fqj) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L123)):*
> ```
> port_ul += td->thread_number - 1;
> ```

Does `td->thread_number` start from 1, not from 0?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/109)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 117 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQrnVFm84QHgKpPYJaf:-MQuw4t2DQr7mGF0Qrqq:b9k56oi) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L117)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> port_out[0] = '\0';
> ```
```
*port_out = `\0`;
```
</blockquote></details>

@grom72 Why is it a blocking issue for you? Both of them are correct, both of them mean and do exactly the same. They are just two different, correct ways of coding the same thing. Why is your version supposed to be better?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/109)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 124 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQrnlMM7cZovCI8NbHw:-MQux4W_C357KwshmXD_:br9jdbm) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L124)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 	port_ul += td->thread_number - 1;
> 	if (port_ul >= UINT_MAX) {
> ```
```
if (port_ul >= (UINT_MAX -  td->thread_number - 1)  {
     port_ul += td->thread_number - 1;
} else {
</blockquote></details>

@grom72 The condition is wrong. I suppose you meant `if (port_ul <= (UINT_MAX -  td->thread_number + 1)  {`, but anyway IMHO the current version is simpler and better - there are fewer arithmetic operations at least.


<!-- Sent from Reviewable.io -->

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/109)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 1008 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQv4kgj5j3u7UVrYW4z:-MQv4kgkDSFanOKwoACb:bt84mxy) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L1008)):*
> ```
> td->o.iodepth = td->thread_number;
> ```

AFAIK `td->thread_number` is a thread index, so should `td->o.iodepth` have a different value for each thread? It seems  I do not understand something here ...

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/109)* status: all files reviewed, 10 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 117 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQrnVFm84QHgKpPYJaf:-MQuDFjI9Y0vrxX_pxQK:b-gkcrra) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L117)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> port_out[0] = '\0';
> ```
```
*port_out = `\0`;
```
</blockquote></details>

BTW do we need this cleanup at all?
___
*[engines/librpma.c, line 124 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQrnlMM7cZovCI8NbHw:-MQvCdU63tkEVwPU_5H8:b-3agmjp) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L124)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 The condition is wrong. I suppose you meant `if (port_ul <= (UINT_MAX -  td->thread_number + 1)  {`, but anyway IMHO the current version is simpler and better - there are fewer arithmetic operations at least.
</blockquote></details>

@ldorau you are right - <= should be. 
But on the other side (ULONG_MAX -1) + 1 + 1 = 0 ;) do we accept this?
   
___
*[engines/librpma.c, line 1008 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQuEeIIAAkrYHpa-Ihs:-MQuEeIIAAkrYHpa-Iht:bplm9b) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L1008)):*
> ```
> td->o.iodepth = td->thread_number;
> ```
does it mean that each server thread has a different iodepth?
___
*[engines/librpma.c, line 1008 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQv4kgj5j3u7UVrYW4z:-MQvEzwlBEp1qBosZun4:b32v57) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L1008)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> td->o.iodepth = td->thread_number;
> ```

AFAIK `td->thread_number` is a thread index, so should `td->o.iodepth` have a different value for each thread? It seems  I do not understand something here ...
</blockquote></details>

+1
___
*[engines/librpma.c, line 1105 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQuFNje-iqDGlsW4ulQ:-MQuFNje-iqDGlsW4ulR:b-bsaysj) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L1105)):*
> ```
> goto err_mr_dereg;
> ```
additional empty line after goto, please
___
*[engines/librpma.c, line 1125 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQuH6BgArNO0gZf3Iyh:-MQuH6BgArNO0gZf3Iyi:bgl6lnn) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L1125)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> 	if (ret)
> 		rpma_td_verror(td, ret, "rpma_conn_next_event");
> 	if (!ret && conn_event != RPMA_CONN_ESTABLISHED) {
> 		log_err("rpma_conn_next_event returned an unexptected event\n");
> 		ret = 1;
> 	}
> 	if (ret)
> 		goto err_conn_delete;
> ```
</details>

Is there any reason to consolidate these two (if + goto) into two if + one goto?
The original code was much clear.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/109)* status: all files reviewed, 10 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma.c, line 124 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQrnlMM7cZovCI8NbHw:-MQvGbEI7erBT1CXuzoP:bgg918o) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L124)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@ldorau you are right - <= should be. 
But on the other side (ULONG_MAX -1) + 1 + 1 = 0 ;) do we accept this?
   
</blockquote></details>

The current code is correct.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/109)* status: all files reviewed, 10 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 124 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQrnlMM7cZovCI8NbHw:-MQvQBrgAWHriOTKhxui:b-5ewv1h) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L124)):*
> ```
> fio.fio:
> base port; ports <port; port + numjobs - 1> will be used
> ```
if base PORT = ULONG_MAX-1 we got port numbers ULONG_NAME1, ULONG_NAME, 0, 1, ...

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/109)* status: all files reviewed, 10 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 124 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQrnlMM7cZovCI8NbHw:-MQvS1V7D3IDmZpH2o1Y:b-e50kna) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L124)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> fio.fio:
> base port; ports <port; port + numjobs - 1> will be used
> ```
if base PORT = ULONG_MAX-1 we got port numbers ULONG_NAME1, ULONG_NAME, 0, 1, ... 
</blockquote></details>

No, if base PORT = UINT_MAX-1, for td->thread_number==2 we just get error, because the condition `if (port_ul >= UINT_MAX) {` will be true.
___
*[engines/librpma.c, line 1008 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQv4kgj5j3u7UVrYW4z:-MQvSSiZ9QCwJfJMIEKW:b3kqx) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L1008)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

.

**Comment by janekmi** [comment]
bw_th_retry

**Review by janekmi — COMMENTED** [review]
No degradation took place. No rationale for any further benchmarking.

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/109#-:-MQvfVZv8EvmuW9LciCl:b-9w2eoy)* status: all files reviewed, 10 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by grom72 — COMMENTED** [review]
OK - let's wait until users will come back with 32 and 64 threads

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/109#-:-MQvhHJrEpEMlV3S-Sfi:bzhrcko)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 124 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQrnlMM7cZovCI8NbHw:-MQvfnzi5PYbSiRNveUo:b32w0x) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L124)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, if base PORT = UINT_MAX-1, for td->thread_number==2 we just get error, because the condition `if (port_ul >= UINT_MAX) {` will be true.
</blockquote></details>

OK

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/109)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 123 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQuucpc6N8OxqCR5seT:-MQvgISj9ntzNFQWwmZo:b-hsk9rm) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L123)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> port_ul += td->thread_number - 1;
> ```

Does `td->thread_number` start from 1, not from 0?
</blockquote></details>

From 1.
___
*[engines/librpma.c, line 902 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQroExE3D4ZhVpy6SAM:-MQvhYzI2IwWJOJF58tH:b-45mle6) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L902)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> port
> ```
```
base_port
```
</blockquote></details>

I like the idea. Maybe another PR.
___
*[engines/librpma.c, line 1006 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQroPnOAuJb6FslKhjh:-MQvhm0tEJTZF8tyX5eG:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L1006)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> leve
> ```
level
</blockquote></details>

Done.
___
*[engines/librpma.c, line 1008 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQv4kgj5j3u7UVrYW4z:-MQvhpev2wYTZ3AEknqX:b-vapmg1) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L1008)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Yes. It is f**ked up. I will do another PR to clean up the topic of offsets.
___
*[engines/librpma.c, line 1008 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQuEeIIAAkrYHpa-Ihs:-MQvi7mV9E-zf-sg1EnU:b-qyqkx2) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L1008)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> td->o.iodepth = td->thread_number;
> ```
does it mean that each server thread has a different iodepth?

</blockquote></details>

Explained offline.
___
*[engines/librpma.c, line 1105 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQuFNje-iqDGlsW4ulQ:-MQviPDNEUSjIk4AmNrc:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L1105)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> goto err_mr_dereg;
> ```
additional empty line after goto, please
</blockquote></details>

Done.
___
*[engines/librpma.c, line 1125 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQuH6BgArNO0gZf3Iyh:-MQvj2Ma24duNoJ3xvYM:b-e3e67d) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L1125)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 	if (ret)
> 		rpma_td_verror(td, ret, "rpma_conn_next_event");
> 	if (!ret && conn_event != RPMA_CONN_ESTABLISHED) {
> 		log_err("rpma_conn_next_event returned an unexptected event\n");
> 		ret = 1;
> 	}
> 	if (ret)
> 		goto err_conn_delete;
> ```
Is there any reason to consolidate these two (if + goto) into two if + one goto?
The original code was much clear.
</blockquote></details>

Yes. It is a copy-paste from the GPSPM server. Even if I would agree with you, I think for consistency sake it will be better to keep it the same for both engines just to not complicate the unification process.
___
*[engines/librpma.c, line 1172 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQrm5UL6ohHEE1gPtyB:-MQvjPFl1-cigzyNRUh_:b-wulvrd) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/engines/librpma.c#L1172)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> |= ret
> ```
```
= 1
```
will be enough just to indicate that an error occurred
same below ...
</blockquote></details>

Same here. Blame GPSPM. APM only does the same thing in the same way. It can be reworked when unified.
___
*[examples/librpma-server.fio, line 13 at r1](https://reviewable.io/reviews/pmem/fio/109#-MQusb_yDbWUk5nr8P1W:-MQvinst-S1ME63dp7Ya:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e71433728a3b95c8e6915ea3122f49e70dbec156/examples/librpma-server.fio#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> client-side
> ```

`client side`
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/109#-:-MQvn0307u9Usb95J5BL:bnfp4nl)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/109)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/109)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/109#-:-MQvtQ0d9khVx2QZVSmQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
