### PR TITLE
rpma: scaffolding of the GPSPM server

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/50)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 218 at r1](https://reviewable.io/reviews/pmem/fio/50#-MLhPGs54r3IuxsTTHjr:-MLhPGs54r3IuxsTTHjs:bjwrjmr) ([raw file](https://github.com/pmem/fio/blob/049cfe07a48848b30cf07d2857a424cf37c341f8/engines/librpma_gpspm.c#L218)):*
> ```C
> 	/*
> 	 * - configure logging thresholds
> 	 * - allocate memory for server's data
> ```

These two should be done in the `init()` hook. Why here?
___
*[engines/librpma_gpspm.c, line 226 at r1](https://reviewable.io/reviews/pmem/fio/50#-MLhPcAL15dcLXnUOfn9:-MLhPcAM4SsKXC-u1HXj:bd8vslh) ([raw file](https://github.com/pmem/fio/blob/049cfe07a48848b30cf07d2857a424cf37c341f8/engines/librpma_gpspm.c#L226)):*
> ```C
> {
> 	/*
> 	 * - allocate memory for messaging buffers in DRAM (iou_s)
> ```

This one should be done by the FIO framework.
___
*[engines/librpma_gpspm.c, line 229 at r1](https://reviewable.io/reviews/pmem/fio/50#-MLhQ9oq8gbXb0S39w2N:-MLhQ9oq8gbXb0S39w2O:b-pmoxkr) ([raw file](https://github.com/pmem/fio/blob/049cfe07a48848b30cf07d2857a424cf37c341f8/engines/librpma_gpspm.c#L229)):*
> ```C
> 	 * - rpma_utils_get_ibv_context
> 	 * - rpma_peer_new
> 	 * - rpma_ep_listen(port=thread_number)
> ```

`base_port + thread_number - 1`
___
*[engines/librpma_gpspm.c, line 229 at r1](https://reviewable.io/reviews/pmem/fio/50#-MLhQFOwB0Ua0AT6eN_l:-MLhQFOwB0Ua0AT6eN_m:b-mjkd1x) ([raw file](https://github.com/pmem/fio/blob/049cfe07a48848b30cf07d2857a424cf37c341f8/engines/librpma_gpspm.c#L229)):*
> ```C
> 	 * - rpma_utils_get_ibv_context
> 	 * - rpma_peer_new
> 	 * - rpma_ep_listen(port=thread_number)
> ```

```c
/* XXX assuming one thread */
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 218 at r1](https://reviewable.io/reviews/pmem/fio/50#-MLhPGs54r3IuxsTTHjr:-MLhT5I2-mcaOUfdpvlz:b-ricg05) ([raw file](https://github.com/pmem/fio/blob/049cfe07a48848b30cf07d2857a424cf37c341f8/engines/librpma_gpspm.c#L218)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

These two should be done in the `init()` hook. Why here?
</blockquote></details>

I thought they should be one for whole server. Moved to `init()`.
___
*[engines/librpma_gpspm.c, line 226 at r1](https://reviewable.io/reviews/pmem/fio/50#-MLhPcAL15dcLXnUOfn9:-MLhTTuu-q-Lk7QApeqH:b-896fix) ([raw file](https://github.com/pmem/fio/blob/049cfe07a48848b30cf07d2857a424cf37c341f8/engines/librpma_gpspm.c#L226)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This one should be done by the FIO framework.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 229 at r1](https://reviewable.io/reviews/pmem/fio/50#-MLhQ9oq8gbXb0S39w2N:-MLhTdj679Y510HnGgjv:b-896fix) ([raw file](https://github.com/pmem/fio/blob/049cfe07a48848b30cf07d2857a424cf37c341f8/engines/librpma_gpspm.c#L229)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`base_port + thread_number - 1`
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 229 at r1](https://reviewable.io/reviews/pmem/fio/50#-MLhQFOwB0Ua0AT6eN_l:-MLhTluz4KASMBuMfIbt:b-8jtx4w) ([raw file](https://github.com/pmem/fio/blob/049cfe07a48848b30cf07d2857a424cf37c341f8/engines/librpma_gpspm.c#L229)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
/* XXX assuming one thread */
```
</blockquote></details>

But only as the first step, right?

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 229 at r1](https://reviewable.io/reviews/pmem/fio/50#-MLhQFOwB0Ua0AT6eN_l:-MLhURz08tROxiX2mtv4:b4jrwfy) ([raw file](https://github.com/pmem/fio/blob/049cfe07a48848b30cf07d2857a424cf37c341f8/engines/librpma_gpspm.c#L229)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

But only as the first step, right?
</blockquote></details>

Yes. In this comment, I meant to add to the `rpma_ep_listen...`.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 229 at r1](https://reviewable.io/reviews/pmem/fio/50#-MLhQFOwB0Ua0AT6eN_l:-MLhY_Cz4zCcOYHS_q_T:ba3dfob) ([raw file](https://github.com/pmem/fio/blob/049cfe07a48848b30cf07d2857a424cf37c341f8/engines/librpma_gpspm.c#L229)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yes. In this comment, I meant to add to the `rpma_ep_listen...`.
</blockquote></details>

Removed

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50#-:-MLhYxhr9UXdz7xvT591:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 244 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhil6X7lLAuZMF8dxa:-MLhil6Y-W9vYsIXdnAa:byfxx22) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L244)):*
> ```C
> static int server_open_file(struct thread_data *td, struct fio_file *f)
> {
> 	/*
> ```

Shall we start with pmem_map_fle?
___
*[engines/librpma_gpspm.c, line 246 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhjnBO37vScbFVxAn7:-MLhjnBO37vScbFVxAn8:buk2lh1) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L246)):*
> ```
> rpma_mr_reg(messaging buffer from DRAM)
> ```
=> post_init() before rpma_recv()
___
*[engines/librpma_gpspm.c, line 258 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhkxcp3ieNkTyRxP3b:-MLhkxcp3ieNkTyRxP3c:b-95nb8m) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L258)):*
> ```
> - rpma_mr_dereg(messaging buffer from DRAM)
> ```
to .cleanup
___
*[engines/librpma_gpspm.c, line 270 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhkamPEZaYoCQ3q6Gh:-MLhkamPEZaYoCQ3q6Gi:bma4f8l) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L270)):*
> ```C
> 	 * - rpma_conn_completion_wait()
> 	 * - rpma_conn_completion_get()
> 	 * - pmem_persist(f, NULL);
> ```

- rpma_recv() to prepare for next incoming receive

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 269 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhnu7c5fG1ynypn49B:-MLhnu7c5fG1ynypn49C:b-j93fa7) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L269)):*
> ```
> rpma_conn_completion_get
> ```
get could also return error => connection close what should be a signal to close/end server side.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: all files reviewed, 7 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 229 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhoiej1wzjwliMA0bb:-MLhoiekBUpMLyDg0L1C:b-xm9ivn) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L229)):*
> ```
> rpma_recv
> ```
do we use io_depth here to post as many recv as io_depth?
___
*[engines/librpma_gpspm.c, line 272 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhpPIx7r-vyylQJITq:-MLhpPIyBubnjRmbRTAA:b1eu3g1) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L272)):*
> ```
> FIO_Q_BUSY
> ```
is this a preparation for flush/drain solution in the future?
shall we skip this for the first implementation? and return here FIO_Q_COMPLETED

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: all files reviewed, 8 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 230 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhqAW76y8UxdaxfNw9:-MLhqAW76y8UxdaxfNwA:b-eo3ikz) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L230)):*
> ```C
> 	/*
> 	 * - rpma_recv()
> 	 */
> ```


shall we here accept connection?
shall we here send pmem_mr to a client?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: all files reviewed, 9 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 221 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhwkCL2Y2B4c49YDSV:-MLhwkCL2Y2B4c49YDSW:b-fq2w9d) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L221)):*
> ```
> rpma_ep_listen(port=(base_port + thread_number - 1))
> ```
I would propose to implement 1:1 relation first

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 221 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhwkCL2Y2B4c49YDSV:-MLiXhFK5tWa0MQrU87U:ba3voab) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L221)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_ep_listen(port=(base_port + thread_number - 1))
> ```
I would propose to implement 1:1 relation first
</blockquote></details>

If by "1:1" you mean a single-threaded workload I do agree. So here we will have just `port`.
Sorry @ldorau for misleading you. I lost my focus. ;-)
___
*[engines/librpma_gpspm.c, line 229 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhoiej1wzjwliMA0bb:-MLiY8YcDt468G1eCViK:brq5xdl) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L229)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_recv
> ```
do we use io_depth here to post as many recv as io_depth?
</blockquote></details>

Yeah. I think we use it at least as the first approximation. We can discuss later if having a separate option for this makes more sense.
___
*[engines/librpma_gpspm.c, line 230 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhqAW76y8UxdaxfNw9:-MLiYWL95URsKSOvDbtx:byki6qi) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L230)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>


shall we here accept connection?
shall we here send pmem_mr to a client?
</blockquote></details>

We can accept a connection only when the file is opened since otherwise, we do not have a memory region to pass.
So we have to:
- post_init()
    - rpma_mr_reg() recv buffers
- open_file()
    - pmem_map_file()
    - rpma_mr_reg(pmem)
    - rpma_ep_next_conn_req()
    - rpma_recv()
    - rpma_conn_connect(pmem's memory region)

Hopefully, we can relay on `post_init() -> open_file()` hooks order.
___
*[engines/librpma_gpspm.c, line 244 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhil6X7lLAuZMF8dxa:-MLiZlQ99259OxisfCMd:bitulan) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L244)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we start with pmem_map_fle?
</blockquote></details>

Yes, we should. See the comment above.
___
*[engines/librpma_gpspm.c, line 246 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhjnBO37vScbFVxAn7:-MLiZuBE-tHGMzlwn1dB:b-pbdqz3) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L246)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_mr_reg(messaging buffer from DRAM)
> ```
=> post_init() before rpma_recv()
</blockquote></details>

Agreed.
___
*[engines/librpma_gpspm.c, line 258 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhkxcp3ieNkTyRxP3b:-MLiZySF0VCLWwg-Kzos:bgaks4g) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L258)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> - rpma_mr_dereg(messaging buffer from DRAM)
> ```
to .cleanup
</blockquote></details>

Yup. You are right.
___
*[engines/librpma_gpspm.c, line 269 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhnu7c5fG1ynypn49B:-MLi_53Y1sl_MxzoDMj3:b3bwoia) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L269)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_conn_completion_get
> ```
get could also return error => connection close what should be a signal to close/end server side.
</blockquote></details>

It is a really advanced thing you are asking for at this stage. Probably we will try to make use of `td->terminate` then.
___
*[engines/librpma_gpspm.c, line 270 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhkamPEZaYoCQ3q6Gh:-MLi_MFS6n8P0srsBrlN:b-ehxdz6) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L270)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

- rpma_recv() to prepare for next incoming receive
</blockquote></details>

Yes and...
- rpma_send(the response)
___
*[engines/librpma_gpspm.c, line 272 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhpPIx7r-vyylQJITq:-MLi_W3z7XmywoqTNsU1:b-96jfcv) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L272)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> FIO_Q_BUSY
> ```
is this a preparation for flush/drain solution in the future?
shall we skip this for the first implementation? and return here FIO_Q_COMPLETED
</blockquote></details>

TBH I believe it is a placeholder just to make the thing able to compile.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72)

___
*[engines/librpma_gpspm.c, line 221 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhwkCL2Y2B4c49YDSV:-MLii8yeEbdfRTOvC9hA:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L221)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If by "1:1" you mean a single-threaded workload I do agree. So here we will have just `port`.
Sorry @ldorau for misleading you. I lost my focus. ;-)
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 229 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhoiej1wzjwliMA0bb:-MLijGKuBv7tpmWRi9Sj:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L229)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yeah. I think we use it at least as the first approximation. We can discuss later if having a separate option for this makes more sense.
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 230 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhqAW76y8UxdaxfNw9:-MLim9wF9VNz-TjyoNG5:bp8l7bf) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L230)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We can accept a connection only when the file is opened since otherwise, we do not have a memory region to pass.
So we have to:
- post_init()
    - rpma_mr_reg() recv buffers
- open_file()
    - pmem_map_file()
    - rpma_mr_reg(pmem)
    - rpma_ep_next_conn_req()
    - rpma_recv()
    - rpma_conn_connect(pmem's memory region)

Hopefully, we can relay on `post_init() -> open_file()` hooks order.
</blockquote></details>

So where should `rpma_recv()`be? In `post_init()` or in `open_file()` ?

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma_gpspm.c, line 230 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhqAW76y8UxdaxfNw9:-MLinnrn3QmABkWuaGUW:b4o4cz7) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L230)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

So where should `rpma_recv()`be? In `post_init()` or in `open_file()` ?
</blockquote></details>

init it if it is executed after file open
___
*[engines/librpma_gpspm.c, line 269 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhnu7c5fG1ynypn49B:-MLij9Xr4scummQ_3ahW:b-yjsi7q) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L269)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is a really advanced thing you are asking for at this stage. Probably we will try to make use of `td->terminate` then.
</blockquote></details>

td->done as this is not an error situation

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma_gpspm.c, line 230 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhqAW76y8UxdaxfNw9:-MLipATc2sSMu9kuUQk2:b-30w2pw) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L230)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

init it if it is executed after file open
</blockquote></details>

but @janekmi wrote ` post_init() -> open_file() ` so it is not ???

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72)

___
*[engines/librpma_gpspm.c, line 230 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhqAW76y8UxdaxfNw9:-MLiwsry1NaH9dKYHMt1:b-2q0jnb) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L230)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

but @janekmi wrote ` post_init() -> open_file() ` so it is not ???
</blockquote></details>

Since we are using `create_serialize=0` the `open_file()` hook is not called before the `init()` hook.
I vote for keeping this assumption, merging this PR, and verifying it later when we pass the non-compilable commentary phase.
___
*[engines/librpma_gpspm.c, line 269 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhnu7c5fG1ynypn49B:-MLiwKcB6ZUhM3rYjKiz:b-wrnl9) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L269)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

td->done as this is not an error situation
</blockquote></details>

It not a part of this sprint nor this PR. Let's discuss it later.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50#-:-MLiy53k01yLFthNmPfz:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50#-:-MLl9S4sCWMfOgEZ67vB:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 230 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhqAW76y8UxdaxfNw9:-MLl9ltS7AX6zA9pN0SD:b32w0x) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L230)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since we are using `create_serialize=0` the `open_file()` hook is not called before the `init()` hook.
I vote for keeping this assumption, merging this PR, and verifying it later when we pass the non-compilable commentary phase.
</blockquote></details>

OK
___
*[engines/librpma_gpspm.c, line 244 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhil6X7lLAuZMF8dxa:-MLl8jjk-WmezHzvUcpK:bb6un1j) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L244)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yes, we should. See the comment above.
</blockquote></details>

Done
___
*[engines/librpma_gpspm.c, line 258 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhkxcp3ieNkTyRxP3b:-MLl9urNA3fGvCwr47bL:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L258)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yup. You are right.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 270 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhkamPEZaYoCQ3q6Gh:-MLlAC2i3t5xYf3sTWBP:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L270)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yes and...
- rpma_send(the response)
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50#-:-MLlFzGj60vUq8_0fCPf:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 230 at r3](https://reviewable.io/reviews/pmem/fio/50#-MLhqAW76y8UxdaxfNw9:-MLlFYPP-bxe6rKJkbfe:b32w0x) ([raw file](https://github.com/pmem/fio/blob/8ef52d0c6a5ac22f579124f76c1fd00f50fa1a21/engines/librpma_gpspm.c#L230)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK
</blockquote></details>

OK

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/50)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
