### PR TITLE
rpma: add setup() hook comment

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/3)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
Please rebase

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/3#-:-MJBOa8r8gA53S_CtzeQ:b-n6khor)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 128 at r1](https://reviewable.io/reviews/pmem/fio/3#-MJBOwTcBrD4DrHBJBc7:-MJBOwTcBrD4DrHBJBc8:b-37obc7) ([raw file](https://github.com/pmem/fio/blob/f2033bbcc6415dfcbc4b52b3a0406081b13869b9/engines/librpma.c#L128)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> static int server_setup(struct thread_data *td)
> {
> 	return 0;
> }
> ```
</details>


Isn't it helpful in `server_setup()` either?

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/3)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/3#-:-MJBUqbZ3J_fc1-9Zu4m:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/3#-:-MJCR3ekEHnx7K3KOFC8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/3)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Pull request merged**
