### PR TITLE
aof: set direct_write_to_pmem

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/249)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/249)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma_aof.c, line 362 at r1](https://reviewable.io/reviews/pmem/fio/249#-MUrgjIg2tN9hlwCi3YI:-MUrgjIhETjfANg4U1UR:bkfj4wo) ([raw file](https://github.com/pmem/fio/blob/687c94a35665f62e5bc3e310509dfd956d463270/engines/librpma_aof.c#L362)):*
> ```C
> 		log_err(
> 			"Note: Direct Write to PMem is not supported by default nor required if you use DRAM instead of PMem on the server side (direct_write_to_pmem).\n"
> 			"Remember that flushing to DRAM does not make your data persistent and may be used only for experimental purposes.\n");
> ```

Please use `librpma_td_log()`. :-)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/249)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_aof.c, line 335 at r1](https://reviewable.io/reviews/pmem/fio/249#-MUrh2LC8erfxu6dxJ1b:-MUrh2LC8erfxu6dxJ1c:b3kqx) ([raw file](https://github.com/pmem/fio/blob/687c94a35665f62e5bc3e310509dfd956d463270/engines/librpma_aof.c#L335)):*
> ```C
> 			if (td->thread_number == 1)
> 				log_err(
> 					"Fio librpma engine will not work until the Direct Write to PMem on the server side is possible (direct_write_to_pmem)\n");
> ```

.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/249)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_aof.c, line 335 at r1](https://reviewable.io/reviews/pmem/fio/249#-MUrhA0e3wSCMoAVFXJB:-MUrhA0e3wSCMoAVFXJC:b-ss9qz) ([raw file](https://github.com/pmem/fio/blob/687c94a35665f62e5bc3e310509dfd956d463270/engines/librpma_aof.c#L335)):*
> ```C
> 			if (td->thread_number == 1)
> 				log_err(
> 					"Fio librpma engine will not work until the Direct Write to PMem on the server side is possible (direct_write_to_pmem)\n");
> ```

... will not work in the 'hw` mode until the Direct Write to PMem...

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/249)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_aof.c, line 348 at r1](https://reviewable.io/reviews/pmem/fio/249#-MUrhWsk8X84CqVCdKPm:-MUrhWsk8X84CqVCdKPn:bdgz5l8) ([raw file](https://github.com/pmem/fio/blob/687c94a35665f62e5bc3e310509dfd956d463270/engines/librpma_aof.c#L348)):*
> ```C
> 			librpma_td_verror(td, ret,
> 				"rpma_peer_cfg_set_direct_write_to_pmem");
> 			goto err_cleanup_common;
> ```

`rpma_peer_cfg_delete()` is missing.
___
*[engines/librpma_aof.c, line 354 at r1](https://reviewable.io/reviews/pmem/fio/249#-MUrh_3LEEzOCxKNcb5z:-MUrh_3LEEzOCxKNcb6-:bdgz5l8) ([raw file](https://github.com/pmem/fio/blob/687c94a35665f62e5bc3e310509dfd956d463270/engines/librpma_aof.c#L354)):*
> ```C
> 			librpma_td_verror(td, ret,
> 				"rpma_conn_apply_remote_peer_cfg");
> 			goto err_cleanup_common;
> ```

`rpma_peer_cfg_delete()` is missing.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/249)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/249)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_aof.c, line 335 at r1](https://reviewable.io/reviews/pmem/fio/249#-MUrh2LC8erfxu6dxJ1b:-MUrjBbd3MuB7MXA5ImY:b-896fix) ([raw file](https://github.com/pmem/fio/blob/687c94a35665f62e5bc3e310509dfd956d463270/engines/librpma_aof.c#L335)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[engines/librpma_aof.c, line 335 at r1](https://reviewable.io/reviews/pmem/fio/249#-MUrhA0e3wSCMoAVFXJB:-MUrjKp-0bsKa05hEwcH:b-896fix) ([raw file](https://github.com/pmem/fio/blob/687c94a35665f62e5bc3e310509dfd956d463270/engines/librpma_aof.c#L335)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... will not work in the 'hw` mode until the Direct Write to PMem...
</blockquote></details>

Done.
___
*[engines/librpma_aof.c, line 348 at r1](https://reviewable.io/reviews/pmem/fio/249#-MUrhWsk8X84CqVCdKPm:-MUrjysH-tpMHwjfwpoe:b-896fix) ([raw file](https://github.com/pmem/fio/blob/687c94a35665f62e5bc3e310509dfd956d463270/engines/librpma_aof.c#L348)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`rpma_peer_cfg_delete()` is missing.
</blockquote></details>

Done.
___
*[engines/librpma_aof.c, line 354 at r1](https://reviewable.io/reviews/pmem/fio/249#-MUrh_3LEEzOCxKNcb5z:-MUrk-c_-7AD6PR-pEqp:b-896fix) ([raw file](https://github.com/pmem/fio/blob/687c94a35665f62e5bc3e310509dfd956d463270/engines/librpma_aof.c#L354)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`rpma_peer_cfg_delete()` is missing.
</blockquote></details>

Done.
___
*[engines/librpma_aof.c, line 362 at r1](https://reviewable.io/reviews/pmem/fio/249#-MUrgjIg2tN9hlwCi3YI:-MUrj3sQ76_yly8mtSpI:b-896fix) ([raw file](https://github.com/pmem/fio/blob/687c94a35665f62e5bc3e310509dfd956d463270/engines/librpma_aof.c#L362)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please use `librpma_td_log()`. :-)
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/249#-:-MUrnue8BrXJycHA8jLR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

___
*[engines/librpma_aof.c, line 347 at r2](https://reviewable.io/reviews/pmem/fio/249#-MUrnwKW7uv6uSpGl58j:-MUrnwKW7uv6uSpGl58k:b1ei5ps) ([raw file](https://github.com/pmem/fio/blob/65370062224cb09cc80d35c6324323960e773d60/engines/librpma_aof.c#L347)):*
> ```C
> 			librpma_td_verror(td, ret,
> 				"rpma_peer_cfg_set_direct_write_to_pmem");
> 			(void) rpma_peer_cfg_delete(&pcfg);
> ```

**Info**: This fix is also needed for the apm engine.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/249)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/249#-:-MUrpcve26gOcOICiM8A:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
