### PR TITLE
rpma: gpspm: each thread registers only its own workspace

### PR DESCRIPTION
**Pull request by janekmi**
It is the equivalent of #112 for the GPSPM engine.

Requires:
- [x] #111
- [x] #112
- [x] #113

bw_th

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/114)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/114)* status: 4 of 5 files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/114)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/114)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/114#-:-MR-bh1E5QRXJhxTm7pd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/114#-:-MR-cPxgEL82slyHkp8i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
