### PR TITLE
rpma: fix all examples job files

### PR DESCRIPTION
**Pull request by janekmi**
- simplify create_serialize requirement
- extend numjobs description
- iomem_align=$pagesize the only valid value
- fix server memory handling description
- fix iodepth GPSPM server description
- unify filename description for both servers
- remove iomem_align from APM server (no longer relevant)
- ...

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/176)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/176#-:-MR_1djR44BRNHnYHISJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/176)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/176#-:-MR_8msIEjGEDpcLZNCy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/176#-:-MR_BCpf2s1rpWMwRBwV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/176)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[examples/librpma-server.fio, line 19 at r2](https://reviewable.io/reviews/pmem/fio/176#-MR_BH-h7HLdXRoCtvuJ:-MR_BH-h7HLdXRoCtvuK:b-p78nk0) ([raw file](https://github.com/pmem/fio/blob/5308f18a278c75c14f6d2b6066fa46ae449251b1/examples/librpma-server.fio#L19)):*
> ```
> set to true
> ```

`set to 1 (true)` ?
___
*[examples/librpma_gpspm-server.fio, line 20 at r2](https://reviewable.io/reviews/pmem/fio/176#-MR_BSHi99tgCn-ytJI0:-MR_BSHi99tgCn-ytJI1:b-u79f9k) ([raw file](https://github.com/pmem/fio/blob/5308f18a278c75c14f6d2b6066fa46ae449251b1/examples/librpma_gpspm-server.fio#L20)):*
> ```
> set to true
> ```

.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/176)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[examples/librpma-server.fio, line 19 at r2](https://reviewable.io/reviews/pmem/fio/176#-MR_BH-h7HLdXRoCtvuJ:-MR_CcyT9FzFxlta7y_n:b-896fix) ([raw file](https://github.com/pmem/fio/blob/5308f18a278c75c14f6d2b6066fa46ae449251b1/examples/librpma-server.fio#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> set to true
> ```

`set to 1 (true)` ?
</blockquote></details>

Done.
___
*[examples/librpma_gpspm-server.fio, line 20 at r2](https://reviewable.io/reviews/pmem/fio/176#-MR_BSHi99tgCn-ytJI0:-MR_CeRU4raBrBnjfg_a:b-896fix) ([raw file](https://github.com/pmem/fio/blob/5308f18a278c75c14f6d2b6066fa46ae449251b1/examples/librpma_gpspm-server.fio#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> set to true
> ```

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/176)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/176#-:-MR_CogP6-ValGnt99sA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
