### PR TITLE
rpma: common: servers' open_file and close_file

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/146)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_common.h, line 217 at r1](https://reviewable.io/reviews/pmem/fio/146#-MRPiMC7-2l48Jdu2-aG:-MRPpNSMCpI7OYoYd1ta:b-7203ui) ([raw file](https://github.com/pmem/fio/blob/aaf88501fdd565b9dab7e9bc215e87cbacac14e9/engines/librpma_common.h#L217)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> int librpma_common_server_open_file(struct thread_data *td, struct fio_file *f,
> 				struct rpma_conn_private_data *pdata);
> ```
shall we also pass ```struct rpma_conn_cfg *cfg``` to avoid ep to be stored (and used) outside of open_file()?
</blockquote></details>

How can it help avoiding using ep outside of open_file()?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_common.h, line 217 at r1](https://reviewable.io/reviews/pmem/fio/146#-MRPiMC7-2l48Jdu2-aG:-MRPu6fV4LLvmtY68OrM:ba5vdqf) ([raw file](https://github.com/pmem/fio/blob/aaf88501fdd565b9dab7e9bc215e87cbacac14e9/engines/librpma_common.h#L217)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

How can it help avoiding using ep outside of open_file()?
</blockquote></details>

Besides `cfg` is not common (yet).

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_common.h, line 217 at r1](https://reviewable.io/reviews/pmem/fio/146#-MRPiMC7-2l48Jdu2-aG:-MRPube55udzxocdf9VK:b-tiy9rj) ([raw file](https://github.com/pmem/fio/blob/aaf88501fdd565b9dab7e9bc215e87cbacac14e9/engines/librpma_common.h#L217)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Besides `cfg` is not common (yet).
</blockquote></details>

Because `cfg` is the missing piece to rule them all. :mage_man: 
___
*[engines/librpma_common.h, line 200 at r2](https://reviewable.io/reviews/pmem/fio/146#-MRPtl1pB7I5sa5ZUU4m:-MRPtl1pB7I5sa5ZUU4n:b-5jdsyy) ([raw file](https://github.com/pmem/fio/blob/c6583eaf75094ce2abb5973144945238bda65f24/engines/librpma_common.h#L200)):*
> ```objc
> struct librpma_common_server_data {
> 	struct rpma_peer *peer;
> 	struct rpma_ep *ep;
> ```

The previous design of open_file hook did as follows:
- ep_listen
- accept
- ep_shutdown

I think we can do the same here so no point in caching ep will remain.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_common.c, line 795 at r2](https://reviewable.io/reviews/pmem/fio/146#-MRPx_ok8FijETQTmkOn:-MRPx_ol6TMeFpS_m4cY:b3pc26v) ([raw file](https://github.com/pmem/fio/blob/c6583eaf75094ce2abb5973144945238bda65f24/engines/librpma_common.c#L795)):*
> ```C
> 	size_t mem_size = td->o.size;
> 	struct rpma_mr_local *mr;
> 	struct librpma_common_workspace ws;
> ```

FYI `ws` is invalid outside this function so `pdata` cannot take it outside.
___
*[engines/librpma_common.c, line 886 at r2](https://reviewable.io/reviews/pmem/fio/146#-MRPyBqTCmAd5_G2s1ss:-MRPyBqTCmAd5_G2s1st:b-9bksmd) ([raw file](https://github.com/pmem/fio/blob/c6583eaf75094ce2abb5973144945238bda65f24/engines/librpma_common.c#L886)):*
> ```C
> 	(void) rpma_ep_shutdown(&ep);
> 
> 	return (ret != 0 ? ret : 1);
> ```

`return 1`?

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_common.c, line 886 at r2](https://reviewable.io/reviews/pmem/fio/146#-MRPyBqTCmAd5_G2s1ss:-MRQ7vNX9O4kSkaimP87:bxvg1ua) ([raw file](https://github.com/pmem/fio/blob/c6583eaf75094ce2abb5973144945238bda65f24/engines/librpma_common.c#L886)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`return 1`?
</blockquote></details>

not this PR

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_common.h, line 217 at r1](https://reviewable.io/reviews/pmem/fio/146#-MRPiMC7-2l48Jdu2-aG:-MRQCBj09gOpLZ4Mv7S6:b-896fix) ([raw file](https://github.com/pmem/fio/blob/aaf88501fdd565b9dab7e9bc215e87cbacac14e9/engines/librpma_common.h#L217)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Because `cfg` is the missing piece to rule them all. :mage_man: 
</blockquote></details>

Done.
___
*[engines/librpma_common.h, line 200 at r2](https://reviewable.io/reviews/pmem/fio/146#-MRPtl1pB7I5sa5ZUU4m:-MRQC9Js954UwjNOVJng:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c6583eaf75094ce2abb5973144945238bda65f24/engines/librpma_common.h#L200)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The previous design of open_file hook did as follows:
- ep_listen
- accept
- ep_shutdown

I think we can do the same here so no point in caching ep will remain.
</blockquote></details>

Done.
___
*[engines/librpma_common.c, line 886 at r2](https://reviewable.io/reviews/pmem/fio/146#-MRPyBqTCmAd5_G2s1ss:-MRQCLKEBIyumb-zJiE2:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c6583eaf75094ce2abb5973144945238bda65f24/engines/librpma_common.c#L886)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

not this PR
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma_gpspm.c, line 554 at r3](https://reviewable.io/reviews/pmem/fio/146#-MRQLSYP7Ul9L1_BtO9T:-MRQLSYP7Ul9L1_BtO9U:b-s225g5) ([raw file](https://github.com/pmem/fio/blob/7e0281ae20fe06293be4b3810a0b4a3704b5530a/engines/librpma_gpspm.c#L554)):*
> ```C
> 	}
> 
> 	ret = librpma_common_server_open_file(td, f);
> ```

`cfg` is not used yet in this revision.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma_common.c, line 886 at r2](https://reviewable.io/reviews/pmem/fio/146#-MRPyBqTCmAd5_G2s1ss:-MRQLrcu5jkUixrOecbl:b20cj2p) ([raw file](https://github.com/pmem/fio/blob/c6583eaf75094ce2abb5973144945238bda65f24/engines/librpma_common.c#L886)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It seems to me that taking into account all we have discussed here it is enough that `ret` is printed whereas returning as an error `-1` is enough.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma_gpspm.c, line 485 at r3](https://reviewable.io/reviews/pmem/fio/146#-MRQMNvK541VE6xY2nlv:-MRQMNvK541VE6xY2nlw:b-6jb7my) ([raw file](https://github.com/pmem/fio/blob/7e0281ae20fe06293be4b3810a0b4a3704b5530a/engines/librpma_gpspm.c#L485)):*
> ```C
> }
> 
> static int prepare_connection(struct thread_data *td, struct rpma_conn_req *conn_req)
> ```

I can imagine you will give here `ep` instead of `conn_req` so you won't need passing a configuration pointer.
To consider.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_common.c, line 886 at r2](https://reviewable.io/reviews/pmem/fio/146#-MRPyBqTCmAd5_G2s1ss:-MRR75G-2-mhmZJHDTIn:bb6un1j) ([raw file](https://github.com/pmem/fio/blob/c6583eaf75094ce2abb5973144945238bda65f24/engines/librpma_common.c#L886)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems to me that taking into account all we have discussed here it is enough that `ret` is printed whereas returning as an error `-1` is enough. 
</blockquote></details>

Done
___
*[engines/librpma_gpspm.c, line 485 at r3](https://reviewable.io/reviews/pmem/fio/146#-MRQMNvK541VE6xY2nlv:-MRRCQaD-HK3RthOK8L8:b-un5ieq) ([raw file](https://github.com/pmem/fio/blob/7e0281ae20fe06293be4b3810a0b4a3704b5530a/engines/librpma_gpspm.c#L485)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I can imagine you will give here `ep` instead of `conn_req` so you won't need passing a configuration pointer.
To consider.
</blockquote></details>

I cannot imagine that ;-) 
1) What is wrong in passing `conn_req` ?
2) How can I extract `conn_req` from `ep`?
___
*[engines/librpma_gpspm.c, line 554 at r3](https://reviewable.io/reviews/pmem/fio/146#-MRQLSYP7Ul9L1_BtO9T:-MRRBb1Q4s4pYJRZIA6z:b-896fix) ([raw file](https://github.com/pmem/fio/blob/7e0281ae20fe06293be4b3810a0b4a3704b5530a/engines/librpma_gpspm.c#L554)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`cfg` is not used yet in this revision.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146#-:-MRREFth6hG9b-SdG_Np:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 485 at r3](https://reviewable.io/reviews/pmem/fio/146#-MRQMNvK541VE6xY2nlv:-MRRE4IHAwksMvLDZ2p5:b5b87eq) ([raw file](https://github.com/pmem/fio/blob/7e0281ae20fe06293be4b3810a0b4a3704b5530a/engines/librpma_gpspm.c#L485)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I cannot imagine that ;-) 
1) What is wrong in passing `conn_req` ?
2) How can I extract `conn_req` from `ep`?
</blockquote></details>

Nothing. It is fine. I have just come up with another possible way of implementing this thing. nvm. ;-)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 485 at r3](https://reviewable.io/reviews/pmem/fio/146#-MRQMNvK541VE6xY2nlv:-MRRG32Z9r1SfbbHVa02:b32w0x) ([raw file](https://github.com/pmem/fio/blob/7e0281ae20fe06293be4b3810a0b4a3704b5530a/engines/librpma_gpspm.c#L485)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Nothing. It is fine. I have just come up with another possible way of implementing this thing. nvm. ;-)
</blockquote></details>

OK

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/146#-MRTP_fG3_1TSnS3MKQp:-MRTP_fHE60a2bke1ain:bqn51tj) (no related file):*
with this PR (especially ```prepare_connection()``` I got an impression that we built our own (custom) calls structure on the top standard fio structure 
Fio: init, post init, open_file
librpma: init, open_file (with prepare_connection hook)

---
___
*[engines/librpma_common.h, line 191 at r4](https://reviewable.io/reviews/pmem/fio/146#-MRTNI85CdOUgsPvgnMR:-MRTNI85CdOUgsPvgnMS:b6z4rib) ([raw file](https://github.com/pmem/fio/blob/1b5b4a19434baf54f7073c3c3516439307d1eb89/engines/librpma_common.h#L191)):*
> ```
> prepare_connection_t
> ```
```librpma_common_prepare_connectio_t``` as it is a part of public interface

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[engines/librpma_common.h, line 191 at r4](https://reviewable.io/reviews/pmem/fio/146#-MRTNI85CdOUgsPvgnMR:-MRTU9CG5k0OePsqIP0B:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1b5b4a19434baf54f7073c3c3516439307d1eb89/engines/librpma_common.h#L191)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> prepare_connection_t
> ```
```librpma_common_prepare_connectio_t``` as it is a part of public interface
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/146#-:-MRTojhx8RZBmI43RQb4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
