### PR TITLE
aof: server open_file (the first approximation)

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #220

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/221)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/221#-:-MUDvPqJ25bhY_NgGcA_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/221)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_aof.c, line 307 at r1](https://reviewable.io/reviews/pmem/fio/221#-MUDxcvV205EnlAkhN1D:-MUDxcvWATKmLe6WKoa5:bj7or86) ([raw file](https://github.com/pmem/fio/blob/d19822ef94257153b7ff9c7bb3df60f50475026a/engines/librpma_aof.c#L307)):*
> ```C
> 	int i;
> 
> 	/* prepare buffers for a flush requests */
> ```

AOF update
___
*[engines/librpma_aof.c, line 340 at r1](https://reviewable.io/reviews/pmem/fio/221#-MUDxglO8NCh1C6h6hhq:-MUDxglO8NCh1C6h6hhr:b3kqx) ([raw file](https://github.com/pmem/fio/blob/d19822ef94257153b7ff9c7bb3df60f50475026a/engines/librpma_aof.c#L340)):*
> ```C
> 	 * Calculate the required queue sizes where:
> 	 * - the send queue (SQ) has to be big enough to accommodate
> 	 *   all possible flush requests (SENDs)
> ```

.
___
*[engines/librpma_aof.c, line 342 at r1](https://reviewable.io/reviews/pmem/fio/221#-MUDxkfV0tNMIa9nZ8u5:-MUDxkfV0tNMIa9nZ8u6:b3kqx) ([raw file](https://github.com/pmem/fio/blob/d19822ef94257153b7ff9c7bb3df60f50475026a/engines/librpma_aof.c#L342)):*
> ```C
> 	 *   all possible flush requests (SENDs)
> 	 * - the receive queue (RQ) has to be big enough to accommodate
> 	 *   all flush responses (RECVs)
> ```

.

**Review by osalyk — COMMENTED** [review]
Please rebase

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/221#-:-MUEDEGS0PxSVLF-VaJF:b-n6khor)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/221)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/221#-:-MUEH5S883mobrcoUMKz:b-896fix)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/221#-:-MUEGaUE5Wx0LdtpGUyg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
