### PR TITLE
Unused ret

### PR DESCRIPTION
**Pull request by osalyk**
+ add missing error logs

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/169)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/169)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma.c, line 137 at r1](https://reviewable.io/reviews/pmem/fio/169#-MRVwl8c7fzh-VYCVIHW:-MRVwl8d0rQTtXIAvhBB:b2tyq5x) ([raw file](https://github.com/pmem/fio/blob/0579cc30397945d49984696e63880d8515475a68/engines/librpma.c#L137)):*
> ```
> ((
> ```
```(```
___
*[engines/librpma.c, line 137 at r1](https://reviewable.io/reviews/pmem/fio/169#-MRVwnRdAJvhIepTeseD:-MRVwnRe7yWu_CiLaWOt:b-5ebmtc) ([raw file](https://github.com/pmem/fio/blob/0579cc30397945d49984696e63880d8515475a68/engines/librpma.c#L137)):*
> ```
> )))
> ```
```))```
___
*[engines/librpma_gpspm.c, line 160 at r1](https://reviewable.io/reviews/pmem/fio/169#-MRVxUav0wAIS1fRb3qk:-MRVxUaw3wq2FzqxqiVu:b2tyq5x) ([raw file](https://github.com/pmem/fio/blob/0579cc30397945d49984696e63880d8515475a68/engines/librpma_gpspm.c#L160)):*
> ```
> ((
> ```
```(```
___
*[engines/librpma_gpspm.c, line 160 at r1](https://reviewable.io/reviews/pmem/fio/169#-MRVxXBr5G034i2sK2rZ:-MRVxXBr5G034i2sK2r_:b-5ebmtc) ([raw file](https://github.com/pmem/fio/blob/0579cc30397945d49984696e63880d8515475a68/engines/librpma_gpspm.c#L160)):*
> ```
> )))
> ```
```))```
___
*[engines/librpma_gpspm.c, line 504 at r1](https://reviewable.io/reviews/pmem/fio/169#-MRVxh4FEY5NJzbq6Tmo:-MRVxh4G-LblyP4EAZRi:b-64xp4l) ([raw file](https://github.com/pmem/fio/blob/0579cc30397945d49984696e63880d8515475a68/engines/librpma_gpspm.c#L504)):*
> ```
> ((
> ```
```(
```

___
*[engines/librpma_gpspm.c, line 506 at r1](https://reviewable.io/reviews/pmem/fio/169#-MRVxmYV7mrpp7cy5cix:-MRVxmYV7mrpp7cy5ciy:b-5ebmtc) ([raw file](https://github.com/pmem/fio/blob/0579cc30397945d49984696e63880d8515475a68/engines/librpma_gpspm.c#L506)):*
> ```
> )))
> ```
```))```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/169)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72)

___
*[engines/librpma.c, line 137 at r1](https://reviewable.io/reviews/pmem/fio/169#-MRVwl8c7fzh-VYCVIHW:-MRYily5B2j51bi5OYHr:b-ief1wm) ([raw file](https://github.com/pmem/fio/blob/0579cc30397945d49984696e63880d8515475a68/engines/librpma.c#L137)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> ((
> ```
```(```
</blockquote></details>

warning: suggest parentheses around assignment used as truth value [-Wparentheses]
___
*[engines/librpma.c, line 137 at r1](https://reviewable.io/reviews/pmem/fio/169#-MRVwnRdAJvhIepTeseD:-MRYiojs03R0fHQAkk_f:b3kqx) ([raw file](https://github.com/pmem/fio/blob/0579cc30397945d49984696e63880d8515475a68/engines/librpma.c#L137)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> )))
> ```
```))```
</blockquote></details>

.
___
*[engines/librpma_gpspm.c, line 160 at r1](https://reviewable.io/reviews/pmem/fio/169#-MRVxUav0wAIS1fRb3qk:-MRYiq-t61INijjlxBuY:b3kqx) ([raw file](https://github.com/pmem/fio/blob/0579cc30397945d49984696e63880d8515475a68/engines/librpma_gpspm.c#L160)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> ((
> ```
```(```
</blockquote></details>

.
___
*[engines/librpma_gpspm.c, line 160 at r1](https://reviewable.io/reviews/pmem/fio/169#-MRVxXBr5G034i2sK2rZ:-MRYir1-4-6RgJP4R2mY:b3kqx) ([raw file](https://github.com/pmem/fio/blob/0579cc30397945d49984696e63880d8515475a68/engines/librpma_gpspm.c#L160)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> )))
> ```
```))```
</blockquote></details>

.
___
*[engines/librpma_gpspm.c, line 504 at r1](https://reviewable.io/reviews/pmem/fio/169#-MRVxh4FEY5NJzbq6Tmo:-MRYisyl2pWSnINlmEf3:b3kqx) ([raw file](https://github.com/pmem/fio/blob/0579cc30397945d49984696e63880d8515475a68/engines/librpma_gpspm.c#L504)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> ((
> ```
```(
</blockquote></details>

.
___
*[engines/librpma_gpspm.c, line 506 at r1](https://reviewable.io/reviews/pmem/fio/169#-MRVxmYV7mrpp7cy5cix:-MRYiun262WSKVFm51jQ:b3kqx) ([raw file](https://github.com/pmem/fio/blob/0579cc30397945d49984696e63880d8515475a68/engines/librpma_gpspm.c#L506)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> )))
> ```
```))```
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/169#-:-MRYljkt3-bbNcfPmKwy:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72)

___
*[engines/librpma.c, line 137 at r1](https://reviewable.io/reviews/pmem/fio/169#-MRVwl8c7fzh-VYCVIHW:-MRYkSkr4fxzJZOuxo_8:bo0pbb6) ([raw file](https://github.com/pmem/fio/blob/0579cc30397945d49984696e63880d8515475a68/engines/librpma.c#L137)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

warning: suggest parentheses around assignment used as truth value [-Wparentheses]
</blockquote></details>

It is OK

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/169)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[engines/librpma_common.c, line 878 at r2](https://reviewable.io/reviews/pmem/fio/169#-MRYo586DTWg29jaGE5I:-MRYo587DINB_VM8NZk0:bmbugt3) ([raw file](https://github.com/pmem/fio/blob/380305ac0a9190a10b306003a3c01951458454f9/engines/librpma_common.c#L878)):*
> ```
> (csd->prepare_connection(td, conn_req)))
> ```

Additional parenthesis are not needed now:

`... && csd->prepare_connection(td, conn_req))`

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/169)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_common.c, line 878 at r2](https://reviewable.io/reviews/pmem/fio/169#-MRYo586DTWg29jaGE5I:-MRYpGGVAmFgafqtSVzC:b-896fix) ([raw file](https://github.com/pmem/fio/blob/380305ac0a9190a10b306003a3c01951458454f9/engines/librpma_common.c#L878)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> (csd->prepare_connection(td, conn_req)))
> ```

Additional parenthesis are not needed now:

`... && csd->prepare_connection(td, conn_req))`
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/169#-:-MRYpW5T9pPcpxJGNe-E:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/169)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/169)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
