### PR TITLE
rpma: implement client_init()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/10)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10)* status: all files reviewed, 6 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 76 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJSP-SV9vPtdOmgkx14:-MJSP-SV9vPtdOmgkx15:b-pqkpeo) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L76)):*
> ```C
> 	int ret;
> 
> 	(void) o; /* XXX delete when o will be used */
> ```

Please delete since the condition is met. :-)
___
*[engines/librpma.c, line 81 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJSHCuDDwn6-FOYKrQv:-MJSHCuDDwn6-FOYKrQw:bbibji3) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L81)):*
> ```C
> 	cd = malloc(sizeof(struct client_data));
> 	if (cd == NULL) {
> 		log_err("fio: malloc() failed: %m\n");
> ```

I can not find what `%m` does.
___
*[engines/librpma.c, line 85 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJSF_DZ1Ir4uSHykc96:-MJSF_DZ1Ir4uSHykc97:b2p8yre) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L85)):*
> ```C
> 	}
> 
> 	memset(cd, 0, sizeof(*cd));
> ```

Some time ago you have argued such use of `sizeof` is not according to standard.
___
*[engines/librpma.c, line 94 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJSHSEM8QFF0TDUv7P2:-MJSHSEM8QFF0TDUv7P3:bsv02gk) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L94)):*
> ```C
> 		goto err_free_cd;
> 	}
> 	memset(cd->io_us_queued, 0, td->o.iodepth * sizeof(struct io_u *));
> ```

It looks like an ideal scenario for `calloc()` e.g.:

```c
cd->io_us_queued = calloc(td->o.iodepth, sizeof(struce io_u *));
if (/* ... */) {
    /* ... */
}
/* no memset here */
```
___
*[engines/librpma.c, line 95 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJSHPg2B5KSgXiuQugL:-MJSHPg2B5KSgXiuQugM:b-d76nvl) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L95)):*
> ```C
> 	}
> 	memset(cd->io_us_queued, 0, td->o.iodepth * sizeof(struct io_u *));
> 	cd->io_u_queued_nr = 0;
> ```

It should be already zeroed.
___
*[engines/librpma.c, line 146 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJSToUT5IuDJIw9nYJ4:-MJSToUT5IuDJIw9nYJ5:b3lmlsb) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L146)):*
> ```C
> 		goto err_req_delete;
> 	}
> ```

You have to wait for RPMA_CONN_ESTABLISHED.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10)* status: all files reviewed, 7 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 167 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJTiqFl3rqglixRyQbM:-MJTiqFl3rqglixRyQbN:b-7624vp) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L167)):*
> ```C
> 	free(cd);
> 
> 	return 1;
> ```

`return ret`?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10)* status: all files reviewed, 8 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 73 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJTj-bW5B3QtGyQ_0Fe:-MJTj-bW5B3QtGyQ_0Ff:bnzbjz5) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L73)):*
> ```C
> 	struct ibv_context *dev = NULL;
> 	struct rpma_conn_req *req = NULL;
> 	struct rpma_conn *conn = NULL;
> ```

`conn` has to be a field in the `struct client_data`.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10)* status: all files reviewed, 12 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 81 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJTntiU3RID266qNzuI:-MJTntiU3RID266qNzuJ:b-mfyy4f) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L81)):*
> ```C
> 	cd = malloc(sizeof(struct client_data));
> 	if (cd == NULL) {
> 		log_err("fio: malloc() failed: %m\n");
> ```

I think the better idea is to use `td_verror()`. It seems also more popular among other engines.
What do you think?
___
*[engines/librpma.c, line 119 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJTo9we1V6jtDd4qME1:-MJTo9we1V6jtDd4qME2:btzczc9) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L119)):*
> ```C
> 	if (ret) {
> 		log_err("fio: rpma_utils_get_ibv_context() failed: %s\n",
> 			rpma_err_2str(ret));
> ```

I think we should an entity created during the hackathon:

```c
#define rpma_td_verror(td, err, func) \
	td_vmsg((td), (err), rpma_err_2str(err), (func))
```

Ref: https://github.com/janekmi/fio/blob/master/engines/librpma_server.c#L20
___
*[engines/librpma.c, line 127 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJToTs_DAcJOt8VwQhZ:-MJToTs_DAcJOt8VwQh_:b3kqx) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L127)):*
> ```C
> 	if (ret) {
> 		log_err("fio: rpma_peer_new() failed: %s\n",
> 			rpma_err_2str(ret));
> ```

.
___
*[engines/librpma.c, line 135 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJToUwo3EjBs647JvEH:-MJToUwo3EjBs647JvEI:b3kqx) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L135)):*
> ```C
> 	if (ret) {
> 		log_err("fio: rpma_conn_req_new() failed: %s\n",
> 			rpma_err_2str(ret));
> ```

.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10)* status: all files reviewed, 13 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma.c, line 146 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJU5GUl4OVPkZKrLis6:-MJU5GUmAzxVI6HgT09E:bpus1ga) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L146)):*
> ```C
> 		goto err_req_delete;
> 	}
> ```

```c
td->io_ops_data = cd;
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10)* status: 0 of 1 files reviewed, 13 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 73 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJTj-bW5B3QtGyQ_0Fe:-MJVeoOF4rNMVB4nX1dY:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L73)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`conn` has to be a field in the `struct client_data`.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 76 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJSP-SV9vPtdOmgkx14:-MJVeqwODOWNUNbdxOKY:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L76)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please delete since the condition is met. :-)
</blockquote></details>

Done.
___
*[engines/librpma.c, line 81 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJSHCuDDwn6-FOYKrQv:-MJVfr_hEipnm6_il_wj:b-4x58t7) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L81)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I can not find what `%m` does.
</blockquote></details>

https://www.gnu.org/software/libc/manual/html_node/Other-Output-Conversions.html

```
The ‘%m’ conversion prints the string corresponding to the error code in errno. See Error Messages. Thus:

             fprintf (stderr, "can't open `%s': %m\n", filename);

is equivalent to:

             fprintf (stderr, "can't open `%s': %s\n", filename, strerror (errno));

The ‘%m’ conversion is a GNU C Library extension.
```
___
*[engines/librpma.c, line 81 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJTntiU3RID266qNzuI:-MJW3D48B7HLdrWaNKRT:b1n57lg) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L81)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think the better idea is to use `td_verror()`. It seems also more popular among other engines.
What do you think?
</blockquote></details>

Do you mean `rpma_td_verror()` ?
___
*[engines/librpma.c, line 85 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJSF_DZ1Ir4uSHykc96:-MJVgCx2CymJHhSLMlqV:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L85)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Some time ago you have argued such use of `sizeof` is not according to standard.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 94 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJSHSEM8QFF0TDUv7P2:-MJVhIrlBqiYOngDoRHM:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L94)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It looks like an ideal scenario for `calloc()` e.g.:

```c
cd->io_us_queued = calloc(td->o.iodepth, sizeof(struce io_u *));
if (/* ... */) {
    /* ... */
}
/* no memset here */
```
</blockquote></details>

Done.
___
*[engines/librpma.c, line 95 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJSHPg2B5KSgXiuQugL:-MJVhJBdCiA45BUSANED:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L95)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It should be already zeroed.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 119 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJTo9we1V6jtDd4qME1:-MJVjjNS2C6v1Vf9FjLF:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L119)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we should an entity created during the hackathon:

```c
#define rpma_td_verror(td, err, func) \
	td_vmsg((td), (err), rpma_err_2str(err), (func))
```

Ref: https://github.com/janekmi/fio/blob/master/engines/librpma_server.c#L20
</blockquote></details>

Done.
___
*[engines/librpma.c, line 127 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJToTs_DAcJOt8VwQhZ:-MJVjjsc-rRgPZVc4kxu:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L127)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 135 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJToUwo3EjBs647JvEH:-MJVjkSu1GW-QpDK4RcD:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L135)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 146 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJSToUT5IuDJIw9nYJ4:-MJWRhft2FlSSSWVx4Ap:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L146)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have to wait for RPMA_CONN_ESTABLISHED.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 146 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJU5GUl4OVPkZKrLis6:-MJWRi3N2GwBGXd6-uFz:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L146)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
td->io_ops_data = cd;
```
</blockquote></details>

Done.
___
*[engines/librpma.c, line 167 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJTiqFl3rqglixRyQbM:-MJWRie08I_kSj7o1Q5o:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L167)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`return ret`?
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10)* status: 0 of 1 files reviewed, 14 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 71 at r2](https://reviewable.io/reviews/pmem/fio/10#-MJWTymw6v16Jzk8o3rW:-MJWTymw6v16Jzk8o3rX:b-gzk1m4) ([raw file](https://github.com/pmem/fio/blob/ae1853f1e61c0312ebc8c5553c43166db891a228/engines/librpma.c#L71)):*
> ```
> client_init
> ```
client_post_init if we want to register local memory before connection is established

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10)* status: all files reviewed, 14 unresolved discussions (waiting on @janekmi and @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10)* status: all files reviewed, 14 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma.c, line 71 at r2](https://reviewable.io/reviews/pmem/fio/10#-MJWTymw6v16Jzk8o3rW:-MJWXApI79d7cnM7fAG6:b-qsl7d0) ([raw file](https://github.com/pmem/fio/blob/ae1853f1e61c0312ebc8c5553c43166db891a228/engines/librpma.c#L71)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> client_init
> ```
client_post_init if we want to register local memory before connection is established
</blockquote></details>

@janekmi do we want ... ?

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 81 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJTntiU3RID266qNzuI:-MJWWiET2baleBTrjUSP:bizjkr1) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L81)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Do you mean `rpma_td_verror()` ?
</blockquote></details>

This line requires specifically `td_verror` since errno does not convey a valid RPMA error code. ;-)
___
*[engines/librpma.c, line 94 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJSHSEM8QFF0TDUv7P2:-MJWXN7R0wulfLwaI6yJ:b-6i1luv) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L94)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nope. Please see the arguments I have proposed above.
___
*[engines/librpma.c, line 119 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJTo9we1V6jtDd4qME1:-MJWXVvZ4Ks-D7iZ7y7u:benie29) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L119)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

errno -> ret
___
*[engines/librpma.c, line 127 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJToTs_DAcJOt8VwQhZ:-MJWXXf0AxbR4kEVsYFG:benie29) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L127)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

errno -> ret
___
*[engines/librpma.c, line 135 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJToUwo3EjBs647JvEH:-MJWX_-PBsmAKMFHonHJ:b-ddknpt) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L135)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

errno->ret
___
*[engines/librpma.c, line 71 at r2](https://reviewable.io/reviews/pmem/fio/10#-MJWTymw6v16Jzk8o3rW:-MJWVOm4Ap2lIN-9Y1Q9:b-1rg26) ([raw file](https://github.com/pmem/fio/blob/ae1853f1e61c0312ebc8c5553c43166db891a228/engines/librpma.c#L71)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> client_init
> ```
client_post_init if we want to register local memory before connection is established
</blockquote></details>

Which is not required for this workload.
Maybe when we will be in a mood to unify all implementations when they will be ready.
___
*[engines/librpma.c, line 132 at r2](https://reviewable.io/reviews/pmem/fio/10#-MJWXbGjAeVTewuw1-2l:-MJWXbGjAeVTewuw1-2m:b-ddknpt) ([raw file](https://github.com/pmem/fio/blob/ae1853f1e61c0312ebc8c5553c43166db891a228/engines/librpma.c#L132)):*
> ```C
> 	ret = rpma_conn_req_connect(&req, NULL, &cd->conn);
> 	if (ret) {
> 		rpma_td_verror(td, errno, "rpma_conn_req_connect()");
> ```

errno->ret

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 81 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJTntiU3RID266qNzuI:-MJWYk1r216Z6QK2xamY:b-896fix) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L81)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This line requires specifically `td_verror` since errno does not convey a valid RPMA error code. ;-)
</blockquote></details>

Done.
___
*[engines/librpma.c, line 94 at r1](https://reviewable.io/reviews/pmem/fio/10#-MJSHSEM8QFF0TDUv7P2:-MJWY7Bs8SGBYrMUshsx:b-t0r8a9) ([raw file](https://github.com/pmem/fio/blob/d1825cc4a8d67375b739e2ebb5386ca56f57e84b/engines/librpma.c#L94)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Nope. Please see the arguments I have proposed above.
</blockquote></details>

Ahh, yes, of course :-)
___
*[engines/librpma.c, line 71 at r2](https://reviewable.io/reviews/pmem/fio/10#-MJWTymw6v16Jzk8o3rW:-MJWY-dz1Wxloh2Wszqy:b-896fix) ([raw file](https://github.com/pmem/fio/blob/ae1853f1e61c0312ebc8c5553c43166db891a228/engines/librpma.c#L71)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Which is not required for this workload.
Maybe when we will be in a mood to unify all implementations when they will be ready.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 132 at r2](https://reviewable.io/reviews/pmem/fio/10#-MJWXbGjAeVTewuw1-2l:-MJWZ4bQBjArvUqXWEMh:b-896fix) ([raw file](https://github.com/pmem/fio/blob/ae1853f1e61c0312ebc8c5553c43166db891a228/engines/librpma.c#L132)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

errno->ret
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma.c, line 83 at r3](https://reviewable.io/reviews/pmem/fio/10#-MJWZxIk5UFA9DSzJE0J:-MJWZxIlAPPhE2LoDHCK:byr6t30) ([raw file](https://github.com/pmem/fio/blob/b07eba0c959b77e8b27b7c7b617c31934d0173ce/engines/librpma.c#L83)):*
> ```C
> 	cd = calloc(1, sizeof(struct client_data));
> 	if (cd == NULL) {
> 		td_verror(td, errno, "calloc()");
> ```

By convention, it seems all usage of this macro omit `()`.
Please fix all occurrences and for `rpma_td_verror` as well.
___
*[engines/librpma.c, line 117 at r3](https://reviewable.io/reviews/pmem/fio/10#-MJW_uYv9zB8riM15i10:-MJW_uYv9zB8riM15i11:b-pdxx02) ([raw file](https://github.com/pmem/fio/blob/b07eba0c959b77e8b27b7c7b617c31934d0173ce/engines/librpma.c#L117)):*
> ```C
> 	/* create a new peer object */
> 	ret = rpma_peer_new(dev, &cd->peer);
> 	if (ret) {
> ```

Please consider compacting these two lines e.g.:

```c
if ((ret = rpma_peer_new(dev, &cd->peer)) {
```

And all other RPMA calls as well.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma.c, line 150 at r4](https://reviewable.io/reviews/pmem/fio/10#-MJWaYUl4YDdqq8Ydqgb:-MJWaYUl4YDdqq8Ydqgc:bl7rvhu) ([raw file](https://github.com/pmem/fio/blob/a50a084523976d73eee852df981ff49eaba06ca2/engines/librpma.c#L150)):*
> ```C
> 	return 0;
> 
> err_conn_delete:
> ```

```c
(void) rpma_conn_disconnect(&cd->conn);
```

A missing step.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 141 at r4](https://reviewable.io/reviews/pmem/fio/10#-MJWb-cMDUjAez2Zm8Dx:-MJWb-cMDUjAez2Zm8Dy:b9ygyh) ([raw file](https://github.com/pmem/fio/blob/a50a084523976d73eee852df981ff49eaba06ca2/engines/librpma.c#L141)):*
> ```C
> 		goto err_conn_delete;
> 	} else if (event != RPMA_CONN_ESTABLISHED) {
> 		log_err("rpma_conn_next_event() returned an unexptected event: %s\n",
> ```

I know we do not have cstyle for this repository but we can do as we have. ;-)
I recommend putting this long string in a separate line.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 83 at r3](https://reviewable.io/reviews/pmem/fio/10#-MJWZxIk5UFA9DSzJE0J:-MJWdahp8qEgBSyETCLq:b-896fix) ([raw file](https://github.com/pmem/fio/blob/b07eba0c959b77e8b27b7c7b617c31934d0173ce/engines/librpma.c#L83)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

By convention, it seems all usage of this macro omit `()`.
Please fix all occurrences and for `rpma_td_verror` as well.
</blockquote></details>

Done.
___
*[engines/librpma.c, line 117 at r3](https://reviewable.io/reviews/pmem/fio/10#-MJW_uYv9zB8riM15i10:-MJWb4063-Fw6hE33GUv:bs5d74x) ([raw file](https://github.com/pmem/fio/blob/b07eba0c959b77e8b27b7c7b617c31934d0173ce/engines/librpma.c#L117)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please consider compacting these two lines e.g.:

```c
if ((ret = rpma_peer_new(dev, &cd->peer)) {
```

And all other RPMA calls as well.
</blockquote></details>

Why? I think it is not a good way. It always implies the question: isn't it a mistake? Should there be '='  or '==' ?
Frankly, I do not like. It is error prone.
___
*[engines/librpma.c, line 150 at r4](https://reviewable.io/reviews/pmem/fio/10#-MJWaYUl4YDdqq8Ydqgb:-MJWcMkmEwX-8NCEL-GX:b-896fix) ([raw file](https://github.com/pmem/fio/blob/a50a084523976d73eee852df981ff49eaba06ca2/engines/librpma.c#L150)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
(void) rpma_conn_disconnect(&cd->conn);
```

A missing step.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10#-:-MJWefdN6yc4xfQezQWH:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 117 at r3](https://reviewable.io/reviews/pmem/fio/10#-MJW_uYv9zB8riM15i10:-MJWeHEZ63tCjAT8WClG:b-chople) ([raw file](https://github.com/pmem/fio/blob/b07eba0c959b77e8b27b7c7b617c31934d0173ce/engines/librpma.c#L117)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why? I think it is not a good way. It always implies the question: isn't it a mistake? Should there be '='  or '==' ?
Frankly, I do not like. It is error prone.
</blockquote></details>

Sure. This is why compilers sometimes force you to add one more pair of `()`.
This is just something we have agreed to use for our examples.
Up to you.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma.c, line 117 at r3](https://reviewable.io/reviews/pmem/fio/10#-MJW_uYv9zB8riM15i10:-MJWffvM5OXfqa99EiF-:b-6c6nz8) ([raw file](https://github.com/pmem/fio/blob/b07eba0c959b77e8b27b7c7b617c31934d0173ce/engines/librpma.c#L117)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Sure. This is why compilers sometimes force you to add one more pair of `()`.
This is just something we have agreed to use for our examples.
Up to you.
</blockquote></details>

Moreover I think it makes the code less clear too, because the syntax is more complicated. I vote for the current convention.

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10#-:-MJWjLJG1rp4K81jzDC5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/10#-:-MJWnC5V6L8K66U098yK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
