### PR TITLE
rpma: increase SEND_QUEUE in write mode

### PR DESCRIPTION
**Pull request by osalyk**
We need space for the flush.

This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/46)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/46)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma.c, line 172 at r1](https://reviewable.io/reviews/pmem/fio/46#-MLDC7FdCZvKiQ7XA-9n:-MLDC7FdCZvKiQ7XA-9o:b-izv8tn) ([raw file](https://github.com/pmem/fio/blob/ceecbdf95418327594fba25c9a1d6b7bad9d0563/engines/librpma.c#L172)):*
> ```
> else sq_size = td->o.iodepth;
> ```

In two lines please:

```
else
      sq_size = td->o.iodepth;
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/46)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma.c, line 172 at r1](https://reviewable.io/reviews/pmem/fio/46#-MLDC7FdCZvKiQ7XA-9n:-MLDCxgz0Q9mrKABZYLw:b-896fix) ([raw file](https://github.com/pmem/fio/blob/ceecbdf95418327594fba25c9a1d6b7bad9d0563/engines/librpma.c#L172)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> else sq_size = td->o.iodepth;
> ```

In two lines please:

```
else
      sq_size = td->o.iodepth;
```
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/46)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/46#-:-MLDP1er8U1Iza6D5wYL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/46)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma.c, line 173 at r2](https://reviewable.io/reviews/pmem/fio/46#-MLEqVQM6l5rKigy--YT:-MLEqVQM6l5rKigy--YU:b-hgjt3g) ([raw file](https://github.com/pmem/fio/blob/a70b82d32ff82535010cccfeb0b52c15c839ff11/engines/librpma.c#L173)):*
> ```C
> 		sq_size = 2 * td->o.iodepth;
> 	else
> 		sq_size = td->o.iodepth;
> ```

```c
if (td_write(td)) {
    if (td->o.sync_io)
        sq_size = 2; /* WRITE + FLUSH */
    else
        sq_size = td->o.iodepth_batch + 1; /* N x WRITE + FLUSH */
} else {
    if (td->o.sync_io)
        sq_size = 1; /* READ */
    else
        sq_size = td->o.iodepth_batch + 1; /* N x READ */
}
```

Note:
- please add comments on why you are using such and such value
- we have to relate the value to async I/O `iodepth_batch` instead of `iodepth`

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/46)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/46)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/fio/46#-MLHOUtOA7rf4XxgVgcf:-MLHOUtOA7rf4XxgVgcg:b-2mwl66) (no related file):*
You have mentioned one of the cases does not work as intended.
Can you elaborate on this?

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/46)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/46#-MLHOUtOA7rf4XxgVgcf:-MLHk1gtBDFBLssMl-m_:b-kml531) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have mentioned one of the cases does not work as intended.
Can you elaborate on this?
</blockquote></details>

In asynchronous read I have to use io_depth instead of io_depth_batch.
This solves the problem.

---

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/46)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/46#-:-MLIOLcZ6WqaMnJ9bPk4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/46)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/46#-:-MLIPEsTDtYwe11svhTe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/46)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
