### PR TITLE
aof: client_cleanup() (the first approximation)

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/218)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/218)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma_aof.c, line 119 at r1](https://reviewable.io/reviews/pmem/fio/218#-MU9G0YDDr0U4-JyGIPB:-MU9G0YDDr0U4-JyGIPC:bagkmb0) ([raw file](https://github.com/pmem/fio/blob/c9333fbe6ffe8d3ded19d04fb5d8a3ede4716bdc/engines/librpma_aof.c#L119)):*
> ```C
> 	 */
> 	(void) librpma_fio_client_io_complete_all_sends(td);
> ```

Please add here something like:

```c
/* XXX here the last message should be sent */
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/218)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_aof.c, line 119 at r1](https://reviewable.io/reviews/pmem/fio/218#-MU9G0YDDr0U4-JyGIPB:-MU9JateBQRW37jwHuGZ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c9333fbe6ffe8d3ded19d04fb5d8a3ede4716bdc/engines/librpma_aof.c#L119)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add here something like:

```c
/* XXX here the last message should be sent */
```
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/218#-:-MU9kmEtCofGvOlzkBLO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/218#-:-MUCfX5dCm4vIJiKruYT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/218)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
