### PR TITLE
aof: move content of client_sw_post_init() to client_sw_init()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/244)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/244)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_aof.c, line 105 at r1](https://reviewable.io/reviews/pmem/fio/244#-MUnAfYI4GWm9XbFvTIM:-MUnAfYI4GWm9XbFvTIN:b-fpxscm) ([raw file](https://github.com/pmem/fio/blob/cd8edcf397ac419187d75bf733bfdb6559cdf5c1/engines/librpma_aof.c#L105)):*
> ```C
> 			return ret;
> 
> 		td->io_ops->post_init = librpma_fio_client_post_init;
> ```

It is now common for both `mode` values, so you can just write it directly to the structure below (`struct ioengine_ops ioengine_client`). No indirection needed.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/244)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_aof.c, line 105 at r1](https://reviewable.io/reviews/pmem/fio/244#-MUnAfYI4GWm9XbFvTIM:-MUnCa2LAVMoXuoS5_A-:biw8y1v) ([raw file](https://github.com/pmem/fio/blob/cd8edcf397ac419187d75bf733bfdb6559cdf5c1/engines/librpma_aof.c#L105)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is now common for both `mode` values, so you can just write it directly to the structure below (`struct ioengine_ops ioengine_client`). No indirection needed.
</blockquote></details>

Right. Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/244)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_aof.c, line 105 at r1](https://reviewable.io/reviews/pmem/fio/244#-MUnAfYI4GWm9XbFvTIM:-MUnEAReAWbdkxucP2zG:b-896fix) ([raw file](https://github.com/pmem/fio/blob/cd8edcf397ac419187d75bf733bfdb6559cdf5c1/engines/librpma_aof.c#L105)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Right. Done.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/244#-:-MUnELUG3kc3QveUe1wq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/244#-:-MUnVeB_Di6gdyra05UF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
