### PR TITLE
rpma: do sync_io

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/34)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/34#-:-MK_7ziI-RtMfQPp7HV6:bdycpsm)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma.c, line 395 at r1](https://reviewable.io/reviews/pmem/fio/34#-MK_6Wd4Au_ygPjng7wX:-MK_6Wd5-ji2EMvEGtQy:b-48xp5a) ([raw file](https://github.com/pmem/fio/blob/878493de51ffb7fff406f2ad9099f4885c89f7f3/engines/librpma.c#L395)):*
> ```C
> 		goto err;
> 	}
> ```

too many EOL

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/34)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma.c, line 395 at r1](https://reviewable.io/reviews/pmem/fio/34#-MK_6Wd4Au_ygPjng7wX:-MK_99o5CS79d3bdet0P:b-896fix) ([raw file](https://github.com/pmem/fio/blob/878493de51ffb7fff406f2ad9099f4885c89f7f3/engines/librpma.c#L395)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

too many EOL
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/34)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/34#-:-MK_X5a22MwTUwjPKM0B:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/34)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/34#-:-MKaiEmgCsy-rUblAziI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/34)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
