### PR TITLE
rpma: common: separate rpma_td_error() and CEIL()

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #114
- [x] #113
- [x] #112
- [x] #111

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/115)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/115)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/115)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/115#-:-MR-hLyB16n5WzAmtt-n:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/115#-:-MR-rpWmEvbbjiT7fAsY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
