### PR TITLE
rpma: gpspm: fix return value of server_open_file

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/162)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/162)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 551 at r1](https://reviewable.io/reviews/pmem/fio/162#-MRUv2af2QAQE1khvgwH:-MRUv2ag8-CORhAed_hO:buqbtp1) ([raw file](https://github.com/pmem/fio/blob/2245ee7232b9565be466fe3e57e5925258874dea/engines/librpma_gpspm.c#L551)):*
> ```
> return (ret <= 0 ? ret : -1);
> ```
return ret;

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/162)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 551 at r1](https://reviewable.io/reviews/pmem/fio/162#-MRUvLq89xdbdPLl1oFM:-MRUvLq89xdbdPLl1oFN:b-dwxpe3) ([raw file](https://github.com/pmem/fio/blob/2245ee7232b9565be466fe3e57e5925258874dea/engines/librpma_gpspm.c#L551)):*
> ```C
> 	(void) rpma_conn_cfg_delete(&cfg);
> 
> 	return (ret <= 0 ? ret : -1);
> ```

Are we at risk of having here a positive error value?

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/162)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/162)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_gpspm.c, line 551 at r1](https://reviewable.io/reviews/pmem/fio/162#-MRUvLq89xdbdPLl1oFM:-MRUva0Q4ISZImXHjVlH:b32v57) ([raw file](https://github.com/pmem/fio/blob/2245ee7232b9565be466fe3e57e5925258874dea/engines/librpma_gpspm.c#L551)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Are we at risk of having here a positive error value?
</blockquote></details>

+1

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/162)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 551 at r1](https://reviewable.io/reviews/pmem/fio/162#-MRUv2af2QAQE1khvgwH:-MRUwkKaEgC1tZHMudZ0:b-896fix) ([raw file](https://github.com/pmem/fio/blob/2245ee7232b9565be466fe3e57e5925258874dea/engines/librpma_gpspm.c#L551)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> return (ret <= 0 ? ret : -1);
> ```
return ret;
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 551 at r1](https://reviewable.io/reviews/pmem/fio/162#-MRUvLq89xdbdPLl1oFM:-MRUwkhS1efv32vbl-3z:bmdrc2x) ([raw file](https://github.com/pmem/fio/blob/2245ee7232b9565be466fe3e57e5925258874dea/engines/librpma_gpspm.c#L551)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

I hope no

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/162)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/162#-:-MRUyhLf564D4TuxkJRY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/162#-:-MRUyxC69UIqGAIgmNic:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 551 at r1](https://reviewable.io/reviews/pmem/fio/162#-MRUvLq89xdbdPLl1oFM:-MRUyq2X-y4jRsvGNYAb:b-9zoc6y) ([raw file](https://github.com/pmem/fio/blob/2245ee7232b9565be466fe3e57e5925258874dea/engines/librpma_gpspm.c#L551)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I hope no
</blockquote></details>

:pray:  with :prayer_beads:

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/162)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
