### PR TITLE
rpma: implement server_open_file and server_close_file

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #50 
- [x] #53
- [x] #55
- [x] #56

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/57)

### CODE REVIEW

**Comment by ldorau** [comment]
Rebased

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 428 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLmuI2y6cUhB489e7G9:-MLmuI2y6cUhB489e7GA:bs5tizy) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L428)):*
> ```C
> 	int ret;
> 
> 	if (!td->o.mmapfile) {
> ```

`f->file_name`
___
*[engines/librpma_gpspm.c, line 454 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLmuQie5-DRQdXJbdt5:-MLmuQie5-DRQdXJbdt6:b2sssa0) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L454)):*
> ```C
> 			RPMA_MR_USAGE_WRITE_DST | RPMA_MR_USAGE_WRITE_SRC |
> 			(mmap_is_pmem ? RPMA_MR_USAGE_FLUSH_TYPE_PERSISTENT :
> 				RPMA_MR_USAGE_FLUSH_TYPE_VISIBILITY),
> ```

Both flush usages are not needed.
___
*[engines/librpma_gpspm.c, line 497 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLmv5wM65rZ2Vm_VI0i:-MLmv5wM65rZ2Vm_VI0j:b6efus7) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L497)):*
> ```C
> 	sd->mmap_ptr = mmap_ptr;
> 	sd->mmap_size = mmap_size;
> 	sd->mmap_is_pmem = mmap_is_pmem;
> ```

I'm not sure we need all of these intermediate variables.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 503 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLmxSGH0bE04DTPcSo6:-MLmxSGH0bE04DTPcSo7:b-ljpnfz) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L503)):*
> ```C
> 
> err_conn_delete:
> 	sd->conn_req = NULL; /* do not call rpma_conn_req_delete() */
> ```

`conn_req` is NULLed by `rpma_conn_req_connect()`.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57)* status: all files reviewed, 8 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 521 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLn7nG_61PweOt6CD0H:-MLn7nG_61PweOt6CD0I:b6yd722) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L521)):*
> ```
> int ret;
> ```
int ret, ret1, ret2;
___
*[engines/librpma_gpspm.c, line 526 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLn7tYyDEmybq_U0O7L:-MLn7tYyDEmybq_U0O7M:b-7m9vhw) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L526)):*
> ```
> if (pmem_unmap(sd->mmap_ptr, sd->mmap_size))
> ```
 if (ret1 = pmem_unmap(sd->mmap_ptr, sd->mmap_size))
___
*[engines/librpma_gpspm.c, line 529 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLn6n5wDEZ1Wz0flTO9:-MLn6n5wDEZ1Wz0flTOA:banxj4f) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L529)):*
> ```
> 	if (sd->conn_req)
> 		(void) rpma_conn_req_delete(&sd->conn_req);
> ```
	if (sd->conn)
		if ((ret2 = rpma_conn_delete(&sd->conn)))
                        rpma_td_verror(td, ret2, "pmem_unmap");
___
*[engines/librpma_gpspm.c, line 532 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLn7YNj0DTBfV_8ADzx:-MLn7YNj0DTBfV_8ADzy:bar4rq3) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L532)):*
> ```
> return 0;
> ```
return ret | ret1 | ret2;

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57)* status: all files reviewed, 8 unresolved discussions (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57)* status: all files reviewed, 9 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 263 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLnJM824eEw_sP7v8Zr:-MLnJM824eEw_sP7v8Zs:beiw99b) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L263)):*
> ```
> struct rpma_ep *ep
> ```
do we need ep all the time or only in file_open()?
ep is no longer needed as soon as the connection is established

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 263 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLnJM824eEw_sP7v8Zr:-MLtLWjp04Ptz-mxb5-h:b-92gp5v) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L263)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> struct rpma_ep *ep
> ```
do we need ep all the time or only in file_open()?
ep is no longer needed as soon as the connection is established
</blockquote></details>

You are right. I think we can create it only for `file_open()` and destroy just after establishing a connection.
I am voting for keeping as little as possible globally.
___
*[engines/librpma_gpspm.c, line 532 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLn7YNj0DTBfV_8ADzx:-MLtMD674ww9GU3ShEAc:b5qee0v) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L532)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> return 0;
> ```
return ret | ret1 | ret2;
</blockquote></details>

I like the idea of returning an error code if the error happens. But it should be done differently in this function:

```c
int ret;

if ((ret = rpma_mr_dereg()))
    rpma_td_error();

if (pmem_map_unmap()) {
    if (!ret)    
        ret = errno;
    td_error();
}

/* no conn req here, please see other comments in this or another PR, I'm not sure */

return ret;
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_gpspm.c, line 532 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLn7YNj0DTBfV_8ADzx:-MLv_0cZBH_SFe33T1sm:b-hrh3tt) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L532)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I like the idea of returning an error code if the error happens. But it should be done differently in this function:

```c
int ret;

if ((ret = rpma_mr_dereg()))
    rpma_td_error();

if (pmem_map_unmap()) {
    if (!ret)    
        ret = errno;
    td_error();
}

/* no conn req here, please see other comments in this or another PR, I'm not sure */

return ret;
```
</blockquote></details>

OK - we should add  rpma_conn_req_delete() result also here

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 263 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLnJM824eEw_sP7v8Zr:-MLvbCmu9UbMGsVBVT1e:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L263)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are right. I think we can create it only for `file_open()` and destroy just after establishing a connection.
I am voting for keeping as little as possible globally.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 428 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLmuI2y6cUhB489e7G9:-MLvcnq3AMN8TJ29i92F:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L428)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`f->file_name`
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 454 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLmuQie5-DRQdXJbdt5:-MLvd1wi3IxrFF-uZQH0:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L454)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Both flush usages are not needed.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 497 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLmv5wM65rZ2Vm_VI0i:-MLvdOr6529uK5tPkwWs:b-tn8ei5) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L497)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm not sure we need all of these intermediate variables.
</blockquote></details>

`mmap_is_pmem` is not needed
___
*[engines/librpma_gpspm.c, line 503 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLmxSGH0bE04DTPcSo6:-MLvdb0pDA1_b8splyTF:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L503)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`conn_req` is NULLed by `rpma_conn_req_connect()`.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 521 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLn7nG_61PweOt6CD0H:-MLvfBo-BfdsQ0XRhhVW:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L521)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> int ret;
> ```
int ret, ret1, ret2;
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 526 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLn7tYyDEmybq_U0O7L:-MLvfCBbCu_Be0cr4-q8:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L526)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> if (pmem_unmap(sd->mmap_ptr, sd->mmap_size))
> ```
 if (ret1 = pmem_unmap(sd->mmap_ptr, sd->mmap_size))
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 529 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLn6n5wDEZ1Wz0flTO9:-MLvfCYU0Vud41jtlGMK:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L529)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 	if (sd->conn_req)
> 		(void) rpma_conn_req_delete(&sd->conn_req);
> ```
	if (sd->conn)
		if ((ret2 = rpma_conn_delete(&sd->conn)))
                        rpma_td_verror(td, ret2, "pmem_unmap");

</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 532 at r2](https://reviewable.io/reviews/pmem/fio/57#-MLn7YNj0DTBfV_8ADzx:-MLvfD3-Cr9ys5Vqabfr:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8dbabfe1b4ba6e608bcc2aebed317b53ac44893a/engines/librpma_gpspm.c#L532)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

OK - we should add  rpma_conn_req_delete() result also here
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57#-:-MLvjWO-47da6-i5jNK2:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
Rebased

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57#-:-MLvk8oW2_lPtFwsjT4p:b9x2p3v)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[engines/librpma_gpspm.c, line 667 at r4](https://reviewable.io/reviews/pmem/fio/57#-MLvkxor9MSpvDCFaM7B:-MLvkxor9MSpvDCFaM7C:bx4b1xt) ([raw file](https://github.com/pmem/fio/blob/f110076b59d8d232c51f8a84aaebf56a46e697fe/engines/librpma_gpspm.c#L667)):*
> ```C
> 			ret = errno;
> 	}
> ```

shall we also remove sd->conn here?

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_gpspm.c, line 667 at r4](https://reviewable.io/reviews/pmem/fio/57#-MLvkxor9MSpvDCFaM7B:-MLvp_a0BcnjOo2neTZh:b-896fix) ([raw file](https://github.com/pmem/fio/blob/f110076b59d8d232c51f8a84aaebf56a46e697fe/engines/librpma_gpspm.c#L667)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

shall we also remove sd->conn here?
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57#-:-MLvtL5PEx286bJijTk9:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 665 at r5](https://reviewable.io/reviews/pmem/fio/57#-MLvsrxx9x9D6Vrd20Th:-MLvsrxx9x9D6Vrd20Ti:bh00so) ([raw file](https://github.com/pmem/fio/blob/e1f67bfb1597928f9e7bc894f5476dc4f5334f41/engines/librpma_gpspm.c#L665)):*
> ```C
> 		rpma_td_verror(td, ret2, "rpma_mr_dereg");
> 
> 	ret = ret1 | ret2;
> ```

I don't think or'ing the RPMA error codes is a good idea. I think you should go with something like:
```c
ret = ret1 ? ret1 : ret2;
```

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 665 at r5](https://reviewable.io/reviews/pmem/fio/57#-MLvsrxx9x9D6Vrd20Th:-MLvuQHc-Rj0s4A9heN3:bk3z4di) ([raw file](https://github.com/pmem/fio/blob/e1f67bfb1597928f9e7bc894f5476dc4f5334f41/engines/librpma_gpspm.c#L665)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I don't think or'ing the RPMA error codes is a good idea. I think you should go with something like:
```c
ret = ret1 ? ret1 : ret2;
```
</blockquote></details>

ret =  ret1 || ret2 ? -1 : 0;

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 665 at r5](https://reviewable.io/reviews/pmem/fio/57#-MLvsrxx9x9D6Vrd20Th:-MLvvXbc6gR2ccoY0g4a:b-896fix) ([raw file](https://github.com/pmem/fio/blob/e1f67bfb1597928f9e7bc894f5476dc4f5334f41/engines/librpma_gpspm.c#L665)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

ret =  ret1 || ret2 ? -1 : 0;
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
