### PR TITLE
aof: client: send the last update message

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/227)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/227)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma_aof.c, line 29 at r1](https://reviewable.io/reviews/pmem/fio/227#-MUI7S6i2yX9f6fkEPlT:-MUI7S6i2yX9f6fkEPlU:b-2m97z7) ([raw file](https://github.com/pmem/fio/blob/1250c9a374f32b1b350872058ffba5c9c72fa4e2/engines/librpma_aof.c#L29)):*
> ```C
> 
> #define AOF_UPDATE_REQUEST__LAST \
> 	{ PROTOBUF_C_MESSAGE_INIT(&aof_update_request__descriptor), 0, 0, 0 }
> ```

Do you even use it? ;-)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/227)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_aof.c, line 29 at r1](https://reviewable.io/reviews/pmem/fio/227#-MUI7S6i2yX9f6fkEPlT:-MUI9i0Z-cigkmjo6TOS:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1250c9a374f32b1b350872058ffba5c9c72fa4e2/engines/librpma_aof.c#L29)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do you even use it? ;-)
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/227)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[engines/librpma_aof.c, line 29 at r1](https://reviewable.io/reviews/pmem/fio/227#-MUI7S6i2yX9f6fkEPlT:-MUIBwCu0uwcJUz-s73B:bgu0425) ([raw file](https://github.com/pmem/fio/blob/1250c9a374f32b1b350872058ffba5c9c72fa4e2/engines/librpma_aof.c#L29)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

By pointing out you do not use it I wanted to drive your attention to the fact you do not need it. ;-)
Please remove it.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/227)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_aof.c, line 29 at r1](https://reviewable.io/reviews/pmem/fio/227#-MUI7S6i2yX9f6fkEPlT:-MUIDCWL1JoeI5sGLj1X:b-896fix) ([raw file](https://github.com/pmem/fio/blob/1250c9a374f32b1b350872058ffba5c9c72fa4e2/engines/librpma_aof.c#L29)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

By pointing out you do not use it I wanted to drive your attention to the fact you do not need it. ;-)
Please remove it.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/227#-:-MUIJD7F69fk7H9OOSGZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/227#-:-MUIqT_f1JnQbkBe_BXA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/227)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
