### PR TITLE
rpma: implement server_post_init

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #50 
- [x] #53

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/55)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 353 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmLH_EAEEYjZ9CiY5z:-MLmLH_EAEEYjZ9CiY6-:bk5srt9) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L353)):*
> ```
> msg_m
> ```
where is it initialized?
___
*[engines/librpma_gpspm.c, line 355 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmKNxQ8uLhHOc2feWP:-MLmKNxQ8uLhHOc2feWQ:b-y3ckca) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L355)):*
> ```
> err_req_delete
> ```
are we sure that rpma_conn_req_delete() deregister memory added via rpma_conn_req_recv()?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[engines/librpma_gpspm.c, line 353 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmLH_EAEEYjZ9CiY5z:-MLmVPHC3tBLVN9shr1G:bsd60b9) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L353)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> msg_m
> ```
where is it initialized?

</blockquote></details>

Do you mean ` sd->msg_mr` ? If yes - in the line no. 341 above.
___
*[engines/librpma_gpspm.c, line 355 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmKNxQ8uLhHOc2feWP:-MLmWP9Z6dCtHN7VhRtG:b-ltmj3s) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L355)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> err_req_delete
> ```
are we sure that rpma_conn_req_delete() deregister memory added via rpma_conn_req_recv()?
</blockquote></details>

`rpma_conn_req_delete()` does not deregisters memory, `rpma_mr_dereg()` does deregisters memory.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 319 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmWK3E5YSRlEXktN6v:-MLmWK3E5YSRlEXktN6w:bytea1d) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L319)):*
> ```C
> static int server_post_init(struct thread_data *td)
> {
> 	struct server_data *sd =  td->io_ops_data;
> ```

Too many spaces.
___
*[engines/librpma_gpspm.c, line 339 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmWoWyACrPeQN9cplr:-MLmWoWyACrPeQN9cpls:b-z5wykx) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L339)):*
> ```C
> 
> 	ret = rpma_mr_reg(sd->peer, sd->orig_buffer_aligned, io_us_size,
> 			RPMA_MR_USAGE_SEND | RPMA_MR_USAGE_RECV |
> ```

Thinking out loud: maybe we should have a separate set of buffers for recvs and sends so we do not need to maintain the balance between them.
___
*[engines/librpma_gpspm.c, line 340 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmWhbY1s04Drz_RKRr:-MLmWhbY1s04Drz_RKRs:b-lnag7t) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L340)):*
> ```C
> 	ret = rpma_mr_reg(sd->peer, sd->orig_buffer_aligned, io_us_size,
> 			RPMA_MR_USAGE_SEND | RPMA_MR_USAGE_RECV |
> 			RPMA_MR_USAGE_FLUSH_TYPE_VISIBILITY,
> ```

The flush usage is not needed here.
___
*[engines/librpma_gpspm.c, line 354 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmXJMXBnWnHHTaf0bd:-MLmXJMXBnWnHHTaf0be:b2huya2) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L354)):*
> ```C
> 	for (i = 0; i < td->o.iodepth; i++)
> 		if ((ret = rpma_conn_req_recv(sd->conn_req, sd->msg_mr,
> 				i * td_max_bs(td), td_max_bs(td), NULL)))
> ```

Please cache `td_max_bs(td)` somewhere and give it a meaningful name e.g. msg_size.
___
*[engines/librpma_gpspm.c, line 355 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmKNxQ8uLhHOc2feWP:-MLmY2Vc5H6FeleGEG8Z:b-8ongab) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L355)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`rpma_conn_req_delete()` does not deregisters memory, `rpma_mr_dereg()` does deregisters memory.
</blockquote></details>

As @ldorau said. Additionally, if @grom72 means emptying the RQ. There is no way to and no point in doing it.
___
*[engines/librpma_gpspm.c, line 360 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmXvRN-K0kZM00zWDu:-MLmXvROAXA_jlEjJpKS:be7xopx) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L360)):*
> ```C
> 
> err_req_delete:
> 	if (sd->conn_req)
> ```

This if seems unnecessary.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma_gpspm.c, line 319 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmWK3E5YSRlEXktN6v:-MLmayVZ4N1SSQGi21OG:b-896fix) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L319)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Too many spaces.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 340 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmWhbY1s04Drz_RKRr:-MLmb42Z-Bf1T-J-xgwd:b-896fix) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L340)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The flush usage is not needed here.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 354 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmXJMXBnWnHHTaf0bd:-MLmbu9n2_-AVdFl-ZA5:b-896fix) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L354)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please cache `td_max_bs(td)` somewhere and give it a meaningful name e.g. msg_size.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 355 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmKNxQ8uLhHOc2feWP:-MLmbNwS8zI6suaodEVZ:b-896fix) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L355)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

As @ldorau said. Additionally, if @grom72 means emptying the RQ. There is no way to and no point in doing it.
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 360 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmXvRN-K0kZM00zWDu:-MLmbOo55o532GYBQEqd:b-896fix) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L360)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This if seems unnecessary.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma_gpspm.c, line 299 at r1](https://reviewable.io/reviews/pmem/fio/55#-MLmarOq6_e60S3PU9mA:-MLmarOr2_harOjxwy8u:b-wny99t) ([raw file](https://github.com/pmem/fio/blob/34ad20511524b8cc4fae3723efb9ba66b92f1646/engines/librpma_gpspm.c#L299)):*
> ```
> td_max_bs
> ```
how do we calculate bs size?
@janekmi :
"FIO allows setting a range for block size. During benchmarking the FIO will pick the block size for each particular io_u.
When you want to be prepared for handling any possible block size td_max_bs() allows getting the maximum possible value."

But is it so that in the case of a gpspm server bs size is a size of memory reserved for each send/receive operation?
___
*[engines/librpma_gpspm.c, line 302 at r1](https://reviewable.io/reviews/pmem/fio/55#-MLm_ZOG4xzuC22kFRDq:-MLm_ZOH1hpxTmpNO7Gr:bgnwfp9) ([raw file](https://github.com/pmem/fio/blob/34ad20511524b8cc4fae3723efb9ba66b92f1646/engines/librpma_gpspm.c#L302)):*
> ```
> rpma_mr_reg
> ```
do we have to wait with this call until post_init or can we reg memory for send/recv in init()?
___
*[engines/librpma_gpspm.c, line 339 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmWoWyACrPeQN9cplr:-MLm_79E9siCnJ_hqjxl:bbo6505) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L339)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Thinking out loud: maybe we should have a separate set of buffers for recvs and sends so we do not need to maintain the balance between them.
</blockquote></details>

+ how shall we understand iodepth ? num of recv + num of send or iodepth = num of recv/send?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[engines/librpma_gpspm.c, line 339 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmWoWyACrPeQN9cplr:-MLmde3Q1bvYqp-s-wrP:b-e4kmit) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L339)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+ how shall we understand iodepth ? num of recv + num of send or iodepth = num of recv/send?
</blockquote></details>

Hmm, I need to think more about the consequences of this ...

**Review by ldorau — COMMENTED** [review]
Rebased

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55#-:-MLmed1j1JL1DKQsuE-c:b9x2p3v)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_gpspm.c, line 339 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmWoWyACrPeQN9cplr:-MLmfLbS667uj3kQRBDh:bsxb3fo) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L339)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Hmm, I need to think more about the consequences of this ...
</blockquote></details>

If we assume that bs_min = send_size and bs_max is rec_size iodepth shows in a natural way 1/2 of max flush to be buffered

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 302 at r1](https://reviewable.io/reviews/pmem/fio/55#-MLm_ZOG4xzuC22kFRDq:-MLmotsz6jsGbRyClvqj:bu2pyu5) ([raw file](https://github.com/pmem/fio/blob/34ad20511524b8cc4fae3723efb9ba66b92f1646/engines/librpma_gpspm.c#L302)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_mr_reg
> ```
do we have to wait with this call until post_init or can we reg memory for send/recv in init()?
</blockquote></details>

We have to wait. This memory is allocated between init() and post_init() hooks.
___
*[engines/librpma_gpspm.c, line 339 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmWoWyACrPeQN9cplr:-MLmp9nCAXDF00lMJNE1:bv4mtd9) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L339)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

If we assume that bs_min = send_size and bs_max is rec_size iodepth shows in a natural way 1/2 of max flush to be buffered
</blockquote></details>

I do not like such type of "encoding". If we really need new options to set both messages size so let's add new options for this.

My thinking is as follows:
- each io_u is a pair: recv + send
- so block size should accommodate the sum of these messages sizes
- because this size is really implementation-dependant we **probably** should overwrite the block size during `init()`
- in `post_init()` we should split a single io_u into space required for recv and send
- **Note**: `struct io_u` has a field called `engine_data` which may help with this.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 357 at r4](https://reviewable.io/reviews/pmem/fio/55#-MLmxqG74OiaN01x9XMl:-MLmxqG74OiaN01x9XMm:buycbqq) ([raw file](https://github.com/pmem/fio/blob/8b165aad8d1882e5d79d7d19b533e8f724a741d4/engines/librpma_gpspm.c#L357)):*
> ```C
> 		if ((ret = rpma_conn_req_recv(sd->conn_req, sd->msg_mr,
> 				i * msg_size, msg_size, NULL)))
> 			goto err_req_delete;
> ```

Considering all the consequences of getting a connection request here but connecting it in the `open_file()`, I recommend doing all of these (rpma_ep_next_conn_req and rpma_conn_req_recvs) in `open_file()`. Such an approach allows not caching `conn_req` in the server's data so we do not need to bother about it in more than one hook.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_gpspm.c, line 339 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmWoWyACrPeQN9cplr:-MLn1O616nyhz8hNFcft:b-mdgq7r) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L339)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not like such type of "encoding". If we really need new options to set both messages size so let's add new options for this.

My thinking is as follows:
- each io_u is a pair: recv + send
- so block size should accommodate the sum of these messages sizes
- because this size is really implementation-dependant we **probably** should overwrite the block size during `init()`
- in `post_init()` we should split a single io_u into space required for recv and send
- **Note**: `struct io_u` has a field called `engine_data` which may help with this.
</blockquote></details>

I do not see anything wrong with block size calculating in init() - it is natural consequences that io_u size depends on e.g. protobuffer
For this sprint, we could use something fixed e.g. 1kB for each io_u, and add support for variable-length io_u later.

Fur this case I would like to see the .fio file added to this PR with the expected value defined there.
___
*[engines/librpma_gpspm.c, line 357 at r4](https://reviewable.io/reviews/pmem/fio/55#-MLmxqG74OiaN01x9XMl:-MLn1GY-446tX1TLuXWj:b3kqu) ([raw file](https://github.com/pmem/fio/blob/8b165aad8d1882e5d79d7d19b533e8f724a741d4/engines/librpma_gpspm.c#L357)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Considering all the consequences of getting a connection request here but connecting it in the `open_file()`, I recommend doing all of these (rpma_ep_next_conn_req and rpma_conn_req_recvs) in `open_file()`. Such an approach allows not caching `conn_req` in the server's data so we do not need to bother about it in more than one hook.
</blockquote></details>

+
___
*[engines/librpma_gpspm.c, line 365 at r4](https://reviewable.io/reviews/pmem/fio/55#-MLmhdLj9_t43GwdWGhe:-MLmhdLj9_t43GwdWGhf:b-wmpn2t) ([raw file](https://github.com/pmem/fio/blob/8b165aad8d1882e5d79d7d19b533e8f724a741d4/engines/librpma_gpspm.c#L365)):*
> ```
> rpma_mr_dereg
> ```
not needed -> will be handled by server_cleanup()

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_gpspm.c, line 339 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmWoWyACrPeQN9cplr:-MLn2nSj769Hfur853IX:b3547b0) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L339)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I do not see anything wrong with block size calculating in init() - it is natural consequences that io_u size depends on e.g. protobuffer
For this sprint, we could use something fixed e.g. 1kB for each io_u, and add support for variable-length io_u later.

Fur this case I would like to see the .fio file added to this PR with the expected value defined there.
</blockquote></details>

One more idea - shall we anyhow consider a separate alignment of every send/receive buffer?
In this case, 1kB should be ok.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 299 at r1](https://reviewable.io/reviews/pmem/fio/55#-MLmarOq6_e60S3PU9mA:-MLtIT11-Si6MH4zDh-V:bcrajn) ([raw file](https://github.com/pmem/fio/blob/34ad20511524b8cc4fae3723efb9ba66b92f1646/engines/librpma_gpspm.c#L299)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> td_max_bs
> ```
how do we calculate bs size?
@janekmi :
"FIO allows setting a range for block size. During benchmarking the FIO will pick the block size for each particular io_u.
When you want to be prepared for handling any possible block size td_max_bs() allows getting the maximum possible value."

But is it so that in the case of a gpspm server bs size is a size of memory reserved for each send/receive operation?
</blockquote></details>

This is the direction we are heading now.
- io_u == (send buff, recv buff) AND
- block_size == size of io_u
ergo
- block_size == (send buff, recv_buff)
___
*[engines/librpma_gpspm.c, line 339 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmWoWyACrPeQN9cplr:-MLtJJ3T3QToIFbVHRn2:b5exi8e) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L339)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

One more idea - shall we anyhow consider a separate alignment of every send/receive buffer?
In this case, 1kB should be ok.
</blockquote></details>

AD1. I think it is a good idea to add to this PR a `blocksize = 1KiB` option to the example librpma_gpspm-server.fio with annotation what it effectively means and suggest a possibility to calculate it at runtime according to what protobuff will suggest.
AD2. Aligning the buffers may give some performance benefits. But we do not know how big may the effect be assuming it even exists. So @ldorau if you will you can put somewhere an XXX comment suggesting it may have a performance effect.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma_gpspm.c, line 365 at r4](https://reviewable.io/reviews/pmem/fio/55#-MLmhdLj9_t43GwdWGhe:-MLtKsDEDBeo_8fTtEtU:b-6vdzoe) ([raw file](https://github.com/pmem/fio/blob/8b165aad8d1882e5d79d7d19b533e8f724a741d4/engines/librpma_gpspm.c#L365)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_mr_dereg
> ```
not needed -> will be handled by server_cleanup()
</blockquote></details>

You are right. The `cleanup()` hook is called on error. But I think it is up to @ldorau to either cleanup here and have a very easy path in the `cleanup()` hook. Or to have a quick exit here and more versatile implementation on `cleanup()`.

It is just a nice thing to consider.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 339 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmWoWyACrPeQN9cplr:-MLvSeZO5EnHfilzh63Z:b97rtkq) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L339)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

AD1. I think it is a good idea to add to this PR a `blocksize = 1KiB` option to the example librpma_gpspm-server.fio with annotation what it effectively means and suggest a possibility to calculate it at runtime according to what protobuff will suggest.
AD2. Aligning the buffers may give some performance benefits. But we do not know how big may the effect be assuming it even exists. So @ldorau if you will you can put somewhere an XXX comment suggesting it may have a performance effect.
</blockquote></details>

Ad 1. Done
Ad 2. Aligning had already been done:

```
	/*
	 * td->orig_buffer is not aligned. The engine requires aligned io_us
	 * so FIO alignes up the address using the formula below.
	 */
	sd->orig_buffer_aligned = PTR_ALIGN(td->orig_buffer, page_mask) +
			td->o.mem_align;
```

Should anything be changed/added here?
___
*[engines/librpma_gpspm.c, line 357 at r4](https://reviewable.io/reviews/pmem/fio/55#-MLmxqG74OiaN01x9XMl:-MLvTqwr5xylmHvTN6k2:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8b165aad8d1882e5d79d7d19b533e8f724a741d4/engines/librpma_gpspm.c#L357)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+
</blockquote></details>

Done.
___
*[engines/librpma_gpspm.c, line 365 at r4](https://reviewable.io/reviews/pmem/fio/55#-MLmhdLj9_t43GwdWGhe:-MLvTts-4dsOtSdeUnxw:b-896fix) ([raw file](https://github.com/pmem/fio/blob/8b165aad8d1882e5d79d7d19b533e8f724a741d4/engines/librpma_gpspm.c#L365)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are right. The `cleanup()` hook is called on error. But I think it is up to @ldorau to either cleanup here and have a very easy path in the `cleanup()` hook. Or to have a quick exit here and more versatile implementation on `cleanup()`.

It is just a nice thing to consider.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 357 at r4](https://reviewable.io/reviews/pmem/fio/55#-MLmxqG74OiaN01x9XMl:-MLvacHR3vUgSP9MRVuq:b-i0ofhx) ([raw file](https://github.com/pmem/fio/blob/8b165aad8d1882e5d79d7d19b533e8f724a741d4/engines/librpma_gpspm.c#L357)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

where do we handle rpma_ep_next_conn_req()?

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55#-:-MLvbtJO8aviqkyA4eZG:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_gpspm.c, line 357 at r4](https://reviewable.io/reviews/pmem/fio/55#-MLmxqG74OiaN01x9XMl:-MLvbsZp1y6ZsalA0wiw:b1u9gb8) ([raw file](https://github.com/pmem/fio/blob/8b165aad8d1882e5d79d7d19b533e8f724a741d4/engines/librpma_gpspm.c#L357)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

where do we handle rpma_ep_next_conn_req()?
</blockquote></details>

Please read the first comment in this thread by @janekmi

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55#-:-MLvfwJrDOPpWFPB2kqJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 339 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmWoWyACrPeQN9cplr:-MLvfDKt7XbU_J-Chgtl:b-662d3) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L339)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ad 1. Done
Ad 2. Aligning had already been done:

```
	/*
	 * td->orig_buffer is not aligned. The engine requires aligned io_us
	 * so FIO alignes up the address using the formula below.
	 */
	sd->orig_buffer_aligned = PTR_ALIGN(td->orig_buffer, page_mask) +
			td->o.mem_align;
```

Should anything be changed/added here?
</blockquote></details>

AD2. I think we have meant aligning each individual message. But I'm not sure what performance it may give. So for now I recommend putting somewhere a comment about this possibility.
___
*[engines/librpma_gpspm.c, line 357 at r4](https://reviewable.io/reviews/pmem/fio/55#-MLmxqG74OiaN01x9XMl:-MLvfmC242PdHsX-fi8a:bflsi1p) ([raw file](https://github.com/pmem/fio/blob/8b165aad8d1882e5d79d7d19b533e8f724a741d4/engines/librpma_gpspm.c#L357)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please read the first comment in this thread by @janekmi 
</blockquote></details>

#57 I suppose. ;-)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[engines/librpma_gpspm.c, line 357 at r4](https://reviewable.io/reviews/pmem/fio/55#-MLmxqG74OiaN01x9XMl:-MLvgd_V1PcEgXo7blX_:b-ht0ukm) ([raw file](https://github.com/pmem/fio/blob/8b165aad8d1882e5d79d7d19b533e8f724a741d4/engines/librpma_gpspm.c#L357)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

#57 I suppose. ;-)
</blockquote></details>

That's right.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @grom72 and @janekmi)

___
*[engines/librpma_gpspm.c, line 339 at r2](https://reviewable.io/reviews/pmem/fio/55#-MLmWoWyACrPeQN9cplr:-MLvjTD0-Jve2MK-Mlik:b-7rrx2l) ([raw file](https://github.com/pmem/fio/blob/306f0a5a13929ba1aa6c1a7f42a1c58abae1cfb4/engines/librpma_gpspm.c#L339)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

AD2. I think we have meant aligning each individual message. But I'm not sure what performance it may give. So for now I recommend putting somewhere a comment about this possibility.
</blockquote></details>

A comment added.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55#-:-MLvmTuO8YOocW6mR4tq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
