### PR TITLE
rpma: do not mix two styles of error handling

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/202)

### CODE REVIEW

**Comment by ldorau** [comment]
9 lines less ! ;-)

**Comment by ldorau** [comment]
10 lines less ! ;-)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/202)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/202)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_fio.c, line 238 at r1](https://reviewable.io/reviews/pmem/fio/202#-MSSg63x2ZNyuSnEfLua:-MSSg63x2ZNyuSnEfLub:b-j06cof) ([raw file](https://github.com/pmem/fio/blob/1d407be6997438b0c45c7046f1a41144227ae417/engines/librpma_fio.c#L238)):*
> ```
> retry < LIBRPMA_FIO_RETRY_MAX_NO
> ```
not used at all

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/202)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_fio.c, line 238 at r1](https://reviewable.io/reviews/pmem/fio/202#-MSSg63x2ZNyuSnEfLua:-MSSoYJ2BopQQaSb27TZ:b-4cd61) ([raw file](https://github.com/pmem/fio/blob/1d407be6997438b0c45c7046f1a41144227ae417/engines/librpma_fio.c#L238)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> retry < LIBRPMA_FIO_RETRY_MAX_NO
> ```
not used at all
</blockquote></details>

Yes, exactly as it was before the PR ...

What do you propose? Any other instruction with this condition will not be used either...
Maybe `do ... while (1);`? - I do not think it is a good solution. 
I think the current code is the best - this is a clear message that this loop will execute ` LIBRPMA_FIO_RETRY_MAX_NO` times at most - it is important to see this at the beginning of this loop.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/202)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_fio.c, line 238 at r1](https://reviewable.io/reviews/pmem/fio/202#-MSSg63x2ZNyuSnEfLua:-MSStETg-w3n0o-0-86A:bmovthr) ([raw file](https://github.com/pmem/fio/blob/1d407be6997438b0c45c7046f1a41144227ae417/engines/librpma_fio.c#L238)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, exactly as it was before the PR ...

What do you propose? Any other instruction with this condition will not be used either...
Maybe `do ... while (1);`? - I do not think it is a good solution. 
I think the current code is the best - this is a clear message that this loop will execute ` LIBRPMA_FIO_RETRY_MAX_NO` times at most - it is important to see this at the beginning of this loop.
</blockquote></details>

Alternative would be  not to use goto in case we run out od retry but handle this after The loop

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/202)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma_fio.c, line 238 at r1](https://reviewable.io/reviews/pmem/fio/202#-MSSg63x2ZNyuSnEfLua:-MSSwA-uBsYNh-iGS-P4:b-a26qjy) ([raw file](https://github.com/pmem/fio/blob/1d407be6997438b0c45c7046f1a41144227ae417/engines/librpma_fio.c#L238)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Alternative would be  not to use goto in case we run out od retry but handle this after The loop   
</blockquote></details>

That's right.

Done.

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/202#-:-MST8HK4-cZI9SUkAEU5:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_fio.c, line 276 at r2](https://reviewable.io/reviews/pmem/fio/202#-MST7nza4NVIdmtOY7jK:-MST7nzbDKWezP-shrJy:bkz406q) ([raw file](https://github.com/pmem/fio/blob/4edc14c03943ba231e98b0de7466783467b55bb8/engines/librpma_fio.c#L276)):*
> ```
> goto err_conn_delete;
> ```
is this an error situation or it is just a normal case that also should be handled the same way as out of retries?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/202)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[engines/librpma_fio.c, line 276 at r2](https://reviewable.io/reviews/pmem/fio/202#-MST7nza4NVIdmtOY7jK:-MST9WYO4HBwo4gdQdGY:b-3vprrk) ([raw file](https://github.com/pmem/fio/blob/4edc14c03943ba231e98b0de7466783467b55bb8/engines/librpma_fio.c#L276)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> goto err_conn_delete;
> ```
is this an error situation or it is just a normal case that also should be handled the same way as out of retries?
</blockquote></details>

Since it is "`an unexptected event`" and we use `log_err()` I think it is an error situation.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/202#-:-MSTRIAN72rWp340fnhv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
