### PR TITLE
aof: server queue processing (the first approximation)

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #219

This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/220)

### CODE REVIEW

**Comment by ldorau** [comment]
Please rebase

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/220)* status: 1 of 2 files reviewed, all discussions resolved

**Review by janekmi — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/220#-:-MUCv5x41tKedioAGJR9:b-896fix)* status: 1 of 2 files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/220#-:-MUDYCrq1fuIdfV3nzL3:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/220)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[engines/librpma_aof.c, line 385 at r2](https://reviewable.io/reviews/pmem/fio/220#-MUDbG2fB3qqpS10d_AY:-MUDbG2fB3qqpS10d_AZ:bkid7ee) ([raw file](https://github.com/pmem/fio/blob/a5b7d48759c9d050aa0fac21be967d1ce918b77c/engines/librpma_aof.c#L385)):*
> ```
> flush
> ```

AOF update

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/220)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma_aof.c, line 385 at r2](https://reviewable.io/reviews/pmem/fio/220#-MUDbG2fB3qqpS10d_AY:-MUDcJLa8blXxtkohsen:b-896fix) ([raw file](https://github.com/pmem/fio/blob/a5b7d48759c9d050aa0fac21be967d1ce918b77c/engines/librpma_aof.c#L385)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> flush
> ```

AOF update
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/220)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/220#-:-MUDm0sT1wqdc-3JDGEF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
