### PR TITLE
rpma: add sync write

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/39)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/39)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma.c, line 416 at r1](https://reviewable.io/reviews/pmem/fio/39#-MKeF87FBV0h0HRbdv7l:-MKeF87FBV0h0HRbdv7m:b-c6r1oj) ([raw file](https://github.com/pmem/fio/blob/359e54a1e1e91838607a4b6bc3faf2ec43b54e2b/engines/librpma.c#L416)):*
> ```C
> 			goto err;
> 		if ((ret = rpma_flush(cd->conn, cd->server_mr,
> 				io_u->offset, 0 /* XXX length of the sequence */,
> ```

`io_u->xfer_buflen`?
___
*[engines/librpma.c, line 417 at r1](https://reviewable.io/reviews/pmem/fio/39#-MKeFEfN0kQJJWCEc-dh:-MKeFEfN0kQJJWCEc-di:b-39c9vr) ([raw file](https://github.com/pmem/fio/blob/359e54a1e1e91838607a4b6bc3faf2ec43b54e2b/engines/librpma.c#L417)):*
> ```C
> 		if ((ret = rpma_flush(cd->conn, cd->server_mr,
> 				io_u->offset, 0 /* XXX length of the sequence */,
> 				RPMA_FLUSH_TYPE_VISIBILITY, RPMA_F_COMPLETION_ALWAYS,
> ```

RPMA_FLUSH_TYPE_PERSISTENT

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/39)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/39)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/39)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma.c, line 416 at r1](https://reviewable.io/reviews/pmem/fio/39#-MKeF87FBV0h0HRbdv7l:-MKiJm0G9msll0PF6Zkg:b-896fix) ([raw file](https://github.com/pmem/fio/blob/359e54a1e1e91838607a4b6bc3faf2ec43b54e2b/engines/librpma.c#L416)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`io_u->xfer_buflen`?
</blockquote></details>

Done.
___
*[engines/librpma.c, line 417 at r1](https://reviewable.io/reviews/pmem/fio/39#-MKeFEfN0kQJJWCEc-dh:-MKiJbbc8Fqv_CSKXCzn:b-896fix) ([raw file](https://github.com/pmem/fio/blob/359e54a1e1e91838607a4b6bc3faf2ec43b54e2b/engines/librpma.c#L417)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

RPMA_FLUSH_TYPE_PERSISTENT
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/39)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/39#-:-MKidBk15I2oURJcjmnA:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/39#-:-MKilxOr2lQ7yZLiynx4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/39)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
