### PR TITLE
rpma: set sizes of SQ and CQ

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/30)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/30)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma.c, line 159 at r2](https://reviewable.io/reviews/pmem/fio/30#-MK1-EIy4OdsHnE6ZMWr:-MK1-EIy4OdsHnE6ZMWs:bpl5a3j) ([raw file](https://github.com/pmem/fio/blob/2b0da5c5319eaaa31d32005352d6f60a07521333/engines/librpma.c#L159)):*
> ```
> 	cq_size = (td->o.iodepth % td->o.iodepth_batch) ?
> 			(td->o.iodepth / td->o.iodepth_batch) + 1 :
> 			(td->o.iodepth / td->o.iodepth_batch);
> ```
```cq_size = (td->o.iodepth + td->o.iodepth_batch -1) / td->o.iodepth_batch```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/30)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[engines/librpma.c, line 159 at r2](https://reviewable.io/reviews/pmem/fio/30#-MK1-EIy4OdsHnE6ZMWr:-MK3VFk27-9y2K8PDwR2:b-hwf66f) ([raw file](https://github.com/pmem/fio/blob/2b0da5c5319eaaa31d32005352d6f60a07521333/engines/librpma.c#L159)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 	cq_size = (td->o.iodepth % td->o.iodepth_batch) ?
> 			(td->o.iodepth / td->o.iodepth_batch) + 1 :
> 			(td->o.iodepth / td->o.iodepth_batch);
> ```
```cq_size = (td->o.iodepth + td->o.iodepth_batch -1) / td->o.iodepth_batch```
</blockquote></details>

No, your proposal is not a correct ceil() function.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/30)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[engines/librpma.c, line 159 at r2](https://reviewable.io/reviews/pmem/fio/30#-MK1-EIy4OdsHnE6ZMWr:-MK4hDkX5VBIp5ews93l:bm8nvoa) ([raw file](https://github.com/pmem/fio/blob/2b0da5c5319eaaa31d32005352d6f60a07521333/engines/librpma.c#L159)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, your proposal is not a correct ceil() function.
</blockquote></details>

do you have any example?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/30)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[engines/librpma.c, line 145 at r2](https://reviewable.io/reviews/pmem/fio/30#-MK4g-6_2QQIyKuWaqFm:-MK4g-6_2QQIyKuWaqFn:biido9p) ([raw file](https://github.com/pmem/fio/blob/2b0da5c5319eaaa31d32005352d6f60a07521333/engines/librpma.c#L145)):*
> ```C
> 	}
> 
> 	ret = rpma_conn_cfg_new(&cfg);
> ```

/* create a connection configuration object */
___
*[engines/librpma.c, line 151 at r2](https://reviewable.io/reviews/pmem/fio/30#-MK4g6E59w6fSlDSn0e-:-MK4g6E59w6fSlDSn0e0:bjwjnoi) ([raw file](https://github.com/pmem/fio/blob/2b0da5c5319eaaa31d32005352d6f60a07521333/engines/librpma.c#L151)):*
> ```C
> 	}
> 
> 	ret = rpma_conn_cfg_set_sq_size(cfg, td->o.iodepth);
> ```

/* the send queue has to be big enough to accommodate all io_u's */
___
*[engines/librpma.c, line 159 at r2](https://reviewable.io/reviews/pmem/fio/30#-MK1-EIy4OdsHnE6ZMWr:-MK4hbxJ9Avgvn-oqUAc:b-g1howo) ([raw file](https://github.com/pmem/fio/blob/2b0da5c5319eaaa31d32005352d6f60a07521333/engines/librpma.c#L159)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

do you have any example?
</blockquote></details>

```c
cq_size = td->o.iodepth / td->o.iodepth_batch +
    (td->o.iodepth % td->o.iodepth_batch ? 1 : 0);
```
I do not like repetition. That's all. ;-)
___
*[engines/librpma.c, line 162 at r2](https://reviewable.io/reviews/pmem/fio/30#-MK4imG11j5aT1y3NtDi:-MK4imG11j5aT1y3NtDj:bxlnzht) ([raw file](https://github.com/pmem/fio/blob/2b0da5c5319eaaa31d32005352d6f60a07521333/engines/librpma.c#L162)):*
> ```C
> 			(td->o.iodepth / td->o.iodepth_batch);
> 
> 	ret = rpma_conn_cfg_set_cq_size(cfg, cq_size);
> ```

/* the completion queue has to be big enough to accommodate one completion for each batch */

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/30)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/fio/30#-MK4kZHr6kSAiZTtLo49:-MK4kZHr6kSAiZTtLo4A:b2w1kyg) (no related file):*
I think you do not really need #29. ;-)
Please rebase and undraft.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/30)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/fio/30#-MK4kZHr6kSAiZTtLo49:-MK4pX3fEBslNjpTGkju:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think you do not really need #29. ;-)
Please rebase and undraft.
</blockquote></details>

Done.

---
___
*[engines/librpma.c, line 145 at r2](https://reviewable.io/reviews/pmem/fio/30#-MK4g-6_2QQIyKuWaqFm:-MK4pD4m8hm5sI9KhrCP:b-896fix) ([raw file](https://github.com/pmem/fio/blob/2b0da5c5319eaaa31d32005352d6f60a07521333/engines/librpma.c#L145)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

/* create a connection configuration object */
</blockquote></details>

Done.
___
*[engines/librpma.c, line 151 at r2](https://reviewable.io/reviews/pmem/fio/30#-MK4g6E59w6fSlDSn0e-:-MK4pLWm2WR5StuTzzyS:b-896fix) ([raw file](https://github.com/pmem/fio/blob/2b0da5c5319eaaa31d32005352d6f60a07521333/engines/librpma.c#L151)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

/* the send queue has to be big enough to accommodate all io_u's */
</blockquote></details>

Done.
___
*[engines/librpma.c, line 159 at r2](https://reviewable.io/reviews/pmem/fio/30#-MK1-EIy4OdsHnE6ZMWr:-MK4n3TI17P3mGRXebTM:bc4pw3q) ([raw file](https://github.com/pmem/fio/blob/2b0da5c5319eaaa31d32005352d6f60a07521333/engines/librpma.c#L159)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
cq_size = td->o.iodepth / td->o.iodepth_batch +
    (td->o.iodepth % td->o.iodepth_batch ? 1 : 0);
```
I do not like repetition. That's all. ;-)
</blockquote></details>

@grom72 I thought I had an example but it turned out to be my mistake ;-) Excuse me - your proposal really is the correct ceil() function :-)
___
*[engines/librpma.c, line 162 at r2](https://reviewable.io/reviews/pmem/fio/30#-MK4imG11j5aT1y3NtDi:-MK4p2XnD1qJLZtTK2Kf:b-896fix) ([raw file](https://github.com/pmem/fio/blob/2b0da5c5319eaaa31d32005352d6f60a07521333/engines/librpma.c#L162)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

/* the completion queue has to be big enough to accommodate one completion for each batch */
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/30)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[engines/librpma.c, line 159 at r2](https://reviewable.io/reviews/pmem/fio/30#-MK1-EIy4OdsHnE6ZMWr:-MK4rNiZ6zC3UP_jvGz1:b-u96qzv) ([raw file](https://github.com/pmem/fio/blob/2b0da5c5319eaaa31d32005352d6f60a07521333/engines/librpma.c#L159)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 I thought I had an example but it turned out to be my mistake ;-) Excuse me - your proposal really is the correct ceil() function :-)
</blockquote></details>

(see "Fractions" in https://janmr.com/blog/2009/09/useful-properties-of-the-floor-and-ceil-functions/)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/30)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/30#-:-MK4xQ3eBnozqcSGMHn2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/30#-:-MK5mJVw4mkceL3dWM_Y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
