### PR TITLE
common: move the full matrix build to a nightly cron build

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/28)

### CODE REVIEW

**Comment by ldorau** [comment]
The cron build can be tested after having replaced 'cron' with 'push':
https://travis-ci.org/github/ldorau/fio/builds/735960061

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/28)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
@janekmi @grom72 @osalyk please review

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/28#-:-MJlUflMBhAN4JSnd54g:b8tps29)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/28#-:-MK-Fffn8NtKIMNauX6x:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
