### PR TITLE
aof: client_init() (the first approximation)

### PR DESCRIPTION
**Pull request by osalyk**
- [x] #213

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/fio/215)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/215)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_aof.c, line 62 at r1](https://reviewable.io/reviews/pmem/fio/215#-MTv96GD-_rjir5Rr1ut:-MTv96GD-_rjir5Rr1uu:bmgc9x3) ([raw file](https://github.com/pmem/fio/blob/c8d78de7aec3f038bd14e4a6b9bf1a1f8c0bece7/engines/librpma_aof.c#L62)):*
> ```C
> 	 *   success and error completions (sq_size + rq_size)
> 	 */
> 	if ((ret = rpma_conn_cfg_set_sq_size(cfg, write_num + cd->msg_num))) {
> ```

`cd->msg_num` is set to `0` intentionally or by copy-paste? ;-)
___
*[engines/librpma_aof.c, line 79 at r1](https://reviewable.io/reviews/pmem/fio/215#-MTv9UBaAVpSJNOViQD3:-MTv9UBaAVpSJNOViQD4:bbllyne) ([raw file](https://github.com/pmem/fio/blob/c8d78de7aec3f038bd14e4a6b9bf1a1f8c0bece7/engines/librpma_aof.c#L79)):*
> ```C
> 
> 	ccd = td->io_ops_data;
> ```

I think we are missing at least this part:

```c
	/* validate the server's RQ capacity */
	if (cd->msg_num > ccd->ws->max_msg_num) {
		log_err(
			"server's RQ size (iodepth) too small to handle the client's workspace requirements (%u < %u)\n",
			ccd->ws->max_msg_num, cd->msg_num);
		goto err_cleanup_common;
	}

	if ((ret = rpma_conn_cfg_delete(&cfg))) {
		librpma_td_verror(td, ret, "rpma_conn_cfg_delete");
		/* non fatal error - continue */
	}
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/215)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[engines/librpma_aof.c, line 62 at r1](https://reviewable.io/reviews/pmem/fio/215#-MTv96GD-_rjir5Rr1ut:-MU7YN3_4X4uChEdsm-Z:b-ey01e8) ([raw file](https://github.com/pmem/fio/blob/c8d78de7aec3f038bd14e4a6b9bf1a1f8c0bece7/engines/librpma_aof.c#L62)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`cd->msg_num` is set to `0` intentionally or by copy-paste? ;-)
</blockquote></details>

copy-paste ;)
Done.
___
*[engines/librpma_aof.c, line 79 at r1](https://reviewable.io/reviews/pmem/fio/215#-MTv9UBaAVpSJNOViQD3:-MU7ZHenBf0GVOQmPGAC:b-896fix) ([raw file](https://github.com/pmem/fio/blob/c8d78de7aec3f038bd14e4a6b9bf1a1f8c0bece7/engines/librpma_aof.c#L79)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we are missing at least this part:

```c
	/* validate the server's RQ capacity */
	if (cd->msg_num > ccd->ws->max_msg_num) {
		log_err(
			"server's RQ size (iodepth) too small to handle the client's workspace requirements (%u < %u)\n",
			ccd->ws->max_msg_num, cd->msg_num);
		goto err_cleanup_common;
	}

	if ((ret = rpma_conn_cfg_delete(&cfg))) {
		librpma_td_verror(td, ret, "rpma_conn_cfg_delete");
		/* non fatal error - continue */
	}
```
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/215)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/215)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[engines/librpma_aof.c, line 54 at r2](https://reviewable.io/reviews/pmem/fio/215#-MU9A8R80yEUUm8-0lQw:-MU9A8R80yEUUm8-0lQx:bvo2irm) ([raw file](https://github.com/pmem/fio/blob/3f397059872f310641fd2f20a750ad495e013fa6/engines/librpma_aof.c#L54)):*
> ```C
> 
> 	write_num = 1; /* WRITE */
> 	cd->msg_num = 1; /* FLUSH */
> ```

**Minor**: Keep the order of events. These two should happen between `calloc()` and `rpma_conn_cfg_new()`.
___
*[engines/librpma_aof.c, line 95 at r2](https://reviewable.io/reviews/pmem/fio/215#-MU9ECEv2hDZGU3CfAD2:-MU9ECEv2hDZGU3CfAD3:b-coyknq) ([raw file](https://github.com/pmem/fio/blob/3f397059872f310641fd2f20a750ad495e013fa6/engines/librpma_aof.c#L95)):*
> ```C
> 		/* non fatal error - continue */
> 	}
> ```

Taking a look at the part which is missing here:

```c
	ccd->flush = client_io_flush;
	ccd->get_io_u_index = client_get_io_u_index;
```

I think you should add these two lines with at least empty stubs with asserts. Assert is always easier to track than SIGSEGV. ;-)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/215)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[engines/librpma_aof.c, line 54 at r2](https://reviewable.io/reviews/pmem/fio/215#-MU9A8R80yEUUm8-0lQw:-MU9FUD2DvrG4hbpgnCl:b-896fix) ([raw file](https://github.com/pmem/fio/blob/3f397059872f310641fd2f20a750ad495e013fa6/engines/librpma_aof.c#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

**Minor**: Keep the order of events. These two should happen between `calloc()` and `rpma_conn_cfg_new()`.
</blockquote></details>

Done.
___
*[engines/librpma_aof.c, line 95 at r2](https://reviewable.io/reviews/pmem/fio/215#-MU9ECEv2hDZGU3CfAD2:-MU9J62A47y0A6RC-cUa:b-896fix) ([raw file](https://github.com/pmem/fio/blob/3f397059872f310641fd2f20a750ad495e013fa6/engines/librpma_aof.c#L95)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Taking a look at the part which is missing here:

```c
	ccd->flush = client_io_flush;
	ccd->get_io_u_index = client_get_io_u_index;
```

I think you should add these two lines with at least empty stubs with asserts. Assert is always easier to track than SIGSEGV. ;-)
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/215#-:-MU9kaAU5Pe-iplJvBK7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/fio/215)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/fio/215#-:-MUAj2WYEezCmJ0xa0Y3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
